# Understanding survey data files {#c03}


* Directory method, the project method, and the approach of opening R Studio by double-clicking a file in the directory you want to work from

Types of files

* R
* Stata
* SAS
* Excel
* Sudaan??

## Survey file types

Survey files come in different file types depending on the program used to output them. R gives you the flexibility to load datasets regardless of their file extension. We will cover the file types you are most likely to encounter in survey analysis: delimiter-separated text files, Excel files, `.dat` files from Stata, and `.sav` files from SAS.

### Loading delimiter-separated files into R

Delimiter-separated files use specific characters to separate values. For example, comma-separated values (CSV) files are separated by commas. These file types are widely used and you can use many applications to read and write them.

Using the tidyverse package {readr}, we can read delimiter-separated files. The {readr} package supports the following files with these `read_*()` functions:

* `read_csv()`: comma-separated values (CSV) files
* `read_tsv()`: tab-separated values (TSV) files
* `read_delim()`: delimited files (CSV and TSV are important special cases)
* `read_fwf()`: fixed-width files
* `read_table()`: whitespace-separated files
* `read_log()`: web log files



```{r, eval=FALSE}

```


