# Reproducible Research {#c09-reprex-data}

The ability to recreate or replicate the results of a data analysis is a crucial aspect of any research. If we pass an analysis project to another person, they should be able to run the entire project from start to finish and obtain the same results. This idea of reproducibility enables the verification of findings and ensures that the conclusions are not dependent on a particular person running the code or workflow or on a particular day and environment. Thus, having reproducible research also can reduce errors in the code as researchers need to be able to replicate and verify the results. Not only is this idea ethical in ensuring that findings are accurate, but it is also becoming a requirement for publishing output in many scientific journals. These journals are now requiring that authors make code, data, and methodology transparent and accessible to other researchers who wish to verify or build on existing work.

To ensure the research is reproducible, we need to ensure that the key components of analysis are available, discoverable, documented, and shared with others.  The main four components that we should consider are:

  - **Code**: source code used for data cleaning, analysis, modeling, and reporting
  - **Data**: raw data used in the workflow, or if data is sensitive or proprietary, as much data as possible that would allow others to run our workflow (e.g., access to a restricted use file (RUF))
  - **Environment**: environment of the project, including the R version, packages, operating system, and other dependencies used in the analysis
  - **Methodology**: analysis methodology, including rationale behind decisions, interpretations, and assumptions

In Chapter \@ref(c08-communicating-results), we briefly mention how discussion on each of these in important to include in the methodology report and when communicating the findings and results of a study. However, for us to be transparent and effective researchers, we need to make sure we not only discuss these through text, but also provide files and additional information when requested. Often when starting a project, researchers will dive into the data and make decisions as they go without full documentation which can be challenging if we need to go back and make changes or understand even what we did a few months ago. Therefore, it would benefit not only other researchers, but potentially our future selves to better document everything from the start.  The good news is that there are many tools, practices, and project management techniques to make survey analysis projects easy to reproduce. For best results, researchers should decide which techniques and tools will be used prior (or very early on) starting a project. This chapter covers some of our suggestions of tools and techniques that can be used in projects. This list is not comprehensive but aims to provide a starting point for teams looking to create a reproducible workflow.

## Version Control: Git

Often a survey analysis project produces a lot of code. As code evolves throughout a project, keeping track of the latest version can become challenging. If a team of analysts is working on the same script, someone may use an outdated version, resulting in incorrect results or duplicative work.

Version control systems like Git can help alleviate these pains. Git is a system that helps track changes in computer files. Survey analysis can use Git to follow the evolution of code and manage asynchronous work. With Git, it is easy to see any changes made in a script, revert changes, and resolve differences between code versions (called conflicts).

Services such as GitHub or GitLab provide hosting and sharing of files as well as version control with Git. For example, we can visit the GitHub repository for this book ([https://github.com/tidy-survey-r/tidy-survey-book](https://github.com/tidy-survey-r/tidy-survey-book)) and see the files that build the book, when they were committed to the repository, and the history of modifications over time.

<!--TODO: Add image-->

In addition to code scripts, platforms like GitHub can store data and documentation. They provide a way to maintain a history of data modifications through versioning and timestamps. By saving the data and documentation alongside the code, it becomes easier for others to refer to and access everything they need in one place.

Using version control in analysis projects makes collaboration and maintenance more manageable. For connecting git with R, we recommend the [Happy Git and GitHub for the useR by Jenny Bryan and Jim Hester](https://happygitwithr.com/) [@git-w-R].

## Package Management: {renv}

Along with version control of code, version control for packages is also important for reproducibility.  If two people run the same code, but use different versions of a package, the outcomes could be different depending on the changes that occurred.  For example, this book currently uses a version of the {srvyr} package from GitHub and not from CRAN.  This is because the version of {srvyr} has some bugs (errors) when doing some calculations. The version on GitHub has corrected these errors, so we have asked users to install the GitHub version to obtain the same results. 

One way to easily handle different package versions is with the {renv} package. This package allows researchers to set the versions for each package used and easily manage package dependencies. Specifically, {renv} creates isolated, project-specific environments that record the packages and their versions used in the code. When initiated by a new user, {renv} checks whether the installed packages are consistent with the recorded version for the project. If not, it installs the correct versions and ensures that others can replicate the project's environment to rerun the code and obtain consistent results.

## Workflow Management: {targets}

With complex studies that involve multiple code files, steps, and dependencies it can be important to ensure that all pieces are implemented in the correct order. This could be done manually (e.g., numbering files to indicate the order or providing detailed documentation on the order) or we can automate the process to ensure there is no confusion on how things flow. Ensuring code is run in the correct order helps ensure that the research is reproducible and that anyone can easily pick up the code and know exactly how to run the code to get the same results.

To automate, we recommend using the {targets} package, which is a workflow manager enabling us to document, automate, and execute complex data workflows with multiple steps and dependencies. With this package, we first define the order of execution for our code and then it will consistently execute the code in that order each time it is run. One nice feature of {targets} is if you are only changing code later in the workflow, only the affected code and its downstream targets (i.e., the subsequent code files) are re-executed when we change a script. The {targets} package also provides interactive progress monitoring and reporting, allowing us to track the status and progress of our analysis pipeline. 

## Documentation: Quarto/R Markdown

Documenting and describing decisions help other researchers reproduce your work and findings. Methodology reports can be one way to do this, by providing a large document of all project decisions. Additionally, using tools like Quarto and R Markdown allow us to create documents that integrate code and text. These documents present analysis results alongside the report's narrative, so there's no need to copy and paste code output into the final documentation. By eliminating manual steps, we can reduce the chances of errors in the final output. 

Quarto and R Markdown documents also allow users to re-execute the underlying code when needed, therefore, another team member can easily recreate the report and obtain the same results. If outputting the file as html, these tools can also allow for more powerful integration of interactive plots, images, videos, links, and anything else researchers might need to document for a project. 

### Parameterization

Another great feature of Quarto and R Markdown is the ability to reduce repetitive code by parameterizing the files. Parameters can control various aspects of the analysis, such as dates, geography, or other analysis variables. By parameterizing our code, we can define and modify these parameters to explore different scenarios or inputs. For example, if we start by creating a document that provides survey analysis results for Michigan but then later decide we want to look at multiple states, we can define a `state` parameter and rerun the same analysis for other states like Wisconsin without having to edit the code throughout the document.

Parameters can be defined in the header or code chunks of our Quarto/R Markdown documents and can easily be modified and documented. Thus, we are reducing errors that may occur by manually editing code throughout the script and it is a flexible way for others to replicate the analysis and explore variations.

## Other Tips for Reproducibility

### Random Number Seeds  

Some tasks in survey analysis require randomness, such as imputation, model training, or creating random samples. By default, the random numbers generated by R will change each time we rerun the code, making it difficult to reproduce the same results. By "setting the seed," we can control the randomness and ensure that the random numbers remain consistent whenever we rerun the code. Others can use the same seed value to reproduce our random numbers and achieve the same results, facilitating reproducibility.

In R, we can use the `set.seed()` function to control the randomness in our code. Set a seed value by providing an integer to the function:

```r
set.seed(999)

runif(5)
```

The `runif()` function generates five random numbers from a uniform distribution. Since the seed is set to `999`, running `runif()` multiple times will always produce the same sequence:

```
[1] 0.38907138 0.58306072 0.09466569 0.85263123 0.78674676
```

The choice of the seed number is up to the researcher. For example, this could be the date (`20240102`) or time of day (`1056`) when analysis was first conducted, a phone number (`8675309`), or the first few numbers that come to mind (`369`). As long as the seed is set for a given analysis, the actual number can be up to the researcher to decide.  However, it is important to note that `set.seed()` should be used *before* random number generation but is only necessary once per program to make the entire program reproducible. For example, we might set the seed at the top of a program where libraries tend to be loaded.

### Descriptive Names and Labels

Something else to assist with reproducible research, is using descriptive variable names or labeling data. For example, in the ANES data, the variable names in the raw data all start with `V20` and are a string of numbers. To make things easier to reproduce, we opted to change the variable names to be more descriptive to what they contained (e.g., `Age`). This can also be done with the data values themselves.  One way to accomplish this is by creating factors for categorical data, which can ensure that we know that a value of `1` really means `Female`, for example. There are other ways of handling this such as attaching labels to the data instead of recoding variables to be descriptive (see Chapter \@ref(c11-missing-data)). As with random number seeds, the exact method for this is up to the researcher, but providing this information can help ensure your research is reproducible.

### Databases

For projects with complex or large data structures, researchers may consider creating a database to better manage the data and any changes. Many databases will allow for a history of changes, which can be useful when recoding variables to ensure no inadvertent errors were introduced. Additionally, a database may be easier to pass to other researchers if there are existing relationships between tables and types that are complex to map. 
