# ANES Derived Variable Codebook {#anes-cb}

```{r}
#| label: anes-cb-setup
#| echo: FALSE
#| error: FALSE
#| warning: FALSE
#| message: FALSE
library(tidyverse)
library(janitor)
library(kableExtra)
library(knitr)

data(anes_2020)

attrlist <- map(anes_2020, attributes)

NULL_to_NA <- function(x){
  if (is.null(x)){
    NA
  }else{
    x
  }
}

anes_var_info <- tibble(
  Vars=names(attrlist),
  Section=map_chr(attrlist, "Section") %>% unname(),
  Question=map(attrlist, "Question") %>% map(NULL_to_NA) %>% unlist(use.names = FALSE),
  Description=map_chr(attrlist, "label") %>% unname(),
  VarType=map(anes_2020, class) ,) %>%
  rowwise() %>%
  mutate(
    VarClass=str_c(VarType, collapse=", "),
    VarType=case_when(
      Vars%in%c("V200001", "CaseID")~ list("ID"),
      Vars=="V201507x"~list("numeric2"),
      TRUE~list(VarType)
    )
  ) %>%
  ungroup()

cb_count <- function(dat, var){
  t <- dat %>%
    count(.data[[var]]) %>%
    mutate(`Unweighted Freq` = n / sum(n)) %>%
    janitor::adorn_totals(where="row", fill="-", na.rm=TRUE, name="Total", n, `Unweighted Freq`) %>%
    mutate(`Unweighted Freq`= round(`Unweighted Freq`, 3)) %>%
    kbl(position="H")
  
   if (knitr:::is_html_output()){
    t %>% kable_minimal() %>% print()
  } else{
    t %>% print()
  }
}

cb_count_labelled <- function(dat, var){
  dat2 <- dat %>%
    mutate(
      Label=as_factor(.data[[var]], levels="labels"),
    ) %>% haven::zap_labels()
  
  
  t <- dat2 %>%
    count(.data[[var]], Label) %>%
    mutate(`Unweighted Freq` = n / sum(n)) %>%
    janitor::adorn_totals(where="row", fill="-", na.rm=TRUE, name="Total", n, `Unweighted Freq`) %>%
    mutate(`Unweighted Freq`= round(`Unweighted Freq`, 3)) %>%
    kbl(position="H")
  
   if (knitr:::is_html_output()){
    t %>% kable_minimal() %>% print()
  } else{
    t %>% print()
  }
}


cb_continuous <- function(dat, var){
  t <- dat %>%
    summarize(
      `N Missing`=sum(is.na(.data[[var]])),
      Minimum = min(.data[[var]], na.rm = TRUE),
      Median = median(.data[[var]], na.rm = TRUE),
      Maximum = max(.data[[var]], na.rm = TRUE)) %>%
    kbl(position="H") 
  
  if (knitr:::is_html_output()){
    t %>% kable_minimal() %>% print()
  } else{
    t %>% print()
  }
  
}

cb_continuous_spec <- function(dat, var){
  dat2 <- dat %>%
    haven::zap_labels()
  
  t_valid <- dat2 %>%
    filter(.data[[var]]>0) %>%
    summarize(
      `N Missing`=sum(is.na(.data[[var]])),
      Minimum = min(.data[[var]], na.rm = TRUE),
      Median = median(.data[[var]], na.rm = TRUE),
      Maximum = max(.data[[var]], na.rm = TRUE)) 
  
  t_ref <- dat2 %>%
    filter(.data[[var]]==-9)  %>%
    count(name="N Refused (-9)")
  
  t <- t_ref %>% bind_cols(t_valid) %>%
    select(`N Missing`, `N Refused (-9)`, everything()) %>%
    kbl(position="H") 
    
  if (knitr:::is_html_output()){
    t %>% kable_minimal() %>% print()
  } else{
    t %>% print()
  }
  
}


make_section <- function(sec){
  cat(str_c("## ", sec, "\n\n"))
  
  make_sum <- function(var){
    cat(str_c("#### ", var, " {-} \n\n"))
    vi <- anes_var_info %>% filter(Vars==var)
    de <- vi %>% pull(Description)
    cat(str_c("Description: ", de, "\n\n"))
    qt <- vi %>% pull(Question)
    if (!is.na(qt)) cat(str_c("Question: ", qt, "\n\n"))
    vc <- vi %>% pull(VarClass)
    cat(str_c("Variable class: ", vc, "\n\n"))
    vt <- vi %>% pull(VarType) %>% unlist()
    
    if (any(c("factor", "character", "logical") %in% vt)){
      anes_2020 %>% cb_count(var)
      cat("\n")
    } else if ("haven_labelled" %in% vt){
      anes_2020 %>% cb_count_labelled(var)
      cat("\n")
    } else if ("numeric" %in% vt){
      anes_2020 %>% cb_continuous(var)
      cat("\n")
    } else if ("numeric2" %in% vt){
      anes_2020 %>% cb_continuous_spec(var)
      cat("\n")
    }
    
  }
  
  anes_var_info %>% filter(Section==sec) %>% pull(Vars) %>%
    walk(make_sum)
}

```

The full codebook with the original variables is available at @anes-cb.

This is a codebook for the ANES data used in this book (`anes_2020`) from the {srvyrexploR} package.


```{r}
#| label: anes-cb-write
#| echo: FALSE
#| results: asis
anes_var_info %>%
  distinct(Section) %>%
  pull(Section) %>%
  walk(make_section)
```
