# RECS Derived Variable Codebook {#recs-cb}

```{r}
#| label: recs-cb-cb-setup
#| echo: FALSE
#| error: FALSE
#| warning: FALSE
#| message: FALSE
library(tidyverse)
library(janitor)
library(kableExtra)
library(knitr)

recs <- recs_2020
```

The full codebook with the original variables is available at [https://www.eia.gov/consumption/residential/data/2020/index.php?view=microdata](https://www.eia.gov/consumption/residential/data/2020/index.php?view=microdata) - "Variable and response codebook". This codebook includes the variables on the dataset included for download along with this book.


```{r}
#| label: recs-cb-prep
#| echo: FALSE

attrlist <- map(recs, attributes)

NULL_to_NA <- function(x){
  if (is.null(x)){
    NA
  }else{
    x
  }
}


recs_var_info <- tibble(
  Vars=names(attrlist),
  Section=map_chr(attrlist, "Section") %>% unname(),
  Question=map(attrlist, "Question") %>% map(NULL_to_NA) %>% unlist(use.names = FALSE),
  Description=map_chr(attrlist, "label") %>% unname(),
  VarType=map(recs, class) ,
) %>%
  mutate(
    VarType=if_else(Vars=="DOEID", list("ID"), VarType)
  )


cb_count <- function(dat, var){
  t <- dat %>%
    count(.data[[var]]) %>%
    mutate(`Unweighted Freq` = n / sum(n)) %>%
    janitor::adorn_totals(where="row", fill="-", na.rm=TRUE, name="Total", n, `Unweighted Freq`) %>%
    mutate(`Unweighted Freq`= round(`Unweighted Freq`, 3)) %>%
    kbl(position="H")
  
   if (knitr:::is_html_output()){
    t %>% kable_minimal() %>% print()
  } else{
    t %>% print()
  }
}

cb_continuous <- function(dat, var){
  t <- dat %>%
    summarize(
      `N Missing`=sum(is.na(.data[[var]])),
      Minimum = min(.data[[var]], na.rm = TRUE),
      Median = median(.data[[var]], na.rm = TRUE),
      Maximum = max(.data[[var]], na.rm = TRUE)) %>%
    kbl(position="H") 
  
  if (knitr:::is_html_output()){
    t %>% kable_minimal() %>% print()
  } else{
    t %>% print()
  }
  
}


make_section <- function(sec){
  cat(str_c("## ", sec, "\n\n"))
  
  make_sum <- function(var){
    cat(str_c("#### ", var, " {-} \n\n"))
    vi <- recs_var_info %>% filter(Vars==var)
    de <- vi %>% pull(Description)
    cat(str_c("Description: ", de, "\n\n"))
    qt <- vi %>% pull(Question)
    if (!is.na(qt)) cat(str_c("Question: ", qt, "\n\n"))
    vt <- vi %>% pull(VarType) %>% unlist()
    
    if (any(c("factor", "character", "logical") %in% vt)){
      recs %>% cb_count(var)
      cat("\n")
    } else if ("numeric" %in% vt){
      recs %>% cb_continuous(var)
      cat("\n")
    }
    
  }
  
  recs_var_info %>% filter(Section==sec) %>% pull(Vars) %>%
    walk(make_sum)
}




```


```{r}
#| label: recs-cb-write
#| echo: FALSE
#| results: asis
recs_var_info %>%
  distinct(Section) %>%
  pull(Section) %>%
  walk(make_section)
```

