<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 Introduction | Tidy Survey Book</title>
  <meta name="description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 Introduction | Tidy Survey Book" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  <meta name="github-repo" content="tidy-survey-r/tidy-survey-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Introduction | Tidy Survey Book" />
  
  <meta name="twitter:description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  

<meta name="author" content="Stephanie Zimmer, Rebecca J. Powell, and Isabella Velásquez" />


<meta name="date" content="2023-08-27" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="c02-overview-surveys.html"/>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="c01-intro.html"><a href="c01-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="c01-intro.html"><a href="c01-intro.html#what-to-expect"><i class="fa fa-check"></i><b>1.1</b> What to expect</a></li>
<li class="chapter" data-level="1.2" data-path="c01-intro.html"><a href="c01-intro.html#book-datasets"><i class="fa fa-check"></i><b>1.2</b> Datasets used in this book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html"><i class="fa fa-check"></i><b>2</b> Overview of Surveys</a>
<ul>
<li class="chapter" data-level="2.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#pre-survey-planning"><i class="fa fa-check"></i><b>2.2</b> Pre-Survey Planning</a></li>
<li class="chapter" data-level="2.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design"><i class="fa fa-check"></i><b>2.3</b> Study Design</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-sampdesign"><i class="fa fa-check"></i><b>2.3.1</b> Sampling Design</a></li>
<li class="chapter" data-level="2.3.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-dcplanning"><i class="fa fa-check"></i><b>2.3.2</b> Data Collection Planning</a></li>
<li class="chapter" data-level="2.3.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-questionnaire"><i class="fa fa-check"></i><b>2.3.3</b> Questionnaire Design</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-datacollection"><i class="fa fa-check"></i><b>2.4</b> Data Collection</a></li>
<li class="chapter" data-level="2.5" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post"><i class="fa fa-check"></i><b>2.5</b> Post-Survey Processing</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-cleaning"><i class="fa fa-check"></i><b>2.5.1</b> Data Cleaning and Imputation</a></li>
<li class="chapter" data-level="2.5.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-weighting"><i class="fa fa-check"></i><b>2.5.2</b> Weighting</a></li>
<li class="chapter" data-level="2.5.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-disclosure"><i class="fa fa-check"></i><b>2.5.3</b> Disclosure</a></li>
<li class="chapter" data-level="2.5.4" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-documentation"><i class="fa fa-check"></i><b>2.5.4</b> Documentation</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#post-survey-data-analysis-and-reporting"><i class="fa fa-check"></i><b>2.6</b> Post-survey data analysis and reporting</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html"><i class="fa fa-check"></i><b>3</b> Specifying sample designs and replicate weights in {srvyr}</a>
<ul>
<li class="chapter" data-level="" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#prereq3"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="3.1" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#common-sampling-designs"><i class="fa fa-check"></i><b>3.2</b> Common sampling designs</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#simple-random-sample-without-replacement"><i class="fa fa-check"></i><b>3.2.1</b> Simple random sample without replacement</a></li>
<li class="chapter" data-level="3.2.2" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#simple-random-sample-with-replacement"><i class="fa fa-check"></i><b>3.2.2</b> Simple random sample with replacement</a></li>
<li class="chapter" data-level="3.2.3" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#stratified-sampling"><i class="fa fa-check"></i><b>3.2.3</b> Stratified sampling</a></li>
<li class="chapter" data-level="3.2.4" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#clustered-sampling"><i class="fa fa-check"></i><b>3.2.4</b> Clustered sampling</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#replicate-weights"><i class="fa fa-check"></i><b>3.3</b> Replicate weights</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#balanced-repeated-replication-brr-method"><i class="fa fa-check"></i><b>3.3.1</b> Balanced Repeated Replication (BRR) Method</a></li>
<li class="chapter" data-level="3.3.2" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#fays-brr-method"><i class="fa fa-check"></i><b>3.3.2</b> Fay’s BRR Method</a></li>
<li class="chapter" data-level="3.3.3" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#jackknife-method"><i class="fa fa-check"></i><b>3.3.3</b> Jackknife method</a></li>
<li class="chapter" data-level="3.3.4" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#bootstrap-method"><i class="fa fa-check"></i><b>3.3.4</b> Bootstrap Method</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#und-surv-doc"><i class="fa fa-check"></i><b>3.4</b> Understanding survey design documentation</a></li>
<li class="chapter" data-level="3.5" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#exercises"><i class="fa fa-check"></i><b>3.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html"><i class="fa fa-check"></i><b>4</b> Understanding Survey Data Documentation</a>
<ul>
<li class="chapter" data-level="" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#prereq4"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="4.1" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#introduction-2"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#types-of-survey-documentation"><i class="fa fa-check"></i><b>4.2</b> Types of Survey Documentation</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#technical-documentation"><i class="fa fa-check"></i><b>4.2.1</b> Technical Documentation</a></li>
<li class="chapter" data-level="4.2.2" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#questionnaires"><i class="fa fa-check"></i><b>4.2.2</b> Questionnaires</a></li>
<li class="chapter" data-level="4.2.3" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#codebooks"><i class="fa fa-check"></i><b>4.2.3</b> Codebooks</a></li>
<li class="chapter" data-level="4.2.4" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#errata"><i class="fa fa-check"></i><b>4.2.4</b> Errata</a></li>
<li class="chapter" data-level="4.2.5" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#additional-resources"><i class="fa fa-check"></i><b>4.2.5</b> Additional Resources</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#working-with-missing-data"><i class="fa fa-check"></i><b>4.3</b> Working with Missing Data</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#accounting-for-questionnaire-skip-patterns"><i class="fa fa-check"></i><b>4.3.1</b> Accounting for Questionnaire Skip Patterns</a></li>
<li class="chapter" data-level="4.3.2" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#accounting-for-unintentional-missing-data"><i class="fa fa-check"></i><b>4.3.2</b> Accounting for Unintentional Missing Data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#example-american-national-election-studies-anes-2020-survey-documentation"><i class="fa fa-check"></i><b>4.4</b> Example: American National Election Studies (ANES) 2020 Survey Documentation</a></li>
<li class="chapter" data-level="4.5" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#searching-for-public-use-survey-data"><i class="fa fa-check"></i><b>4.5</b> Searching for Public-Use Survey Data</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html"><i class="fa fa-check"></i><b>5</b> Descriptive Analyses in {srvyr}</a>
<ul>
<li class="chapter" data-level="" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#prereq5"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="5.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#introduction-4"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#similarities-between-dplyr-and-srvyr-functions"><i class="fa fa-check"></i><b>5.2</b> Similarities Between {dplyr} and {srvyr} Functions</a></li>
<li class="chapter" data-level="5.3" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#counts-and-cross-tabulations"><i class="fa fa-check"></i><b>5.3</b> Counts and Cross-Tabulations</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-count-syntax"><i class="fa fa-check"></i><b>5.3.1</b> Syntax</a></li>
<li class="chapter" data-level="5.3.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples"><i class="fa fa-check"></i><b>5.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#totals-and-sums"><i class="fa fa-check"></i><b>5.4</b> Totals and Sums</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax"><i class="fa fa-check"></i><b>5.4.1</b> Syntax</a></li>
<li class="chapter" data-level="5.4.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-1"><i class="fa fa-check"></i><b>5.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-meanprop"><i class="fa fa-check"></i><b>5.5</b> Means and Proportions</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-meanprop-syntax"><i class="fa fa-check"></i><b>5.5.1</b> Syntax</a></li>
<li class="chapter" data-level="5.5.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-2"><i class="fa fa-check"></i><b>5.5.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#quantiles-and-medians"><i class="fa fa-check"></i><b>5.6</b> Quantiles and Medians</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-1"><i class="fa fa-check"></i><b>5.6.1</b> Syntax</a></li>
<li class="chapter" data-level="5.6.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-3"><i class="fa fa-check"></i><b>5.6.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#ratios"><i class="fa fa-check"></i><b>5.7</b> Ratios</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-2"><i class="fa fa-check"></i><b>5.7.1</b> Syntax</a></li>
<li class="chapter" data-level="5.7.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-4"><i class="fa fa-check"></i><b>5.7.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#correlations"><i class="fa fa-check"></i><b>5.8</b> Correlations</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-3"><i class="fa fa-check"></i><b>5.8.1</b> Syntax</a></li>
<li class="chapter" data-level="5.8.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-5"><i class="fa fa-check"></i><b>5.8.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#standard-deviation-and-variance"><i class="fa fa-check"></i><b>5.9</b> Standard Deviation and Variance</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-4"><i class="fa fa-check"></i><b>5.9.1</b> Syntax</a></li>
<li class="chapter" data-level="5.9.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-6"><i class="fa fa-check"></i><b>5.9.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#additional-topics"><i class="fa fa-check"></i><b>5.10</b> Additional Topics</a>
<ul>
<li class="chapter" data-level="5.10.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#unweighted-analysis"><i class="fa fa-check"></i><b>5.10.1</b> Unweighted Analysis</a></li>
<li class="chapter" data-level="5.10.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#subpopulation-analysis"><i class="fa fa-check"></i><b>5.10.2</b> Subpopulation Analysis</a></li>
<li class="chapter" data-level="5.10.3" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-deff"><i class="fa fa-check"></i><b>5.10.3</b> Design Effects</a></li>
<li class="chapter" data-level="5.10.4" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#creating-summary-rows"><i class="fa fa-check"></i><b>5.10.4</b> Creating Summary Rows</a></li>
<li class="chapter" data-level="5.10.5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#calculating-estimates-for-many-outcomes"><i class="fa fa-check"></i><b>5.10.5</b> Calculating Estimates for Many Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="5.11" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#exercises-1"><i class="fa fa-check"></i><b>5.11</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html"><i class="fa fa-check"></i><b>6</b> Statistical testing</a>
<ul>
<li class="chapter" data-level="" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#prereq6"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="6.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#introduction-5"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#dot-notation"><i class="fa fa-check"></i><b>6.2</b> Dot Notation</a></li>
<li class="chapter" data-level="6.3" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest"><i class="fa fa-check"></i><b>6.3</b> Comparison of Proportions and Means</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest-syntax"><i class="fa fa-check"></i><b>6.3.1</b> Syntax</a></li>
<li class="chapter" data-level="6.3.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest-examples"><i class="fa fa-check"></i><b>6.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi"><i class="fa fa-check"></i><b>6.4</b> Chi-Square Tests</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi-syntax"><i class="fa fa-check"></i><b>6.4.1</b> Syntax</a></li>
<li class="chapter" data-level="6.4.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi-examples"><i class="fa fa-check"></i><b>6.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-exercises"><i class="fa fa-check"></i><b>6.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="c07-modeling.html"><a href="c07-modeling.html"><i class="fa fa-check"></i><b>7</b> Modeling</a>
<ul>
<li class="chapter" data-level="" data-path="c07-modeling.html"><a href="c07-modeling.html#prereq7"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="7.1" data-path="c07-modeling.html"><a href="c07-modeling.html#introduction-6"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="c07-modeling.html"><a href="c07-modeling.html#analysis-of-variance-anova"><i class="fa fa-check"></i><b>7.2</b> Analysis of Variance (ANOVA)</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-6"><i class="fa fa-check"></i><b>7.2.1</b> Syntax</a></li>
<li class="chapter" data-level="7.2.2" data-path="c07-modeling.html"><a href="c07-modeling.html#example-10"><i class="fa fa-check"></i><b>7.2.2</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="c07-modeling.html"><a href="c07-modeling.html#gaussian-linear-regression"><i class="fa fa-check"></i><b>7.3</b> Gaussian Linear regression</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-7"><i class="fa fa-check"></i><b>7.3.1</b> Syntax</a></li>
<li class="chapter" data-level="7.3.2" data-path="c07-modeling.html"><a href="c07-modeling.html#example-11"><i class="fa fa-check"></i><b>7.3.2</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="c07-modeling.html"><a href="c07-modeling.html#logistic-regression"><i class="fa fa-check"></i><b>7.4</b> Logistic regression</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-8"><i class="fa fa-check"></i><b>7.4.1</b> Syntax</a></li>
<li class="chapter" data-level="7.4.2" data-path="c07-modeling.html"><a href="c07-modeling.html#example-12"><i class="fa fa-check"></i><b>7.4.2</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="c07-modeling.html"><a href="c07-modeling.html#exercises-2"><i class="fa fa-check"></i><b>7.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html"><i class="fa fa-check"></i><b>8</b> Communicating Results</a>
<ul>
<li class="chapter" data-level="" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#prereq8"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="8.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#introduction-7"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#describing-results-through-text"><i class="fa fa-check"></i><b>8.2</b> Describing Results through Text</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#methodology"><i class="fa fa-check"></i><b>8.2.1</b> Methodology</a></li>
<li class="chapter" data-level="8.2.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#analysis"><i class="fa fa-check"></i><b>8.2.2</b> Analysis</a></li>
<li class="chapter" data-level="8.2.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#results"><i class="fa fa-check"></i><b>8.2.3</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#visualizing-data"><i class="fa fa-check"></i><b>8.3</b> Visualizing Data</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#tables"><i class="fa fa-check"></i><b>8.3.1</b> Tables</a></li>
<li class="chapter" data-level="8.3.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#charts-and-plots"><i class="fa fa-check"></i><b>8.3.2</b> Charts and Plots</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#reproducibility"><i class="fa fa-check"></i><b>8.4</b> Reproducibility</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#setting-random-number-seeds"><i class="fa fa-check"></i><b>8.4.1</b> Setting Random Number Seeds</a></li>
<li class="chapter" data-level="8.4.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#git"><i class="fa fa-check"></i><b>8.4.2</b> Git</a></li>
<li class="chapter" data-level="8.4.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#renv"><i class="fa fa-check"></i><b>8.4.3</b> {renv}</a></li>
<li class="chapter" data-level="8.4.4" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#quartor-markdown"><i class="fa fa-check"></i><b>8.4.4</b> Quarto/R Markdown</a></li>
<li class="chapter" data-level="8.4.5" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#the-targets-package"><i class="fa fa-check"></i><b>8.4.5</b> The {targets} package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html"><i class="fa fa-check"></i><b>9</b> National Crime Victimization Survey Vignette</a>
<ul>
<li class="chapter" data-level="" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#prereq9"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="9.1" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#introduction-8"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#data-structure"><i class="fa fa-check"></i><b>9.2</b> Data structure</a></li>
<li class="chapter" data-level="9.3" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#survey-notation"><i class="fa fa-check"></i><b>9.3</b> Survey notation</a></li>
<li class="chapter" data-level="9.4" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#data-file-preparation"><i class="fa fa-check"></i><b>9.4</b> Data file preparation</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#preparing-files-for-estimation-of-victimization-rates"><i class="fa fa-check"></i><b>9.4.1</b> Preparing files for estimation of victimization rates</a></li>
<li class="chapter" data-level="9.4.2" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#derived-demographic-variables"><i class="fa fa-check"></i><b>9.4.2</b> Derived demographic variables</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#survey-design-objects"><i class="fa fa-check"></i><b>9.5</b> Survey design objects</a></li>
<li class="chapter" data-level="9.6" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#calculating-estimates"><i class="fa fa-check"></i><b>9.6</b> Calculating estimates</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#victimization-totals"><i class="fa fa-check"></i><b>9.6.1</b> Victimization totals</a></li>
<li class="chapter" data-level="9.6.2" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#victimization-proportions"><i class="fa fa-check"></i><b>9.6.2</b> Victimization proportions</a></li>
<li class="chapter" data-level="9.6.3" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#victimization-rates"><i class="fa fa-check"></i><b>9.6.3</b> Victimization rates</a></li>
<li class="chapter" data-level="9.6.4" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#prevalence-rates"><i class="fa fa-check"></i><b>9.6.4</b> Prevalence rates</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#exercises-3"><i class="fa fa-check"></i><b>9.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html"><i class="fa fa-check"></i><b>10</b> AmericasBarometer Vignette</a>
<ul>
<li class="chapter" data-level="" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#prereq10"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="10.1" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#introduction-9"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#data-structure-1"><i class="fa fa-check"></i><b>10.2</b> Data Structure</a></li>
<li class="chapter" data-level="10.3" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#preparing-files"><i class="fa fa-check"></i><b>10.3</b> Preparing files</a></li>
<li class="chapter" data-level="10.4" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#survey-design-objects-1"><i class="fa fa-check"></i><b>10.4</b> Survey design objects</a></li>
<li class="chapter" data-level="10.5" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#calculating-estimates-and-making-tables"><i class="fa fa-check"></i><b>10.5</b> Calculating estimates and making tables</a></li>
<li class="chapter" data-level="10.6" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#mapping-survey-data"><i class="fa fa-check"></i><b>10.6</b> Mapping survey data</a></li>
<li class="chapter" data-level="10.7" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#exercises-4"><i class="fa fa-check"></i><b>10.7</b> Exercises</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tidy Survey Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="c01-intro" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Chapter 1</span> Introduction<a href="c01-intro.html#c01-intro" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Surveys are used to gather information about a population. They are frequently used by researchers, governments, and businesses to better understand public opinion and behavior. For example, a non-profit group might be interested in public opinion on a given topic, government agencies may be interested in behaviors to inform policy, or companies may survey potential consumers about what they want from their products. Developing and fielding a survey is a method to gather information about topics that interest us.</p>
<!--Consider pulling out definitions into call out boxes or a glossary-->
<p>This book focuses on how to <strong>analyze</strong> the data collected from a survey. We assume that you have conducted a survey or obtained a microdata file. Microdata, also known as respondent-level or row-level data, contains individual survey responses, analysis weights, and design variables (as opposed to opposed to summarized data in tables). For the purposes of this book, you need the weights and design variables for your survey data. These are required to accurately calculate unbiased estimates<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>. Understanding the concepts and techniques discussed in this book will help you to extract meaningful insights from your survey data.</p>
<p>To account for the weights and study design, researchers rely on statistical software such as SAS, Stata, SUDAAN, and R. In this book, we will use R to provide an overview to survey analysis. Our goal is to provide a comprehensive guide for individuals new to survey analysis but have some statistics and R programming background. We will use a combination of both the {survey} and {srvyr} packages and present the code following best practices from the tidyverse.</p>
<p>In 2003, the {survey} package was released on CRAN and has been continuously developed over time<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>. This package, primarily developed by Thomas Lumley, is extensive and includes the following features:</p>
<ul>
<li>Estimates of point estimates and their associated variances, including means, totals, ratios, quantiles, and proportions</li>
<li>Estimation of regression models, including generalized linear models, log-linear models, and survival curves</li>
<li>Variances by Taylor linearization or by replicate weights (balance repeated replication, jackknife, bootstrap, multistage bootstrap, or user-supplied)</li>
<li>Hypothesis testing for means, proportions, and more</li>
</ul>
<p>The {srvyr} package in R builds on the {survey} package. It provides wrappers for functions that align with the tidyverse philosophy, which is our motivation for using and recommending this package. We find that the {srvyr} package is user-friendly for those familiar with tidyverse packages in R. For example, while many functions in the {survey} package use variables as formulas, the {srvyr} package uses tidy selection to pass variable names<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> (a common feature in the tidyverse). Users of the tidyverse are most likely familiar with the magittr pipe (<code>%&gt;%</code>), which seamlessly works with functions from the {srvyr} package. Moreover, several common functions from {dplyr}, such as including <code>filter()</code>, <code>mutate()</code>, and <code>summarize()</code>, can be applied to survey objects. Users can streamline their analysis workflow and capitalize on the benefits of both the {srvyr} and tidyverse packages.</p>
<p>There is one limitation to the {srvyr} package: it doesn’t fully incorporate the modeling capabilities of the {survey} package into its tidy versions. This book will use the {survey} package when discussing modeling and hypothesis testing. However, we will guide you on how to apply the pipe to these functions to ensure clarity in your analyses.</p>
<div id="what-to-expect" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> What to expect<a href="c01-intro.html#what-to-expect" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This book will cover all aspects of survey research, from understanding how to create design effects to conducting descriptive analysis, statistical tests, and models. Additionally, we emphasize best practices in coding and presenting results. Throughout this book, we use real-world data and present practical examples to help you gain proficiency in survey analysis. While we provide a brief overview of survey methodology and statistical theory, this book is not intended to be the sole resource for these topics. We reference other materials throughout the book and encourage readers to seek those out for more information. Below is a summary of each chapter:</p>
<ul>
<li><strong>Chapter <a href="c02-overview-surveys.html#c02-overview-surveys">2</a></strong>: An overview of surveys and the process of designing surveys. This is only an overview, and we include many references for more in-depth knowledge.</li>
<li><strong>Chapter <a href="c03-specifying-sample-designs.html#c03-specifying-sample-designs">3</a></strong>: Specifying sampling designs. Descriptions of common sampling designs, when they are used, the math behind the mean and standard error estimates, how to specify the designs in R, and examples using real data.</li>
<li><strong>Chapter <a href="c04-understanding-survey-data-documentation.html#c04-understanding-survey-data-documentation">4</a></strong>: Understanding survey documentation. How to read the various components of survey documentation, working with missing data, and finding the documentation.</li>
<li><strong>Chapter <a href="c05-descriptive-analysis.html#c05-descriptive-analysis">5</a></strong>: Descriptive analyses. Calculating point estimates along with their standard errors, confidence intervals, and design effects.</li>
<li><strong>Chapter <a href="c06-statistical-testing.html#c06-statistical-testing">6</a></strong>: Statistical testing. Testing for differences between groups, including comparisons of means and proportions as well as goodness of fit tests, tests of independence, and tests of homogeneity.</li>
<li><strong>Chapter <a href="c07-modeling.html#c07-modeling">7</a></strong>: Modeling. Linear regression, ANOVA, and logistic regression.</li>
<li><strong>Chapter <a href="c08-communicating-results.html#c08-communicating-results">8</a></strong>: Communicating results. Describing results, reproducibility, making publishable tables and graphs, and helpful functions.</li>
<li><strong>Chapter <a href="c09-ncvs-vignette.html#c09-ncvs-vignette">9</a></strong>: National Crime Victimization Survey Vignette. A vignette on how to analyze data from the NCVS, a survey in the U.S. that collects information on crimes and their characteristics. This illustrates an analysis that requires multiple files to calculate victimization rates.</li>
<li><strong>Chapter <a href="c10-ambarom-vignette.html#c10-ambarom-vignette">10</a></strong>: AmericasBarometer Vignette. A vignette on how to analyze data from the AmericasBarometer, a survey of attitudes, evaluations, experiences, and behavior in countries in the Western Hemisphere. This includes how to make choropleth maps with survey estimates.</li>
</ul>
<p>In most chapters, you’ll find code that you can follow. Each of these chapters starts with a “set-up” section. This section will include the code needed to load the necessary packages and datasets in the chapter. We then provide the main idea of the chapter and examples on how to use the functions. Most chapters end with exercises to work through. Solutions to the exercises can be found in the Appendix.</p>
</div>
<div id="book-datasets" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Datasets used in this book<a href="c01-intro.html#book-datasets" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We work with two key datasets throughout the book: the Residential Energy Consumption Survey <span class="citation">(RECS – <a href="#ref-recs-2015-micro" role="doc-biblioref">U.S. Energy Information Administration 2017</a>)</span> and the American National Election Studies <span class="citation">(ANES – <a href="#ref-debell" role="doc-biblioref">DeBell 2010</a>)</span>. To ensure that all readers can follow the examples, we have provided analytic datasets available on OSF<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a>. If there is any data you need from the book that isn’t part of existing packages, we have created a helper function, <code>read_osf()</code>, to help you load it. Here’s how to use the code to read in the RECS and ANES datasets:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="c01-intro.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="c01-intro.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey)</span>
<span id="cb1-3"><a href="c01-intro.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(srvyr)</span>
<span id="cb1-4"><a href="c01-intro.html#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(osfr)</span>
<span id="cb1-5"><a href="c01-intro.html#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;helper-fun/helper-functions.R&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="c01-intro.html#cb2-1" aria-hidden="true" tabindex="-1"></a>recs_in <span class="ot">&lt;-</span> <span class="fu">read_osf</span>(<span class="st">&quot;recs_2015.rds&quot;</span>)</span>
<span id="cb2-2"><a href="c01-intro.html#cb2-2" aria-hidden="true" tabindex="-1"></a>anes_in <span class="ot">&lt;-</span> <span class="fu">read_osf</span>(<span class="st">&quot;anes_2020.rds&quot;</span>)</span></code></pre></div>
<p>RECS is a study that provides energy consumption and expenditures data in American households. The Energy Information Administration funds RECS, and the data is collected through interviews with energy suppliers. These interviews happen in person, over the phone, and on the web. It has been fielded 14 times between 1950 and 2020. The survey includes questions about appliances, electronics, heating, air conditioning (A/C), temperatures, water heating, lighting, energy bills, respondent demographics, and energy assistance. Below is an overview of the <code>recs_in</code> data:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="c01-intro.html#cb3-1" aria-hidden="true" tabindex="-1"></a>recs_in</span></code></pre></div>
<pre><code>## # A tibble: 5,686 × 141
##    DOEID REGIONC Region    Division MSAStatus Urbanicity HousingUnitType
##    &lt;dbl&gt;   &lt;dbl&gt; &lt;fct&gt;     &lt;fct&gt;    &lt;fct&gt;     &lt;fct&gt;      &lt;fct&gt;          
##  1 10001       4 West      Pacific  Metropol… Urban Area Single-family …
##  2 10002       3 South     West So… None      Rural      Single-family …
##  3 10003       3 South     East So… Metropol… Urban Area Single-family …
##  4 10004       2 Midwest   West No… Micropol… Urban Clu… Single-family …
##  5 10005       1 Northeast Middle … Metropol… Urban Area Single-family …
##  6 10006       1 Northeast New Eng… None      Urban Clu… Apartment: 5 o…
##  7 10007       3 South     South A… Metropol… Urban Area Apartment: 2-4…
##  8 10008       2 Midwest   East No… Metropol… Rural      Single-family …
##  9 10009       1 Northeast Middle … Metropol… Urban Area Single-family …
## 10 10010       3 South     West So… Metropol… Urban Area Single-family …
## # ℹ 5,676 more rows
## # ℹ 134 more variables: YearMade &lt;ord&gt;, SpaceHeatingUsed &lt;lgl&gt;,
## #   HeatingBehavior &lt;fct&gt;, WinterTempDay &lt;dbl&gt;, WinterTempAway &lt;dbl&gt;,
## #   WinterTempNight &lt;dbl&gt;, ACUsed &lt;lgl&gt;, ACBehavior &lt;fct&gt;,
## #   SummerTempDay &lt;dbl&gt;, SummerTempAway &lt;dbl&gt;, SummerTempNight &lt;dbl&gt;,
## #   TOTCSQFT &lt;dbl&gt;, TOTHSQFT &lt;dbl&gt;, TOTSQFT_EN &lt;dbl&gt;, TOTUCSQFT &lt;dbl&gt;,
## #   TOTUSQFT &lt;dbl&gt;, NWEIGHT &lt;dbl&gt;, BRRWT1 &lt;dbl&gt;, BRRWT2 &lt;dbl&gt;, …</code></pre>
<p>From this output, we can see that there are 5,686 rows and 141 variables. We can see that there are variables containing an ID (<code>DOEID</code>), regional information (e.g., <code>Region</code>, <code>MSAStatus</code>), along with information about the house, including the type of house (<code>HousingUnitType</code>) and when the house was built (<code>YearMade</code>). Additionally, there is a long list of weighting variables that we will use in the analysis (e.g., <code>NWEIGHT</code>, <code>BRRWT1</code>). We will discuss using these weighting variables in Chapter <a href="c03-specifying-sample-designs.html#c03-specifying-sample-designs">3</a>.</p>
<p>The ANES is a series study that has collected data from election surveys since 1948. These surveys contain data on public opinion and voting behavior in U.S. presidential elections. The 2020 survey (the data we will be using) was fielded to individuals over the web, through live video interviewing, or over with computer-assisted telephone interviewing (CATI). The survey includes questions on party affiliation, voting choice, and level of trust with the government. Here is an overview of the <code>anes_in</code> data. First, we show the variables starting with “V” followed by a number; these are the original variables. Then, we show you the remaining variables that we created based on the original data:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="c01-intro.html#cb5-1" aria-hidden="true" tabindex="-1"></a>anes_in <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">matches</span>(<span class="st">&quot;^V</span><span class="sc">\\</span><span class="st">d&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 7,453 × 22
##    V200010b V200010d V200010c    V200002 V201006 V201102 V201101 V201103
##       &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;hvn_lbll&gt; &lt;hvn_l&gt; &lt;hvn_l&gt; &lt;hvn_l&gt; &lt;hvn_l&gt;
##  1    1.01         9        2          3       2       1      -1       2
##  2    1.16        26        2          3       3       1      -1       5
##  3    0.769       41        1          3       2       1      -1       1
##  4    0.521       29        2          3       3       1      -1       1
##  5    0.966       23        1          3       2       1      -1       2
##  6    0.235       37        2          3       1       2      -1      -1
##  7    0.441        7        1          3       2       1      -1       5
##  8    0.769       37        2          3       3       2      -1      -1
##  9    1.42        32        2          3       2      -1       1       1
## 10    1.84        41        2          3       2      -1       1       1
## # ℹ 7,443 more rows
## # ℹ 14 more variables: V201025x &lt;hvn_lbll&gt;, V201231x &lt;hvn_lbll&gt;,
## #   V201233 &lt;hvn_lbll&gt;, V201237 &lt;hvn_lbll&gt;, V201507x &lt;hvn_lbll&gt;,
## #   V201510 &lt;hvn_lbll&gt;, V201549x &lt;hvn_lbll&gt;, V201600 &lt;hvn_lbll&gt;,
## #   V201617x &lt;hvn_lbll&gt;, V202066 &lt;hvn_lbll&gt;, V202109x &lt;hvn_lbll&gt;,
## #   V202072 &lt;hvn_lbll&gt;, V202073 &lt;hvn_lbll&gt;, V202110x &lt;hvn_lbll&gt;</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="c01-intro.html#cb7-1" aria-hidden="true" tabindex="-1"></a>anes_in <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">matches</span>(<span class="st">&quot;^V</span><span class="sc">\\</span><span class="st">d&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 7,453 × 20
##    InterviewMode Weight Stratum VarUnit   Age AgeGroup    Gender RaceEth
##    &lt;fct&gt;          &lt;dbl&gt; &lt;fct&gt;   &lt;fct&gt;   &lt;dbl&gt; &lt;fct&gt;       &lt;fct&gt;  &lt;fct&gt;  
##  1 Web            1.01  9       2          46 40-49       Male   Hispan…
##  2 Web            1.16  26      2          37 30-39       Female Asian,…
##  3 Web            0.769 41      1          40 40-49       Female White  
##  4 Web            0.521 29      2          41 40-49       Male   Asian,…
##  5 Web            0.966 23      1          72 70 or older Male   AI/AN  
##  6 Web            0.235 37      2          71 70 or older Female White  
##  7 Web            0.441 7       1          37 30-39       Female White  
##  8 Web            0.769 37      2          45 40-49       Female White  
##  9 Web            1.42  32      2          70 70 or older Female White  
## 10 Web            1.84  41      2          43 40-49       Male   Hispan…
## # ℹ 7,443 more rows
## # ℹ 12 more variables: PartyID &lt;fct&gt;, Education &lt;fct&gt;, Income &lt;fct&gt;,
## #   Income7 &lt;fct&gt;, CampaignInterest &lt;fct&gt;, TrustGovernment &lt;fct&gt;,
## #   TrustPeople &lt;fct&gt;, VotedPres2016 &lt;fct&gt;,
## #   VotedPres2016_selection &lt;fct&gt;, VotedPres2020 &lt;fct&gt;,
## #   VotedPres2020_selection &lt;fct&gt;, EarlyVote2020 &lt;fct&gt;</code></pre>
<p>From this output we can see that there are 7,453 rows and 42 variables. Most of the variables start with V20, so referencing the documentation for survey will be crucial to not get lost (see Chapter <a href="c04-understanding-survey-data-documentation.html#c04-understanding-survey-data-documentation">4</a>). We have created some more descriptive variables for you to use throughout this book, such as the age (<code>Age</code>) and gender (<code>Gender</code>) of the respondent, along with variables that represent their party affiliation (<code>PartyID</code>). Additionally, we need the variables <code>Weight</code> and <code>Stratum</code> to analyze this data accurately. We will discuss how to use these weighting variables in Chapters <a href="c03-specifying-sample-designs.html#c03-specifying-sample-designs">3</a> and <a href="c04-understanding-survey-data-documentation.html#c04-understanding-survey-data-documentation">4</a>.</p>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-debell" class="csl-entry">
DeBell, Matthew. 2010. <span>“How to Analyze ANES Survey Data.”</span> ANES Technical Report Series nes012492. Palo Alto, CA: Stanford University; Ann Arbor, MI: the University of Michigan. <a href="https://electionstudies.org/wp-content/uploads/2018/05/HowToAnalyzeANESData.pdf">https://electionstudies.org/wp-content/uploads/2018/05/HowToAnalyzeANESData.pdf</a>.
</div>
<div id="ref-recs-2015-micro" class="csl-entry">
U.S. Energy Information Administration. 2017. <span>“Residential Energy Consumption Survey (RECS): Using the 2015 Microdata File to Compute Estimates and Standard Errors (RSEs).”</span> <a href="https://www.eia.gov/consumption/residential/data/2015/pdf/microdata_v3.pdf">https://www.eia.gov/consumption/residential/data/2015/pdf/microdata_v3.pdf</a>.
</div>
<div id="ref-Valliant2018weights" class="csl-entry">
Valliant, Richard, and Jill A. Dever. 2018. <em>Survey Weights: A Step-by-Step Guide to Calculation</em>. Stata Press.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>If you do not already have weights created for the survey data you are using, we recommend reviewing other resources focused on weight creation such as <span class="citation">Valliant and Dever (<a href="#ref-Valliant2018weights" role="doc-biblioref">2018</a>)</span><a href="c01-intro.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p><a href="https://cran.r-project.org/src/contrib/Archive/survey/" class="uri">https://cran.r-project.org/src/contrib/Archive/survey/</a><a href="c01-intro.html#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p><a href="https://dplyr.tidyverse.org/reference/dplyr_tidy_select.html" class="uri">https://dplyr.tidyverse.org/reference/dplyr_tidy_select.html</a><a href="c01-intro.html#fnref3" class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p><a href="https://osf.io/gzbkn/?view_only=8ca80573293b4e12b7f934a0f742b957" class="uri">https://osf.io/gzbkn/?view_only=8ca80573293b4e12b7f934a0f742b957</a><a href="c01-intro.html#fnref4" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="c02-overview-surveys.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/01-introduction.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
