<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Getting started | Exploring Complex Survey Data Analysis in R</title>
  <meta name="description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Getting started | Exploring Complex Survey Data Analysis in R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  <meta name="github-repo" content="tidy-survey-r/tidy-survey-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Getting started | Exploring Complex Survey Data Analysis in R" />
  
  <meta name="twitter:description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  

<meta name="author" content="Stephanie Zimmer, Rebecca J. Powell, and Isabella Velásquez" />


<meta name="date" content="2024-03-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="c03-understanding-survey-data-documentation.html"/>
<link rel="next" href="c05-descriptive-analysis.html"/>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>
<script src="libs/htmlwidgets/htmlwidgets.js"></script>
<script src="libs/d3/d3.min.js"></script>
<script src="libs/dagre/dagre-d3.min.js"></script>
<link href="libs/mermaid/dist/mermaid.css" rel="stylesheet" />
<script src="libs/mermaid/dist/mermaid.slim.min.js"></script>
<link href="libs/DiagrammeR-styles/styles.css" rel="stylesheet" />
<script src="libs/chromatography/chromatography.js"></script>
<script src="libs/DiagrammeR-binding/DiagrammeR.js"></script>
<script defer data-domain="tidy-survey-r.github.io/tidy-survey-book" src="https://plausible.io/js/script.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Exploring Complex Survey Data Analysis in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="part"><span><b>I Intro</b></span></li>
<li class="chapter" data-level="1" data-path="c01-intro.html"><a href="c01-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="c01-intro.html"><a href="c01-intro.html#what-to-expect"><i class="fa fa-check"></i><b>1.1</b> What to expect</a></li>
<li class="chapter" data-level="1.2" data-path="c01-intro.html"><a href="c01-intro.html#datasets-used-in-this-book"><i class="fa fa-check"></i><b>1.2</b> Datasets used in this book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html"><i class="fa fa-check"></i><b>2</b> Overview of Surveys</a>
<ul>
<li class="chapter" data-level="2.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#searching-for-public-use-survey-data"><i class="fa fa-check"></i><b>2.2</b> Searching for public-use survey data</a></li>
<li class="chapter" data-level="2.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#pre-survey-planning"><i class="fa fa-check"></i><b>2.3</b> Pre-Survey Planning</a></li>
<li class="chapter" data-level="2.4" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design"><i class="fa fa-check"></i><b>2.4</b> Study Design</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-sampdesign"><i class="fa fa-check"></i><b>2.4.1</b> Sampling Design</a></li>
<li class="chapter" data-level="2.4.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-dcplanning"><i class="fa fa-check"></i><b>2.4.2</b> Data Collection Planning</a></li>
<li class="chapter" data-level="2.4.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-questionnaire"><i class="fa fa-check"></i><b>2.4.3</b> Questionnaire Design</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-datacollection"><i class="fa fa-check"></i><b>2.5</b> Data Collection</a></li>
<li class="chapter" data-level="2.6" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post"><i class="fa fa-check"></i><b>2.6</b> Post-Survey Processing</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-cleaning"><i class="fa fa-check"></i><b>2.6.1</b> Data Cleaning and Imputation</a></li>
<li class="chapter" data-level="2.6.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-weighting"><i class="fa fa-check"></i><b>2.6.2</b> Weighting</a></li>
<li class="chapter" data-level="2.6.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-disclosure"><i class="fa fa-check"></i><b>2.6.3</b> Disclosure</a></li>
<li class="chapter" data-level="2.6.4" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-documentation"><i class="fa fa-check"></i><b>2.6.4</b> Documentation</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#post-survey-data-analysis-and-reporting"><i class="fa fa-check"></i><b>2.7</b> Post-survey data analysis and reporting</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html"><i class="fa fa-check"></i><b>3</b> Understanding Survey Data Documentation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#types-of-survey-documentation"><i class="fa fa-check"></i><b>3.2</b> Types of survey documentation</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#technical-documentation"><i class="fa fa-check"></i><b>3.2.1</b> Technical documentation</a></li>
<li class="chapter" data-level="3.2.2" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#questionnaires"><i class="fa fa-check"></i><b>3.2.2</b> Questionnaires</a></li>
<li class="chapter" data-level="3.2.3" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#codebooks"><i class="fa fa-check"></i><b>3.2.3</b> Codebooks</a></li>
<li class="chapter" data-level="3.2.4" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#errata"><i class="fa fa-check"></i><b>3.2.4</b> Errata</a></li>
<li class="chapter" data-level="3.2.5" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#additional-resources"><i class="fa fa-check"></i><b>3.2.5</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#missing-data-coding"><i class="fa fa-check"></i><b>3.3</b> Missing data coding</a></li>
<li class="chapter" data-level="3.4" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#example-american-national-election-studies-anes-2020-survey-documentation"><i class="fa fa-check"></i><b>3.4</b> Example: American National Election Studies (ANES) 2020 Survey Documentation</a>
<ul>
<li class="chapter" data-level="" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#methodology"><i class="fa fa-check"></i>Methodology</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Analysis</b></span></li>
<li class="chapter" data-level="4" data-path="c04-getting-started.html"><a href="c04-getting-started.html"><i class="fa fa-check"></i><b>4</b> Getting started</a>
<ul>
<li class="chapter" data-level="4.1" data-path="c04-getting-started.html"><a href="c04-getting-started.html#introduction-3"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="c04-getting-started.html"><a href="c04-getting-started.html#setup"><i class="fa fa-check"></i><b>4.2</b> Setup</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="c04-getting-started.html"><a href="c04-getting-started.html#packages"><i class="fa fa-check"></i><b>4.2.1</b> Packages</a></li>
<li class="chapter" data-level="4.2.2" data-path="c04-getting-started.html"><a href="c04-getting-started.html#data"><i class="fa fa-check"></i><b>4.2.2</b> Data</a></li>
<li class="chapter" data-level="4.2.3" data-path="c04-getting-started.html"><a href="c04-getting-started.html#setup-des-obj"><i class="fa fa-check"></i><b>4.2.3</b> Design objects</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="c04-getting-started.html"><a href="c04-getting-started.html#survey-analysis-process"><i class="fa fa-check"></i><b>4.3</b> Survey analysis process</a></li>
<li class="chapter" data-level="4.4" data-path="c04-getting-started.html"><a href="c04-getting-started.html#similarities-dplyr-srvyr"><i class="fa fa-check"></i><b>4.4</b> Similarities between {dplyr} and {srvyr} functions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html"><i class="fa fa-check"></i><b>5</b> Descriptive analyses</a>
<ul>
<li class="chapter" data-level="" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#prereq5"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="5.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#introduction-4"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#counts-and-cross-tabulations"><i class="fa fa-check"></i><b>5.2</b> Counts and cross-tabulations</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-count-syntax"><i class="fa fa-check"></i><b>5.2.1</b> Syntax</a></li>
<li class="chapter" data-level="5.2.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples"><i class="fa fa-check"></i><b>5.2.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#totals-and-sums"><i class="fa fa-check"></i><b>5.3</b> Totals and sums</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax"><i class="fa fa-check"></i><b>5.3.1</b> Syntax</a></li>
<li class="chapter" data-level="5.3.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-1"><i class="fa fa-check"></i><b>5.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-meanprop"><i class="fa fa-check"></i><b>5.4</b> Means and proportions</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-meanprop-syntax"><i class="fa fa-check"></i><b>5.4.1</b> Syntax</a></li>
<li class="chapter" data-level="5.4.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-2"><i class="fa fa-check"></i><b>5.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#quantiles-and-medians"><i class="fa fa-check"></i><b>5.5</b> Quantiles and medians</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-1"><i class="fa fa-check"></i><b>5.5.1</b> Syntax</a></li>
<li class="chapter" data-level="5.5.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-3"><i class="fa fa-check"></i><b>5.5.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#ratios"><i class="fa fa-check"></i><b>5.6</b> Ratios</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-2"><i class="fa fa-check"></i><b>5.6.1</b> Syntax</a></li>
<li class="chapter" data-level="5.6.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-4"><i class="fa fa-check"></i><b>5.6.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#correlations"><i class="fa fa-check"></i><b>5.7</b> Correlations</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-3"><i class="fa fa-check"></i><b>5.7.1</b> Syntax</a></li>
<li class="chapter" data-level="5.7.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-5"><i class="fa fa-check"></i><b>5.7.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#standard-deviation-and-variance"><i class="fa fa-check"></i><b>5.8</b> Standard deviation and variance</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-4"><i class="fa fa-check"></i><b>5.8.1</b> Syntax</a></li>
<li class="chapter" data-level="5.8.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-6"><i class="fa fa-check"></i><b>5.8.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#additional-topics"><i class="fa fa-check"></i><b>5.9</b> Additional topics</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#unweighted-analysis"><i class="fa fa-check"></i><b>5.9.1</b> Unweighted analysis</a></li>
<li class="chapter" data-level="5.9.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#subpopulation-analysis"><i class="fa fa-check"></i><b>5.9.2</b> Subpopulation analysis</a></li>
<li class="chapter" data-level="5.9.3" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-deff"><i class="fa fa-check"></i><b>5.9.3</b> Design effects</a></li>
<li class="chapter" data-level="5.9.4" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#creating-summary-rows"><i class="fa fa-check"></i><b>5.9.4</b> Creating summary rows</a></li>
<li class="chapter" data-level="5.9.5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#calculating-estimates-for-many-outcomes"><i class="fa fa-check"></i><b>5.9.5</b> Calculating estimates for many outcomes</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#exercises"><i class="fa fa-check"></i><b>5.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html"><i class="fa fa-check"></i><b>6</b> Statistical testing</a>
<ul>
<li class="chapter" data-level="" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#prereq6"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="6.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#introduction-5"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#dot-notation"><i class="fa fa-check"></i><b>6.2</b> Dot Notation</a></li>
<li class="chapter" data-level="6.3" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest"><i class="fa fa-check"></i><b>6.3</b> Comparison of Proportions and Means</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest-syntax"><i class="fa fa-check"></i><b>6.3.1</b> Syntax</a></li>
<li class="chapter" data-level="6.3.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest-examples"><i class="fa fa-check"></i><b>6.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi"><i class="fa fa-check"></i><b>6.4</b> Chi-Square Tests</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi-syntax"><i class="fa fa-check"></i><b>6.4.1</b> Syntax</a></li>
<li class="chapter" data-level="6.4.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi-examples"><i class="fa fa-check"></i><b>6.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-exercises"><i class="fa fa-check"></i><b>6.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="c07-modeling.html"><a href="c07-modeling.html"><i class="fa fa-check"></i><b>7</b> Modeling</a>
<ul>
<li class="chapter" data-level="" data-path="c07-modeling.html"><a href="c07-modeling.html#prereq7"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="7.1" data-path="c07-modeling.html"><a href="c07-modeling.html#model-intro"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="c07-modeling.html"><a href="c07-modeling.html#analysis-of-variance-anova"><i class="fa fa-check"></i><b>7.2</b> Analysis of Variance (ANOVA)</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-6"><i class="fa fa-check"></i><b>7.2.1</b> Syntax</a></li>
<li class="chapter" data-level="7.2.2" data-path="c07-modeling.html"><a href="c07-modeling.html#example-1"><i class="fa fa-check"></i><b>7.2.2</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="c07-modeling.html"><a href="c07-modeling.html#normal-linear-regression"><i class="fa fa-check"></i><b>7.3</b> Normal Linear Regression</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-7"><i class="fa fa-check"></i><b>7.3.1</b> Syntax</a></li>
<li class="chapter" data-level="7.3.2" data-path="c07-modeling.html"><a href="c07-modeling.html#examples-7"><i class="fa fa-check"></i><b>7.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="c07-modeling.html"><a href="c07-modeling.html#logistic-regression"><i class="fa fa-check"></i><b>7.4</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-8"><i class="fa fa-check"></i><b>7.4.1</b> Syntax</a></li>
<li class="chapter" data-level="7.4.2" data-path="c07-modeling.html"><a href="c07-modeling.html#examples-8"><i class="fa fa-check"></i><b>7.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="c07-modeling.html"><a href="c07-modeling.html#exercises-1"><i class="fa fa-check"></i><b>7.5</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>III Reporting</b></span></li>
<li class="chapter" data-level="8" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html"><i class="fa fa-check"></i><b>8</b> Communicating results</a>
<ul>
<li class="chapter" data-level="" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#prereq8"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="8.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#introduction-6"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#describing-results-through-text"><i class="fa fa-check"></i><b>8.2</b> Describing results through text</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#methodology-1"><i class="fa fa-check"></i><b>8.2.1</b> Methodology</a></li>
<li class="chapter" data-level="8.2.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#analysis"><i class="fa fa-check"></i><b>8.2.2</b> Analysis</a></li>
<li class="chapter" data-level="8.2.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#results"><i class="fa fa-check"></i><b>8.2.3</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#visualizing-data"><i class="fa fa-check"></i><b>8.3</b> Visualizing data</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#tables"><i class="fa fa-check"></i><b>8.3.1</b> Tables</a></li>
<li class="chapter" data-level="8.3.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#charts-and-plots"><i class="fa fa-check"></i><b>8.3.2</b> Charts and plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html"><i class="fa fa-check"></i><b>9</b> Reproducible research</a>
<ul>
<li class="chapter" data-level="9.1" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#introduction-7"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#project-based-workflows"><i class="fa fa-check"></i><b>9.2</b> Project-based workflows</a></li>
<li class="chapter" data-level="9.3" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#functions-and-packages"><i class="fa fa-check"></i><b>9.3</b> Functions and packages</a></li>
<li class="chapter" data-level="9.4" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#version-control-with-git"><i class="fa fa-check"></i><b>9.4</b> Version control with Git</a></li>
<li class="chapter" data-level="9.5" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#package-management-with-renv"><i class="fa fa-check"></i><b>9.5</b> Package management with {renv}</a></li>
<li class="chapter" data-level="9.6" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#r-environments-with-docker"><i class="fa fa-check"></i><b>9.6</b> R environments with Docker</a></li>
<li class="chapter" data-level="9.7" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#workflow-management-with-targets"><i class="fa fa-check"></i><b>9.7</b> Workflow management with {targets}</a></li>
<li class="chapter" data-level="9.8" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#documentation-with-quarto-and-r-markdown"><i class="fa fa-check"></i><b>9.8</b> Documentation with Quarto and R Markdown</a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#parameterization"><i class="fa fa-check"></i><b>9.8.1</b> Parameterization</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#other-tips-for-reproducibility"><i class="fa fa-check"></i><b>9.9</b> Other tips for reproducibility</a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#random-number-seeds"><i class="fa fa-check"></i><b>9.9.1</b> Random number seeds</a></li>
<li class="chapter" data-level="9.9.2" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#descriptive-names-and-labels"><i class="fa fa-check"></i><b>9.9.2</b> Descriptive names and labels</a></li>
</ul></li>
<li class="chapter" data-level="9.10" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#summary"><i class="fa fa-check"></i><b>9.10</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>IV Real life data</b></span></li>
<li class="chapter" data-level="10" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html"><i class="fa fa-check"></i><b>10</b> Specifying sample designs and replicate weights in {srvyr}</a>
<ul>
<li class="chapter" data-level="" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#prereq3"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="10.1" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#introduction-8"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#common-sampling-designs"><i class="fa fa-check"></i><b>10.2</b> Common sampling designs</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#simple-random-sample-without-replacement"><i class="fa fa-check"></i><b>10.2.1</b> Simple random sample without replacement</a></li>
<li class="chapter" data-level="10.2.2" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#simple-random-sample-with-replacement"><i class="fa fa-check"></i><b>10.2.2</b> Simple random sample with replacement</a></li>
<li class="chapter" data-level="10.2.3" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#stratified-sampling"><i class="fa fa-check"></i><b>10.2.3</b> Stratified sampling</a></li>
<li class="chapter" data-level="10.2.4" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#samp-cluster"><i class="fa fa-check"></i><b>10.2.4</b> Clustered sampling</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#samp-combo"><i class="fa fa-check"></i><b>10.3</b> Combining sampling methods</a>
<ul>
<li class="chapter" data-level="" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#example-6"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#replicate-weights"><i class="fa fa-check"></i><b>10.4</b> Replicate weights</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#balanced-repeated-replication-brr-method"><i class="fa fa-check"></i><b>10.4.1</b> Balanced Repeated Replication (BRR) method</a></li>
<li class="chapter" data-level="10.4.2" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#fays-brr-method"><i class="fa fa-check"></i><b>10.4.2</b> Fay’s BRR method</a></li>
<li class="chapter" data-level="10.4.3" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#jackknife-method"><i class="fa fa-check"></i><b>10.4.3</b> Jackknife method</a></li>
<li class="chapter" data-level="10.4.4" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#bootstrap-method"><i class="fa fa-check"></i><b>10.4.4</b> Bootstrap method</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#exercises-2"><i class="fa fa-check"></i><b>10.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="c11-missing-data.html"><a href="c11-missing-data.html"><i class="fa fa-check"></i><b>11</b> Missing data</a>
<ul>
<li class="chapter" data-level="" data-path="c11-missing-data.html"><a href="c11-missing-data.html#prereq11"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="11.1" data-path="c11-missing-data.html"><a href="c11-missing-data.html#introduction-9"><i class="fa fa-check"></i><b>11.1</b> Introduction</a></li>
<li class="chapter" data-level="11.2" data-path="c11-missing-data.html"><a href="c11-missing-data.html#missing-data-mechanisms"><i class="fa fa-check"></i><b>11.2</b> Missing data mechanisms</a></li>
<li class="chapter" data-level="11.3" data-path="c11-missing-data.html"><a href="c11-missing-data.html#assessing-missing-data"><i class="fa fa-check"></i><b>11.3</b> Assessing missing data</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="c11-missing-data.html"><a href="c11-missing-data.html#summarize-data"><i class="fa fa-check"></i><b>11.3.1</b> Summarize data</a></li>
<li class="chapter" data-level="11.3.2" data-path="c11-missing-data.html"><a href="c11-missing-data.html#visualization-of-missing-data"><i class="fa fa-check"></i><b>11.3.2</b> Visualization of missing data</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="c11-missing-data.html"><a href="c11-missing-data.html#analysis-with-missing-data"><i class="fa fa-check"></i><b>11.4</b> Analysis with missing data</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="c11-missing-data.html"><a href="c11-missing-data.html#recoding-missing-data"><i class="fa fa-check"></i><b>11.4.1</b> Recoding missing data</a></li>
<li class="chapter" data-level="11.4.2" data-path="c11-missing-data.html"><a href="c11-missing-data.html#accounting-for-skip-patterns"><i class="fa fa-check"></i><b>11.4.2</b> Accounting for skip patterns</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="c12-pitfalls.html"><a href="c12-pitfalls.html"><i class="fa fa-check"></i><b>12</b> Common pitfalls</a></li>
<li class="part"><span><b>V Vignettes</b></span></li>
<li class="chapter" data-level="13" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html"><i class="fa fa-check"></i><b>13</b> National Crime Victimization Survey Vignette</a>
<ul>
<li class="chapter" data-level="" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#prereq9"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="13.1" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#introduction-10"><i class="fa fa-check"></i><b>13.1</b> Introduction</a></li>
<li class="chapter" data-level="13.2" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#data-structure"><i class="fa fa-check"></i><b>13.2</b> Data Structure</a></li>
<li class="chapter" data-level="13.3" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#survey-notation"><i class="fa fa-check"></i><b>13.3</b> Survey Notation</a></li>
<li class="chapter" data-level="13.4" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#data-file-preparation"><i class="fa fa-check"></i><b>13.4</b> Data File Preparation</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#preparing-files-for-estimation-of-victimization-rates"><i class="fa fa-check"></i><b>13.4.1</b> Preparing Files for Estimation of Victimization Rates</a></li>
<li class="chapter" data-level="13.4.2" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#derived-demographic-variables"><i class="fa fa-check"></i><b>13.4.2</b> Derived Demographic Variables</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#survey-design-objects"><i class="fa fa-check"></i><b>13.5</b> Survey Design Objects</a></li>
<li class="chapter" data-level="13.6" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#calculating-estimates"><i class="fa fa-check"></i><b>13.6</b> Calculating Estimates</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#vic-tot"><i class="fa fa-check"></i><b>13.6.1</b> Estimation 1: Victimization Totals</a></li>
<li class="chapter" data-level="13.6.2" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#vic-prop"><i class="fa fa-check"></i><b>13.6.2</b> Estimation 2: Victimization Proportions</a></li>
<li class="chapter" data-level="13.6.3" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#vic-rate"><i class="fa fa-check"></i><b>13.6.3</b> Estimation 3: Victimization Rates</a></li>
<li class="chapter" data-level="13.6.4" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#prev-rate"><i class="fa fa-check"></i><b>13.6.4</b> Estimation 4: Prevalence Rates</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#statistical-testing"><i class="fa fa-check"></i><b>13.7</b> Statistical testing</a></li>
<li class="chapter" data-level="13.8" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#exercises-3"><i class="fa fa-check"></i><b>13.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html"><i class="fa fa-check"></i><b>14</b> AmericasBarometer Vignette</a>
<ul>
<li class="chapter" data-level="" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#prereq10"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="14.1" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#introduction-11"><i class="fa fa-check"></i><b>14.1</b> Introduction</a></li>
<li class="chapter" data-level="14.2" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#data-structure-1"><i class="fa fa-check"></i><b>14.2</b> Data structure</a></li>
<li class="chapter" data-level="14.3" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#preparing-files"><i class="fa fa-check"></i><b>14.3</b> Preparing files</a></li>
<li class="chapter" data-level="14.4" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#survey-design-objects-1"><i class="fa fa-check"></i><b>14.4</b> Survey design objects</a></li>
<li class="chapter" data-level="14.5" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#ambarom-estimates"><i class="fa fa-check"></i><b>14.5</b> Calculating estimates</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#example-worried-about-covid"><i class="fa fa-check"></i><b>14.5.1</b> Example: Worried about COVID</a></li>
<li class="chapter" data-level="14.5.2" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#example-education-affected-by-covid"><i class="fa fa-check"></i><b>14.5.2</b> Example: Education affected by COVID</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#ambarom-maps"><i class="fa fa-check"></i><b>14.6</b> Mapping survey data</a></li>
<li class="chapter" data-level="14.7" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#exercises-4"><i class="fa fa-check"></i><b>14.7</b> Exercises</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="anes-cb.html"><a href="anes-cb.html"><i class="fa fa-check"></i><b>A</b> ANES Derived Variable Codebook</a>
<ul>
<li class="chapter" data-level="A.1" data-path="anes-cb.html"><a href="anes-cb.html#admin"><i class="fa fa-check"></i><b>A.1</b> ADMIN</a></li>
<li class="chapter" data-level="A.2" data-path="anes-cb.html"><a href="anes-cb.html#weights"><i class="fa fa-check"></i><b>A.2</b> WEIGHTS</a></li>
<li class="chapter" data-level="A.3" data-path="anes-cb.html"><a href="anes-cb.html#pre-election-survey-questionnaire"><i class="fa fa-check"></i><b>A.3</b> PRE-ELECTION SURVEY QUESTIONNAIRE</a></li>
<li class="chapter" data-level="A.4" data-path="anes-cb.html"><a href="anes-cb.html#post-election-survey-questionnaire"><i class="fa fa-check"></i><b>A.4</b> POST-ELECTION SURVEY QUESTIONNAIRE</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="recs-cb.html"><a href="recs-cb.html"><i class="fa fa-check"></i><b>B</b> RECS Derived Variable Codebook</a>
<ul>
<li class="chapter" data-level="B.1" data-path="recs-cb.html"><a href="recs-cb.html#admin-1"><i class="fa fa-check"></i><b>B.1</b> ADMIN</a></li>
<li class="chapter" data-level="B.2" data-path="recs-cb.html"><a href="recs-cb.html#geography"><i class="fa fa-check"></i><b>B.2</b> GEOGRAPHY</a></li>
<li class="chapter" data-level="B.3" data-path="recs-cb.html"><a href="recs-cb.html#weather"><i class="fa fa-check"></i><b>B.3</b> WEATHER</a></li>
<li class="chapter" data-level="B.4" data-path="recs-cb.html"><a href="recs-cb.html#your-home"><i class="fa fa-check"></i><b>B.4</b> YOUR HOME</a></li>
<li class="chapter" data-level="B.5" data-path="recs-cb.html"><a href="recs-cb.html#space-heating"><i class="fa fa-check"></i><b>B.5</b> SPACE HEATING</a></li>
<li class="chapter" data-level="B.6" data-path="recs-cb.html"><a href="recs-cb.html#air-conditioning"><i class="fa fa-check"></i><b>B.6</b> AIR CONDITIONING</a></li>
<li class="chapter" data-level="B.7" data-path="recs-cb.html"><a href="recs-cb.html#thermostat"><i class="fa fa-check"></i><b>B.7</b> THERMOSTAT</a></li>
<li class="chapter" data-level="B.8" data-path="recs-cb.html"><a href="recs-cb.html#weights-1"><i class="fa fa-check"></i><b>B.8</b> WEIGHTS</a></li>
<li class="chapter" data-level="B.9" data-path="recs-cb.html"><a href="recs-cb.html#consumption-and-expenditure"><i class="fa fa-check"></i><b>B.9</b> CONSUMPTION AND EXPENDITURE</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html"><i class="fa fa-check"></i><b>C</b> Importing survey data into R</a>
<ul>
<li class="chapter" data-level="C.1" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-delimiter-separated-files-into-r"><i class="fa fa-check"></i><b>C.1</b> Importing delimiter-separated files into R</a></li>
<li class="chapter" data-level="C.2" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#loading-excel-files-into-r"><i class="fa fa-check"></i><b>C.2</b> Loading Excel files into R</a></li>
<li class="chapter" data-level="C.3" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-stata-sas-and-spss-files-into-r"><i class="fa fa-check"></i><b>C.3</b> Importing Stata, SAS, and SPSS files into R</a>
<ul>
<li class="chapter" data-level="C.3.1" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#syntax-9"><i class="fa fa-check"></i><b>C.3.1</b> Syntax</a></li>
<li class="chapter" data-level="C.3.2" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#working-with-labeled-data"><i class="fa fa-check"></i><b>C.3.2</b> Working with labeled data</a></li>
<li class="chapter" data-level="C.3.3" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#labeled-missing-data-values"><i class="fa fa-check"></i><b>C.3.3</b> Labeled missing data values</a></li>
</ul></li>
<li class="chapter" data-level="C.4" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-data-from-apis-into-r"><i class="fa fa-check"></i><b>C.4</b> Importing data from APIs into R</a></li>
<li class="chapter" data-level="C.5" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#accessing-databases-in-r"><i class="fa fa-check"></i><b>C.5</b> Accessing databases in R</a></li>
<li class="chapter" data-level="C.6" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-data-from-other-formats"><i class="fa fa-check"></i><b>C.6</b> Importing data from other formats</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Exploring Complex Survey Data Analysis in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="c04-getting-started" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Getting started<a href="c04-getting-started.html#c04-getting-started" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introduction-3" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Introduction<a href="c04-getting-started.html#introduction-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This chapter provides an overview of the packages, data, and design objects we use frequently throughout this book. As mentioned in Chapter <a href="c02-overview-surveys.html#c02-overview-surveys">2</a>, understanding how a survey was conducted helps us make sense of the results and interpret findings. Therefore, we provide background on the datasets used in examples and exercises. Next, we walk through how to create the survey design objects necessary to begin analysis. Finally, we provide an overview of the {srvyr} package and the steps needed for analysis. If you have questions or face issues while going through the book, please report them in the book’s <a href="https://github.com/tidy-survey-r/tidy-survey-book">GitHub repository</a>.</p>
</div>
<div id="setup" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Setup<a href="c04-getting-started.html#setup" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The Setup section provides details on the required packages and data, as well as the steps for preparing survey design objects. For a streamlined learning experience, we recommend taking the time to walk through the code provided and making sure everything is properly set up.</p>
<div id="packages" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Packages<a href="c04-getting-started.html#packages" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We use several packages throughout the book, but let’s install and load specific ones for this chapter. Many functions in the examples and exercises are from three packages: {tidyverse}, {survey}, and {srvyr}. If they are not already installed, use the code below. The {tidyverse} and {survey} packages can both be installed from the Comprehensive R Archive Network (CRAN). We use the GitHub development version of {srvyr} because of its additional functionality compared to the one on CRAN. Install the package directly from GitHub using the {remotes} package:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="c04-getting-started.html#cb13-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">&quot;tidyverse&quot;</span>, <span class="st">&quot;survey&quot;</span>, <span class="st">&quot;remotes&quot;</span>))</span>
<span id="cb13-2"><a href="c04-getting-started.html#cb13-2" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;gergness/srvyr&quot;</span>)</span></code></pre></div>
<p>We bundled the datasets used in the book in an R package, {srvyrexploR}. Install it directly from GitHub using the {remotes} package:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="c04-getting-started.html#cb14-1" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;tidy-survey-r/srvyrexploR&quot;</span>)</span></code></pre></div>
<p>After installing these packages, load them using the <code>library()</code> function:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="c04-getting-started.html#cb15-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb15-2"><a href="c04-getting-started.html#cb15-2" tabindex="-1"></a><span class="fu">library</span>(survey)</span>
<span id="cb15-3"><a href="c04-getting-started.html#cb15-3" tabindex="-1"></a><span class="fu">library</span>(srvyr)</span>
<span id="cb15-4"><a href="c04-getting-started.html#cb15-4" tabindex="-1"></a><span class="fu">library</span>(srvyrexploR)</span></code></pre></div>
<p>The packages {broom}, {gt}, and {gtsummary} play a role in displaying output and creating formatted tables. Install them with the provided code<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a>:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="c04-getting-started.html#cb16-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">&quot;gt&quot;</span>, <span class="st">&quot;gtsummary&quot;</span>))</span></code></pre></div>
<p>After installing these packages, load them using the <code>library()</code> function:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="c04-getting-started.html#cb17-1" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb17-2"><a href="c04-getting-started.html#cb17-2" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb17-3"><a href="c04-getting-started.html#cb17-3" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span></code></pre></div>
<p>Install and load the {censusapi} package to access the Current Population Survey (CPS), which we use to ensure accurate weighting of a key dataset in the book. Run the code below to install {censusapi}:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="c04-getting-started.html#cb18-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;censusapi&quot;</span>)</span></code></pre></div>
<p>After installing this package, load it using the <code>library()</code> function:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="c04-getting-started.html#cb19-1" tabindex="-1"></a><span class="fu">library</span>(censusapi)</span></code></pre></div>
<p>Note that the {censusapi} package requires a Census API key, available for free from the <a href="https://api.census.gov/data/key_signup.html">U.S. Census Bureau website</a> (refer to the package documentation for more information). We recommend storing the Census API key in our R environment instead of directly in the code. After obtaining the API key, save it in your R environment by running <code>Sys.setenv()</code>:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="c04-getting-started.html#cb20-1" tabindex="-1"></a><span class="fu">Sys.setenv</span>(<span class="at">CENSUS_KEY=</span><span class="st">&quot;YOUR_API_KEY_HERE&quot;</span>)</span></code></pre></div>
<p>Then, restart the R session. Once the Census API key is stored, we can retrieve it in our R code with <code>Sys.getenv("CENSUS_KEY")</code>.</p>
<p>There are a few other packages used in the book in limited frequency. We list them in the Prerequisite boxes at the beginning of each chapter. As we work through the book, make sure to check the Prerequisite box and install any missing packages before proceeding.</p>
</div>
<div id="data" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Data<a href="c04-getting-started.html#data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As mentioned above, the {srvyrexploR} package contains the datasets used in the book. Once installed and loaded, explore the documentation using the <code>help()</code> function. Read the descriptions of the datasets to understand what they contain:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="c04-getting-started.html#cb21-1" tabindex="-1"></a><span class="fu">help</span>(<span class="at">package =</span> <span class="st">&quot;srvyrexploR&quot;</span>)</span></code></pre></div>
<p>This book uses two main datasets: the American National Election Studies <span class="citation">(ANES – <a href="#ref-debell">DeBell 2010</a>)</span> and the Residential Energy Consumption Survey <span class="citation">(RECS – <a href="#ref-recs-2020-tech">U.S. Energy Information Administration 2023a</a>)</span>. We can load these datasets individually with the <code>data()</code> function by specifying the dataset name as an argument. In the code below, we load the <code>anes_2020</code> and <code>recs_2020</code> datasets into objects with their respective names:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="c04-getting-started.html#cb22-1" tabindex="-1"></a><span class="fu">data</span>(anes_2020)</span>
<span id="cb22-2"><a href="c04-getting-started.html#cb22-2" tabindex="-1"></a><span class="fu">data</span>(recs_2020)</span></code></pre></div>
<div id="american-national-election-studies-anes-data" class="section level4 unnumbered hasAnchor">
<h4>American National Election Studies (ANES) Data<a href="c04-getting-started.html#american-national-election-studies-anes-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The ANES is a study that collects data from election surveys dating back to 1948. These surveys contain information on public opinion and voting behavior in U.S. presidential elections and some midterm elections<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a>. They cover topics such as party affiliation, voting choice, and level of trust in the government. The 2020 survey, the data we use in the book, was fielded online, through live video interviews, or via computer-assisted telephone interviews (CATI).</p>
<p>When working with new survey data, analysts should review the survey documentation (see Chapter <a href="c03-understanding-survey-data-documentation.html#c03-understanding-survey-data-documentation">3</a>) to understand the data collection methods. The original ANES data contains variables starting with <code>V20</code> <span class="citation">(<a href="#ref-debell">DeBell 2010</a>)</span>, so to assist with our analysis throughout the book, we created descriptive variable names. For example, the respondent’s age is now in a variable called <code>Age</code>, and gender is in a variable called <code>Gender</code>. These descriptive variables are included in the {srvyrexploR} package, and Table <a href="c04-getting-started.html#tab:anes-view-tab">4.1</a> displays the list of these renamed variables. A complete overview of all variables can be found in Appendix <a href="anes-cb.html#anes-cb">A</a>.</p>

<div id="cwvjobtdpc" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#cwvjobtdpc table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#cwvjobtdpc thead, #cwvjobtdpc tbody, #cwvjobtdpc tfoot, #cwvjobtdpc tr, #cwvjobtdpc td, #cwvjobtdpc th {
  border-style: none;
}

#cwvjobtdpc p {
  margin: 0;
  padding: 0;
}

#cwvjobtdpc .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#cwvjobtdpc .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#cwvjobtdpc .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#cwvjobtdpc .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#cwvjobtdpc .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cwvjobtdpc .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cwvjobtdpc .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cwvjobtdpc .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#cwvjobtdpc .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#cwvjobtdpc .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#cwvjobtdpc .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#cwvjobtdpc .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#cwvjobtdpc .gt_spanner_row {
  border-bottom-style: hidden;
}

#cwvjobtdpc .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#cwvjobtdpc .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#cwvjobtdpc .gt_from_md > :first-child {
  margin-top: 0;
}

#cwvjobtdpc .gt_from_md > :last-child {
  margin-bottom: 0;
}

#cwvjobtdpc .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#cwvjobtdpc .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#cwvjobtdpc .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#cwvjobtdpc .gt_row_group_first td {
  border-top-width: 2px;
}

#cwvjobtdpc .gt_row_group_first th {
  border-top-width: 2px;
}

#cwvjobtdpc .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cwvjobtdpc .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#cwvjobtdpc .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#cwvjobtdpc .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cwvjobtdpc .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cwvjobtdpc .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#cwvjobtdpc .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#cwvjobtdpc .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#cwvjobtdpc .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cwvjobtdpc .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cwvjobtdpc .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cwvjobtdpc .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cwvjobtdpc .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cwvjobtdpc .gt_left {
  text-align: left;
}

#cwvjobtdpc .gt_center {
  text-align: center;
}

#cwvjobtdpc .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#cwvjobtdpc .gt_font_normal {
  font-weight: normal;
}

#cwvjobtdpc .gt_font_bold {
  font-weight: bold;
}

#cwvjobtdpc .gt_font_italic {
  font-style: italic;
}

#cwvjobtdpc .gt_super {
  font-size: 65%;
}

#cwvjobtdpc .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#cwvjobtdpc .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#cwvjobtdpc .gt_indent_1 {
  text-indent: 5px;
}

#cwvjobtdpc .gt_indent_2 {
  text-indent: 10px;
}

#cwvjobtdpc .gt_indent_3 {
  text-indent: 15px;
}

#cwvjobtdpc .gt_indent_4 {
  text-indent: 20px;
}

#cwvjobtdpc .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" style="table-layout: fixed;; width: 0px" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <caption><span id="tab:anes-view-tab">TABLE 4.1: </span>List of created variables in the ANES Data</caption>
  <colgroup>
    <col style="width:295px;"/>
  </colgroup>
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Variable Name">Variable Name</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="Variable Name" class="gt_row gt_left">CaseID</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">InterviewMode</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">Weight</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">VarUnit</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">Stratum</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">CampaignInterest</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">VotedPres2016</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">VotedPres2016_selection</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">PartyID</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">TrustGovernment</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">TrustPeople</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">Age</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">AgeGroup</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">Education</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">RaceEth</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">Gender</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">Income</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">Income7</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">VotedPres2020</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">VotedPres2020_selection</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">EarlyVote2020</td></tr>
  </tbody>
  
  
</table>
</div>
<p>Before beginning an analysis, it is useful to view the data to understand the available variables. The <code>dplyr::glimpse()</code> function produces a list of all variables, their types (e.g., function, double), and a few example values. Below, we remove variables containing a “V” followed by numbers with <code>select(-matches("^V\\d"))</code> before using <code>glimpse()</code> to get a quick overview of the data with descriptive variable names:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="c04-getting-started.html#cb23-1" tabindex="-1"></a>anes_2020 <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="c04-getting-started.html#cb23-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">matches</span>(<span class="st">&quot;^V</span><span class="sc">\\</span><span class="st">d&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="c04-getting-started.html#cb23-3" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 7,453
## Columns: 21
## $ CaseID                  &lt;dbl&gt; 200015, 200022, 200039, 200046, 200053…
## $ InterviewMode           &lt;fct&gt; Web, Web, Web, Web, Web, Web, Web, Web…
## $ Weight                  &lt;dbl&gt; 1.0057, 1.1635, 0.7687, 0.5210, 0.9658…
## $ VarUnit                 &lt;fct&gt; 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 2,…
## $ Stratum                 &lt;fct&gt; 9, 26, 41, 29, 23, 37, 7, 37, 32, 41, …
## $ CampaignInterest        &lt;fct&gt; Somewhat interested, Not much interest…
## $ VotedPres2016           &lt;fct&gt; Yes, Yes, Yes, Yes, Yes, No, Yes, No, …
## $ VotedPres2016_selection &lt;fct&gt; Trump, Other, Clinton, Clinton, Trump,…
## $ PartyID                 &lt;fct&gt; Strong republican, Independent, Indepe…
## $ TrustGovernment         &lt;fct&gt; Never, Never, Some of the time, About …
## $ TrustPeople             &lt;fct&gt; About half the time, Some of the time,…
## $ Age                     &lt;dbl&gt; 46, 37, 40, 41, 72, 71, 37, 45, 70, 43…
## $ AgeGroup                &lt;fct&gt; 40-49, 30-39, 40-49, 40-49, 70 or olde…
## $ Education               &lt;fct&gt; Bachelor&#39;s, Post HS, High school, Post…
## $ RaceEth                 &lt;fct&gt; &quot;Hispanic&quot;, &quot;Asian, NH/PI&quot;, &quot;White&quot;, &quot;…
## $ Gender                  &lt;fct&gt; Male, Female, Female, Male, Male, Fema…
## $ Income                  &lt;fct&gt; &quot;$175,000-249,999&quot;, &quot;$70,000-74,999&quot;, …
## $ Income7                 &lt;fct&gt; $125k or more, $60-80k, $100-125k, $20…
## $ VotedPres2020           &lt;fct&gt; NA, Yes, Yes, Yes, Yes, Yes, Yes, NA, …
## $ VotedPres2020_selection &lt;fct&gt; NA, Other, Biden, Biden, Trump, Biden,…
## $ EarlyVote2020           &lt;fct&gt; NA, No, No, No, No, No, No, NA, Yes, N…</code></pre>
<p>From the output, we can see there are 7,453 rows and 21 variables in the ANES data. This output also indicates that most of the variables are factors (e.g., <code>InterviewMode</code>), while a few variables are in double (numeric) format (e.g., <code>Age</code>).</p>
</div>
<div id="residential-energy-consumption-survey-recs-data" class="section level4 unnumbered hasAnchor">
<h4>Residential Energy Consumption Survey (RECS) Data<a href="c04-getting-started.html#residential-energy-consumption-survey-recs-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>RECS is a study that measures energy consumption and expenditure in American households. Funded by the Energy Information Administration, the RECS data are collected through interviews with household members and energy suppliers. These interviews take place in person, over the phone, via mail, and on the web with modes changing over time. The survey has been fielded 14 times between 1950 and 2020. It includes questions about appliances, electronics, heating, air conditioning (A/C), temperatures, water heating, lighting, energy bills, respondent demographics, and energy assistance.</p>
<p>As mentioned above, analysts should read the survey documentation (see Chapter <a href="c03-understanding-survey-data-documentation.html#c03-understanding-survey-data-documentation">3</a>) to understand how the data was collected and implemented. Table <a href="c04-getting-started.html#tab:recs-view-tab">4.2</a> displays the list of variables in the RECS data (not including the weights, which start with <code>NWEIGHT</code> and will be described in more detail in Chapter <a href="c10-specifying-sample-designs.html#c10-specifying-sample-designs">10</a>). An overview of all variables can be found in Appendix <a href="recs-cb.html#recs-cb">B</a>.</p>

<div id="pepikafuts" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#pepikafuts table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#pepikafuts thead, #pepikafuts tbody, #pepikafuts tfoot, #pepikafuts tr, #pepikafuts td, #pepikafuts th {
  border-style: none;
}

#pepikafuts p {
  margin: 0;
  padding: 0;
}

#pepikafuts .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#pepikafuts .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#pepikafuts .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#pepikafuts .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#pepikafuts .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pepikafuts .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pepikafuts .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pepikafuts .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#pepikafuts .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#pepikafuts .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#pepikafuts .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#pepikafuts .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#pepikafuts .gt_spanner_row {
  border-bottom-style: hidden;
}

#pepikafuts .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#pepikafuts .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#pepikafuts .gt_from_md > :first-child {
  margin-top: 0;
}

#pepikafuts .gt_from_md > :last-child {
  margin-bottom: 0;
}

#pepikafuts .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#pepikafuts .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#pepikafuts .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#pepikafuts .gt_row_group_first td {
  border-top-width: 2px;
}

#pepikafuts .gt_row_group_first th {
  border-top-width: 2px;
}

#pepikafuts .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pepikafuts .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#pepikafuts .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#pepikafuts .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pepikafuts .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pepikafuts .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#pepikafuts .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#pepikafuts .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#pepikafuts .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pepikafuts .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pepikafuts .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pepikafuts .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pepikafuts .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pepikafuts .gt_left {
  text-align: left;
}

#pepikafuts .gt_center {
  text-align: center;
}

#pepikafuts .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#pepikafuts .gt_font_normal {
  font-weight: normal;
}

#pepikafuts .gt_font_bold {
  font-weight: bold;
}

#pepikafuts .gt_font_italic {
  font-style: italic;
}

#pepikafuts .gt_super {
  font-size: 65%;
}

#pepikafuts .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#pepikafuts .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#pepikafuts .gt_indent_1 {
  text-indent: 5px;
}

#pepikafuts .gt_indent_2 {
  text-indent: 10px;
}

#pepikafuts .gt_indent_3 {
  text-indent: 15px;
}

#pepikafuts .gt_indent_4 {
  text-indent: 20px;
}

#pepikafuts .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" style="table-layout: fixed;; width: 0px" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <caption><span id="tab:recs-view-tab">TABLE 4.2: </span>List of Variables in the RECS Data</caption>
  <colgroup>
    <col style="width:295px;"/>
  </colgroup>
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Variable Name">Variable Name</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="Variable Name" class="gt_row gt_left">DOEID</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ClimateRegion_BA</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">Urbanicity</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">Region</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">REGIONC</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">Division</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">STATE_FIPS</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">state_postal</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">state_name</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">HDD65</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">CDD65</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">HDD30YR</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">CDD30YR</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">HousingUnitType</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">YearMade</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">TOTSQFT_EN</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">TOTHSQFT</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">TOTCSQFT</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZTOTSQFT_EN</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZYearMade</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZHousingUnitType</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">SpaceHeatingUsed</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZSpaceHeatingUsed</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ACUsed</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZACUsed</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZACBehavior</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">HeatingBehavior</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">WinterTempDay</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">WinterTempAway</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">WinterTempNight</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ACBehavior</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">SummerTempDay</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">SummerTempAway</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">SummerTempNight</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZHeatingBehavior</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZWinterTempAway</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZSummerTempAway</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZWinterTempDay</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZSummerTempDay</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZWinterTempNight</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZSummerTempNight</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">BTUEL</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">DOLLAREL</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZBTUEL</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">BTUNG</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">DOLLARNG</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZBTUNG</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">BTULP</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">DOLLARLP</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZBTULP</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">BTUFO</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">DOLLARFO</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZBTUFO</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">BTUWOOD</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">ZBTUWOOD</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">TOTALBTU</td></tr>
    <tr><td headers="Variable Name" class="gt_row gt_left">TOTALDOL</td></tr>
  </tbody>
  
  
</table>
</div>
<p>Before starting an analysis, we recommend viewing the data to understand the types of data and variables that are included. The <code>dplyr::glimpse()</code> function produces a list of all variables, the type of the variable (e.g., function, double), and a few example values. Below, we remove the weight variables with <code>select(-matches("^NWEIGHT"))</code> before using <code>glimpse()</code> to get a quick overview of the data:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="c04-getting-started.html#cb25-1" tabindex="-1"></a>recs_2020 <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="c04-getting-started.html#cb25-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">matches</span>(<span class="st">&quot;^NWEIGHT&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb25-3"><a href="c04-getting-started.html#cb25-3" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 18,496
## Columns: 57
## $ DOEID             &lt;dbl&gt; 1e+05, 1e+05, 1e+05, 1e+05, 1e+05, 1e+05, 1e…
## $ ClimateRegion_BA  &lt;fct&gt; Mixed-Dry, Mixed-Humid, Mixed-Dry, Mixed-Hum…
## $ Urbanicity        &lt;fct&gt; Urban Area, Urban Area, Urban Area, Urban Ar…
## $ Region            &lt;fct&gt; West, South, West, South, Northeast, South, …
## $ REGIONC           &lt;chr&gt; &quot;WEST&quot;, &quot;SOUTH&quot;, &quot;WEST&quot;, &quot;SOUTH&quot;, &quot;NORTHEAST…
## $ Division          &lt;fct&gt; Mountain South, West South Central, Mountain…
## $ STATE_FIPS        &lt;chr&gt; &quot;35&quot;, &quot;05&quot;, &quot;35&quot;, &quot;45&quot;, &quot;34&quot;, &quot;48&quot;, &quot;40&quot;, &quot;2…
## $ state_postal      &lt;fct&gt; NM, AR, NM, SC, NJ, TX, OK, MS, DC, AZ, CA, …
## $ state_name        &lt;fct&gt; New Mexico, Arkansas, New Mexico, South Caro…
## $ HDD65             &lt;dbl&gt; 3844, 3766, 3819, 2614, 4219, 901, 3148, 182…
## $ CDD65             &lt;dbl&gt; 1679, 1458, 1696, 1718, 1363, 3558, 2128, 23…
## $ HDD30YR           &lt;dbl&gt; 4451, 4429, 4500, 3229, 4896, 1150, 3564, 26…
## $ CDD30YR           &lt;dbl&gt; 1027, 1305, 1010, 1653, 1059, 3588, 2043, 21…
## $ HousingUnitType   &lt;fct&gt; Single-family detached, Apartment: 5 or more…
## $ YearMade          &lt;ord&gt; 1970-1979, 1980-1989, 1960-1969, 1980-1989, …
## $ TOTSQFT_EN        &lt;dbl&gt; 2100, 590, 900, 2100, 800, 4520, 2100, 900, …
## $ TOTHSQFT          &lt;dbl&gt; 2100, 590, 900, 2100, 800, 3010, 1200, 900, …
## $ TOTCSQFT          &lt;dbl&gt; 2100, 590, 900, 2100, 800, 3010, 1200, 0, 50…
## $ ZTOTSQFT_EN       &lt;fct&gt; Not imputed, Not imputed, Not imputed, Not i…
## $ ZYearMade         &lt;fct&gt; Not imputed, Not imputed, Not imputed, Not i…
## $ ZHousingUnitType  &lt;fct&gt; Not imputed, Not imputed, Not imputed, Not i…
## $ SpaceHeatingUsed  &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TR…
## $ ZSpaceHeatingUsed &lt;fct&gt; Not imputed, Not imputed, Not imputed, Not i…
## $ ACUsed            &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FA…
## $ ZACUsed           &lt;fct&gt; Not imputed, Not imputed, Not imputed, Not i…
## $ ZACBehavior       &lt;fct&gt; Not imputed, Imputed, Not imputed, Not imput…
## $ HeatingBehavior   &lt;fct&gt; Set one temp and leave it, Turn on or off as…
## $ WinterTempDay     &lt;dbl&gt; 70, 70, 69, 68, 68, 76, 74, 70, 68, 70, 72, …
## $ WinterTempAway    &lt;dbl&gt; 70, 65, 68, 68, 68, 76, 65, 70, 60, 70, 70, …
## $ WinterTempNight   &lt;dbl&gt; 68, 65, 67, 68, 68, 68, 74, 68, 62, 68, 72, …
## $ ACBehavior        &lt;fct&gt; Set one temp and leave it, Turn on or off as…
## $ SummerTempDay     &lt;dbl&gt; 71, 68, 70, 72, 72, 69, 68, NA, 72, 74, 77, …
## $ SummerTempAway    &lt;dbl&gt; 71, 68, 68, 72, 72, 74, 70, NA, 76, 74, 77, …
## $ SummerTempNight   &lt;dbl&gt; 71, 68, 68, 72, 72, 68, 70, NA, 68, 72, 77, …
## $ ZHeatingBehavior  &lt;fct&gt; Not imputed, Not imputed, Not imputed, Not i…
## $ ZWinterTempAway   &lt;fct&gt; Not imputed, Not imputed, Not imputed, Not i…
## $ ZSummerTempAway   &lt;fct&gt; Not imputed, Not imputed, Not imputed, Not i…
## $ ZWinterTempDay    &lt;fct&gt; Not imputed, Not imputed, Not imputed, Not i…
## $ ZSummerTempDay    &lt;fct&gt; Not imputed, Not imputed, Not imputed, Not i…
## $ ZWinterTempNight  &lt;fct&gt; Not imputed, Not imputed, Not imputed, Not i…
## $ ZSummerTempNight  &lt;fct&gt; Not imputed, Not imputed, Not imputed, Not i…
## $ BTUEL             &lt;dbl&gt; 42723, 17889, 8147, 31647, 20027, 48968, 494…
## $ DOLLAREL          &lt;dbl&gt; 1955.06, 713.27, 334.51, 1424.86, 1087.00, 1…
## $ ZBTUEL            &lt;fct&gt; Not imputed, Not imputed, Imputed amount and…
## $ BTUNG             &lt;dbl&gt; 101924.4, 10145.3, 22603.1, 55118.7, 39099.5…
## $ DOLLARNG          &lt;dbl&gt; 701.83, 261.73, 188.14, 636.91, 376.04, 439.…
## $ ZBTUNG            &lt;fct&gt; Not imputed, Not imputed, Imputed, Not imput…
## $ BTULP             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17…
## $ DOLLARLP          &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,…
## $ ZBTULP            &lt;fct&gt; Not applicable, Not applicable, Not applicab…
## $ BTUFO             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 68…
## $ DOLLARFO          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18…
## $ ZBTUFO            &lt;fct&gt; Not applicable, Not applicable, Not applicab…
## $ BTUWOOD           &lt;dbl&gt; 0, 0, 0, 0, 0, 3000, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ ZBTUWOOD          &lt;fct&gt; Not applicable, Not applicable, Not applicab…
## $ TOTALBTU          &lt;dbl&gt; 144648, 28035, 30750, 86765, 59127, 85401, 1…
## $ TOTALDOL          &lt;dbl&gt; 2656.9, 975.0, 522.6, 2061.8, 1463.0, 2335.1…</code></pre>
<p>From the output, we can see that there are 18,496 rows and 57 non-weight variables in the RECS data. This output also indicates that most of the variables are in double (numeric) format (e.g., <code>TOTSQFT_EN</code>), with some factor (e.g., <code>Region</code>), Boolean (e.g., <code>ACUsed</code>), character (e.g., <code>REGIONC</code>), and ordinal (e.g., <code>YearMade</code>) variables.</p>
</div>
</div>
<div id="setup-des-obj" class="section level3 hasAnchor" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> Design objects<a href="c04-getting-started.html#setup-des-obj" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The design object is the backbone for survey analysis. It is where we specify the sampling design, weights, and other necessary information to ensure we account for errors in the data. Before creating the design object, analysts should carefully review the survey documentation to understand how to create the design object for accurate analysis.</p>
<p>In this chapter, we provide details on how to code the design object for the ANES and RECS data used in the book. However, we only provide a high-level overview to get readers started. For a deeper understanding of creating these design objects for a variety of sampling designs, see Chapter <a href="c10-specifying-sample-designs.html#c10-specifying-sample-designs">10</a>.</p>
<p>While we recommend conducting exploratory data analysis on the original data before diving into complex survey analysis (see Chapter <a href="c12-pitfalls.html#c12-pitfalls">12</a>), the actual analysis and inference should be performed with the survey design objects instead of the original survey data. For example, the ANES data is called <code>anes_2020</code>. If we create a survey design object called <code>anes_des</code>, our analyses should begin with <code>anes_des</code> and not <code>anes_2020</code>. Using the survey design object ensures that our calculations are appropriately accounting for the details of the survey design.</p>
<div id="american-national-election-studies-anes-design-object" class="section level4 unnumbered hasAnchor">
<h4>American National Election Studies (ANES) Design Object<a href="c04-getting-started.html#american-national-election-studies-anes-design-object" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The ANES documentation <span class="citation">(<a href="#ref-debell">DeBell 2010</a>)</span> details the sampling and weighting implications for analyzing the survey data. From this documentation and as noted in Chapter <a href="c03-understanding-survey-data-documentation.html#c03-understanding-survey-data-documentation">3</a>, the 2020 ANES data is weighted to the sample, not the population. To make generalizations about the population, we need to weigh the data against the full population count. The ANES methodology recommends using the Current Population Survey (CPS) to determine the number of non-institutional U.S. citizens aged 18 or older living in the 50 U.S. states or D.C. in March of 2020.</p>
<p>We can use the {censusapi} package to obtain the information needed for the survey design object. The <code>getCensus()</code> function allows us to retrieve the CPS data for March (<code>cps/basic/mar</code>) in 2020 (<code>vintage = 2020</code>). Additionally, we extract several variables from the CPS:</p>
<ul>
<li>month (<code>HRMONTH</code>) and year (<code>HRYEAR4</code>) of the interview: to confirm the correct time period</li>
<li>age (<code>PRTAGE</code>) of the respondent: to narrow the population to 18 and older (eligible age to vote)</li>
<li>citizenship status (<code>PRCITSHP</code>) of the respondent: to narrow the population to only those eligible to vote</li>
<li>final person-level weight (<code>PWSSWGT</code>)</li>
</ul>
<p>Detailed information for these variables can be found in the <a href="https://www2.census.gov/programs-surveys/cps/datasets/2020/basic/2020_Basic_CPS_Public_Use_Record_Layout_plus_IO_Code_list.txt">CPS data dictionary</a>.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="c04-getting-started.html#cb27-1" tabindex="-1"></a>cps_state_in <span class="ot">&lt;-</span> <span class="fu">getCensus</span>(<span class="at">name =</span> <span class="st">&quot;cps/basic/mar&quot;</span>,</span>
<span id="cb27-2"><a href="c04-getting-started.html#cb27-2" tabindex="-1"></a>                          <span class="at">vintage =</span> <span class="dv">2020</span>,</span>
<span id="cb27-3"><a href="c04-getting-started.html#cb27-3" tabindex="-1"></a>                          <span class="at">region =</span> <span class="st">&quot;state&quot;</span>,</span>
<span id="cb27-4"><a href="c04-getting-started.html#cb27-4" tabindex="-1"></a>                          <span class="at">vars =</span> <span class="fu">c</span>(<span class="st">&quot;HRMONTH&quot;</span>, <span class="st">&quot;HRYEAR4&quot;</span>, </span>
<span id="cb27-5"><a href="c04-getting-started.html#cb27-5" tabindex="-1"></a>                                   <span class="st">&quot;PRTAGE&quot;</span>, <span class="st">&quot;PRCITSHP&quot;</span>, <span class="st">&quot;PWSSWGT&quot;</span>), </span>
<span id="cb27-6"><a href="c04-getting-started.html#cb27-6" tabindex="-1"></a>                          <span class="at">key =</span> <span class="fu">Sys.getenv</span>(<span class="st">&quot;CENSUS_KEY&quot;</span>))</span>
<span id="cb27-7"><a href="c04-getting-started.html#cb27-7" tabindex="-1"></a></span>
<span id="cb27-8"><a href="c04-getting-started.html#cb27-8" tabindex="-1"></a>cps_state <span class="ot">&lt;-</span> cps_state_in <span class="sc">%&gt;%</span></span>
<span id="cb27-9"><a href="c04-getting-started.html#cb27-9" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb27-10"><a href="c04-getting-started.html#cb27-10" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb27-11"><a href="c04-getting-started.html#cb27-11" tabindex="-1"></a>                <span class="at">.fns =</span> as.numeric))</span></code></pre></div>
<p>In the code above, we include <code>region = "state"</code>. The default region type for the CPS data is at the state level. While not required, including the region can be helpful for understanding the geographical context of the data.</p>
<p>In <code>getCensus()</code>, we filtered the dataset by specifying the month (<code>HRMONTH == 3</code>) and year (<code>HRYEAR4 == 2020</code>) of our request. Therefore, we expect that all interviews within our output were conducted during that particular month and year. We can confirm that the data is from March 2020 by running the code below:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="c04-getting-started.html#cb28-1" tabindex="-1"></a>cps_state <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="c04-getting-started.html#cb28-2" tabindex="-1"></a>  <span class="fu">distinct</span>(HRMONTH, HRYEAR4)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   HRMONTH HRYEAR4
##     &lt;dbl&gt;   &lt;dbl&gt;
## 1       3    2020</code></pre>
<p>We can narrow down the dataset using the age and citizenship variables to include only individuals who are 18 years or older (<code>PRTAGE &gt;= 18</code>) and have U.S. citizenship (<code>PRCITSHIP %in% c(1:4)</code>):</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="c04-getting-started.html#cb30-1" tabindex="-1"></a>cps_narrow_resp <span class="ot">&lt;-</span> cps_state <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="c04-getting-started.html#cb30-2" tabindex="-1"></a>  <span class="fu">filter</span>(PRTAGE <span class="sc">&gt;=</span> <span class="dv">18</span>,</span>
<span id="cb30-3"><a href="c04-getting-started.html#cb30-3" tabindex="-1"></a>         PRCITSHP <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>))</span></code></pre></div>
<p>To calculate the U.S. population from the filtered data, we sum the person weights (<code>PWSSWGT</code>):</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="c04-getting-started.html#cb31-1" tabindex="-1"></a>targetpop <span class="ot">&lt;-</span> cps_narrow_resp <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="c04-getting-started.html#cb31-2" tabindex="-1"></a>  <span class="fu">pull</span>(PWSSWGT) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="c04-getting-started.html#cb31-3" tabindex="-1"></a>  <span class="fu">sum</span>()</span></code></pre></div>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="c04-getting-started.html#cb32-1" tabindex="-1"></a>scales<span class="sc">::</span><span class="fu">comma</span>(targetpop)</span></code></pre></div>
<pre><code>## [1] &quot;231,034,125&quot;</code></pre>
<p>The target population in 2020 is 231,034,125. This result gives us what we need to create the survey design object for estimating population statistics. Using the <code>anes_2020</code> data, we adjust the weighting variable (<code>V200010b</code>) using the target population we just calculated (<code>targetpop</code>). We determine the proportion of the total weight for each individual weight (<code>V200010b / sum(V200010b)</code>) and then multiply that proportion by the calculated target population.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="c04-getting-started.html#cb34-1" tabindex="-1"></a>anes_adjwgt <span class="ot">&lt;-</span> anes_2020 <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="c04-getting-started.html#cb34-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Weight =</span> V200010b <span class="sc">/</span> <span class="fu">sum</span>(V200010b) <span class="sc">*</span> targetpop) </span></code></pre></div>
<p>Once we have the adjusted weights, we can refer to the rest of the documentation to create the survey design. The documentation indicates that the study uses a stratified cluster sampling design. Therefore, we need to specify variables for <code>strata</code> and <code>ids</code> (cluster) and fill in the <code>nest</code> argument. The documentation provides guidance on which strata and cluster variables to use depending on whether we are analyzing pre- or post-election data. In this book, we analyze post-election data, so we need to use the post-election weight <code>V200010b</code>, strata variable <code>V200010d</code>, and PSU/cluster variable <code>V200010c</code>. Additionally, we set <code>nest=TRUE</code> to ensure the clusters are nested within the strata.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="c04-getting-started.html#cb35-1" tabindex="-1"></a>anes_des <span class="ot">&lt;-</span> anes_adjwgt <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="c04-getting-started.html#cb35-2" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">weights =</span> Weight,</span>
<span id="cb35-3"><a href="c04-getting-started.html#cb35-3" tabindex="-1"></a>                   <span class="at">strata =</span> V200010d,</span>
<span id="cb35-4"><a href="c04-getting-started.html#cb35-4" tabindex="-1"></a>                   <span class="at">ids =</span> V200010c,</span>
<span id="cb35-5"><a href="c04-getting-started.html#cb35-5" tabindex="-1"></a>                   <span class="at">nest =</span> <span class="cn">TRUE</span>)</span>
<span id="cb35-6"><a href="c04-getting-started.html#cb35-6" tabindex="-1"></a></span>
<span id="cb35-7"><a href="c04-getting-started.html#cb35-7" tabindex="-1"></a>anes_des</span></code></pre></div>
<pre><code>## Stratified 1 - level Cluster Sampling design (with replacement)
## With (101) clusters.
## Called via srvyr
## Sampling variables:
##   - ids: V200010c 
##   - strata: V200010d 
##   - weights: Weight 
## Data variables: 
##   - V200001 (dbl), CaseID (dbl), V200002 (hvn_lbll), InterviewMode
##     (fct), V200010b (dbl), Weight (dbl), V200010c (dbl), VarUnit (fct),
##     V200010d (dbl), Stratum (fct), V201006 (hvn_lbll), CampaignInterest
##     (fct), V201024 (hvn_lbll), V201025x (hvn_lbll), V201029 (hvn_lbll),
##     V201101 (hvn_lbll), V201102 (hvn_lbll), VotedPres2016 (fct),
##     V201103 (hvn_lbll), VotedPres2016_selection (fct), V201228
##     (hvn_lbll), V201229 (hvn_lbll), V201230 (hvn_lbll), V201231x
##     (hvn_lbll), PartyID (fct), V201233 (hvn_lbll), TrustGovernment
##     (fct), V201237 (hvn_lbll), TrustPeople (fct), V201507x (hvn_lbll),
##     Age (dbl), AgeGroup (fct), V201510 (hvn_lbll), Education (fct),
##     V201546 (hvn_lbll), V201547a (hvn_lbll), V201547b (hvn_lbll),
##     V201547c (hvn_lbll), V201547d (hvn_lbll), V201547e (hvn_lbll),
##     V201547z (hvn_lbll), V201549x (hvn_lbll), RaceEth (fct), V201600
##     (hvn_lbll), Gender (fct), V201607 (hvn_lbll), V201610 (hvn_lbll),
##     V201611 (hvn_lbll), V201613 (hvn_lbll), V201615 (hvn_lbll), V201616
##     (hvn_lbll), V201617x (hvn_lbll), Income (fct), Income7 (fct),
##     V202051 (hvn_lbll), V202066 (hvn_lbll), V202072 (hvn_lbll),
##     VotedPres2020 (fct), V202073 (hvn_lbll), V202109x (hvn_lbll),
##     V202110x (hvn_lbll), VotedPres2020_selection (fct), EarlyVote2020
##     (fct)</code></pre>
<p>We can examine this new object to learn more about the survey design, such that the ANES is a “Stratified 1 - level Cluster Sampling design (with replacement) With (101) clusters”. Additionally, the output displays the sampling variables and then lists the remaining variables in the dataset. This design object will be used throughout this book to conduct survey analysis.</p>
</div>
<div id="residential-energy-consumption-survey-recs-design-object" class="section level4 unnumbered hasAnchor">
<h4>Residential Energy Consumption Survey (RECS) Design Object<a href="c04-getting-started.html#residential-energy-consumption-survey-recs-design-object" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The RECS documentation <span class="citation">(<a href="#ref-recs-2020-tech">U.S. Energy Information Administration 2023a</a>)</span> provides information on the survey’s sampling and weighting implications for analysis. The documentation shows the 2020 RECS uses Jackknife weights, where the main analytic weight is <code>NWEIGHT</code>, and the Jackknife weights are <code>NWEIGHT1</code>-<code>NWEIGHT60</code>. We can specify these in the weights and repweights arguments in the survey design object code, respectively.</p>
<p>With Jackknife weights, additional information is required: <code>type</code>, <code>scale</code>, and <code>mse</code>. Chapter <a href="c10-specifying-sample-designs.html#c10-specifying-sample-designs">10</a> goes into depth about each of these arguments, but to quickly get started, the documentation lets us know that <code>type=JK1</code>, <code>scale=59/60</code>, and <code>mse = TRUE</code>. We can use the following code to create the survey design object:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="c04-getting-started.html#cb37-1" tabindex="-1"></a>recs_des <span class="ot">&lt;-</span> recs_2020 <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="c04-getting-started.html#cb37-2" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(</span>
<span id="cb37-3"><a href="c04-getting-started.html#cb37-3" tabindex="-1"></a>    <span class="at">weights =</span> NWEIGHT,</span>
<span id="cb37-4"><a href="c04-getting-started.html#cb37-4" tabindex="-1"></a>    <span class="at">repweights =</span> NWEIGHT1<span class="sc">:</span>NWEIGHT60,</span>
<span id="cb37-5"><a href="c04-getting-started.html#cb37-5" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">&quot;JK1&quot;</span>,</span>
<span id="cb37-6"><a href="c04-getting-started.html#cb37-6" tabindex="-1"></a>    <span class="at">scale =</span> <span class="dv">59</span> <span class="sc">/</span> <span class="dv">60</span>,</span>
<span id="cb37-7"><a href="c04-getting-started.html#cb37-7" tabindex="-1"></a>    <span class="at">mse =</span> <span class="cn">TRUE</span></span>
<span id="cb37-8"><a href="c04-getting-started.html#cb37-8" tabindex="-1"></a>  )</span>
<span id="cb37-9"><a href="c04-getting-started.html#cb37-9" tabindex="-1"></a></span>
<span id="cb37-10"><a href="c04-getting-started.html#cb37-10" tabindex="-1"></a>recs_des</span></code></pre></div>
<pre><code>## Call: Called via srvyr
## Unstratified cluster jacknife (JK1) with 60 replicates and MSE variances.
## Sampling variables:
##   - repweights: `NWEIGHT1 + NWEIGHT2 + NWEIGHT3 + NWEIGHT4 + NWEIGHT5 +
##     NWEIGHT6 + NWEIGHT7 + NWEIGHT8 + NWEIGHT9 + NWEIGHT10 + NWEIGHT11 +
##     NWEIGHT12 + NWEIGHT13 + NWEIGHT14 + NWEIGHT15 + NWEIGHT16 +
##     NWEIGHT17 + NWEIGHT18 + NWEIGHT19 + NWEIGHT20 + NWEIGHT21 +
##     NWEIGHT22 + NWEIGHT23 + NWEIGHT24 + NWEIGHT25 + NWEIGHT26 +
##     NWEIGHT27 + NWEIGHT28 + NWEIGHT29 + NWEIGHT30 + NWEIGHT31 +
##     NWEIGHT32 + NWEIGHT33 + NWEIGHT34 + NWEIGHT35 + NWEIGHT36 +
##     NWEIGHT37 + NWEIGHT38 + NWEIGHT39 + NWEIGHT40 + NWEIGHT41 +
##     NWEIGHT42 + NWEIGHT43 + NWEIGHT44 + NWEIGHT45 + NWEIGHT46 +
##     NWEIGHT47 + NWEIGHT48 + NWEIGHT49 + NWEIGHT50 + NWEIGHT51 +
##     NWEIGHT52 + NWEIGHT53 + NWEIGHT54 + NWEIGHT55 + NWEIGHT56 +
##     NWEIGHT57 + NWEIGHT58 + NWEIGHT59 + NWEIGHT60` 
##   - weights: NWEIGHT 
## Data variables: 
##   - DOEID (dbl), ClimateRegion_BA (fct), Urbanicity (fct), Region
##     (fct), REGIONC (chr), Division (fct), STATE_FIPS (chr),
##     state_postal (fct), state_name (fct), HDD65 (dbl), CDD65 (dbl),
##     HDD30YR (dbl), CDD30YR (dbl), HousingUnitType (fct), YearMade
##     (ord), TOTSQFT_EN (dbl), TOTHSQFT (dbl), TOTCSQFT (dbl),
##     ZTOTSQFT_EN (fct), ZYearMade (fct), ZHousingUnitType (fct),
##     SpaceHeatingUsed (lgl), ZSpaceHeatingUsed (fct), ACUsed (lgl),
##     ZACUsed (fct), ZACBehavior (fct), HeatingBehavior (fct),
##     WinterTempDay (dbl), WinterTempAway (dbl), WinterTempNight (dbl),
##     ACBehavior (fct), SummerTempDay (dbl), SummerTempAway (dbl),
##     SummerTempNight (dbl), ZHeatingBehavior (fct), ZWinterTempAway
##     (fct), ZSummerTempAway (fct), ZWinterTempDay (fct), ZSummerTempDay
##     (fct), ZWinterTempNight (fct), ZSummerTempNight (fct), NWEIGHT
##     (dbl), NWEIGHT1 (dbl), NWEIGHT2 (dbl), NWEIGHT3 (dbl), NWEIGHT4
##     (dbl), NWEIGHT5 (dbl), NWEIGHT6 (dbl), NWEIGHT7 (dbl), NWEIGHT8
##     (dbl), NWEIGHT9 (dbl), NWEIGHT10 (dbl), NWEIGHT11 (dbl), NWEIGHT12
##     (dbl), NWEIGHT13 (dbl), NWEIGHT14 (dbl), NWEIGHT15 (dbl), NWEIGHT16
##     (dbl), NWEIGHT17 (dbl), NWEIGHT18 (dbl), NWEIGHT19 (dbl), NWEIGHT20
##     (dbl), NWEIGHT21 (dbl), NWEIGHT22 (dbl), NWEIGHT23 (dbl), NWEIGHT24
##     (dbl), NWEIGHT25 (dbl), NWEIGHT26 (dbl), NWEIGHT27 (dbl), NWEIGHT28
##     (dbl), NWEIGHT29 (dbl), NWEIGHT30 (dbl), NWEIGHT31 (dbl), NWEIGHT32
##     (dbl), NWEIGHT33 (dbl), NWEIGHT34 (dbl), NWEIGHT35 (dbl), NWEIGHT36
##     (dbl), NWEIGHT37 (dbl), NWEIGHT38 (dbl), NWEIGHT39 (dbl), NWEIGHT40
##     (dbl), NWEIGHT41 (dbl), NWEIGHT42 (dbl), NWEIGHT43 (dbl), NWEIGHT44
##     (dbl), NWEIGHT45 (dbl), NWEIGHT46 (dbl), NWEIGHT47 (dbl), NWEIGHT48
##     (dbl), NWEIGHT49 (dbl), NWEIGHT50 (dbl), NWEIGHT51 (dbl), NWEIGHT52
##     (dbl), NWEIGHT53 (dbl), NWEIGHT54 (dbl), NWEIGHT55 (dbl), NWEIGHT56
##     (dbl), NWEIGHT57 (dbl), NWEIGHT58 (dbl), NWEIGHT59 (dbl), NWEIGHT60
##     (dbl), BTUEL (dbl), DOLLAREL (dbl), ZBTUEL (fct), BTUNG (dbl),
##     DOLLARNG (dbl), ZBTUNG (fct), BTULP (dbl), DOLLARLP (dbl), ZBTULP
##     (fct), BTUFO (dbl), DOLLARFO (dbl), ZBTUFO (fct), BTUWOOD (dbl),
##     ZBTUWOOD (fct), TOTALBTU (dbl), TOTALDOL (dbl)</code></pre>
<p>Viewing this new object provides information about the survey design, such that the RECS is an “unstratified cluster jacknife (JK1) with 60 replicates and MSE variances”. Additionally, the output shows the sampling variables (<code>NWEIGHT1</code>-<code>NWEIGHT60</code>) and then lists the remaining variables in the dataset. This design object will be used throughout this book to conduct survey analysis.</p>
</div>
</div>
</div>
<div id="survey-analysis-process" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Survey analysis process<a href="c04-getting-started.html#survey-analysis-process" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The section above walked through the installation and loading of several packages, introduced the survey data available in the {srvyrexploR} package, and provided context on preparing survey design objects for the ANES and RECS data. Once the survey design objects are created, there is a general process for analyzing data to create estimates with {srvyr} package:</p>
<ol style="list-style-type: decimal">
<li><p>Create a <code>tbl_svy</code> object (a survey object) using: <code>as_survey_design()</code> or <code>as_survey_rep()</code></p></li>
<li><p>Subset data (if needed) using <code>filter()</code> (to create subpopulations)</p></li>
<li><p>Specify domains of analysis using <code>group_by()</code></p></li>
<li><p>Within <code>summarize()</code>, specify variables to calculate, including means, totals, proportions, quantiles, and more</p></li>
</ol>
<p>In Section <a href="c04-getting-started.html#setup-des-obj">4.2.3</a>, we follow Step #1 to create the survey design objects for the ANES and RECS data featured in this book. Additional details on how to create design objects can be found in <a href="c10-specifying-sample-designs.html#c10-specifying-sample-designs">10</a>. Then, once we have the design object, we can then filter the data to any subpopulation of interest (if needed). It is important to filter the data <strong>after</strong> creating the design object. This ensures that we are accurately accounting for the survey design in our calculations. Finally, we can use <code>group_by()</code>, <code>summarize()</code>, and other functions from the {survey} and {srvyr} packages to analyze the survey data by estimating means, totals, and so on.</p>
</div>
<div id="similarities-dplyr-srvyr" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Similarities between {dplyr} and {srvyr} functions<a href="c04-getting-started.html#similarities-dplyr-srvyr" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The {dplyr} package from the tidyverse offers flexible and intuitive functions for data wrangling. One of the major advantages of using {srvyr} is that it applies {dplyr}-like syntax to the {survey} package. We can use pipes, such as <code>%&gt;%</code> from the {magrittr} package, to specify a survey design object, apply a function, and then feed that output into the next function’s first argument. Functions follow the ‘tidy’ convention of snake_case function names.</p>
<p>To help explain the similarities between {dplyr} functions and {srvyr} functions, we use the <code>towny</code> dataset from the {gt} package and <code>apistrat</code> data that comes in the {survey} package. The <code>towny</code> dataset provides population data for municipalities in Ontario, Canada on Census years between 1996 and 2021. We can load the data into our environment using <code>data(towny)</code>. Taking a look at <code>towny</code> with <code>dplyr::glimpse()</code>, we can see the dataset has 25 columns with a mix of character and numeric data.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="c04-getting-started.html#cb39-1" tabindex="-1"></a><span class="fu">data</span>(towny)</span>
<span id="cb39-2"><a href="c04-getting-started.html#cb39-2" tabindex="-1"></a></span>
<span id="cb39-3"><a href="c04-getting-started.html#cb39-3" tabindex="-1"></a>towny <span class="sc">%&gt;%</span> </span>
<span id="cb39-4"><a href="c04-getting-started.html#cb39-4" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 414
## Columns: 25
## $ name                     &lt;chr&gt; &quot;Addington Highlands&quot;, &quot;Adelaide Metc…
## $ website                  &lt;chr&gt; &quot;https://addingtonhighlands.ca&quot;, &quot;htt…
## $ status                   &lt;chr&gt; &quot;lower-tier&quot;, &quot;lower-tier&quot;, &quot;lower-ti…
## $ csd_type                 &lt;chr&gt; &quot;township&quot;, &quot;township&quot;, &quot;township&quot;, &quot;…
## $ census_div               &lt;chr&gt; &quot;Lennox and Addington&quot;, &quot;Middlesex&quot;, …
## $ latitude                 &lt;dbl&gt; 45.00, 42.95, 44.13, 45.53, 43.86, 48…
## $ longitude                &lt;dbl&gt; -77.25, -81.70, -79.93, -76.90, -79.0…
## $ land_area_km2            &lt;dbl&gt; 1293.99, 331.11, 371.53, 519.59, 66.6…
## $ population_1996          &lt;int&gt; 2429, 3128, 9359, 2837, 64430, 1027, …
## $ population_2001          &lt;int&gt; 2402, 3149, 10082, 2824, 73753, 956, …
## $ population_2006          &lt;int&gt; 2512, 3135, 10695, 2716, 90167, 958, …
## $ population_2011          &lt;int&gt; 2517, 3028, 10603, 2844, 109600, 864,…
## $ population_2016          &lt;int&gt; 2318, 2990, 10975, 2935, 119677, 969,…
## $ population_2021          &lt;int&gt; 2534, 3011, 10989, 2995, 126666, 954,…
## $ density_1996             &lt;dbl&gt; 1.88, 9.45, 25.19, 5.46, 966.84, 8.81…
## $ density_2001             &lt;dbl&gt; 1.86, 9.51, 27.14, 5.44, 1106.74, 8.2…
## $ density_2006             &lt;dbl&gt; 1.94, 9.47, 28.79, 5.23, 1353.05, 8.2…
## $ density_2011             &lt;dbl&gt; 1.95, 9.14, 28.54, 5.47, 1644.66, 7.4…
## $ density_2016             &lt;dbl&gt; 1.79, 9.03, 29.54, 5.65, 1795.87, 8.3…
## $ density_2021             &lt;dbl&gt; 1.96, 9.09, 29.58, 5.76, 1900.75, 8.1…
## $ pop_change_1996_2001_pct &lt;dbl&gt; -0.0111, 0.0067, 0.0773, -0.0046, 0.1…
## $ pop_change_2001_2006_pct &lt;dbl&gt; 0.0458, -0.0044, 0.0608, -0.0382, 0.2…
## $ pop_change_2006_2011_pct &lt;dbl&gt; 0.0020, -0.0341, -0.0086, 0.0471, 0.2…
## $ pop_change_2011_2016_pct &lt;dbl&gt; -0.0791, -0.0125, 0.0351, 0.0320, 0.0…
## $ pop_change_2016_2021_pct &lt;dbl&gt; 0.0932, 0.0070, 0.0013, 0.0204, 0.058…</code></pre>
<p>Let’s examine the <code>towny</code> object’s class. We verify that it is a tibble, as indicated by <code>"tbl_df"</code>, by running the code below:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="c04-getting-started.html#cb41-1" tabindex="-1"></a><span class="fu">class</span>(towny)</span></code></pre></div>
<pre><code>## [1] &quot;tbl_df&quot;     &quot;tbl&quot;        &quot;data.frame&quot;</code></pre>
<p>All tibbles are data.frames but not all data.frames are tibbles. Compared to data.frames, tibbles have some advantages with the printing behavior being a noticeable advantage.</p>
<p>The {survey} package contains datasets related to the California Academic Performance Index, which measures student performance in schools with at least 100 students in California. We can access these datasets by loading the {survey} package and running <code>data(api)</code>.</p>
<p>Let’s work with the <code>apistrat</code> dataset, a stratified simple random sample of three school types (elementary, middle, high) in each stratum. We can follow the process outlined in Section <a href="c04-getting-started.html#setup-des-obj">4.2.3</a> to create the survey design object. The sample is stratified by the <code>stype</code> variable and the sampling weights are found in the <code>pw</code> variable. We can use this information to construct the design object, <code>dstrata</code>.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="c04-getting-started.html#cb43-1" tabindex="-1"></a><span class="fu">data</span>(api)</span>
<span id="cb43-2"><a href="c04-getting-started.html#cb43-2" tabindex="-1"></a></span>
<span id="cb43-3"><a href="c04-getting-started.html#cb43-3" tabindex="-1"></a>dstrata <span class="ot">&lt;-</span> apistrat <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="c04-getting-started.html#cb43-4" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">strata =</span> stype, <span class="at">weights =</span> pw)</span></code></pre></div>
<p>When we check the class of <code>dstrata</code>, it is not a typical <code>data.frame</code>. Applying the <code>as_survey_design()</code> function transforms the data into a <code>tbl_svy</code>, a special class specifically for survey design objects. The {srvyr} package is designed to work with the <code>tbl_svy</code> class of objects.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="c04-getting-started.html#cb44-1" tabindex="-1"></a><span class="fu">class</span>(dstrata)</span></code></pre></div>
<pre><code>## [1] &quot;tbl_svy&quot;        &quot;survey.design2&quot; &quot;survey.design&quot;</code></pre>
<p>Let’s look at how {dplyr} works with regular data frames. The example below calculates the mean and median for the <code>land_area_km2</code> variable in the <code>towny</code> dataset.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="c04-getting-started.html#cb46-1" tabindex="-1"></a>towny <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="c04-getting-started.html#cb46-2" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">area_mean =</span> <span class="fu">mean</span>(land_area_km2),</span>
<span id="cb46-3"><a href="c04-getting-started.html#cb46-3" tabindex="-1"></a>            <span class="at">area_median =</span> <span class="fu">median</span>(land_area_km2))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   area_mean area_median
##       &lt;dbl&gt;       &lt;dbl&gt;
## 1      373.        273.</code></pre>
<p>In the code below, we calculate the mean and median of the variable <code>api00</code> using <code>dstrata</code>. Note the similarity in the syntax. When we dig into the {srvyr} functions later, we will show that the outputs share a similar structure. Each group (if present) generates one row of output, but with additional columns. By default, the standard error of the statistic is also calculated in addition to the statistic itself.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="c04-getting-started.html#cb48-1" tabindex="-1"></a>dstrata <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="c04-getting-started.html#cb48-2" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">api00_mean =</span> <span class="fu">survey_mean</span>(api00),</span>
<span id="cb48-3"><a href="c04-getting-started.html#cb48-3" tabindex="-1"></a>            <span class="at">api00_med =</span> <span class="fu">survey_median</span>(api00))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##   api00_mean api00_mean_se api00_med api00_med_se
##        &lt;dbl&gt;         &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;
## 1       662.          9.54       668         13.7</code></pre>
<p>The functions in {srvyr} also play nicely with other tidyverse functions. For example, if we wanted to select columns with shared characteristics, we can use {tidyselect} functions such as <code>starts_with()</code>, <code>num_range()</code>, etc. In the examples below, we use a combination of <code>across()</code> and <code>starts_with()</code> to calculate the mean of variables starting with “population” in the <code>towny</code> data frame and those beginning with <code>api</code> in the <code>dstrata</code> survey object.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="c04-getting-started.html#cb50-1" tabindex="-1"></a>towny <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="c04-getting-started.html#cb50-2" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">&quot;population&quot;</span>), <span class="sc">~</span><span class="fu">mean</span>(.x, <span class="at">na.rm=</span><span class="cn">TRUE</span>)))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 6
##   population_1996 population_2001 population_2006 population_2011
##             &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt;
## 1          25866.          27538.          29173.          30838.
## # ℹ 2 more variables: population_2016 &lt;dbl&gt;, population_2021 &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="c04-getting-started.html#cb52-1" tabindex="-1"></a>dstrata <span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="c04-getting-started.html#cb52-2" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">&quot;api&quot;</span>), survey_mean))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 6
##   api00 api00_se api99 api99_se api.stu api.stu_se
##   &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;
## 1  662.     9.54  629.     10.1    498.       16.4</code></pre>
<p>We have the flexibility to use {dplyr} verbs such as <code>mutate()</code>, <code>filter()</code>, and <code>select()</code> on our survey design object. As mentioned in Section <a href="c04-getting-started.html#survey-analysis-process">4.3</a>, these steps should be performed on the survey design object. This ensures our survey design is properly considered in all our calculations.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="c04-getting-started.html#cb54-1" tabindex="-1"></a>dstrata_mod <span class="ot">&lt;-</span> dstrata <span class="sc">%&gt;%</span></span>
<span id="cb54-2"><a href="c04-getting-started.html#cb54-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">api_diff =</span> api00 <span class="sc">-</span> api99) <span class="sc">%&gt;%</span></span>
<span id="cb54-3"><a href="c04-getting-started.html#cb54-3" tabindex="-1"></a>  <span class="fu">filter</span>(stype <span class="sc">==</span> <span class="st">&quot;E&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb54-4"><a href="c04-getting-started.html#cb54-4" tabindex="-1"></a>  <span class="fu">select</span>(stype, api99, api00, api_diff, <span class="at">api_students =</span> api.stu)</span>
<span id="cb54-5"><a href="c04-getting-started.html#cb54-5" tabindex="-1"></a></span>
<span id="cb54-6"><a href="c04-getting-started.html#cb54-6" tabindex="-1"></a>dstrata_mod</span></code></pre></div>
<pre><code>## Stratified Independent Sampling design (with replacement)
## Called via srvyr
## Sampling variables:
##   - ids: `1` 
##   - strata: stype 
##   - weights: pw 
## Data variables: 
##   - stype (fct), api99 (int), api00 (int), api_diff (int), api_students
##     (int)</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="c04-getting-started.html#cb56-1" tabindex="-1"></a>dstrata</span></code></pre></div>
<pre><code>## Stratified Independent Sampling design (with replacement)
## Called via srvyr
## Sampling variables:
##   - ids: `1` 
##   - strata: stype 
##   - weights: pw 
## Data variables: 
##   - cds (chr), stype (fct), name (chr), sname (chr), snum (dbl), dname
##     (chr), dnum (int), cname (chr), cnum (int), flag (int), pcttest
##     (int), api00 (int), api99 (int), target (int), growth (int),
##     sch.wide (fct), comp.imp (fct), both (fct), awards (fct), meals
##     (int), ell (int), yr.rnd (fct), mobility (int), acs.k3 (int),
##     acs.46 (int), acs.core (int), pct.resp (int), not.hsg (int), hsg
##     (int), some.col (int), col.grad (int), grad.sch (int), avg.ed
##     (dbl), full (int), emer (int), enroll (int), api.stu (int), pw
##     (dbl), fpc (dbl)</code></pre>
<p>Several functions in {srvyr} must be called within <code>srvyr::summarize()</code>, with the exception of <code>srvyr::survey_count()</code> and <code>srvyr::survey_tally()</code>. This is similar to how <code>dplyr::count()</code> and <code>dplyr::tally()</code> are not called within <code>dplyr::summarize()</code>. The <code>summarize()</code> function can be used in conjunction with <code>group_by()</code> or <code>by/.by</code>, which applies the functions on a group-by-group basis to create grouped summaries.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="c04-getting-started.html#cb58-1" tabindex="-1"></a>towny <span class="sc">%&gt;%</span></span>
<span id="cb58-2"><a href="c04-getting-started.html#cb58-2" tabindex="-1"></a>  <span class="fu">group_by</span>(csd_type) <span class="sc">%&gt;%</span></span>
<span id="cb58-3"><a href="c04-getting-started.html#cb58-3" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">area_mean =</span> <span class="fu">mean</span>(land_area_km2),</span>
<span id="cb58-4"><a href="c04-getting-started.html#cb58-4" tabindex="-1"></a>                   <span class="at">area_median =</span> <span class="fu">median</span>(land_area_km2))</span></code></pre></div>
<pre><code>## # A tibble: 5 × 3
##   csd_type     area_mean area_median
##   &lt;chr&gt;            &lt;dbl&gt;       &lt;dbl&gt;
## 1 city             498.        198. 
## 2 municipality     607.        488. 
## 3 town             183.        129. 
## 4 township         363.        301. 
## 5 village           23.0         3.3</code></pre>
<p>We use a similar setup to summarize data in {srvyr}:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="c04-getting-started.html#cb60-1" tabindex="-1"></a>dstrata <span class="sc">%&gt;%</span></span>
<span id="cb60-2"><a href="c04-getting-started.html#cb60-2" tabindex="-1"></a>  <span class="fu">group_by</span>(stype) <span class="sc">%&gt;%</span></span>
<span id="cb60-3"><a href="c04-getting-started.html#cb60-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">api00_mean =</span> <span class="fu">survey_mean</span>(api00),</span>
<span id="cb60-4"><a href="c04-getting-started.html#cb60-4" tabindex="-1"></a>            <span class="at">api00_median =</span> <span class="fu">survey_median</span>(api00))</span></code></pre></div>
<pre><code>## # A tibble: 3 × 5
##   stype api00_mean api00_mean_se api00_median api00_median_se
##   &lt;fct&gt;      &lt;dbl&gt;         &lt;dbl&gt;        &lt;dbl&gt;           &lt;dbl&gt;
## 1 E           674.          12.5          671            20.7
## 2 H           626.          15.5          635            21.6
## 3 M           637.          16.6          648            24.1</code></pre>
<p>At this time, the <code>.by</code> argument is <code>srvyr::summarize()</code> does not exist as it does in {dplyr}. An alternative way to do the grouped analysis on the <code>towny</code> data would be:</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="c04-getting-started.html#cb62-1" tabindex="-1"></a>towny <span class="sc">%&gt;%</span></span>
<span id="cb62-2"><a href="c04-getting-started.html#cb62-2" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">area_mean =</span> <span class="fu">mean</span>(land_area_km2),</span>
<span id="cb62-3"><a href="c04-getting-started.html#cb62-3" tabindex="-1"></a>                   <span class="at">area_median =</span> <span class="fu">median</span>(land_area_km2), </span>
<span id="cb62-4"><a href="c04-getting-started.html#cb62-4" tabindex="-1"></a>                   <span class="at">.by=</span>csd_type)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 3
##   csd_type     area_mean area_median
##   &lt;chr&gt;            &lt;dbl&gt;       &lt;dbl&gt;
## 1 township         363.        301. 
## 2 town             183.        129. 
## 3 municipality     607.        488. 
## 4 city             498.        198. 
## 5 village           23.0         3.3</code></pre>
<p>However, the <code>.by</code> syntax is not yet available in {srvyr}:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="c04-getting-started.html#cb64-1" tabindex="-1"></a>dstrata <span class="sc">%&gt;%</span></span>
<span id="cb64-2"><a href="c04-getting-started.html#cb64-2" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">api00_mean =</span> <span class="fu">survey_mean</span>(api00),</span>
<span id="cb64-3"><a href="c04-getting-started.html#cb64-3" tabindex="-1"></a>            <span class="at">api00_median =</span> <span class="fu">survey_median</span>(api00),</span>
<span id="cb64-4"><a href="c04-getting-started.html#cb64-4" tabindex="-1"></a>            <span class="at">.by=</span>stype)</span></code></pre></div>
<pre><code>## Error in `dplyr::summarise()` at gergness-srvyr-1917f75/R/summarise.r:10:3:
## ℹ In argument: `api00_mean = survey_mean(api00)`.
## ℹ In group 1: `stype = E`.
## Caused by error in `[[&lt;-` at gergness-srvyr-1917f75/R/survey_statistics_helpers.R:48:5:
## ! Assigned data `x` must be compatible with existing data.
## ✖ Existing data has 200 rows.
## ✖ Assigned data has 100 rows.
## ℹ Only vectors of size 1 are recycled.
## Caused by error in `vectbl_recycle_rhs_rows()`:
## ! Can&#39;t recycle input of size 100 to size 200.</code></pre>
<p>As mentioned above, {srvyr} functions are meant for <code>tbl_svy</code> objects. Attempting to perform data manipulation on non-<code>tbl_svy</code> objects, like the <code>towny</code> example shown below, will result in an error. Running the code will let you know what the issue is: <code>Survey context not set</code>.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="c04-getting-started.html#cb66-1" tabindex="-1"></a>towny <span class="sc">%&gt;%</span></span>
<span id="cb66-2"><a href="c04-getting-started.html#cb66-2" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">area_mean =</span> <span class="fu">survey_mean</span>(land_area_km2))</span></code></pre></div>
<pre><code>## Error in `summarize()`:
## ℹ In argument: `area_mean = survey_mean(land_area_km2)`.
## Caused by error in `cur_svy()` at gergness-srvyr-1917f75/R/survey_statistics.r:114:3:
## ! Survey context not set</code></pre>
<p>A few functions in {srvyr} have counterparts in {dplyr}, such as <code>srvyr::summarize()</code> and <code>srvyr::group_by()</code>. Unlike {srvyr}-specific verbs, {srvyr} recognizes these parallel functions if applied to a non-survey object. Instead of causing an error, the package will provide the equivalent output from {dplyr}:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="c04-getting-started.html#cb68-1" tabindex="-1"></a>towny <span class="sc">%&gt;%</span></span>
<span id="cb68-2"><a href="c04-getting-started.html#cb68-2" tabindex="-1"></a>  srvyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">area_mean =</span> <span class="fu">mean</span>(land_area_km2))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   area_mean
##       &lt;dbl&gt;
## 1      373.</code></pre>
<p>Because this book focuses on survey analysis, most of our pipes will stem from a survey object. When we load the {dplyr} and {srvyr} packages, the functions will automatically figure out the class of data and use the appropriate one from {dplyr} or {srvyr}. Therefore, we do not need to include the namespace for each function (e.g., <code>srvyr::summarize()</code>).</p>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-debell" class="csl-entry">
DeBell, Matthew. 2010. <span>“How to Analyze ANES Survey Data.”</span> ANES Technical Report Series nes012492. Palo Alto, CA: Stanford University; Ann Arbor, MI: the University of Michigan; <a href="https://electionstudies.org/wp-content/uploads/2018/05/HowToAnalyzeANESData.pdf" class="uri">https://electionstudies.org/wp-content/uploads/2018/05/HowToAnalyzeANESData.pdf</a>.
</div>
<div id="ref-recs-2020-tech" class="csl-entry">
———. 2023a. <span>“<span>2020 Residential Energy Consumption Survey: Household Characteristics Technical Documentation Summary</span>.”</span> <a href="https://www.eia.gov/consumption/residential/data/2020/pdf/2020%20RECS_Methodology%20Report.pdf" class="uri">https://www.eia.gov/consumption/residential/data/2020/pdf/2020%20RECS_Methodology%20Report.pdf</a>.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="5">
<li id="fn5"><p>Note: {broom} is already included in the tidyverse, so no separate installation is required<a href="c04-getting-started.html#fnref5" class="footnote-back">↩︎</a></p></li>
<li id="fn6"><p>In the United States, presidential elections are held in years divisible by four. In other even years, there are elections at the federal level for congress which are referred to as midterm elections as they occur at the middle of the term of a president.<a href="c04-getting-started.html#fnref6" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="c03-understanding-survey-data-documentation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="c05-descriptive-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": true,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "github", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/tidy-survey-r/tidy-survey-book/blob/main/04-set-up.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
