<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Setup | Exploring Complex Survey Data Analysis in R: A Tidy Introduction with srvyr</title>
  <meta name="description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Setup | Exploring Complex Survey Data Analysis in R: A Tidy Introduction with srvyr" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  <meta name="github-repo" content="tidy-survey-r/tidy-survey-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Setup | Exploring Complex Survey Data Analysis in R: A Tidy Introduction with srvyr" />
  
  <meta name="twitter:description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  

<meta name="author" content="Stephanie Zimmer, Rebecca J. Powell, and Isabella Velásquez" />


<meta name="date" content="2024-02-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="c03-understanding-survey-data-documentation.html"/>
<link rel="next" href="c05-descriptive-analysis.html"/>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>
<script defer data-domain="tidy-survey-r.github.io/tidy-survey-book" src="https://plausible.io/js/script.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Exploring Complex Survey Data Analysis in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="part"><span><b>I Intro</b></span></li>
<li class="chapter" data-level="1" data-path="c01-intro.html"><a href="c01-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="c01-intro.html"><a href="c01-intro.html#what-to-expect"><i class="fa fa-check"></i><b>1.1</b> What to expect</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html"><i class="fa fa-check"></i><b>2</b> Overview of Surveys</a>
<ul>
<li class="chapter" data-level="2.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#pre-survey-planning"><i class="fa fa-check"></i><b>2.2</b> Pre-Survey Planning</a></li>
<li class="chapter" data-level="2.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design"><i class="fa fa-check"></i><b>2.3</b> Study Design</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-sampdesign"><i class="fa fa-check"></i><b>2.3.1</b> Sampling Design</a></li>
<li class="chapter" data-level="2.3.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-dcplanning"><i class="fa fa-check"></i><b>2.3.2</b> Data Collection Planning</a></li>
<li class="chapter" data-level="2.3.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-questionnaire"><i class="fa fa-check"></i><b>2.3.3</b> Questionnaire Design</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-datacollection"><i class="fa fa-check"></i><b>2.4</b> Data Collection</a></li>
<li class="chapter" data-level="2.5" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post"><i class="fa fa-check"></i><b>2.5</b> Post-Survey Processing</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-cleaning"><i class="fa fa-check"></i><b>2.5.1</b> Data Cleaning and Imputation</a></li>
<li class="chapter" data-level="2.5.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-weighting"><i class="fa fa-check"></i><b>2.5.2</b> Weighting</a></li>
<li class="chapter" data-level="2.5.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-disclosure"><i class="fa fa-check"></i><b>2.5.3</b> Disclosure</a></li>
<li class="chapter" data-level="2.5.4" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-documentation"><i class="fa fa-check"></i><b>2.5.4</b> Documentation</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#post-survey-data-analysis-and-reporting"><i class="fa fa-check"></i><b>2.6</b> Post-survey data analysis and reporting</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html"><i class="fa fa-check"></i><b>3</b> Understanding Survey Data Documentation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#types-of-survey-documentation"><i class="fa fa-check"></i><b>3.2</b> Types of Survey Documentation</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#technical-documentation"><i class="fa fa-check"></i><b>3.2.1</b> Technical Documentation</a></li>
<li class="chapter" data-level="3.2.2" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#questionnaires"><i class="fa fa-check"></i><b>3.2.2</b> Questionnaires</a></li>
<li class="chapter" data-level="3.2.3" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#codebooks"><i class="fa fa-check"></i><b>3.2.3</b> Codebooks</a></li>
<li class="chapter" data-level="3.2.4" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#errata"><i class="fa fa-check"></i><b>3.2.4</b> Errata</a></li>
<li class="chapter" data-level="3.2.5" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#additional-resources"><i class="fa fa-check"></i><b>3.2.5</b> Additional Resources</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#working-with-missing-data"><i class="fa fa-check"></i><b>3.3</b> Working with Missing Data</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#accounting-for-questionnaire-skip-patterns"><i class="fa fa-check"></i><b>3.3.1</b> Accounting for Questionnaire Skip Patterns</a></li>
<li class="chapter" data-level="3.3.2" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#accounting-for-unintentional-missing-data"><i class="fa fa-check"></i><b>3.3.2</b> Accounting for Unintentional Missing Data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#example-american-national-election-studies-anes-2020-survey-documentation"><i class="fa fa-check"></i><b>3.4</b> Example: American National Election Studies (ANES) 2020 Survey Documentation</a></li>
<li class="chapter" data-level="3.5" data-path="c03-understanding-survey-data-documentation.html"><a href="c03-understanding-survey-data-documentation.html#searching-for-public-use-survey-data"><i class="fa fa-check"></i><b>3.5</b> Searching for Public-Use Survey Data</a></li>
</ul></li>
<li class="part"><span><b>II Analysis</b></span></li>
<li class="chapter" data-level="4" data-path="c04-set-up.html"><a href="c04-set-up.html"><i class="fa fa-check"></i><b>4</b> Setup</a>
<ul>
<li class="chapter" data-level="4.1" data-path="c04-set-up.html"><a href="c04-set-up.html#packages"><i class="fa fa-check"></i><b>4.1</b> Packages</a></li>
<li class="chapter" data-level="4.2" data-path="c04-set-up.html"><a href="c04-set-up.html#data"><i class="fa fa-check"></i><b>4.2</b> Data</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="c04-set-up.html"><a href="c04-set-up.html#data-american-national-election-studies-anes"><i class="fa fa-check"></i><b>4.2.1</b> Data: American National Election Studies (ANES)</a></li>
<li class="chapter" data-level="4.2.2" data-path="c04-set-up.html"><a href="c04-set-up.html#residential-energy-consumption-survey-recs"><i class="fa fa-check"></i><b>4.2.2</b> Residential Energy Consumption Survey (RECS)</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="c04-set-up.html"><a href="c04-set-up.html#design-objects"><i class="fa fa-check"></i><b>4.3</b> Design Objects</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="c04-set-up.html"><a href="c04-set-up.html#american-national-election-studies-anes"><i class="fa fa-check"></i><b>4.3.1</b> American National Election Studies (ANES)</a></li>
<li class="chapter" data-level="4.3.2" data-path="c04-set-up.html"><a href="c04-set-up.html#residential-energy-consumption-survey-recs-1"><i class="fa fa-check"></i><b>4.3.2</b> Residential Energy Consumption Survey (RECS)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html"><i class="fa fa-check"></i><b>5</b> Descriptive Analyses in {srvyr}</a>
<ul>
<li class="chapter" data-level="" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#prereq5"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="5.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#introduction-3"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#similarities-between-dplyr-and-srvyr-functions"><i class="fa fa-check"></i><b>5.2</b> Similarities Between {dplyr} and {srvyr} Functions</a></li>
<li class="chapter" data-level="5.3" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#counts-and-cross-tabulations"><i class="fa fa-check"></i><b>5.3</b> Counts and Cross-Tabulations</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-count-syntax"><i class="fa fa-check"></i><b>5.3.1</b> Syntax</a></li>
<li class="chapter" data-level="5.3.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples"><i class="fa fa-check"></i><b>5.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#totals-and-sums"><i class="fa fa-check"></i><b>5.4</b> Totals and Sums</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax"><i class="fa fa-check"></i><b>5.4.1</b> Syntax</a></li>
<li class="chapter" data-level="5.4.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-1"><i class="fa fa-check"></i><b>5.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-meanprop"><i class="fa fa-check"></i><b>5.5</b> Means and Proportions</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-meanprop-syntax"><i class="fa fa-check"></i><b>5.5.1</b> Syntax</a></li>
<li class="chapter" data-level="5.5.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-2"><i class="fa fa-check"></i><b>5.5.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#quantiles-and-medians"><i class="fa fa-check"></i><b>5.6</b> Quantiles and Medians</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-1"><i class="fa fa-check"></i><b>5.6.1</b> Syntax</a></li>
<li class="chapter" data-level="5.6.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-3"><i class="fa fa-check"></i><b>5.6.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#ratios"><i class="fa fa-check"></i><b>5.7</b> Ratios</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-2"><i class="fa fa-check"></i><b>5.7.1</b> Syntax</a></li>
<li class="chapter" data-level="5.7.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-4"><i class="fa fa-check"></i><b>5.7.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#correlations"><i class="fa fa-check"></i><b>5.8</b> Correlations</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-3"><i class="fa fa-check"></i><b>5.8.1</b> Syntax</a></li>
<li class="chapter" data-level="5.8.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-5"><i class="fa fa-check"></i><b>5.8.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#standard-deviation-and-variance"><i class="fa fa-check"></i><b>5.9</b> Standard Deviation and Variance</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-4"><i class="fa fa-check"></i><b>5.9.1</b> Syntax</a></li>
<li class="chapter" data-level="5.9.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-6"><i class="fa fa-check"></i><b>5.9.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#additional-topics"><i class="fa fa-check"></i><b>5.10</b> Additional Topics</a>
<ul>
<li class="chapter" data-level="5.10.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#unweighted-analysis"><i class="fa fa-check"></i><b>5.10.1</b> Unweighted Analysis</a></li>
<li class="chapter" data-level="5.10.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#subpopulation-analysis"><i class="fa fa-check"></i><b>5.10.2</b> Subpopulation Analysis</a></li>
<li class="chapter" data-level="5.10.3" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-deff"><i class="fa fa-check"></i><b>5.10.3</b> Design Effects</a></li>
<li class="chapter" data-level="5.10.4" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#creating-summary-rows"><i class="fa fa-check"></i><b>5.10.4</b> Creating Summary Rows</a></li>
<li class="chapter" data-level="5.10.5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#calculating-estimates-for-many-outcomes"><i class="fa fa-check"></i><b>5.10.5</b> Calculating Estimates for Many Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="5.11" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#exercises"><i class="fa fa-check"></i><b>5.11</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html"><i class="fa fa-check"></i><b>6</b> Statistical testing</a>
<ul>
<li class="chapter" data-level="" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#prereq6"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="6.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#introduction-4"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#dot-notation"><i class="fa fa-check"></i><b>6.2</b> Dot Notation</a></li>
<li class="chapter" data-level="6.3" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest"><i class="fa fa-check"></i><b>6.3</b> Comparison of Proportions and Means</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest-syntax"><i class="fa fa-check"></i><b>6.3.1</b> Syntax</a></li>
<li class="chapter" data-level="6.3.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest-examples"><i class="fa fa-check"></i><b>6.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi"><i class="fa fa-check"></i><b>6.4</b> Chi-Square Tests</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi-syntax"><i class="fa fa-check"></i><b>6.4.1</b> Syntax</a></li>
<li class="chapter" data-level="6.4.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi-examples"><i class="fa fa-check"></i><b>6.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-exercises"><i class="fa fa-check"></i><b>6.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="c07-modeling.html"><a href="c07-modeling.html"><i class="fa fa-check"></i><b>7</b> Modeling</a>
<ul>
<li class="chapter" data-level="" data-path="c07-modeling.html"><a href="c07-modeling.html#prereq7"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="7.1" data-path="c07-modeling.html"><a href="c07-modeling.html#introduction-5"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="c07-modeling.html"><a href="c07-modeling.html#analysis-of-variance-anova"><i class="fa fa-check"></i><b>7.2</b> Analysis of Variance (ANOVA)</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-6"><i class="fa fa-check"></i><b>7.2.1</b> Syntax</a></li>
<li class="chapter" data-level="7.2.2" data-path="c07-modeling.html"><a href="c07-modeling.html#example-1"><i class="fa fa-check"></i><b>7.2.2</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="c07-modeling.html"><a href="c07-modeling.html#gaussian-linear-regression"><i class="fa fa-check"></i><b>7.3</b> Gaussian Linear Regression</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-7"><i class="fa fa-check"></i><b>7.3.1</b> Syntax</a></li>
<li class="chapter" data-level="7.3.2" data-path="c07-modeling.html"><a href="c07-modeling.html#examples-7"><i class="fa fa-check"></i><b>7.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="c07-modeling.html"><a href="c07-modeling.html#logistic-regression"><i class="fa fa-check"></i><b>7.4</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-8"><i class="fa fa-check"></i><b>7.4.1</b> Syntax</a></li>
<li class="chapter" data-level="7.4.2" data-path="c07-modeling.html"><a href="c07-modeling.html#examples-8"><i class="fa fa-check"></i><b>7.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="c07-modeling.html"><a href="c07-modeling.html#exercises-1"><i class="fa fa-check"></i><b>7.5</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>III Reporting</b></span></li>
<li class="chapter" data-level="8" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html"><i class="fa fa-check"></i><b>8</b> Communicating Results</a>
<ul>
<li class="chapter" data-level="" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#prereq8"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="8.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#introduction-6"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#describing-results-through-text"><i class="fa fa-check"></i><b>8.2</b> Describing Results through Text</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#methodology"><i class="fa fa-check"></i><b>8.2.1</b> Methodology</a></li>
<li class="chapter" data-level="8.2.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#analysis"><i class="fa fa-check"></i><b>8.2.2</b> Analysis</a></li>
<li class="chapter" data-level="8.2.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#results"><i class="fa fa-check"></i><b>8.2.3</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#visualizing-data"><i class="fa fa-check"></i><b>8.3</b> Visualizing Data</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#tables"><i class="fa fa-check"></i><b>8.3.1</b> Tables</a></li>
<li class="chapter" data-level="8.3.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#charts-and-plots"><i class="fa fa-check"></i><b>8.3.2</b> Charts and Plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html"><i class="fa fa-check"></i><b>9</b> Reproducible Research</a>
<ul>
<li class="chapter" data-level="9.1" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#project-based-workflows"><i class="fa fa-check"></i><b>9.1</b> Project-based workflows</a></li>
<li class="chapter" data-level="9.2" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#version-control-git"><i class="fa fa-check"></i><b>9.2</b> Version Control: Git</a></li>
<li class="chapter" data-level="9.3" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#package-management-renv"><i class="fa fa-check"></i><b>9.3</b> Package Management: {renv}</a></li>
<li class="chapter" data-level="9.4" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#workflow-management-targets"><i class="fa fa-check"></i><b>9.4</b> Workflow Management: {targets}</a></li>
<li class="chapter" data-level="9.5" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#documentation-quarto-and-r-markdown"><i class="fa fa-check"></i><b>9.5</b> Documentation: Quarto and R Markdown</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#parameterization"><i class="fa fa-check"></i><b>9.5.1</b> Parameterization</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#other-tips-for-reproducibility"><i class="fa fa-check"></i><b>9.6</b> Other Tips for Reproducibility</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#random-number-seeds"><i class="fa fa-check"></i><b>9.6.1</b> Random Number Seeds</a></li>
<li class="chapter" data-level="9.6.2" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#descriptive-names-and-labels"><i class="fa fa-check"></i><b>9.6.2</b> Descriptive Names and Labels</a></li>
<li class="chapter" data-level="9.6.3" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#databases"><i class="fa fa-check"></i><b>9.6.3</b> Databases</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#summary"><i class="fa fa-check"></i><b>9.7</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>IV Real life data</b></span></li>
<li class="chapter" data-level="10" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html"><i class="fa fa-check"></i><b>10</b> Specifying sample designs and replicate weights in {srvyr}</a>
<ul>
<li class="chapter" data-level="" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#prereq3"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="10.1" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#introduction-7"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#common-sampling-designs"><i class="fa fa-check"></i><b>10.2</b> Common sampling designs</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#simple-random-sample-without-replacement"><i class="fa fa-check"></i><b>10.2.1</b> Simple random sample without replacement</a></li>
<li class="chapter" data-level="10.2.2" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#simple-random-sample-with-replacement"><i class="fa fa-check"></i><b>10.2.2</b> Simple random sample with replacement</a></li>
<li class="chapter" data-level="10.2.3" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#stratified-sampling"><i class="fa fa-check"></i><b>10.2.3</b> Stratified sampling</a></li>
<li class="chapter" data-level="10.2.4" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#samp-cluster"><i class="fa fa-check"></i><b>10.2.4</b> Clustered sampling</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#replicate-weights"><i class="fa fa-check"></i><b>10.3</b> Replicate weights</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#balanced-repeated-replication-brr-method"><i class="fa fa-check"></i><b>10.3.1</b> Balanced Repeated Replication (BRR) Method</a></li>
<li class="chapter" data-level="10.3.2" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#fays-brr-method"><i class="fa fa-check"></i><b>10.3.2</b> Fay’s BRR Method</a></li>
<li class="chapter" data-level="10.3.3" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#jackknife-method"><i class="fa fa-check"></i><b>10.3.3</b> Jackknife method</a></li>
<li class="chapter" data-level="10.3.4" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#bootstrap-method"><i class="fa fa-check"></i><b>10.3.4</b> Bootstrap Method</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#und-surv-doc"><i class="fa fa-check"></i><b>10.4</b> Understanding survey design documentation</a></li>
<li class="chapter" data-level="10.5" data-path="c10-specifying-sample-designs.html"><a href="c10-specifying-sample-designs.html#exercises-2"><i class="fa fa-check"></i><b>10.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="c11-missing-data.html"><a href="c11-missing-data.html"><i class="fa fa-check"></i><b>11</b> Missing data</a></li>
<li class="chapter" data-level="12" data-path="c12-pitfalls.html"><a href="c12-pitfalls.html"><i class="fa fa-check"></i><b>12</b> Common pitfalls</a></li>
<li class="part"><span><b>V Vignettes</b></span></li>
<li class="chapter" data-level="13" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html"><i class="fa fa-check"></i><b>13</b> National Crime Victimization Survey Vignette</a>
<ul>
<li class="chapter" data-level="" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#prereq9"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="13.1" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#introduction-8"><i class="fa fa-check"></i><b>13.1</b> Introduction</a></li>
<li class="chapter" data-level="13.2" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#data-structure"><i class="fa fa-check"></i><b>13.2</b> Data Structure</a></li>
<li class="chapter" data-level="13.3" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#survey-notation"><i class="fa fa-check"></i><b>13.3</b> Survey Notation</a></li>
<li class="chapter" data-level="13.4" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#data-file-preparation"><i class="fa fa-check"></i><b>13.4</b> Data File Preparation</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#preparing-files-for-estimation-of-victimization-rates"><i class="fa fa-check"></i><b>13.4.1</b> Preparing Files for Estimation of Victimization Rates</a></li>
<li class="chapter" data-level="13.4.2" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#derived-demographic-variables"><i class="fa fa-check"></i><b>13.4.2</b> Derived Demographic Variables</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#survey-design-objects"><i class="fa fa-check"></i><b>13.5</b> Survey Design Objects</a></li>
<li class="chapter" data-level="13.6" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#calculating-estimates"><i class="fa fa-check"></i><b>13.6</b> Calculating Estimates</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#vic-tot"><i class="fa fa-check"></i><b>13.6.1</b> Estimation 1: Victimization Totals</a></li>
<li class="chapter" data-level="13.6.2" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#vic-prop"><i class="fa fa-check"></i><b>13.6.2</b> Estimation 2: Victimization Proportions</a></li>
<li class="chapter" data-level="13.6.3" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#vic-rate"><i class="fa fa-check"></i><b>13.6.3</b> Estimation 3: Victimization Rates</a></li>
<li class="chapter" data-level="13.6.4" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#prev-rate"><i class="fa fa-check"></i><b>13.6.4</b> Estimation 4: Prevalence Rates</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#exercises-3"><i class="fa fa-check"></i><b>13.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html"><i class="fa fa-check"></i><b>14</b> AmericasBarometer Vignette</a>
<ul>
<li class="chapter" data-level="" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#prereq10"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="14.1" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#introduction-9"><i class="fa fa-check"></i><b>14.1</b> Introduction</a></li>
<li class="chapter" data-level="14.2" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#data-structure-1"><i class="fa fa-check"></i><b>14.2</b> Data Structure</a></li>
<li class="chapter" data-level="14.3" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#preparing-files"><i class="fa fa-check"></i><b>14.3</b> Preparing files</a></li>
<li class="chapter" data-level="14.4" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#survey-design-objects-1"><i class="fa fa-check"></i><b>14.4</b> Survey design objects</a></li>
<li class="chapter" data-level="14.5" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#ambarom-tables"><i class="fa fa-check"></i><b>14.5</b> Calculating estimates and making tables</a></li>
<li class="chapter" data-level="14.6" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#mapping-survey-data"><i class="fa fa-check"></i><b>14.6</b> Mapping survey data</a></li>
<li class="chapter" data-level="14.7" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#exercises-4"><i class="fa fa-check"></i><b>14.7</b> Exercises</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="anes-cb.html"><a href="anes-cb.html"><i class="fa fa-check"></i><b>A</b> ANES Derived Variable Codebook</a>
<ul>
<li class="chapter" data-level="A.1" data-path="anes-cb.html"><a href="anes-cb.html#admin"><i class="fa fa-check"></i><b>A.1</b> ADMIN</a></li>
<li class="chapter" data-level="A.2" data-path="anes-cb.html"><a href="anes-cb.html#weights"><i class="fa fa-check"></i><b>A.2</b> WEIGHTS</a></li>
<li class="chapter" data-level="A.3" data-path="anes-cb.html"><a href="anes-cb.html#pre-election-survey-questionnaire"><i class="fa fa-check"></i><b>A.3</b> PRE-ELECTION SURVEY QUESTIONNAIRE</a></li>
<li class="chapter" data-level="A.4" data-path="anes-cb.html"><a href="anes-cb.html#post-election-survey-questionnaire"><i class="fa fa-check"></i><b>A.4</b> POST-ELECTION SURVEY QUESTIONNAIRE</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="recs-cb.html"><a href="recs-cb.html"><i class="fa fa-check"></i><b>B</b> RECS Derived Variable Codebook</a>
<ul>
<li class="chapter" data-level="B.1" data-path="recs-cb.html"><a href="recs-cb.html#admin-1"><i class="fa fa-check"></i><b>B.1</b> ADMIN</a></li>
<li class="chapter" data-level="B.2" data-path="recs-cb.html"><a href="recs-cb.html#geography"><i class="fa fa-check"></i><b>B.2</b> GEOGRAPHY</a></li>
<li class="chapter" data-level="B.3" data-path="recs-cb.html"><a href="recs-cb.html#weather"><i class="fa fa-check"></i><b>B.3</b> WEATHER</a></li>
<li class="chapter" data-level="B.4" data-path="recs-cb.html"><a href="recs-cb.html#your-home"><i class="fa fa-check"></i><b>B.4</b> YOUR HOME</a></li>
<li class="chapter" data-level="B.5" data-path="recs-cb.html"><a href="recs-cb.html#space-heating"><i class="fa fa-check"></i><b>B.5</b> SPACE HEATING</a></li>
<li class="chapter" data-level="B.6" data-path="recs-cb.html"><a href="recs-cb.html#air-conditioning"><i class="fa fa-check"></i><b>B.6</b> AIR CONDITIONING</a></li>
<li class="chapter" data-level="B.7" data-path="recs-cb.html"><a href="recs-cb.html#thermostat"><i class="fa fa-check"></i><b>B.7</b> THERMOSTAT</a></li>
<li class="chapter" data-level="B.8" data-path="recs-cb.html"><a href="recs-cb.html#weights-1"><i class="fa fa-check"></i><b>B.8</b> WEIGHTS</a></li>
<li class="chapter" data-level="B.9" data-path="recs-cb.html"><a href="recs-cb.html#consumption-and-expenditure"><i class="fa fa-check"></i><b>B.9</b> CONSUMPTION AND EXPENDITURE</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html"><i class="fa fa-check"></i><b>C</b> Importing survey data into R</a>
<ul>
<li class="chapter" data-level="C.1" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-delimiter-separated-files-into-r"><i class="fa fa-check"></i><b>C.1</b> Importing delimiter-separated files into R</a></li>
<li class="chapter" data-level="C.2" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#loading-excel-files-into-r"><i class="fa fa-check"></i><b>C.2</b> Loading Excel files into R</a></li>
<li class="chapter" data-level="C.3" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-stata-sas-and-spss-files-into-r"><i class="fa fa-check"></i><b>C.3</b> Importing Stata, SAS, and SPSS files into R</a>
<ul>
<li class="chapter" data-level="C.3.1" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#syntax-9"><i class="fa fa-check"></i><b>C.3.1</b> Syntax</a></li>
<li class="chapter" data-level="C.3.2" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#working-with-labeled-data"><i class="fa fa-check"></i><b>C.3.2</b> Working with labeled data</a></li>
<li class="chapter" data-level="C.3.3" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#labeled-missing-data-values"><i class="fa fa-check"></i><b>C.3.3</b> Labeled missing data values</a></li>
</ul></li>
<li class="chapter" data-level="C.4" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-data-from-apis-into-r"><i class="fa fa-check"></i><b>C.4</b> Importing data from APIs into R</a></li>
<li class="chapter" data-level="C.5" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#accessing-databases-in-r"><i class="fa fa-check"></i><b>C.5</b> Accessing databases in R</a></li>
<li class="chapter" data-level="C.6" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-data-from-other-formats"><i class="fa fa-check"></i><b>C.6</b> Importing data from other formats</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Exploring Complex Survey Data Analysis in R: A Tidy Introduction with srvyr</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="c04-set-up" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Setup<a href="c04-set-up.html#c04-set-up" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This chapter provides an overview of the packages, datasets, and design objects used throughout this book. We recommend taking the time to walk through the code provided here and make sure you have everything installed to ensure a smoother learning experience. Additionally, as mentioned in Chapter <a href="c02-overview-surveys.html#c02-overview-surveys">2</a>, researchers and analysts need to understand how the survey was conducted to better understand the results and interpret findings. Therefore, we provide some overview information about the datasets used throughout this book in examples and exercises. If you have questions or run into issues with the code provided, please visit the GitHub repository for this book, <a href="https://github.com/tidy-survey-r/tidy-survey-book">https://github.com/tidy-survey-r/tidy-survey-book</a>.</p>
<div id="packages" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Packages<a href="c04-set-up.html#packages" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Most functions in this book are from three main packages: {tidyverse}, {survey}, and {srvyr}. If you have not installed these packages, use the following code. We use the development version of srvyr from GitHub because of its additional functionality compared to the one on CRAN.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="c04-set-up.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">&quot;tidyverse&quot;</span>,<span class="st">&quot;survey&quot;</span>))</span>
<span id="cb7-2"><a href="c04-set-up.html#cb7-2" aria-hidden="true" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;https://github.com/gergness/srvyr&quot;</span>)</span></code></pre></div>
<p>Additionally, to ensure that all readers can follow the examples throughout the book, we provide the analytic datasets in an R package, {srvyr.data}. Readers can install the package directly from GitHub using the {remotes} package.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="c04-set-up.html#cb8-1" aria-hidden="true" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;https://github.com/tidy-survey-r/srvyr.data&quot;</span>)</span></code></pre></div>
<p>Once these packages are installed, load these packages using the <code>library()</code> function:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="c04-set-up.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb9-2"><a href="c04-set-up.html#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey)</span>
<span id="cb9-3"><a href="c04-set-up.html#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(srvyr)</span>
<span id="cb9-4"><a href="c04-set-up.html#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(srvyr.data)</span></code></pre></div>
<p>In addition to these four packages, we want to highlight three others: {broom}, {gt}, and {gtsummary}. These help display output and create formatted tables that are easy to read and interpret. You will also want to make sure you install these packages using the following code<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a>:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="c04-set-up.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">&quot;gt&quot;</span>,<span class="st">&quot;gtsummary&quot;</span>))</span></code></pre></div>
<p>Once these packages are installed, load these packages using the <code>library()</code> function:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="c04-set-up.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb11-2"><a href="c04-set-up.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb11-3"><a href="c04-set-up.html#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span></code></pre></div>
<p>In addition to the packages above, this setup chapter requires that you install and load the {censusapi} package. This will be used to assist with correctly weighting one of our key datasets used in this book. If you do not already have this package installed, run this code:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="c04-set-up.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;censusapi&quot;</span>)</span></code></pre></div>
<p>Once this package is installed, load it using the <code>library()</code> function:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="c04-set-up.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(censusapi)</span></code></pre></div>
<p>Additional packages are used in the vignettes. We list them in the Prerequisite boxes at the beginning of the chapters. When working through those chapters, please ensure you pay attention to the setup box at the beginning of the chapter and install all necessary packages.</p>
</div>
<div id="data" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Data<a href="c04-set-up.html#data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As mentioned above, the {srvyr.data} package includes the datasets used throughout the book. Once installed and loaded using the code above, readers can explore the documentation using the <code>help()</code> function and read the descriptions for the datasets provided:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="c04-set-up.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(<span class="at">package=</span><span class="st">&quot;srvyr.data&quot;</span>)</span></code></pre></div>
<p>The book provides examples and exercises using two key datasets: the American National Election Studies <span class="citation">(ANES – <a href="#ref-debell" role="doc-biblioref">DeBell 2010</a>)</span> and the Residential Energy Consumption Survey <span class="citation">(RECS – <a href="#ref-recs-2020-tech" role="doc-biblioref">U.S. Energy Information Administration 2023a</a>)</span>. Use the <code>data()</code> command to load the datasets from the {srvyr.data} package into the environment. You can either load all datasets by using the <code>data()</code> function without any arguments, or you can include the specific datasets (e.g.,<code>recs_2020</code>) as an argument. In the code chunk below, we are loading the <code>anes_2020</code> and <code>recs_2020</code> datasets into objects with their respective names:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="c04-set-up.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(anes_2020)</span>
<span id="cb15-2"><a href="c04-set-up.html#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(recs_2020)</span></code></pre></div>
<div id="data-american-national-election-studies-anes" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Data: American National Election Studies (ANES)<a href="c04-set-up.html#data-american-national-election-studies-anes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The ANES is a series study that has collected data from election surveys since 1948. These surveys contain data on public opinion and voting behavior in U.S. presidential elections. The 2020 survey (the data we use in the book) was fielded to individuals over the web, through live video interviewing, or with computer-assisted telephone interviewing (CATI). The survey includes questions on party affiliation, voting choice, and level of trust in the government.</p>
<p>When first looking at new survey data, data users should read the survey documentation (see Chapter <a href="c03-understanding-survey-data-documentation.html#c03-understanding-survey-data-documentation">3</a> to understand how the data was collected and implemented). The original data from ANES contained variables starting with V20 <span class="citation">(<a href="#ref-debell" role="doc-biblioref">DeBell 2010</a>)</span>, so to assist with our analysis throughout the book, we created descriptive variable names. For example, the respondent’s age is now in a variable called <code>Age</code>, and gender is in a variable called <code>Gender</code>. These descriptive variables are included in the data from the {srvyr.data} package, and Table <a href="c04-set-up.html#tab:ANESvars">4.1</a> displays the list of these renamed variables. A complete overview of all variables can be found in Appendix <a href="anes-cb.html#anes-cb">A</a>.</p>
<table>
<caption><span id="tab:ANESvars">TABLE 4.1: </span> List of Variables in the ANES Data</caption>
<thead>
<tr class="header">
<th align="left">Variable Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">CaseID</td>
</tr>
<tr class="even">
<td align="left">InterviewMode</td>
</tr>
<tr class="odd">
<td align="left">Weight</td>
</tr>
<tr class="even">
<td align="left">VarUnit</td>
</tr>
<tr class="odd">
<td align="left">Stratum</td>
</tr>
<tr class="even">
<td align="left">CampaignInterest</td>
</tr>
<tr class="odd">
<td align="left">VotedPres2016</td>
</tr>
<tr class="even">
<td align="left">VotedPres2016_selection</td>
</tr>
<tr class="odd">
<td align="left">PartyID</td>
</tr>
<tr class="even">
<td align="left">TrustGovernment</td>
</tr>
<tr class="odd">
<td align="left">TrustPeople</td>
</tr>
<tr class="even">
<td align="left">Age</td>
</tr>
<tr class="odd">
<td align="left">AgeGroup</td>
</tr>
<tr class="even">
<td align="left">Education</td>
</tr>
<tr class="odd">
<td align="left">RaceEth</td>
</tr>
<tr class="even">
<td align="left">Gender</td>
</tr>
<tr class="odd">
<td align="left">Income</td>
</tr>
<tr class="even">
<td align="left">Income7</td>
</tr>
<tr class="odd">
<td align="left">VotedPres2020</td>
</tr>
<tr class="even">
<td align="left">VotedPres2020_selection</td>
</tr>
<tr class="odd">
<td align="left">EarlyVote2020</td>
</tr>
</tbody>
</table>
<p>Before starting an analysis, it is good to view the data to understand the types of data and variables that are included. The <code>dplyr::glimpse()</code> function produces a list of all variables, the type of the variable (e.g., function, double), and a few example values. Below, we remove the variables with numbers to see a glimpse of the ones with descriptive names:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="c04-set-up.html#cb16-1" aria-hidden="true" tabindex="-1"></a>anes_2020 <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="c04-set-up.html#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">matches</span>(<span class="st">&quot;^V</span><span class="sc">\\</span><span class="st">d&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="c04-set-up.html#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 7,453
## Columns: 21
## $ CaseID                  &lt;dbl&gt; 200015, 200022, 200039, 200046, 200053…
## $ InterviewMode           &lt;fct&gt; Web, Web, Web, Web, Web, Web, Web, Web…
## $ Weight                  &lt;dbl&gt; 1.0057, 1.1635, 0.7687, 0.5210, 0.9658…
## $ VarUnit                 &lt;fct&gt; 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 2,…
## $ Stratum                 &lt;fct&gt; 9, 26, 41, 29, 23, 37, 7, 37, 32, 41, …
## $ CampaignInterest        &lt;fct&gt; Somewhat interested, Not much interest…
## $ VotedPres2016           &lt;fct&gt; Yes, Yes, Yes, Yes, Yes, No, Yes, No, …
## $ VotedPres2016_selection &lt;fct&gt; Trump, Other, Clinton, Clinton, Trump,…
## $ PartyID                 &lt;fct&gt; Strong republican, Independent, Indepe…
## $ TrustGovernment         &lt;fct&gt; Never, Never, Some of the time, About …
## $ TrustPeople             &lt;fct&gt; About half the time, Some of the time,…
## $ Age                     &lt;dbl&gt; 46, 37, 40, 41, 72, 71, 37, 45, 70, 43…
## $ AgeGroup                &lt;fct&gt; 40-49, 30-39, 40-49, 40-49, 70 or olde…
## $ Education               &lt;fct&gt; Bachelor&#39;s, Post HS, High school, Post…
## $ RaceEth                 &lt;fct&gt; &quot;Hispanic&quot;, &quot;Asian, NH/PI&quot;, &quot;White&quot;, &quot;…
## $ Gender                  &lt;fct&gt; Male, Female, Female, Male, Male, Fema…
## $ Income                  &lt;fct&gt; &quot;$175,000-249,999&quot;, &quot;$70,000-74,999&quot;, …
## $ Income7                 &lt;fct&gt; $125k or more, $60-80k, $100-125k, $20…
## $ VotedPres2020           &lt;fct&gt; NA, Yes, Yes, Yes, Yes, Yes, Yes, NA, …
## $ VotedPres2020_selection &lt;fct&gt; NA, Other, Biden, Biden, Trump, Biden,…
## $ EarlyVote2020           &lt;fct&gt; NA, No, No, No, No, No, No, NA, Yes, N…</code></pre>
<p>From this, we can see there are 7,453 rows and 21 variables in the ANES data. This output also indicates that most of the variables are factors (e.g., <code>InterviewMode</code>), and a few variables are in double (numeric) format (e.g., <code>Age</code>).</p>
</div>
<div id="residential-energy-consumption-survey-recs" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Residential Energy Consumption Survey (RECS)<a href="c04-set-up.html#residential-energy-consumption-survey-recs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>RECS is a study that provides energy consumption and expenditure data in American households. The Energy Information Administration funds RECS, and the data is collected through interviews with energy suppliers. These interviews happen in person, over the phone, and online. It has been fielded 14 times between 1950 and 2020. The survey includes questions about appliances, electronics, heating, air conditioning (A/C), temperatures, water heating, lighting, energy bills, respondent demographics, and energy assistance.</p>
<p>When first looking at new survey data, data users should read the survey documentation (see Chapter <a href="c03-understanding-survey-data-documentation.html#c03-understanding-survey-data-documentation">3</a>) to understand how the data was collected and implemented. Table <a href="c04-set-up.html#tab:RECSvars">4.2</a> displays the list of variables in the RECS data (not including the weights, which start with <code>NWEIGHT</code> and will be described in more detail in Chapter <a href="c10-specifying-sample-designs.html#c10-specifying-sample-designs">10</a>). An overview of all variables can be found in Appendix <a href="recs-cb.html#recs-cb">B</a>.</p>
<table>
<caption><span id="tab:RECSvars">TABLE 4.2: </span> List of Variables in the RECS Data</caption>
<thead>
<tr class="header">
<th align="left">Variable Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DOEID</td>
</tr>
<tr class="even">
<td align="left">ClimateRegion_BA</td>
</tr>
<tr class="odd">
<td align="left">Urbanicity</td>
</tr>
<tr class="even">
<td align="left">Region</td>
</tr>
<tr class="odd">
<td align="left">REGIONC</td>
</tr>
<tr class="even">
<td align="left">Division</td>
</tr>
<tr class="odd">
<td align="left">STATE_FIPS</td>
</tr>
<tr class="even">
<td align="left">state_postal</td>
</tr>
<tr class="odd">
<td align="left">state_name</td>
</tr>
<tr class="even">
<td align="left">HDD65</td>
</tr>
<tr class="odd">
<td align="left">CDD65</td>
</tr>
<tr class="even">
<td align="left">HDD30YR</td>
</tr>
<tr class="odd">
<td align="left">CDD30YR</td>
</tr>
<tr class="even">
<td align="left">HousingUnitType</td>
</tr>
<tr class="odd">
<td align="left">YearMade</td>
</tr>
<tr class="even">
<td align="left">TOTSQFT_EN</td>
</tr>
<tr class="odd">
<td align="left">TOTHSQFT</td>
</tr>
<tr class="even">
<td align="left">TOTCSQFT</td>
</tr>
<tr class="odd">
<td align="left">SpaceHeatingUsed</td>
</tr>
<tr class="even">
<td align="left">ACUsed</td>
</tr>
<tr class="odd">
<td align="left">HeatingBehavior</td>
</tr>
<tr class="even">
<td align="left">WinterTempDay</td>
</tr>
<tr class="odd">
<td align="left">WinterTempAway</td>
</tr>
<tr class="even">
<td align="left">WinterTempNight</td>
</tr>
<tr class="odd">
<td align="left">ACBehavior</td>
</tr>
<tr class="even">
<td align="left">SummerTempDay</td>
</tr>
<tr class="odd">
<td align="left">SummerTempAway</td>
</tr>
<tr class="even">
<td align="left">SummerTempNight</td>
</tr>
<tr class="odd">
<td align="left">BTUEL</td>
</tr>
<tr class="even">
<td align="left">DOLLAREL</td>
</tr>
<tr class="odd">
<td align="left">BTUNG</td>
</tr>
<tr class="even">
<td align="left">DOLLARNG</td>
</tr>
<tr class="odd">
<td align="left">BTULP</td>
</tr>
<tr class="even">
<td align="left">DOLLARLP</td>
</tr>
<tr class="odd">
<td align="left">BTUFO</td>
</tr>
<tr class="even">
<td align="left">DOLLARFO</td>
</tr>
<tr class="odd">
<td align="left">BTUWOOD</td>
</tr>
<tr class="even">
<td align="left">TOTALBTU</td>
</tr>
<tr class="odd">
<td align="left">TOTALDOL</td>
</tr>
</tbody>
</table>
<p>Before starting an analysis, it is good to view the data to understand the types of data and variables that are included. The <code>dplyr::glimpse()</code> function produces a list of all variables, the type of the variable (e.g., function, double), and a few example values.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="c04-set-up.html#cb18-1" aria-hidden="true" tabindex="-1"></a>recs_2020 <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="c04-set-up.html#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">matches</span>(<span class="st">&quot;^NWEIGHT&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb18-3"><a href="c04-set-up.html#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 18,496
## Columns: 39
## $ DOEID            &lt;dbl&gt; 1e+05, 1e+05, 1e+05, 1e+05, 1e+05, 1e+05, 1e+…
## $ ClimateRegion_BA &lt;fct&gt; Mixed-Dry, Mixed-Humid, Mixed-Dry, Mixed-Humi…
## $ Urbanicity       &lt;fct&gt; Urban Area, Urban Area, Urban Area, Urban Are…
## $ Region           &lt;fct&gt; West, South, West, South, Northeast, South, S…
## $ REGIONC          &lt;chr&gt; &quot;WEST&quot;, &quot;SOUTH&quot;, &quot;WEST&quot;, &quot;SOUTH&quot;, &quot;NORTHEAST&quot;…
## $ Division         &lt;fct&gt; Mountain South, West South Central, Mountain …
## $ STATE_FIPS       &lt;chr&gt; &quot;35&quot;, &quot;05&quot;, &quot;35&quot;, &quot;45&quot;, &quot;34&quot;, &quot;48&quot;, &quot;40&quot;, &quot;28…
## $ state_postal     &lt;fct&gt; NM, AR, NM, SC, NJ, TX, OK, MS, DC, AZ, CA, T…
## $ state_name       &lt;fct&gt; New Mexico, Arkansas, New Mexico, South Carol…
## $ HDD65            &lt;dbl&gt; 3844, 3766, 3819, 2614, 4219, 901, 3148, 1825…
## $ CDD65            &lt;dbl&gt; 1679, 1458, 1696, 1718, 1363, 3558, 2128, 237…
## $ HDD30YR          &lt;dbl&gt; 4451, 4429, 4500, 3229, 4896, 1150, 3564, 266…
## $ CDD30YR          &lt;dbl&gt; 1027, 1305, 1010, 1653, 1059, 3588, 2043, 216…
## $ HousingUnitType  &lt;fct&gt; Single-family detached, Apartment: 5 or more …
## $ YearMade         &lt;ord&gt; 1970-1979, 1980-1989, 1960-1969, 1980-1989, 1…
## $ TOTSQFT_EN       &lt;dbl&gt; 2100, 590, 900, 2100, 800, 4520, 2100, 900, 7…
## $ TOTHSQFT         &lt;dbl&gt; 2100, 590, 900, 2100, 800, 3010, 1200, 900, 7…
## $ TOTCSQFT         &lt;dbl&gt; 2100, 590, 900, 2100, 800, 3010, 1200, 0, 500…
## $ SpaceHeatingUsed &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRU…
## $ ACUsed           &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FAL…
## $ HeatingBehavior  &lt;fct&gt; Set one temp and leave it, Turn on or off as …
## $ WinterTempDay    &lt;dbl&gt; 70, 70, 69, 68, 68, 76, 74, 70, 68, 70, 72, 7…
## $ WinterTempAway   &lt;dbl&gt; 70, 65, 68, 68, 68, 76, 65, 70, 60, 70, 70, 7…
## $ WinterTempNight  &lt;dbl&gt; 68, 65, 67, 68, 68, 68, 74, 68, 62, 68, 72, 7…
## $ ACBehavior       &lt;fct&gt; Set one temp and leave it, Turn on or off as …
## $ SummerTempDay    &lt;dbl&gt; 71, 68, 70, 72, 72, 69, 68, NA, 72, 74, 77, 7…
## $ SummerTempAway   &lt;dbl&gt; 71, 68, 68, 72, 72, 74, 70, NA, 76, 74, 77, 7…
## $ SummerTempNight  &lt;dbl&gt; 71, 68, 68, 72, 72, 68, 70, NA, 68, 72, 77, 7…
## $ BTUEL            &lt;dbl&gt; 42723, 17889, 8147, 31647, 20027, 48968, 4940…
## $ DOLLAREL         &lt;dbl&gt; 1955.06, 713.27, 334.51, 1424.86, 1087.00, 18…
## $ BTUNG            &lt;dbl&gt; 101924.4, 10145.3, 22603.1, 55118.7, 39099.5,…
## $ DOLLARNG         &lt;dbl&gt; 701.83, 261.73, 188.14, 636.91, 376.04, 439.4…
## $ BTULP            &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 178…
## $ DOLLARLP         &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, …
## $ BTUFO            &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 681…
## $ DOLLARFO         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 187…
## $ BTUWOOD          &lt;dbl&gt; 0, 0, 0, 0, 0, 3000, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ TOTALBTU         &lt;dbl&gt; 144648, 28035, 30750, 86765, 59127, 85401, 13…
## $ TOTALDOL         &lt;dbl&gt; 2656.9, 975.0, 522.6, 2061.8, 1463.0, 2335.1,…</code></pre>
<p>From this, we can see that there are 18,496 rows and 39 non-weight variables in the RECS data. This output also indicates that most of the variables are in double (numeric) format (e.g., <code>TOTSQFT_EN</code>), with some factor (e.g., <code>Region</code>), Boolean (e.g., <code>ACUsed</code>), character (e.g., <code>REGIONC</code>), and ordinal (e.g., <code>YearMade</code>) variables.</p>
</div>
</div>
<div id="design-objects" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Design Objects<a href="c04-set-up.html#design-objects" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The design object is the backbone for survey analysis. This object is where we specify the sampling design, weights, and other necessary information to ensure the error in the data is accounted for. Analysts will need to review the survey documentation to understand the sampling and weighting structure of the data before creating thie design object.</p>
<p>In this chapter, we will provide details on how to code the design object for the ANES and RECS data used in the book. However, we only provide a high-level overview to get you going. For a more in-depth understanding of creating these design objects for a variety of sampling designs, see Chapter <a href="c10-specifying-sample-designs.html#c10-specifying-sample-designs">10</a>.</p>
<p>Once we have the design objects, all analysis uses these objects and not the original survey data. For example, the ANES data is called <code>anes_2020</code>. If we create a design object called <code>anes_des</code>, all analyses should start with <code>anes_des</code> and not <code>anes_2020</code>. You can still review the original data and do an exploratory data review on the original data prior to conducting complex survey analysis (and, in fact, is highly recommended – see Chapter <a href="c12-pitfalls.html#c12-pitfalls">12</a>).</p>
<div id="american-national-election-studies-anes" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> American National Election Studies (ANES)<a href="c04-set-up.html#american-national-election-studies-anes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Creating the ANES design object requires reviewing the documentation <span class="citation">(<a href="#ref-debell" role="doc-biblioref">DeBell 2010</a>)</span> to understand the sampling and weighting implications for analysis. From this documentation and as noted in Chapter <a href="c03-understanding-survey-data-documentation.html#c03-understanding-survey-data-documentation">3</a>, the 2020 ANES data is weighted to the sample, not the population. If we want to get generalizations for the population, we need to weigh the data against the full population count. To do this, we will use the Current Population Survey (CPS) to find a number of the non-institutional U.S. citizens aged 18 or older living in the 50 U.S. states or D.C. in March of 2020, as is recommended in the ANES methodology.</p>
<p>The {censusapi} package allows us to run a reproducible analysis of the CPS data. Note that this package requires a Census API key, which you can get for free from the Census website (more information can be found in the package documentation). A best practice is to include the Census API key in our R environment and not directly in the code. We can use the {usethis} package’s <code>edit_r_environ()</code> function to access the R environment (located in a file called <code>.Renviron</code>). Run <code>edit_r_environ()</code>, save the Census API key on a new line as <code>CENSUS_KEY=yourkeyhere</code>, and restart RStudio. Once the Census API key is saved in the R environment, we access it in our code with <code>Sys.getenv("CENSUS_KEY")</code>.</p>
<p>Since the ANES data is from March 2020, we will want to get a population count for that same time period. To do this, we will use the March data from CPS (<code>cps/basic/mar</code>) and the year for 2020 (<code>vintage = 2020</code>). Additionally, we need to extract several variables from the CPS:</p>
<ul>
<li>month (<code>HRMONTH</code>) and year (<code>HRYEAR4</code>) of the interview: to confirm the correct time period</li>
<li>age (<code>PRTAGE</code>) of the respondent: to narrow the population to 18 and older (eligible age to vote)</li>
<li>citizenship status (<code>PRCITSHP</code>) of the respondent: to narrow the population to only those eligible to vote</li>
<li>final person-level weight (<code>PWSSWGT</code>)</li>
</ul>
<p>Detailed information for these variables can be found in the data dictionary<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a>.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="c04-set-up.html#cb20-1" aria-hidden="true" tabindex="-1"></a>cps_state_in <span class="ot">&lt;-</span> <span class="fu">getCensus</span>(<span class="at">name =</span> <span class="st">&quot;cps/basic/mar&quot;</span>,</span>
<span id="cb20-2"><a href="c04-set-up.html#cb20-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">vintage =</span> <span class="dv">2020</span>,</span>
<span id="cb20-3"><a href="c04-set-up.html#cb20-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">region =</span> <span class="st">&quot;state&quot;</span>,</span>
<span id="cb20-4"><a href="c04-set-up.html#cb20-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">vars =</span> <span class="fu">c</span>(<span class="st">&quot;HRMONTH&quot;</span>, <span class="st">&quot;HRYEAR4&quot;</span>, </span>
<span id="cb20-5"><a href="c04-set-up.html#cb20-5" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;PRTAGE&quot;</span>, <span class="st">&quot;PRCITSHP&quot;</span>, <span class="st">&quot;PWSSWGT&quot;</span>), </span>
<span id="cb20-6"><a href="c04-set-up.html#cb20-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">key =</span> <span class="fu">Sys.getenv</span>(<span class="st">&quot;CENSUS_KEY&quot;</span>))</span>
<span id="cb20-7"><a href="c04-set-up.html#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="c04-set-up.html#cb20-8" aria-hidden="true" tabindex="-1"></a>cps_state <span class="ot">&lt;-</span> cps_state_in <span class="sc">%&gt;%</span></span>
<span id="cb20-9"><a href="c04-set-up.html#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb20-10"><a href="c04-set-up.html#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb20-11"><a href="c04-set-up.html#cb20-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">.fns =</span> as.numeric))</span></code></pre></div>
<p>As we narrowed the dataset to March 2020, we expect all interviews to have been conducted during that month and year. As we requested the month and year of interview variables, we can confirm that all the data is from March (<code>HRMONTH == 3</code>) of 2020 (<code>HRYEAR4 == 2020</code>).</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="c04-set-up.html#cb21-1" aria-hidden="true" tabindex="-1"></a>cps_state <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="c04-set-up.html#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(HRMONTH, HRYEAR4)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   HRMONTH HRYEAR4
##     &lt;dbl&gt;   &lt;dbl&gt;
## 1       3    2020</code></pre>
<p>We then can use the age and citizenship variables to filter the data to only those who are 18 years or older (<code>PRTAGE &gt;= 18</code>) and have U.S. citizenship (<code>PRCITSHIP %in% (1:4)</code>).</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="c04-set-up.html#cb23-1" aria-hidden="true" tabindex="-1"></a>cps_narrow_resp <span class="ot">&lt;-</span> cps_state <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="c04-set-up.html#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="c04-set-up.html#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(PRTAGE <span class="sc">&gt;=</span> <span class="dv">18</span>,</span>
<span id="cb23-4"><a href="c04-set-up.html#cb23-4" aria-hidden="true" tabindex="-1"></a>         PRCITSHP <span class="sc">%in%</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>))</span></code></pre></div>
<p>To calculate the U.S. population from the narrowed data, we sum the person weights (<code>PWSSWGT</code>).</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="c04-set-up.html#cb24-1" aria-hidden="true" tabindex="-1"></a>targetpop <span class="ot">&lt;-</span> cps_narrow_resp <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="c04-set-up.html#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(PWSSWGT) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="c04-set-up.html#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>()</span>
<span id="cb24-4"><a href="c04-set-up.html#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="c04-set-up.html#cb24-5" aria-hidden="true" tabindex="-1"></a>targetpop</span></code></pre></div>
<pre><code>## [1] 2.31e+08</code></pre>
<p>The target population in 2020 is 231,034,125. This information gives us what we need to create the survey design object that can be used to estimate data for the population. Using the <code>anes_2020</code> data, we will adjust the weighting variable (<code>V200010b</code>) using the target population we just calculated (<code>targetpop</code>).</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="c04-set-up.html#cb26-1" aria-hidden="true" tabindex="-1"></a>anes_adjwgt <span class="ot">&lt;-</span> anes_2020 <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="c04-set-up.html#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Weight =</span> V200010b <span class="sc">/</span> <span class="fu">sum</span>(V200010b) <span class="sc">*</span> targetpop) </span></code></pre></div>
<p>Once we have the adjusted weights, we can review the rest of the documentation to determine how to create the survey design. The documentation indicates that the study is conducted using a stratified cluster sampling design This means that we will need to specify variables for <code>strata</code> and <code>ids</code> (cluster) and fill in the <code>nest</code> argument. The document provides information on which strata and cluster variables to use depending on whether you are analyzing pre- or post-election data. Throughout this book, we analyze the post-election data, so we need to use the post-election weight of <code>V200010b</code>, strata variable or <code>V200010d</code>, and PSU/cluster variable of <code>V200010c</code>. Additionally, we specify <code>nest=TRUE</code>, which enforces nesting of the clusters within the strata.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="c04-set-up.html#cb27-1" aria-hidden="true" tabindex="-1"></a>anes_des <span class="ot">&lt;-</span> anes_adjwgt <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="c04-set-up.html#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">weights =</span> Weight,</span>
<span id="cb27-3"><a href="c04-set-up.html#cb27-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">strata =</span> V200010d,</span>
<span id="cb27-4"><a href="c04-set-up.html#cb27-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ids =</span> V200010c,</span>
<span id="cb27-5"><a href="c04-set-up.html#cb27-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">nest =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-6"><a href="c04-set-up.html#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="c04-set-up.html#cb27-7" aria-hidden="true" tabindex="-1"></a>anes_des</span></code></pre></div>
<pre><code>## Stratified 1 - level Cluster Sampling design (with replacement)
## With (101) clusters.
## Called via srvyr
## Sampling variables:
##   - ids: V200010c 
##   - strata: V200010d 
##   - weights: Weight 
## Data variables: 
##   - V200001 (dbl), CaseID (dbl), V200002 (hvn_lbll), InterviewMode
##     (fct), V200010b (dbl), Weight (dbl), V200010c (dbl), VarUnit (fct),
##     V200010d (dbl), Stratum (fct), V201006 (hvn_lbll), CampaignInterest
##     (fct), V201024 (hvn_lbll), V201025x (hvn_lbll), V201029 (hvn_lbll),
##     V201101 (hvn_lbll), V201102 (hvn_lbll), VotedPres2016 (fct),
##     V201103 (hvn_lbll), VotedPres2016_selection (fct), V201228
##     (hvn_lbll), V201229 (hvn_lbll), V201230 (hvn_lbll), V201231x
##     (hvn_lbll), PartyID (fct), V201233 (hvn_lbll), TrustGovernment
##     (fct), V201237 (hvn_lbll), TrustPeople (fct), V201507x (hvn_lbll),
##     Age (dbl), AgeGroup (fct), V201510 (hvn_lbll), Education (fct),
##     V201546 (hvn_lbll), V201547a (hvn_lbll), V201547b (hvn_lbll),
##     V201547c (hvn_lbll), V201547d (hvn_lbll), V201547e (hvn_lbll),
##     V201547z (hvn_lbll), V201549x (hvn_lbll), RaceEth (fct), V201600
##     (hvn_lbll), Gender (fct), V201607 (hvn_lbll), V201610 (hvn_lbll),
##     V201611 (hvn_lbll), V201613 (hvn_lbll), V201615 (hvn_lbll), V201616
##     (hvn_lbll), V201617x (hvn_lbll), Income (fct), Income7 (fct),
##     V202051 (hvn_lbll), V202066 (hvn_lbll), V202072 (hvn_lbll),
##     VotedPres2020 (fct), V202073 (hvn_lbll), V202109x (hvn_lbll),
##     V202110x (hvn_lbll), VotedPres2020_selection (fct), EarlyVote2020
##     (fct)</code></pre>
<p>Viewing this new object outputs information about the survey design object and specifies that ANES is a “Stratified 1 - level Cluster Sampling design (with replacement)
With (101) clusters”. Additionally, the output displays the sampling variables and then lists the rest of the variables on the dataset. This design object will be used throughout this book to conduct survey analysis.</p>
</div>
<div id="residential-energy-consumption-survey-recs-1" class="section level3 hasAnchor" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Residential Energy Consumption Survey (RECS)<a href="c04-set-up.html#residential-energy-consumption-survey-recs-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Creating the RECS design object requires reviewing the documentation <span class="citation">(<a href="#ref-recs-2020-tech" role="doc-biblioref">U.S. Energy Information Administration 2023a</a>)</span> to understand the sampling and weighting implications for analysis. The documentation shows the 2020 RECS uses Jackknife weights where the main analytic weight is <code>NWEIGHT</code>, and the Jackknife weights are <code>NWEIGHT1</code>-<code>NWEIGHT60</code>. In the design object code, we can specify these in the <code>weights</code> and <code>repweights</code> arguments, respectively.</p>
<p>With Jackknife weights, a few more pieces of information needed: <code>type</code>, <code>scale</code>, and <code>mse</code>. Chapter <a href="c10-specifying-sample-designs.html#c10-specifying-sample-designs">10</a> goes into more detail about each of these arguments. For the purposes of getting you up and running with analyses, the documentation provides information on each of these values, and we can use the following code to create the design object: <code>type=JK1</code>, <code>scale=59/60</code> and <code>mse = TRUE</code>.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="c04-set-up.html#cb29-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="ot">&lt;-</span> recs_2020 <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="c04-set-up.html#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(</span>
<span id="cb29-3"><a href="c04-set-up.html#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> NWEIGHT,</span>
<span id="cb29-4"><a href="c04-set-up.html#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">repweights =</span> NWEIGHT1<span class="sc">:</span>NWEIGHT60,</span>
<span id="cb29-5"><a href="c04-set-up.html#cb29-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">&quot;JK1&quot;</span>,</span>
<span id="cb29-6"><a href="c04-set-up.html#cb29-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">scale =</span> <span class="dv">59</span><span class="sc">/</span><span class="dv">60</span>,</span>
<span id="cb29-7"><a href="c04-set-up.html#cb29-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mse =</span> <span class="cn">TRUE</span></span>
<span id="cb29-8"><a href="c04-set-up.html#cb29-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb29-9"><a href="c04-set-up.html#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="c04-set-up.html#cb29-10" aria-hidden="true" tabindex="-1"></a>recs_des</span></code></pre></div>
<pre><code>## Call: Called via srvyr
## Unstratified cluster jacknife (JK1) with 60 replicates and MSE variances.
## Sampling variables:
##   - repweights: `NWEIGHT1 + NWEIGHT2 + NWEIGHT3 + NWEIGHT4 + NWEIGHT5 +
##     NWEIGHT6 + NWEIGHT7 + NWEIGHT8 + NWEIGHT9 + NWEIGHT10 + NWEIGHT11 +
##     NWEIGHT12 + NWEIGHT13 + NWEIGHT14 + NWEIGHT15 + NWEIGHT16 +
##     NWEIGHT17 + NWEIGHT18 + NWEIGHT19 + NWEIGHT20 + NWEIGHT21 +
##     NWEIGHT22 + NWEIGHT23 + NWEIGHT24 + NWEIGHT25 + NWEIGHT26 +
##     NWEIGHT27 + NWEIGHT28 + NWEIGHT29 + NWEIGHT30 + NWEIGHT31 +
##     NWEIGHT32 + NWEIGHT33 + NWEIGHT34 + NWEIGHT35 + NWEIGHT36 +
##     NWEIGHT37 + NWEIGHT38 + NWEIGHT39 + NWEIGHT40 + NWEIGHT41 +
##     NWEIGHT42 + NWEIGHT43 + NWEIGHT44 + NWEIGHT45 + NWEIGHT46 +
##     NWEIGHT47 + NWEIGHT48 + NWEIGHT49 + NWEIGHT50 + NWEIGHT51 +
##     NWEIGHT52 + NWEIGHT53 + NWEIGHT54 + NWEIGHT55 + NWEIGHT56 +
##     NWEIGHT57 + NWEIGHT58 + NWEIGHT59 + NWEIGHT60` 
##   - weights: NWEIGHT 
## Data variables: 
##   - DOEID (dbl), ClimateRegion_BA (fct), Urbanicity (fct), Region
##     (fct), REGIONC (chr), Division (fct), STATE_FIPS (chr),
##     state_postal (fct), state_name (fct), HDD65 (dbl), CDD65 (dbl),
##     HDD30YR (dbl), CDD30YR (dbl), HousingUnitType (fct), YearMade
##     (ord), TOTSQFT_EN (dbl), TOTHSQFT (dbl), TOTCSQFT (dbl),
##     SpaceHeatingUsed (lgl), ACUsed (lgl), HeatingBehavior (fct),
##     WinterTempDay (dbl), WinterTempAway (dbl), WinterTempNight (dbl),
##     ACBehavior (fct), SummerTempDay (dbl), SummerTempAway (dbl),
##     SummerTempNight (dbl), NWEIGHT (dbl), NWEIGHT1 (dbl), NWEIGHT2
##     (dbl), NWEIGHT3 (dbl), NWEIGHT4 (dbl), NWEIGHT5 (dbl), NWEIGHT6
##     (dbl), NWEIGHT7 (dbl), NWEIGHT8 (dbl), NWEIGHT9 (dbl), NWEIGHT10
##     (dbl), NWEIGHT11 (dbl), NWEIGHT12 (dbl), NWEIGHT13 (dbl), NWEIGHT14
##     (dbl), NWEIGHT15 (dbl), NWEIGHT16 (dbl), NWEIGHT17 (dbl), NWEIGHT18
##     (dbl), NWEIGHT19 (dbl), NWEIGHT20 (dbl), NWEIGHT21 (dbl), NWEIGHT22
##     (dbl), NWEIGHT23 (dbl), NWEIGHT24 (dbl), NWEIGHT25 (dbl), NWEIGHT26
##     (dbl), NWEIGHT27 (dbl), NWEIGHT28 (dbl), NWEIGHT29 (dbl), NWEIGHT30
##     (dbl), NWEIGHT31 (dbl), NWEIGHT32 (dbl), NWEIGHT33 (dbl), NWEIGHT34
##     (dbl), NWEIGHT35 (dbl), NWEIGHT36 (dbl), NWEIGHT37 (dbl), NWEIGHT38
##     (dbl), NWEIGHT39 (dbl), NWEIGHT40 (dbl), NWEIGHT41 (dbl), NWEIGHT42
##     (dbl), NWEIGHT43 (dbl), NWEIGHT44 (dbl), NWEIGHT45 (dbl), NWEIGHT46
##     (dbl), NWEIGHT47 (dbl), NWEIGHT48 (dbl), NWEIGHT49 (dbl), NWEIGHT50
##     (dbl), NWEIGHT51 (dbl), NWEIGHT52 (dbl), NWEIGHT53 (dbl), NWEIGHT54
##     (dbl), NWEIGHT55 (dbl), NWEIGHT56 (dbl), NWEIGHT57 (dbl), NWEIGHT58
##     (dbl), NWEIGHT59 (dbl), NWEIGHT60 (dbl), BTUEL (dbl), DOLLAREL
##     (dbl), BTUNG (dbl), DOLLARNG (dbl), BTULP (dbl), DOLLARLP (dbl),
##     BTUFO (dbl), DOLLARFO (dbl), BTUWOOD (dbl), TOTALBTU (dbl),
##     TOTALDOL (dbl)</code></pre>
<p>Viewing this new object outputs information about the survey design object and specifies that RECS is an “unstratified cluster jacknife (JK1) with 60 replicates and MSE variances”. Additionally, the output displays the sampling variables (as <code>NWEIGHT1</code>-<code>NWEIGHT50</code>) and then lists the rest of the variables on the dataset. This design object will be used throughout this book to conduct survey analysis.</p>

</div>
</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-debell" class="csl-entry">
DeBell, Matthew. 2010. <span>“How to Analyze ANES Survey Data.”</span> ANES Technical Report Series nes012492. Palo Alto, CA: Stanford University; Ann Arbor, MI: the University of Michigan; <a href="https://electionstudies.org/wp-content/uploads/2018/05/HowToAnalyzeANESData.pdf" class="uri">https://electionstudies.org/wp-content/uploads/2018/05/HowToAnalyzeANESData.pdf</a>.
</div>
<div id="ref-recs-2020-tech" class="csl-entry">
———. 2023a. <span>“<span>2020 Residential Energy Consumption Survey: Household Characteristics Technical Documentation Summary</span>.”</span> <a href="https://www.eia.gov/consumption/residential/data/2020/pdf/2020%20RECS_Methodology%20Report.pdf" class="uri">https://www.eia.gov/consumption/residential/data/2020/pdf/2020%20RECS_Methodology%20Report.pdf</a>.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="5">
<li id="fn5"><p>Note that {broom} is part of the tidyverse, so it does not need to be installed separately<a href="c04-set-up.html#fnref5" class="footnote-back">↩︎</a></p></li>
<li id="fn6"><p><a href="https://www2.census.gov/programs-surveys/cps/datasets/2020/basic/2020_Basic_CPS_Public_Use_Record_Layout_plus_IO_Code_list.txt" class="uri">https://www2.census.gov/programs-surveys/cps/datasets/2020/basic/2020_Basic_CPS_Public_Use_Record_Layout_plus_IO_Code_list.txt</a><a href="c04-set-up.html#fnref6" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="c03-understanding-survey-data-documentation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="c05-descriptive-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/tidy-survey-r/tidy-survey-book/04-set-up.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
