<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Statistical testing | Tidy Survey Book</title>
  <meta name="description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Statistical testing | Tidy Survey Book" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  <meta name="github-repo" content="tidy-survey-r/tidy-survey-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Statistical testing | Tidy Survey Book" />
  
  <meta name="twitter:description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  

<meta name="author" content="Stephanie Zimmer, Rebecca J. Powell, and Isabella Velásquez" />


<meta name="date" content="2023-08-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="c05-descriptive-analysis.html"/>
<link rel="next" href="c07-modeling.html"/>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="c01-intro.html"><a href="c01-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="c01-intro.html"><a href="c01-intro.html#what-to-expect"><i class="fa fa-check"></i><b>1.1</b> What to expect</a></li>
<li class="chapter" data-level="1.2" data-path="c01-intro.html"><a href="c01-intro.html#book-datasets"><i class="fa fa-check"></i><b>1.2</b> Datasets used in this book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html"><i class="fa fa-check"></i><b>2</b> Overview of Surveys</a>
<ul>
<li class="chapter" data-level="2.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#pre-survey-planning"><i class="fa fa-check"></i><b>2.2</b> Pre-Survey Planning</a></li>
<li class="chapter" data-level="2.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design"><i class="fa fa-check"></i><b>2.3</b> Study Design</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-sampdesign"><i class="fa fa-check"></i><b>2.3.1</b> Sampling Design</a></li>
<li class="chapter" data-level="2.3.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-dcplanning"><i class="fa fa-check"></i><b>2.3.2</b> Data Collection Planning</a></li>
<li class="chapter" data-level="2.3.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-questionnaire"><i class="fa fa-check"></i><b>2.3.3</b> Questionnaire Design</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-datacollection"><i class="fa fa-check"></i><b>2.4</b> Data Collection</a></li>
<li class="chapter" data-level="2.5" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post"><i class="fa fa-check"></i><b>2.5</b> Post-Survey Processing</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-cleaning"><i class="fa fa-check"></i><b>2.5.1</b> Data Cleaning and Imputation</a></li>
<li class="chapter" data-level="2.5.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-weighting"><i class="fa fa-check"></i><b>2.5.2</b> Weighting</a></li>
<li class="chapter" data-level="2.5.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-disclosure"><i class="fa fa-check"></i><b>2.5.3</b> Disclosure</a></li>
<li class="chapter" data-level="2.5.4" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-documentation"><i class="fa fa-check"></i><b>2.5.4</b> Documentation</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#post-survey-data-analysis-and-reporting"><i class="fa fa-check"></i><b>2.6</b> Post-survey data analysis and reporting</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html"><i class="fa fa-check"></i><b>3</b> Specifying sample designs and replicate weights in {srvyr}</a>
<ul>
<li class="chapter" data-level="" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#prereq3"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="3.1" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#common-sampling-designs"><i class="fa fa-check"></i><b>3.2</b> Common sampling designs</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#simple-random-sample-without-replacement"><i class="fa fa-check"></i><b>3.2.1</b> Simple random sample without replacement</a></li>
<li class="chapter" data-level="3.2.2" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#simple-random-sample-with-replacement"><i class="fa fa-check"></i><b>3.2.2</b> Simple random sample with replacement</a></li>
<li class="chapter" data-level="3.2.3" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#stratified-sampling"><i class="fa fa-check"></i><b>3.2.3</b> Stratified sampling</a></li>
<li class="chapter" data-level="3.2.4" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#samp-cluster"><i class="fa fa-check"></i><b>3.2.4</b> Clustered sampling</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#replicate-weights"><i class="fa fa-check"></i><b>3.3</b> Replicate weights</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#balanced-repeated-replication-brr-method"><i class="fa fa-check"></i><b>3.3.1</b> Balanced Repeated Replication (BRR) Method</a></li>
<li class="chapter" data-level="3.3.2" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#fays-brr-method"><i class="fa fa-check"></i><b>3.3.2</b> Fay’s BRR Method</a></li>
<li class="chapter" data-level="3.3.3" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#jackknife-method"><i class="fa fa-check"></i><b>3.3.3</b> Jackknife method</a></li>
<li class="chapter" data-level="3.3.4" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#bootstrap-method"><i class="fa fa-check"></i><b>3.3.4</b> Bootstrap Method</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#und-surv-doc"><i class="fa fa-check"></i><b>3.4</b> Understanding survey design documentation</a></li>
<li class="chapter" data-level="3.5" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#exercises"><i class="fa fa-check"></i><b>3.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html"><i class="fa fa-check"></i><b>4</b> Understanding Survey Data Documentation</a>
<ul>
<li class="chapter" data-level="" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#prereq4"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="4.1" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#introduction-2"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#types-of-survey-documentation"><i class="fa fa-check"></i><b>4.2</b> Types of Survey Documentation</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#technical-documentation"><i class="fa fa-check"></i><b>4.2.1</b> Technical Documentation</a></li>
<li class="chapter" data-level="4.2.2" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#questionnaires"><i class="fa fa-check"></i><b>4.2.2</b> Questionnaires</a></li>
<li class="chapter" data-level="4.2.3" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#codebooks"><i class="fa fa-check"></i><b>4.2.3</b> Codebooks</a></li>
<li class="chapter" data-level="4.2.4" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#errata"><i class="fa fa-check"></i><b>4.2.4</b> Errata</a></li>
<li class="chapter" data-level="4.2.5" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#additional-resources"><i class="fa fa-check"></i><b>4.2.5</b> Additional Resources</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#working-with-missing-data"><i class="fa fa-check"></i><b>4.3</b> Working with Missing Data</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#accounting-for-questionnaire-skip-patterns"><i class="fa fa-check"></i><b>4.3.1</b> Accounting for Questionnaire Skip Patterns</a></li>
<li class="chapter" data-level="4.3.2" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#accounting-for-unintentional-missing-data"><i class="fa fa-check"></i><b>4.3.2</b> Accounting for Unintentional Missing Data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#example-american-national-election-studies-anes-2020-survey-documentation"><i class="fa fa-check"></i><b>4.4</b> Example: American National Election Studies (ANES) 2020 Survey Documentation</a></li>
<li class="chapter" data-level="4.5" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#searching-for-public-use-survey-data"><i class="fa fa-check"></i><b>4.5</b> Searching for Public-Use Survey Data</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html"><i class="fa fa-check"></i><b>5</b> Descriptive Analyses in {srvyr}</a>
<ul>
<li class="chapter" data-level="" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#prereq5"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="5.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#introduction-4"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#similarities-between-dplyr-and-srvyr-functions"><i class="fa fa-check"></i><b>5.2</b> Similarities Between {dplyr} and {srvyr} Functions</a></li>
<li class="chapter" data-level="5.3" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#counts-and-cross-tabulations"><i class="fa fa-check"></i><b>5.3</b> Counts and Cross-Tabulations</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-count-syntax"><i class="fa fa-check"></i><b>5.3.1</b> Syntax</a></li>
<li class="chapter" data-level="5.3.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples"><i class="fa fa-check"></i><b>5.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#totals-and-sums"><i class="fa fa-check"></i><b>5.4</b> Totals and Sums</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax"><i class="fa fa-check"></i><b>5.4.1</b> Syntax</a></li>
<li class="chapter" data-level="5.4.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-1"><i class="fa fa-check"></i><b>5.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-meanprop"><i class="fa fa-check"></i><b>5.5</b> Means and Proportions</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-meanprop-syntax"><i class="fa fa-check"></i><b>5.5.1</b> Syntax</a></li>
<li class="chapter" data-level="5.5.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-2"><i class="fa fa-check"></i><b>5.5.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#quantiles-and-medians"><i class="fa fa-check"></i><b>5.6</b> Quantiles and Medians</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-1"><i class="fa fa-check"></i><b>5.6.1</b> Syntax</a></li>
<li class="chapter" data-level="5.6.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-3"><i class="fa fa-check"></i><b>5.6.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#ratios"><i class="fa fa-check"></i><b>5.7</b> Ratios</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-2"><i class="fa fa-check"></i><b>5.7.1</b> Syntax</a></li>
<li class="chapter" data-level="5.7.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-4"><i class="fa fa-check"></i><b>5.7.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#correlations"><i class="fa fa-check"></i><b>5.8</b> Correlations</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-3"><i class="fa fa-check"></i><b>5.8.1</b> Syntax</a></li>
<li class="chapter" data-level="5.8.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-5"><i class="fa fa-check"></i><b>5.8.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#standard-deviation-and-variance"><i class="fa fa-check"></i><b>5.9</b> Standard Deviation and Variance</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-4"><i class="fa fa-check"></i><b>5.9.1</b> Syntax</a></li>
<li class="chapter" data-level="5.9.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-6"><i class="fa fa-check"></i><b>5.9.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#additional-topics"><i class="fa fa-check"></i><b>5.10</b> Additional Topics</a>
<ul>
<li class="chapter" data-level="5.10.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#unweighted-analysis"><i class="fa fa-check"></i><b>5.10.1</b> Unweighted Analysis</a></li>
<li class="chapter" data-level="5.10.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#subpopulation-analysis"><i class="fa fa-check"></i><b>5.10.2</b> Subpopulation Analysis</a></li>
<li class="chapter" data-level="5.10.3" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-deff"><i class="fa fa-check"></i><b>5.10.3</b> Design Effects</a></li>
<li class="chapter" data-level="5.10.4" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#creating-summary-rows"><i class="fa fa-check"></i><b>5.10.4</b> Creating Summary Rows</a></li>
<li class="chapter" data-level="5.10.5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#calculating-estimates-for-many-outcomes"><i class="fa fa-check"></i><b>5.10.5</b> Calculating Estimates for Many Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="5.11" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#exercises-1"><i class="fa fa-check"></i><b>5.11</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html"><i class="fa fa-check"></i><b>6</b> Statistical testing</a>
<ul>
<li class="chapter" data-level="" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#prereq6"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="6.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#introduction-5"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#dot-notation"><i class="fa fa-check"></i><b>6.2</b> Dot Notation</a></li>
<li class="chapter" data-level="6.3" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest"><i class="fa fa-check"></i><b>6.3</b> Comparison of Proportions and Means</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest-syntax"><i class="fa fa-check"></i><b>6.3.1</b> Syntax</a></li>
<li class="chapter" data-level="6.3.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest-examples"><i class="fa fa-check"></i><b>6.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi"><i class="fa fa-check"></i><b>6.4</b> Chi-Square Tests</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi-syntax"><i class="fa fa-check"></i><b>6.4.1</b> Syntax</a></li>
<li class="chapter" data-level="6.4.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi-examples"><i class="fa fa-check"></i><b>6.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-exercises"><i class="fa fa-check"></i><b>6.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="c07-modeling.html"><a href="c07-modeling.html"><i class="fa fa-check"></i><b>7</b> Modeling</a>
<ul>
<li class="chapter" data-level="" data-path="c07-modeling.html"><a href="c07-modeling.html#prereq7"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="7.1" data-path="c07-modeling.html"><a href="c07-modeling.html#introduction-6"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="c07-modeling.html"><a href="c07-modeling.html#analysis-of-variance-anova"><i class="fa fa-check"></i><b>7.2</b> Analysis of Variance (ANOVA)</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-6"><i class="fa fa-check"></i><b>7.2.1</b> Syntax</a></li>
<li class="chapter" data-level="7.2.2" data-path="c07-modeling.html"><a href="c07-modeling.html#example-10"><i class="fa fa-check"></i><b>7.2.2</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="c07-modeling.html"><a href="c07-modeling.html#gaussian-linear-regression"><i class="fa fa-check"></i><b>7.3</b> Gaussian Linear Regression</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-7"><i class="fa fa-check"></i><b>7.3.1</b> Syntax</a></li>
<li class="chapter" data-level="7.3.2" data-path="c07-modeling.html"><a href="c07-modeling.html#examples-7"><i class="fa fa-check"></i><b>7.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="c07-modeling.html"><a href="c07-modeling.html#logistic-regression"><i class="fa fa-check"></i><b>7.4</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-8"><i class="fa fa-check"></i><b>7.4.1</b> Syntax</a></li>
<li class="chapter" data-level="7.4.2" data-path="c07-modeling.html"><a href="c07-modeling.html#examples-8"><i class="fa fa-check"></i><b>7.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="c07-modeling.html"><a href="c07-modeling.html#exercises-2"><i class="fa fa-check"></i><b>7.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html"><i class="fa fa-check"></i><b>8</b> Communicating Results</a>
<ul>
<li class="chapter" data-level="" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#prereq8"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="8.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#introduction-7"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#describing-results-through-text"><i class="fa fa-check"></i><b>8.2</b> Describing Results through Text</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#methodology"><i class="fa fa-check"></i><b>8.2.1</b> Methodology</a></li>
<li class="chapter" data-level="8.2.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#analysis"><i class="fa fa-check"></i><b>8.2.2</b> Analysis</a></li>
<li class="chapter" data-level="8.2.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#results"><i class="fa fa-check"></i><b>8.2.3</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#visualizing-data"><i class="fa fa-check"></i><b>8.3</b> Visualizing Data</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#tables"><i class="fa fa-check"></i><b>8.3.1</b> Tables</a></li>
<li class="chapter" data-level="8.3.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#charts-and-plots"><i class="fa fa-check"></i><b>8.3.2</b> Charts and Plots</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#reproducibility"><i class="fa fa-check"></i><b>8.4</b> Reproducibility</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#setting-random-number-seeds"><i class="fa fa-check"></i><b>8.4.1</b> Setting Random Number Seeds</a></li>
<li class="chapter" data-level="8.4.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#git"><i class="fa fa-check"></i><b>8.4.2</b> Git</a></li>
<li class="chapter" data-level="8.4.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#renv"><i class="fa fa-check"></i><b>8.4.3</b> {renv}</a></li>
<li class="chapter" data-level="8.4.4" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#quartor-markdown"><i class="fa fa-check"></i><b>8.4.4</b> Quarto/R Markdown</a></li>
<li class="chapter" data-level="8.4.5" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#the-targets-package"><i class="fa fa-check"></i><b>8.4.5</b> The {targets} package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html"><i class="fa fa-check"></i><b>9</b> National Crime Victimization Survey Vignette</a>
<ul>
<li class="chapter" data-level="" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#prereq9"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="9.1" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#introduction-8"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#data-structure"><i class="fa fa-check"></i><b>9.2</b> Data structure</a></li>
<li class="chapter" data-level="9.3" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#survey-notation"><i class="fa fa-check"></i><b>9.3</b> Survey notation</a></li>
<li class="chapter" data-level="9.4" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#data-file-preparation"><i class="fa fa-check"></i><b>9.4</b> Data file preparation</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#preparing-files-for-estimation-of-victimization-rates"><i class="fa fa-check"></i><b>9.4.1</b> Preparing files for estimation of victimization rates</a></li>
<li class="chapter" data-level="9.4.2" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#derived-demographic-variables"><i class="fa fa-check"></i><b>9.4.2</b> Derived demographic variables</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#survey-design-objects"><i class="fa fa-check"></i><b>9.5</b> Survey design objects</a></li>
<li class="chapter" data-level="9.6" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#calculating-estimates"><i class="fa fa-check"></i><b>9.6</b> Calculating estimates</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#victimization-totals"><i class="fa fa-check"></i><b>9.6.1</b> Victimization totals</a></li>
<li class="chapter" data-level="9.6.2" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#victimization-proportions"><i class="fa fa-check"></i><b>9.6.2</b> Victimization proportions</a></li>
<li class="chapter" data-level="9.6.3" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#victimization-rates"><i class="fa fa-check"></i><b>9.6.3</b> Victimization rates</a></li>
<li class="chapter" data-level="9.6.4" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#prevalence-rates"><i class="fa fa-check"></i><b>9.6.4</b> Prevalence rates</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#exercises-3"><i class="fa fa-check"></i><b>9.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html"><i class="fa fa-check"></i><b>10</b> AmericasBarometer Vignette</a>
<ul>
<li class="chapter" data-level="" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#prereq10"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="10.1" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#introduction-9"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#data-structure-1"><i class="fa fa-check"></i><b>10.2</b> Data Structure</a></li>
<li class="chapter" data-level="10.3" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#preparing-files"><i class="fa fa-check"></i><b>10.3</b> Preparing files</a></li>
<li class="chapter" data-level="10.4" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#survey-design-objects-1"><i class="fa fa-check"></i><b>10.4</b> Survey design objects</a></li>
<li class="chapter" data-level="10.5" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#calculating-estimates-and-making-tables"><i class="fa fa-check"></i><b>10.5</b> Calculating estimates and making tables</a></li>
<li class="chapter" data-level="10.6" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#mapping-survey-data"><i class="fa fa-check"></i><b>10.6</b> Mapping survey data</a></li>
<li class="chapter" data-level="10.7" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#exercises-4"><i class="fa fa-check"></i><b>10.7</b> Exercises</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tidy Survey Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="c06-statistical-testing" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Chapter 6</span> Statistical testing<a href="c06-statistical-testing.html#c06-statistical-testing" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="prereq6" class="section level3 unnumbered hasAnchor prereqbox-header">
<h3>Prerequisites<a href="c06-statistical-testing.html#prereq6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
</div>
<div class="prereqbox">
<p>For this chapter, here are the packages and helper functions we will need:</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="c06-statistical-testing.html#cb251-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb251-2"><a href="c06-statistical-testing.html#cb251-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey) </span>
<span id="cb251-3"><a href="c06-statistical-testing.html#cb251-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(srvyr) </span>
<span id="cb251-4"><a href="c06-statistical-testing.html#cb251-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(osfr)</span>
<span id="cb251-5"><a href="c06-statistical-testing.html#cb251-5" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;helper-fun/helper-functions.R&quot;</span>)</span>
<span id="cb251-6"><a href="c06-statistical-testing.html#cb251-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb251-7"><a href="c06-statistical-testing.html#cb251-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span></code></pre></div>
<p>We will be using data from ANES and RECS. Here is the code to create the design objects for each to use throughout this chapter. For ANES, we need to adjust the weight so it sums to the population instead of the sample (see the ANES documentation and Chapter <a href="c04-understanding-survey-data-documentation.html#c04-understanding-survey-data-documentation">4</a> for more information).</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="c06-statistical-testing.html#cb252-1" aria-hidden="true" tabindex="-1"></a>anes_in <span class="ot">&lt;-</span> <span class="fu">read_osf</span>(<span class="st">&quot;anes_2020.rds&quot;</span>)</span>
<span id="cb252-2"><a href="c06-statistical-testing.html#cb252-2" aria-hidden="true" tabindex="-1"></a>target_pop <span class="ot">&lt;-</span> <span class="dv">231592693</span></span>
<span id="cb252-3"><a href="c06-statistical-testing.html#cb252-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb252-4"><a href="c06-statistical-testing.html#cb252-4" aria-hidden="true" tabindex="-1"></a>anes_adjwgt <span class="ot">&lt;-</span> anes_in <span class="sc">%&gt;%</span></span>
<span id="cb252-5"><a href="c06-statistical-testing.html#cb252-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Weight =</span> Weight <span class="sc">/</span> <span class="fu">sum</span>(Weight) <span class="sc">*</span> targetpop)</span>
<span id="cb252-6"><a href="c06-statistical-testing.html#cb252-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb252-7"><a href="c06-statistical-testing.html#cb252-7" aria-hidden="true" tabindex="-1"></a>anes_des <span class="ot">&lt;-</span> anes_adjwgt <span class="sc">%&gt;%</span></span>
<span id="cb252-8"><a href="c06-statistical-testing.html#cb252-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(</span>
<span id="cb252-9"><a href="c06-statistical-testing.html#cb252-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> Weight,</span>
<span id="cb252-10"><a href="c06-statistical-testing.html#cb252-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">strata =</span> Stratum,</span>
<span id="cb252-11"><a href="c06-statistical-testing.html#cb252-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">ids =</span> VarUnit,</span>
<span id="cb252-12"><a href="c06-statistical-testing.html#cb252-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">nest =</span> <span class="cn">TRUE</span></span>
<span id="cb252-13"><a href="c06-statistical-testing.html#cb252-13" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>For RECS, details are included in the RECS documentation and Chapter <a href="c03-specifying-sample-designs.html#c03-specifying-sample-designs">3</a>.</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="c06-statistical-testing.html#cb253-1" aria-hidden="true" tabindex="-1"></a>recs_in <span class="ot">&lt;-</span> <span class="fu">read_osf</span>(<span class="st">&quot;recs_2015.rds&quot;</span>)</span>
<span id="cb253-2"><a href="c06-statistical-testing.html#cb253-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb253-3"><a href="c06-statistical-testing.html#cb253-3" aria-hidden="true" tabindex="-1"></a>recs_des <span class="ot">&lt;-</span> recs_in <span class="sc">%&gt;%</span></span>
<span id="cb253-4"><a href="c06-statistical-testing.html#cb253-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(</span>
<span id="cb253-5"><a href="c06-statistical-testing.html#cb253-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> NWEIGHT,</span>
<span id="cb253-6"><a href="c06-statistical-testing.html#cb253-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">repweights =</span> <span class="fu">starts_with</span>(<span class="st">&quot;BRRWT&quot;</span>),</span>
<span id="cb253-7"><a href="c06-statistical-testing.html#cb253-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">&quot;Fay&quot;</span>,</span>
<span id="cb253-8"><a href="c06-statistical-testing.html#cb253-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">rho =</span> <span class="fl">0.5</span>,</span>
<span id="cb253-9"><a href="c06-statistical-testing.html#cb253-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">mse =</span> <span class="cn">TRUE</span></span>
<span id="cb253-10"><a href="c06-statistical-testing.html#cb253-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<div id="introduction-5" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Introduction<a href="c06-statistical-testing.html#introduction-5" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When analyzing results from a survey, the point estimates described in Chapter <a href="c05-descriptive-analysis.html#c05-descriptive-analysis">5</a> help us understand the data at a high level. Still, researchers and the public often want to make comparisons between different groups. These comparisons are calculated through statistical testing.</p>
<p>The general idea of statistical testing is the same for data obtained through surveys and data obtained through other methods, where we compare the point estimates and variance estimates of each statistic to see if statistically significant differences exist. However, statistical testing for complex surveys involves additional considerations due to the need to account for the sampling design in order to obtain accurate variance estimates.</p>
<p>The functions in the {survey} packages allow for the correct estimation of the variances. This chapter will cover the following statistical tests with survey data and functions:</p>
<ul>
<li>Comparison of proportions <code>svyttest()</code></li>
<li>Comparison of means <code>svyttest()</code></li>
<li>Goodness of fit tests <code>svygofchisq()</code></li>
<li>Tests of independence <code>svychisq()</code></li>
<li>Tests of homogeneity <code>svychisq()</code></li>
</ul>
</div>
<div id="dot-notation" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Dot Notation<a href="c06-statistical-testing.html#dot-notation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Up to this point, we have shown functions that use wrappers from the {srvyr} package. This means that the functions work with tidyverse syntax. However, the functions in this chapter do not have wrappers in the {srvyr} package and are instead used directly from the {survey} package. Therefore, the design object is <em>not</em> the first argument, and to use these functions with the magrittr pipe <code>%&gt;%</code> and tidyverse syntax, we will need to use dot (<code>.</code>) notation.</p>
<p>Functions that work with the magrittr pipe (<code>%&gt;%</code>) have the data as the first argument. When we run a function with the pipe, it automatically places anything to the left of the pipe into the first argument of the function to the right of the pipe. For example, if we wanted to take the <code>mtcars</code> data and filter to cars with six cylinders, we can write the code in at least four different ways:</p>
<ol style="list-style-type: decimal">
<li><code>filter(mtcars, cyl == 6)</code></li>
<li><code>mtcars %&gt;% filter(cyl == 6)</code></li>
<li><code>mtcars %&gt;% filter(., cyl == 6)</code></li>
<li><code>mtcars %&gt;% filter(.data = ., cyl == 6)</code></li>
</ol>
<p>Each of these lines of code will produce the same output since the argument that takes the data is in the first spot in <code>filter()</code>. The first two are probably familiar to those who have worked with the tidyverse. The third option functions the same way as the second one but is explicit that <code>mtcars</code> goes into the first argument, and the fourth option indicates that <code>mtcars</code> is going into the named argument of <code>.data</code>. Here, we are telling R to take what’s on the left side of the pipe (<code>mtcars</code>) and pipe it into the spot with the dot (<code>.</code>)—the first argument.</p>
<p>In functions that are not part of the tidyverse, the data argument may not be in the first spot. For example, in <code>svyttest()</code>, the data argument is in the second spot, which means we need to place the dot (<code>.</code>) in the second spot and not the first. For example:</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="c06-statistical-testing.html#cb254-1" aria-hidden="true" tabindex="-1"></a>svydata_des <span class="sc">%&gt;%</span></span>
<span id="cb254-2"><a href="c06-statistical-testing.html#cb254-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">svyttest</span>(x <span class="sc">~</span> y, .)</span></code></pre></div>
<p>By default, the pipe places the left-hand object in the first argument spot. Placing the dot (<code>.</code>) in the second argument spot indicates that the survey design object <code>svydata_des</code> should be used in the second argument and not the first.</p>
<p>Alternatively, named arguments could be used to place the dot first, as in the following:</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="c06-statistical-testing.html#cb255-1" aria-hidden="true" tabindex="-1"></a>svydata_des <span class="sc">%&gt;%</span></span>
<span id="cb255-2"><a href="c06-statistical-testing.html#cb255-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">svyttest</span>(<span class="at">design =</span> ., x <span class="sc">~</span> y)</span></code></pre></div>
</div>
<div id="stattest-ttest" class="section level2 hasAnchor" number="6.3">
<h2><span class="header-section-number">6.3</span> Comparison of Proportions and Means<a href="c06-statistical-testing.html#stattest-ttest" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We use t-tests to compare two proportions or means. T-tests allow us to determine if one proportion or mean is statistically different from another. They are commonly used to determine if a single estimate differs from a known value (e.g., 0 or 50%) or to compare two group means (e.g., North versus South). Comparing a single estimate to a known value is called a <em>one sample t-test</em>, and we can set up the hypothesis test as follows:</p>
<ul>
<li><span class="math inline">\(H_0: \mu = 0\)</span> where <span class="math inline">\(\mu\)</span> is the mean outcome and <span class="math inline">\(0\)</span> is the value we are comparing it to</li>
<li><span class="math inline">\(H_A: \mu \neq 0\)</span></li>
</ul>
<p>For comparing two estimates, this is called a <em>two-sample t-test</em> and we can set up the hypothesis test as follows:</p>
<ul>
<li><span class="math inline">\(H_0: \mu_1 = \mu_2\)</span> where <span class="math inline">\(\mu_i\)</span> is the mean outcome for group <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(H_A: \mu_1 \neq \mu_2\)</span></li>
</ul>
<p>Two sample t-tests can also be <em>paired</em> or <em>unpaired</em>. If the data come from two different populations (e.g., North versus South), the t-test run will be an <em>unpaired</em> or <em>independent samples</em> t-test. <em>Paired</em> t-tests occur when the data come from the same population. This is commonly seen with data from the same population in two different time periods (e.g., before and after an intervention).</p>
<p>The difference between t-tests with non-survey data and survey data is based on the underlying variance estimation difference. Chapter <a href="c03-specifying-sample-designs.html#c03-specifying-sample-designs">3</a> provides a detailed overview of the math behind the mean and sampling error calculations for various sample designs. The functions in the {survey} package will account for these nuances, provided the design object is correctly defined.</p>
<div id="stattest-ttest-syntax" class="section level3 hasAnchor" number="6.3.1">
<h3><span class="header-section-number">6.3.1</span> Syntax<a href="c06-statistical-testing.html#stattest-ttest-syntax" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When we do not have survey data, we can use the <code>t.test()</code> function from the {stats} package. This function does not allow for weights or the variance structure that need to be accounted for with survey data. Therefore, we need to use the <code>svyttest()</code> function from {survey} when using survey data. Many of the arguments are the same between the two functions, but there are a few key differences:</p>
<ul>
<li>We need to use the survey design object instead of the original data frame</li>
<li>We can only use a formula and not separate x and y data</li>
<li>The confidence level cannot be specified and will always be set to 95%. However, we will show examples of how the confidence level can be changed after running using the <code>confint()</code> function.</li>
</ul>
<p>Here is the syntax for the <code>svyttest()</code> function:</p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="c06-statistical-testing.html#cb256-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svyttest</span>(formula,</span>
<span id="cb256-2"><a href="c06-statistical-testing.html#cb256-2" aria-hidden="true" tabindex="-1"></a>         design,</span>
<span id="cb256-3"><a href="c06-statistical-testing.html#cb256-3" aria-hidden="true" tabindex="-1"></a>         ...)</span></code></pre></div>
<p>The arguments are:</p>
<ul>
<li><code>formula</code>: Formula, <code>outcome~group</code> for two-sample, <code>outcome~0</code> or <code>outcome~1</code> for one-sample. The group variable must be a factor or character with two levels, or be coded 0/1 or 1/2. We give more details on formula set-up below for different types of tests.</li>
<li><code>design</code>: survey design object</li>
<li><code>...</code>: This passes options on for one-sided tests only, and thus, we can specify <code>na.rm=TRUE</code></li>
</ul>
<p>Notice that the first argument here is the <code>formula</code> and not the <code>design</code>. This means we must use the dot <code>(.)</code> if we pipe in the survey design object (as described at the beginning of this chapter).</p>
<p>The <code>formula</code> argument can take several different forms depending on what we are measuring. Here are a few common scenarios:</p>
<ol style="list-style-type: decimal">
<li><strong>One-sample t-test:</strong>
<ol style="list-style-type: lower-alpha">
<li><strong>Comparison to 0:</strong> <code>var ~ 0</code>, where <code>var</code> is the measure of interest, and we compare it to the value <code>0</code>. For example, we could test if the population mean of household debt is different from <code>0</code>.</li>
<li><strong>Comparison to a different value:</strong> <code>var - value ~ 0</code>, where <code>var</code> is the measure of interest and <code>value</code> is what we are comparing to. For example, we could test if the proportion of the population that has blue eyes is different from <code>25%</code> by using <code>var - 0.25 ~ 0</code>. Note that specifying the formula as <code>var ~ 0.25</code> is not equivalent.</li>
</ol></li>
<li><strong>Two-sample t-test:</strong>
<ol style="list-style-type: lower-alpha">
<li><strong>Unpaired:</strong>
<ul>
<li><strong>2 level grouping variable:</strong> <code>var ~ groupVar</code>, where <code>var</code> is the measure of interest and <code>groupVar</code> is a variable with two categories. For example, we could test if the average age of the population who voted for president in 2020 differed from the age of people who did not vote. In this case, age would be used for <code>var</code>, and a binary variable indicating voting activity would be the <code>groupVar</code>.</li>
<li><strong>3+ level grouping variable:</strong> <code>var ~ groupVar == level</code>, where <code>var</code> is the measure of interest, <code>groupVar</code> is the categorical variable, and <code>level</code> is the category level to isolate. For example, we could test if the test scores in one classroom differed from all other classrooms.</li>
</ul></li>
<li><strong>Paired:</strong> <code>var_1 - var_2 ~ 0</code>, where <code>var_1</code> is the first variable of interest and <code>var_2</code> is the second variable of interest. For example, we could test if test scores on a subject differed between the start and the end of a course.</li>
</ol></li>
</ol>
<p>The <code>na.rm</code> argument defaults to <code>FALSE</code>, which means if any data is missing, the t-test will not compute. Throughout this chapter, we will always set <code>na.rm = TRUE</code>, but before analyzing the survey data, review the notes provided in Chapter <a href="c04-understanding-survey-data-documentation.html#c04-understanding-survey-data-documentation">4</a> to better understand how to handle missing data.</p>
<p>Let’s walk through a few examples using the ANES and RECS data.</p>
</div>
<div id="stattest-ttest-examples" class="section level3 hasAnchor" number="6.3.2">
<h3><span class="header-section-number">6.3.2</span> Examples<a href="c06-statistical-testing.html#stattest-ttest-examples" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="stattest-ttest-ex1" class="section level4 unnumbered hasAnchor">
<h4>Example 1: One-sample t-test for Mean<a href="c06-statistical-testing.html#stattest-ttest-ex1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>RECS asks respondents to indicate what temperature they set their house to during the summer at night.<a href="#fn20" class="footnote-ref" id="fnref20"><sup>20</sup></a> In our data, we have called this variable <code>SummerTempNight</code>. If we want to see if the average U.S. household sets its temperature at a value different from 68<span class="math inline">\(^\circ\)</span>F, we could set up the hypothesis as follows:</p>
<ul>
<li><span class="math inline">\(H_0: \mu = 68\)</span> where <span class="math inline">\(\mu\)</span> is the average temperature U.S. households set their thermostat to in the summer at night</li>
<li><span class="math inline">\(H_A: \mu \neq 68\)</span></li>
</ul>
<p>To conduct this in R, we use <code>svyttest()</code> with and subtract the temperature on the right-hand side of the formula:</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="c06-statistical-testing.html#cb257-1" aria-hidden="true" tabindex="-1"></a>ttest_ex1 <span class="ot">&lt;-</span> recs_des <span class="sc">%&gt;%</span></span>
<span id="cb257-2"><a href="c06-statistical-testing.html#cb257-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyttest</span>(</span>
<span id="cb257-3"><a href="c06-statistical-testing.html#cb257-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> SummerTempNight <span class="sc">-</span> <span class="dv">68</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb257-4"><a href="c06-statistical-testing.html#cb257-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb257-5"><a href="c06-statistical-testing.html#cb257-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb257-6"><a href="c06-statistical-testing.html#cb257-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb257-7"><a href="c06-statistical-testing.html#cb257-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb257-8"><a href="c06-statistical-testing.html#cb257-8" aria-hidden="true" tabindex="-1"></a>ttest_ex1</span></code></pre></div>
<pre><code>## 
##  Design-based one-sample t-test
## 
## data:  SummerTempNight - 68 ~ 0
## t = 41, df = 94, p-value &lt;2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  3.425 3.773
## sample estimates:
##  mean 
## 3.599</code></pre>
<p>To pull out specific output, we can use R’s built-in <code>$</code> operator. For instance, to obtain the estimate <span class="math inline">\(\mu - 68\)</span>, we run <code>ttest_ex1$estimate</code>.</p>
<p>If we want the average, we take our t-test estimate and add it to 68:</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="c06-statistical-testing.html#cb259-1" aria-hidden="true" tabindex="-1"></a>ttest_ex1<span class="sc">$</span>estimate <span class="sc">+</span> <span class="dv">68</span></span></code></pre></div>
<pre><code>## mean 
## 71.6</code></pre>
<p>Or, we can use the <code>survey_mean()</code> function described in Chapter <a href="c05-descriptive-analysis.html#c05-descriptive-analysis">5</a>:</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="c06-statistical-testing.html#cb261-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb261-2"><a href="c06-statistical-testing.html#cb261-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mu =</span> <span class="fu">survey_mean</span>(SummerTempNight, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##      mu  mu_se
##   &lt;dbl&gt;  &lt;dbl&gt;
## 1  71.6 0.0878</code></pre>
<p>The result is the same in both methods, so we see that the average temperature U.S. households set their thermostat to in the summer at night is 71.6<span class="math inline">\(^\circ\)</span>F. Looking at the output from <code>svyttest()</code>, the t-statistic is 41, and the p-value is <span class="math inline">\(8.67\times 10^{-62}\)</span>, indicating that the average is statistically different from 68<span class="math inline">\(^\circ\)</span>F at an <span class="math inline">\(\alpha\)</span> level of <span class="math inline">\(0.05\)</span>.</p>
<p>If we want an 80% confidence interval for the test statistic, we can use the function <code>confint()</code> to change the confidence level. Below, we print both the original 95% confidence interval and the 80% confidence interval:</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="c06-statistical-testing.html#cb263-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(ttest_ex1, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##                                  2.5 % 97.5 %
## as.numeric(SummerTempNight - 68) 3.425  3.773
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="c06-statistical-testing.html#cb265-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(ttest_ex1, <span class="at">level =</span> <span class="fl">0.8</span>)</span></code></pre></div>
<pre><code>## [1] 3.486 3.712
## attr(,&quot;conf.level&quot;)
## [1] 0.8</code></pre>
</div>
<div id="stattest-ttest-ex2" class="section level4 unnumbered hasAnchor">
<h4>Example 2: One-sample t-test for Proportion<a href="c06-statistical-testing.html#stattest-ttest-ex2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>ANES asked respondents if they voted in the presidential election in 2020.<a href="#fn21" class="footnote-ref" id="fnref21"><sup>21</sup></a> In our data, we call this variable <code>VotedPres2020</code>. Let’s look at the proportion of the U.S. voting-eligible population that voted for the president in 2020 using the <code>survey_prop()</code> function we learned in Chapter <a href="c05-descriptive-analysis.html#c05-descriptive-analysis">5</a>.</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="c06-statistical-testing.html#cb267-1" aria-hidden="true" tabindex="-1"></a>voteprop <span class="ot">&lt;-</span> anes_des <span class="sc">%&gt;%</span></span>
<span id="cb267-2"><a href="c06-statistical-testing.html#cb267-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(VotedPres2020) <span class="sc">%&gt;%</span></span>
<span id="cb267-3"><a href="c06-statistical-testing.html#cb267-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">p =</span> <span class="fu">survey_prop</span>())</span>
<span id="cb267-4"><a href="c06-statistical-testing.html#cb267-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb267-5"><a href="c06-statistical-testing.html#cb267-5" aria-hidden="true" tabindex="-1"></a>voteprop</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   VotedPres2020       p     p_se
##   &lt;fct&gt;           &lt;dbl&gt;    &lt;dbl&gt;
## 1 Yes           0.772   0.00757 
## 2 No            0.227   0.00763 
## 3 &lt;NA&gt;          0.00113 0.000464</code></pre>
<p>Based on this, 77.2% of the U.S. voting-eligible population voted for president in 2020. If we wanted to know how this compares to another country, we could use <code>svyttest()</code>. For example, if we know that the voter turnout in Germany in the 2017 general election was 76.2%, we could set up our hypothesis as follows:</p>
<ul>
<li><span class="math inline">\(H_0: p = 0.762\)</span> where <span class="math inline">\(p\)</span> is the proportion of the U.S. voting-eligible population that voted for president in 2020</li>
<li><span class="math inline">\(H_A: p \neq 0.762\)</span></li>
</ul>
<p>To conduct this in R, we use the <code>svyttest()</code> function as follows:</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="c06-statistical-testing.html#cb269-1" aria-hidden="true" tabindex="-1"></a>ttest_ex2 <span class="ot">&lt;-</span> anes_des <span class="sc">%&gt;%</span></span>
<span id="cb269-2"><a href="c06-statistical-testing.html#cb269-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyttest</span>(</span>
<span id="cb269-3"><a href="c06-statistical-testing.html#cb269-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> (VotedPres2020 <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span>) <span class="sc">-</span> <span class="fl">0.762</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb269-4"><a href="c06-statistical-testing.html#cb269-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb269-5"><a href="c06-statistical-testing.html#cb269-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb269-6"><a href="c06-statistical-testing.html#cb269-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb269-7"><a href="c06-statistical-testing.html#cb269-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb269-8"><a href="c06-statistical-testing.html#cb269-8" aria-hidden="true" tabindex="-1"></a>ttest_ex2</span></code></pre></div>
<pre><code>## 
##  Design-based one-sample t-test
## 
## data:  (VotedPres2020 == &quot;Yes&quot;) - 0.762 ~ 0
## t = 1.4, df = 50, p-value = 0.2
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -0.004729  0.025899
## sample estimates:
##    mean 
## 0.01058</code></pre>
<p>The output from the <code>svyttest()</code> function can be a bit hard to read. Using the {broom} package from tidymodels, a collection of packages for modeling using the tidyverse principles, we can clean up the output into a tibble to more easily understand what the test tells us.</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="c06-statistical-testing.html#cb271-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(ttest_ex2)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 8
##   estimate statistic p.value parameter conf.low conf.high method        
##      &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;         
## 1   0.0106      1.39   0.171        50 -0.00473    0.0259 Design-based …
## # ℹ 1 more variable: alternative &lt;chr&gt;</code></pre>
<p>The estimate differs from example one in that the estimate is not displaying <span class="math inline">\(\mu - 0.762\)</span> but rather <span class="math inline">\(\mu\)</span>, or the difference between the U.S. proportion and the German proportion we are comparing. We can see that there is a difference of 1.06 percentage points. Additionally, the t-statistic value in the <code>statistic</code> column is 1.39, and the p-value is 0.171. These results indicate that the U.S. and Germany have similar voter turnout.</p>
<!--Add in callout box about how to use the $ notation to help call out the different values? Maybe indicate how this will be covered more in the reporting chapter? IV: I added a bit up top, not sure if it needs a whole call out box but happy to revisit.-->
</div>
<div id="stattest-ttest-ex3" class="section level4 unnumbered hasAnchor">
<h4>Example 3: Unpaired two-sample t-test<a href="c06-statistical-testing.html#stattest-ttest-ex3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Two additional variables in the RECS data are the electric bill cost (<code>DOLLAREL</code>) and whether the house used AC or not (<code>ACUsed</code>).<a href="#fn22" class="footnote-ref" id="fnref22"><sup>22</sup></a> If we want to know if the U.S. households that used AC had higher electrical bills compared to those that did not, we could set up the hypothesis as follows:</p>
<ul>
<li><span class="math inline">\(H_0: \mu_{AC} = \mu_{noAC}\)</span> where <span class="math inline">\(\mu_{AC}\)</span> is the electrical bill cost for U.S. households that used AC and <span class="math inline">\(\mu_{noAC}\)</span> is the electrical bill cost for U.S. households that did not use AC</li>
<li><span class="math inline">\(H_A: \mu_{AC} \neq \mu_{noAC}\)</span></li>
</ul>
<p>Let’s take a quick look at the data to see the format the data are in:</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="c06-statistical-testing.html#cb273-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb273-2"><a href="c06-statistical-testing.html#cb273-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ACUsed) <span class="sc">%&gt;%</span></span>
<span id="cb273-3"><a href="c06-statistical-testing.html#cb273-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">survey_mean</span>(DOLLAREL, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   ACUsed  mean mean_se
##   &lt;lgl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1 FALSE   972.    25.8
## 2 TRUE   1435.    15.8</code></pre>
<p>To conduct this in R, we use <code>svyttest()</code>:</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="c06-statistical-testing.html#cb275-1" aria-hidden="true" tabindex="-1"></a>ttest_ex3 <span class="ot">&lt;-</span> recs_des <span class="sc">%&gt;%</span></span>
<span id="cb275-2"><a href="c06-statistical-testing.html#cb275-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyttest</span>(<span class="at">formula =</span> DOLLAREL <span class="sc">~</span> ACUsed,</span>
<span id="cb275-3"><a href="c06-statistical-testing.html#cb275-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">design =</span> .,</span>
<span id="cb275-4"><a href="c06-statistical-testing.html#cb275-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb275-5"><a href="c06-statistical-testing.html#cb275-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb275-6"><a href="c06-statistical-testing.html#cb275-6" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(ttest_ex3)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 8
##   estimate statistic  p.value parameter conf.low conf.high method       
##      &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;        
## 1     463.      14.8 3.08e-26        94     401.      525. Design-based…
## # ℹ 1 more variable: alternative &lt;chr&gt;</code></pre>
<p>The results indicate that the difference in electrical bills for those that used AC and those that did not is, on average, $462.87. The difference appears to be statistically significant as the t-statistic is 14.8 and the p-value is <span class="math inline">\(3.08\times 10^{-26}\)</span>. Households that used AC spent, on average, $462.90 more in 2015.</p>
</div>
<div id="stattest-ttest-ex4" class="section level4 unnumbered hasAnchor">
<h4>Example 4: Paired two-sample t-test<a href="c06-statistical-testing.html#stattest-ttest-ex4" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let’s say we want to test whether the temperature that U.S. households set their thermostat at night differs depending on the season (comparing summer<a href="#fn23" class="footnote-ref" id="fnref23"><sup>23</sup></a> and winter<a href="#fn24" class="footnote-ref" id="fnref24"><sup>24</sup></a> temperatures). We could set up the hypothesis as follows:</p>
<ul>
<li><span class="math inline">\(H_0: \mu_{summer} = \mu_{winter}\)</span> where <span class="math inline">\(\mu_{summer}\)</span> is the temperature that U.S. households set their thermostat to during summer nights, and <span class="math inline">\(\mu_{winter}\)</span> is the temperature that U.S. households set their thermostat to during winter nights</li>
<li><span class="math inline">\(H_A: \mu_{summer} \neq \mu_{winter}\)</span></li>
</ul>
<p>To conduct this in R, we use <code>svyttest()</code> by calculating the temperature difference on the left-hand side as follows:</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="c06-statistical-testing.html#cb277-1" aria-hidden="true" tabindex="-1"></a>ttest_ex4 <span class="ot">&lt;-</span> recs_des <span class="sc">%&gt;%</span></span>
<span id="cb277-2"><a href="c06-statistical-testing.html#cb277-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyttest</span>(</span>
<span id="cb277-3"><a href="c06-statistical-testing.html#cb277-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb277-4"><a href="c06-statistical-testing.html#cb277-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> SummerTempNight <span class="sc">-</span> WinterTempNight <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb277-5"><a href="c06-statistical-testing.html#cb277-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb277-6"><a href="c06-statistical-testing.html#cb277-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb277-7"><a href="c06-statistical-testing.html#cb277-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb277-8"><a href="c06-statistical-testing.html#cb277-8" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(ttest_ex4)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 8
##   estimate statistic  p.value parameter conf.low conf.high method       
##      &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;        
## 1     3.21      29.1 8.83e-49        94     3.00      3.43 Design-based…
## # ℹ 1 more variable: alternative &lt;chr&gt;</code></pre>
<p>U.S. households set their thermostat on average 3.2<span class="math inline">\(^\circ\)</span>F warmer in summer nights than winter nights, which is statistically significant (t = 29.1, p-value = <span class="math inline">\(8.83\times 10^{-49}\)</span>).</p>
</div>
</div>
</div>
<div id="stattest-chi" class="section level2 hasAnchor" number="6.4">
<h2><span class="header-section-number">6.4</span> Chi-Square Tests<a href="c06-statistical-testing.html#stattest-chi" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Chi-square tests (<span class="math inline">\(\chi^2\)</span>) allow us to examine multiple proportions using a goodness-of-fit test, a test of independence, or a test of homogeneity. These three tests have the same <span class="math inline">\(\chi^2\)</span> distributions but with slightly different underlying assumptions.</p>
<p>First, <strong>goodness-of-fit</strong> tests are used when comparing <em>observed</em> data to <em>expected</em> data. For example, this could be used to determine if respondent demographics (the observed data) match known population information (the expected data). In this case, we can set up the hypothesis test as follows:</p>
<ul>
<li><span class="math inline">\(H_0: p_1 = \pi_1, ~ p_2 = \pi_2, ~ ..., ~ p_k = \pi_k\)</span> where <span class="math inline">\(p_i\)</span> is the observed proportion for category <span class="math inline">\(i\)</span>, <span class="math inline">\(\pi_i\)</span> is expected proportion for category <span class="math inline">\(i\)</span>, and <span class="math inline">\(k\)</span> is the number of categories</li>
<li><span class="math inline">\(H_A:\)</span> at least one level of <span class="math inline">\(p_i\)</span> does not match <span class="math inline">\(\pi_i\)</span></li>
</ul>
<p>Second, <strong>tests of independence</strong> are used when comparing two types of <em>observed</em> data to see if there is a relationship. For example, this could be used to determine if the proportion of respondents who voted for each political party in the presidential election matches the proportion of respondents who voted for each political party in a local election. In this case, we can set up the hypothesis test as follows:</p>
<ul>
<li><span class="math inline">\(H_0:\)</span> The two variables/factors are independent</li>
<li><span class="math inline">\(H_A:\)</span> The two variables/factors are <em>not</em> independent</li>
</ul>
<p>Third, <strong>tests of homogeneity</strong> are used to compare two distributions to see if they match. For example, this could be used to determine if the highest education achieved is the same for both men and women. In this case, we can set up the hypothesis test as follows:</p>
<ul>
<li><span class="math inline">\(H_0: p_{1a} = p_{1b}, ~ p_{2a} = p_{2b}, ~ ..., ~ p_{ka} = p_{kb}\)</span> where <span class="math inline">\(p_{ia}\)</span> is the observed proportion of category <span class="math inline">\(i\)</span> for subgroup <span class="math inline">\(a\)</span>, <span class="math inline">\(p_{ib}\)</span> is the observed proportion of category <span class="math inline">\(i\)</span> for subgroup <span class="math inline">\(a\)</span> and <span class="math inline">\(k\)</span> is the number of categories</li>
<li><span class="math inline">\(H_A:\)</span> at least one category of <span class="math inline">\(p_{ia}\)</span> does not match <span class="math inline">\(p_{ib}\)</span></li>
</ul>
<p>As with t-tests, the difference between using <span class="math inline">\(\chi^2\)</span> tests with non-survey data and survey data is based on the underlying variance estimation. The functions in the {survey} package will account for these nuances, provided the design object is correctly defined. For basic variance estimation formulas for different survey design types, refer to Chapter <a href="c03-specifying-sample-designs.html#c03-specifying-sample-designs">3</a>.</p>
<div id="stattest-chi-syntax" class="section level3 hasAnchor" number="6.4.1">
<h3><span class="header-section-number">6.4.1</span> Syntax<a href="c06-statistical-testing.html#stattest-chi-syntax" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When we do not have survey data, we may be able to use the <code>chisq.test()</code> function from the {stats} package. However, this function does not allow for weights or the variance structure to be accounted for with survey data. Therefore, when using survey data, we need to use one of two functions:</p>
<ul>
<li><code>svygofchisq()</code>: For goodness of fit tests</li>
<li><code>svychisq()</code>: For tests of independence and homogeneity</li>
</ul>
<p>The non-survey data function of <code>chisq.test()</code> requires either a single set of counts and given proportions (for goodness of fit tests) or two sets of counts for tests of independence and homogeneity. The functions we use with survey data require respondent-level data and formulas instead of counts. This ensures that the variances are correctly calculated.</p>
<p>First, the function for the goodness of fit tests is <code>svygofchisq()</code>:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="c06-statistical-testing.html#cb279-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svygofchisq</span>(formula,</span>
<span id="cb279-2"><a href="c06-statistical-testing.html#cb279-2" aria-hidden="true" tabindex="-1"></a>            p,</span>
<span id="cb279-3"><a href="c06-statistical-testing.html#cb279-3" aria-hidden="true" tabindex="-1"></a>            design,</span>
<span id="cb279-4"><a href="c06-statistical-testing.html#cb279-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">na.rm =</span> <span class="cn">TRUE</span>,</span>
<span id="cb279-5"><a href="c06-statistical-testing.html#cb279-5" aria-hidden="true" tabindex="-1"></a>            ...)</span></code></pre></div>
<p>The arguments are:</p>
<ul>
<li><code>formula</code>: Formula specifying a single factor variable</li>
<li><code>p</code>: Vector of probabilities for the categories of the factor in the correct order. If they probabilities do not sum to 1, they will be rescaled to sum to 1.</li>
<li><code>design</code>: Survey design object</li>
<li>…: Other arguments to pass on, such as <code>na.rm</code></li>
</ul>
<p>Based on the order of the arguments, we again must use the dot <code>(.)</code> notation if we pipe in the survey design object or explicitly name the arguments (as described at the beginning of this chapter). For the goodness of fit tests, the formula will be a single variable <code>formula = ~var</code> as we compare the observed data from this variable to the expected data. The expected probabilities are then entered in the <code>p</code> argument and need to be a vector of the same length as the number of categories in the variable. For example, if we want to know if the proportion of males and females matches a distribution of 30/70, then the sex variable (with two categories) would be used <code>formula = ~SEX</code>, and the proportions would be included as <code>p = c(.3, .7)</code>. It is important to note that the variable entered into the formula should be formatted as either a factor or a character. The examples below provide more detail and tips on how to make sure the levels match up correctly.</p>
<p>For tests of homogeneity and independence, the <code>svychisq()</code> function should be used. The syntax is as follows:</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="c06-statistical-testing.html#cb280-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svychisq</span>(</span>
<span id="cb280-2"><a href="c06-statistical-testing.html#cb280-2" aria-hidden="true" tabindex="-1"></a>  formula,</span>
<span id="cb280-3"><a href="c06-statistical-testing.html#cb280-3" aria-hidden="true" tabindex="-1"></a>  design,</span>
<span id="cb280-4"><a href="c06-statistical-testing.html#cb280-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">statistic =</span> <span class="fu">c</span>(<span class="st">&quot;F&quot;</span>, <span class="st">&quot;Chisq&quot;</span>, <span class="st">&quot;Wald&quot;</span>, <span class="st">&quot;adjWald&quot;</span>,</span>
<span id="cb280-5"><a href="c06-statistical-testing.html#cb280-5" aria-hidden="true" tabindex="-1"></a>                <span class="st">&quot;lincom&quot;</span>, <span class="st">&quot;saddlepoint&quot;</span>),</span>
<span id="cb280-6"><a href="c06-statistical-testing.html#cb280-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb280-7"><a href="c06-statistical-testing.html#cb280-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>The arguments are:</p>
<ul>
<li><code>formula</code>: Model formula specifying the table (shown in examples)</li>
<li><code>design</code>: Survey design object</li>
<li><code>statistic</code>: Type of test statistic to use in test (details below)</li>
<li><code>na.rm</code>: Remove missing values</li>
</ul>
<p>There are six statistics that are accepted in this formula. For tests of homogeneity (when comparing cross-tabulations), the <code>F</code> or <code>Chisq</code> statistics should be used.<a href="#fn25" class="footnote-ref" id="fnref25"><sup>25</sup></a> The <code>F</code> statistic is the default and uses the Rao-Scott second-order correction. This correction is designed to assist with complicated sampling designs (i.e., those other than a simple random sample) <span class="citation">(<a href="#ref-Scott2007" role="doc-biblioref">Scott 2007</a>)</span>. The <code>Chisq</code> statistic is an adjusted version of the Pearson <span class="math inline">\(\chi^2\)</span> statistic. The version of this statistic in the <code>svychisq()</code> function compares the design effect estimate from the provided survey data to what the <span class="math inline">\(\chi^2\)</span> distribution would have been if the data came from a simple random sampling.</p>
<p>For tests of independence, the <code>Wald</code> and <code>adjWald</code> are recommended as they provide a better adjustment for variable comparisons <span class="citation">(<a href="#ref-lumley2010complex" role="doc-biblioref">Lumley 2010</a>)</span>. If the data has a small number of primary sampling units (PSUs) compared to the degrees of freedom, then the <code>adjWald</code> statistic should be used to account for this. The <code>lincom</code> and <code>saddlepoint</code> statistics are available for more complicated data structures.</p>
<p>The formula argument will always be one-sided, unlike the <code>svyttest()</code> function. The two variables of interest should be included with a plus sign: <code>formula = ~ var_1 + var_2</code>. As with the <code>svygofchisq()</code> function, the variables entered into the formula should be formatted as either a factor or a character.</p>
<p>Additionally, as with the t-test function, both <code>svygofchisq()</code> and <code>svychisq()</code> have the <code>na.rm</code> argument. If any data is missing, the <span class="math inline">\(\chi^2\)</span> tests will assume that <code>NA</code> is a category and include it in the calculation. Throughout this chapter, we will always set <code>na.rm = TRUE</code>, but before analyzing the survey data, review the notes provided in Chapter <a href="c04-understanding-survey-data-documentation.html#c04-understanding-survey-data-documentation">4</a> to better understand how to handle missing data.</p>
</div>
<div id="stattest-chi-examples" class="section level3 hasAnchor" number="6.4.2">
<h3><span class="header-section-number">6.4.2</span> Examples<a href="c06-statistical-testing.html#stattest-chi-examples" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s walk through a few examples using the ANES data.</p>
<div id="stattest-chi-ex1" class="section level4 unnumbered hasAnchor">
<h4>Example 1: Goodness of Fit Test<a href="c06-statistical-testing.html#stattest-chi-ex1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>ANES asked respondents about their highest education level.<a href="#fn26" class="footnote-ref" id="fnref26"><sup>26</sup></a> Based on the data from the 2020 American Community Survey (ACS) 5-year estimates<a href="#fn27" class="footnote-ref" id="fnref27"><sup>27</sup></a>, the education distribution of those 18+ in the U.S. is as follows:</p>
<ul>
<li>11% had less than High School degree</li>
<li>27% had a High School degree</li>
<li>29% had some college or associate’s degree</li>
<li>33% had a bachelor’s degree or higher</li>
</ul>
<p>If we want to see if the weighted distribution from the ANES 2020 data matches this distribution, we could set up the hypothesis as follows:</p>
<ul>
<li><span class="math inline">\(H_0: p_1 = 0.11, ~ p_2 = 0.27, ~ p_3 = 0.29, ~ p_4 = 0.33\)</span></li>
<li><span class="math inline">\(H_A:\)</span> at least one of the education levels does not match between the ANES and the ACS</li>
</ul>
<p>To conduct this in R, let’s first look at the education variable (<code>Education</code>) we have on the ANES data. Using the <code>survey_mean()</code> function discussed in Chapter <a href="c05-descriptive-analysis.html#c05-descriptive-analysis">5</a>, we can see the education levels and estimated proportions.</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="c06-statistical-testing.html#cb281-1" aria-hidden="true" tabindex="-1"></a>anes_des <span class="sc">%&gt;%</span></span>
<span id="cb281-2"><a href="c06-statistical-testing.html#cb281-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(Education) <span class="sc">%&gt;%</span></span>
<span id="cb281-3"><a href="c06-statistical-testing.html#cb281-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Education) <span class="sc">%&gt;%</span></span>
<span id="cb281-4"><a href="c06-statistical-testing.html#cb281-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">p =</span> <span class="fu">survey_mean</span>())</span></code></pre></div>
<pre><code>## # A tibble: 5 × 3
##   Education         p    p_se
##   &lt;fct&gt;         &lt;dbl&gt;   &lt;dbl&gt;
## 1 Less than HS 0.0805 0.00568
## 2 High school  0.277  0.0102 
## 3 Post HS      0.290  0.00713
## 4 Bachelor&#39;s   0.226  0.00633
## 5 Graduate     0.126  0.00499</code></pre>
<p>Based on this output, we can see that we have different levels than the ACS data provides. Specifically, the education data from ANES has two levels for Bachelor’s Degree or Higher (Bachelor’s and Graduate), so these two categories need to be collapsed into a single category to match the ACS data. For this, we can use the {forcats} package from the tidyverse. The package’s <code>fct_collapse()</code> function helps us create a new variable by collapsing categories into a single one. Then, we will use the <code>svygofchisq()</code> function to compare the ANES data to the ACS data:</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="c06-statistical-testing.html#cb283-1" aria-hidden="true" tabindex="-1"></a>anes_des_educ <span class="ot">&lt;-</span> anes_des <span class="sc">%&gt;%</span></span>
<span id="cb283-2"><a href="c06-statistical-testing.html#cb283-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Education2 =</span></span>
<span id="cb283-3"><a href="c06-statistical-testing.html#cb283-3" aria-hidden="true" tabindex="-1"></a>           <span class="fu">fct_collapse</span>(Education,</span>
<span id="cb283-4"><a href="c06-statistical-testing.html#cb283-4" aria-hidden="true" tabindex="-1"></a>                        <span class="st">&quot;Bachelor or Higher&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Bachelor&#39;s&quot;</span>,</span>
<span id="cb283-5"><a href="c06-statistical-testing.html#cb283-5" aria-hidden="true" tabindex="-1"></a>                                                 <span class="st">&quot;Graduate&quot;</span>)))</span>
<span id="cb283-6"><a href="c06-statistical-testing.html#cb283-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb283-7"><a href="c06-statistical-testing.html#cb283-7" aria-hidden="true" tabindex="-1"></a>anes_des_educ <span class="sc">%&gt;%</span></span>
<span id="cb283-8"><a href="c06-statistical-testing.html#cb283-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(Education2) <span class="sc">%&gt;%</span></span>
<span id="cb283-9"><a href="c06-statistical-testing.html#cb283-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Education2) <span class="sc">%&gt;%</span></span>
<span id="cb283-10"><a href="c06-statistical-testing.html#cb283-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">p =</span> <span class="fu">survey_mean</span>())</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
##   Education2              p    p_se
##   &lt;fct&gt;               &lt;dbl&gt;   &lt;dbl&gt;
## 1 Less than HS       0.0805 0.00568
## 2 High school        0.277  0.0102 
## 3 Post HS            0.290  0.00713
## 4 Bachelor or Higher 0.352  0.00732</code></pre>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="c06-statistical-testing.html#cb285-1" aria-hidden="true" tabindex="-1"></a>chi_ex1 <span class="ot">&lt;-</span> anes_des_educ <span class="sc">%&gt;%</span></span>
<span id="cb285-2"><a href="c06-statistical-testing.html#cb285-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svygofchisq</span>(</span>
<span id="cb285-3"><a href="c06-statistical-testing.html#cb285-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span>  <span class="sc">~</span> Education2,</span>
<span id="cb285-4"><a href="c06-statistical-testing.html#cb285-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.11</span>, <span class="fl">0.27</span>, <span class="fl">0.29</span>, <span class="fl">0.33</span>),</span>
<span id="cb285-5"><a href="c06-statistical-testing.html#cb285-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb285-6"><a href="c06-statistical-testing.html#cb285-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb285-7"><a href="c06-statistical-testing.html#cb285-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb285-8"><a href="c06-statistical-testing.html#cb285-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb285-9"><a href="c06-statistical-testing.html#cb285-9" aria-hidden="true" tabindex="-1"></a>chi_ex1</span></code></pre></div>
<pre><code>## 
##  Design-based chi-squared test for given probabilities
## 
## data:  ~Education2
## X-squared = 2172220, scale = 1.1e+05, df = 2.3e+00, p-value =
## 9e-05</code></pre>
<p>The output from the <code>svygofchisq()</code> indicates that at least one proportion from ANES does not match the ACS data (<span class="math inline">\(\chi^2 =\)</span> 2.1722^{6}; <span class="math inline">\(p-value =\)</span> 8.74^{-5}). To get a better idea of the differences, we can use the <code>expected</code> output along with <code>survey_mean()</code> to create a comparison table:</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="c06-statistical-testing.html#cb287-1" aria-hidden="true" tabindex="-1"></a>ex1_table <span class="ot">&lt;-</span> anes_des_educ <span class="sc">%&gt;%</span></span>
<span id="cb287-2"><a href="c06-statistical-testing.html#cb287-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(Education2) <span class="sc">%&gt;%</span></span>
<span id="cb287-3"><a href="c06-statistical-testing.html#cb287-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Education2) <span class="sc">%&gt;%</span></span>
<span id="cb287-4"><a href="c06-statistical-testing.html#cb287-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Observed =</span> <span class="fu">survey_mean</span>(<span class="at">vartype =</span> <span class="st">&quot;ci&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb287-5"><a href="c06-statistical-testing.html#cb287-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Education =</span> Education2) <span class="sc">%&gt;%</span></span>
<span id="cb287-6"><a href="c06-statistical-testing.html#cb287-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Expected=</span><span class="fu">c</span>(<span class="fl">0.11</span>, <span class="fl">0.27</span>, <span class="fl">0.29</span>, <span class="fl">0.33</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb287-7"><a href="c06-statistical-testing.html#cb287-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Education, Expected, <span class="fu">everything</span>())</span>
<span id="cb287-8"><a href="c06-statistical-testing.html#cb287-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb287-9"><a href="c06-statistical-testing.html#cb287-9" aria-hidden="true" tabindex="-1"></a>ex1_table</span></code></pre></div>
<pre><code>## # A tibble: 4 × 5
##   Education          Expected Observed Observed_low Observed_upp
##   &lt;fct&gt;                 &lt;dbl&gt;    &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;
## 1 Less than HS           0.11   0.0805       0.0691       0.0919
## 2 High school            0.27   0.277        0.257        0.298 
## 3 Post HS                0.29   0.290        0.276        0.305 
## 4 Bachelor or Higher     0.33   0.352        0.337        0.367</code></pre>
<p>This output includes our expected proportions from the ACS that we provided the <code>svygofchisq()</code> function along with the output of the observed proportions and their confidence intervals. This table shows that the “High school” and “Post HS” categories have nearly identical proportions but that the other two categories are slightly different. Looking at the confidence intervals, we can see that the ANES data skews to include fewer people in the “Less than HS” category and more people in the “Bachelor or Higher” category. This may be easier to see if we plot this (see Figure <a href="c06-statistical-testing.html#fig:stattest-chi-ex1-graph">6.1</a>).
<!--Will want to remove the legend title...need to look this up. --></p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="c06-statistical-testing.html#cb289-1" aria-hidden="true" tabindex="-1"></a>ex1_table <span class="sc">%&gt;%</span></span>
<span id="cb289-2"><a href="c06-statistical-testing.html#cb289-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb289-3"><a href="c06-statistical-testing.html#cb289-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">c</span>(<span class="st">&quot;Expected&quot;</span>, <span class="st">&quot;Observed&quot;</span>),</span>
<span id="cb289-4"><a href="c06-statistical-testing.html#cb289-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">&quot;Names&quot;</span>,</span>
<span id="cb289-5"><a href="c06-statistical-testing.html#cb289-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">&quot;Proportion&quot;</span></span>
<span id="cb289-6"><a href="c06-statistical-testing.html#cb289-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb289-7"><a href="c06-statistical-testing.html#cb289-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb289-8"><a href="c06-statistical-testing.html#cb289-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Observed_low =</span> <span class="fu">if_else</span>(Names <span class="sc">==</span> <span class="st">&quot;Observed&quot;</span>, Observed_low, <span class="cn">NA_real_</span>),</span>
<span id="cb289-9"><a href="c06-statistical-testing.html#cb289-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Observed_upp =</span> <span class="fu">if_else</span>(Names <span class="sc">==</span> <span class="st">&quot;Observed&quot;</span>, Observed_upp, <span class="cn">NA_real_</span>)</span>
<span id="cb289-10"><a href="c06-statistical-testing.html#cb289-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb289-11"><a href="c06-statistical-testing.html#cb289-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Education, <span class="at">y =</span> Proportion, <span class="at">color =</span> Names)) <span class="sc">+</span></span>
<span id="cb289-12"><a href="c06-statistical-testing.html#cb289-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.75</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb289-13"><a href="c06-statistical-testing.html#cb289-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> Observed_low, <span class="at">ymax =</span> Observed_upp), <span class="at">width =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb289-14"><a href="c06-statistical-testing.html#cb289-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb289-15"><a href="c06-statistical-testing.html#cb289-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name =</span> <span class="st">&quot;Type&quot;</span>, <span class="at">values =</span> book_colors[<span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">1</span>)]) <span class="sc">+</span></span>
<span id="cb289-16"><a href="c06-statistical-testing.html#cb289-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:stattest-chi-ex1-graph"></span>
<img src="bookdown_files/figure-html/stattest-chi-ex1-graph-1.png" alt="Expected and observed proportions of education, showing the confidence intervals for the expected proportions and whether the observed proportions lie within them. The x-axis has labels 'Less than HS', 'High school', 'Post HS', and 'Bachelor or Higher'. The only ones where expected proportion is outside of the intervals is 'Less than HS' and 'Bachelor or Higher'." width="672" />
<p class="caption">
FIGURE 6.1: Expected and observed proportions of education, showing the confidence intervals for the expected proportions and whether the observed proportions lie within them.
</p>
</div>
</div>
<div id="stattest-chi-ex2" class="section level4 unnumbered hasAnchor">
<h4>Example 2: Test of Independence<a href="c06-statistical-testing.html#stattest-chi-ex2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>ANES asked respondents two questions about trust:</p>
<ul>
<li>How often can you trust the federal government to do what is right?</li>
<li>How often can you trust other people?</li>
</ul>
<p>If we want to see if the distributions of these two questions are similar or not, we can conduct a test of independence. Here is how the hypothesis could be set up:</p>
<ul>
<li><span class="math inline">\(H_0:\)</span> People’s trust in the federal government and their trust in other people are independent (i.e., <em>not</em> related)</li>
<li><span class="math inline">\(H_A:\)</span> People’s trust in the federal government and their trust in other people are <em>not</em> independent (i.e., they are related)</li>
</ul>
<p>To conduct this in R, we use the <code>svychisq()</code> function to compare the two variables:</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="c06-statistical-testing.html#cb290-1" aria-hidden="true" tabindex="-1"></a>chi_ex2 <span class="ot">&lt;-</span> anes_des <span class="sc">%&gt;%</span></span>
<span id="cb290-2"><a href="c06-statistical-testing.html#cb290-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svychisq</span>(</span>
<span id="cb290-3"><a href="c06-statistical-testing.html#cb290-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span>  <span class="sc">~</span> TrustGovernment <span class="sc">+</span> TrustPeople,</span>
<span id="cb290-4"><a href="c06-statistical-testing.html#cb290-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb290-5"><a href="c06-statistical-testing.html#cb290-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="st">&quot;Wald&quot;</span>,</span>
<span id="cb290-6"><a href="c06-statistical-testing.html#cb290-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb290-7"><a href="c06-statistical-testing.html#cb290-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb290-8"><a href="c06-statistical-testing.html#cb290-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb290-9"><a href="c06-statistical-testing.html#cb290-9" aria-hidden="true" tabindex="-1"></a>chi_ex2</span></code></pre></div>
<pre><code>## 
##  Design-based Wald test of association
## 
## data:  NextMethod()
## F = 21, ndf = 16, ddf = 51, p-value &lt;2e-16</code></pre>
<p>The output from <code>svychisq()</code> indicates that the distribution of people’s trust in the federal government and their trust in other people are <em>not</em> independent, meaning that they are related. Let’s output the distributions in a table to see the relationship. The <code>observed</code> output from the test provides a cross-tabulation of the counts for each category:</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="c06-statistical-testing.html#cb292-1" aria-hidden="true" tabindex="-1"></a>chi_ex2<span class="sc">$</span>observed</span></code></pre></div>
<pre><code>##                      TrustPeople
## TrustGovernment         Always Most of the time About half the time
##   Always                16.470           25.009              31.848
##   Most of the time      11.020          539.377             196.258
##   About half the time   11.772          934.858             861.971
##   Some of the time      17.007         1353.779             839.863
##   Never                  3.174          236.785             174.272
##                      TrustPeople
## TrustGovernment       Some of the time    Never
##   Always                        36.854    5.523
##   Most of the time             206.556   27.184
##   About half the time          428.871   65.024
##   Some of the time             932.628   89.596
##   Never                        217.994  189.307</code></pre>
<p>However, as researchers, we often want to know about the proportions and not just the respondent counts from the survey. There are a couple of different ways that we can do this. The first is using the counts from <code>chi_ex2$observed</code> to calculate the proportion. We can then pivot the table to create a cross-tabulation similar to the counts table above. Adding <code>group_by()</code> to the code means that we are obtaining the proportions within each level of that variable. In this case, we are looking at the distribution of <code>TrustGovernment</code> for each level of <code>TrustPeople</code>.</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="c06-statistical-testing.html#cb294-1" aria-hidden="true" tabindex="-1"></a>chi_ex2<span class="sc">$</span>observed <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb294-2"><a href="c06-statistical-testing.html#cb294-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TrustPeople) <span class="sc">%&gt;%</span></span>
<span id="cb294-3"><a href="c06-statistical-testing.html#cb294-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> <span class="fu">round</span>(n <span class="sc">/</span> <span class="fu">sum</span>(n), <span class="dv">3</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb294-4"><a href="c06-statistical-testing.html#cb294-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>n) <span class="sc">%&gt;%</span></span>
<span id="cb294-5"><a href="c06-statistical-testing.html#cb294-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> TrustPeople, <span class="at">values_from =</span> prop) <span class="sc">%&gt;%</span></span>
<span id="cb294-6"><a href="c06-statistical-testing.html#cb294-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>(<span class="at">rowname_col =</span> <span class="st">&quot;TrustGovernment&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb294-7"><a href="c06-statistical-testing.html#cb294-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_stubhead</span>(<span class="at">label =</span> <span class="st">&quot;Trust in Government&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb294-8"><a href="c06-statistical-testing.html#cb294-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_spanner</span>(<span class="at">label =</span> <span class="st">&quot;Trust in People&quot;</span>,</span>
<span id="cb294-9"><a href="c06-statistical-testing.html#cb294-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">columns =</span> <span class="fu">everything</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb294-10"><a href="c06-statistical-testing.html#cb294-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_label</span>(<span class="st">`</span><span class="at">Most of the time</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">md</span>(<span class="st">&quot;Most of&lt;br /&gt;the time&quot;</span>),</span>
<span id="cb294-11"><a href="c06-statistical-testing.html#cb294-11" aria-hidden="true" tabindex="-1"></a>             <span class="st">`</span><span class="at">About half the time</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">md</span>(<span class="st">&quot;About half&lt;br /&gt;the time&quot;</span>),</span>
<span id="cb294-12"><a href="c06-statistical-testing.html#cb294-12" aria-hidden="true" tabindex="-1"></a>             <span class="st">`</span><span class="at">Some of the time</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">md</span>(<span class="st">&quot;Some of&lt;br /&gt;the time&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb294-13"><a href="c06-statistical-testing.html#cb294-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_caption</span>(<span class="st">&quot;Estimates of proportion of people </span></span>
<span id="cb294-14"><a href="c06-statistical-testing.html#cb294-14" aria-hidden="true" tabindex="-1"></a><span class="st">              by levels of trust in people and government, </span></span>
<span id="cb294-15"><a href="c06-statistical-testing.html#cb294-15" aria-hidden="true" tabindex="-1"></a><span class="st">              ANES 2020&quot;</span>)</span></code></pre></div>
<div id="edxahdlkim" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#edxahdlkim table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#edxahdlkim thead, #edxahdlkim tbody, #edxahdlkim tfoot, #edxahdlkim tr, #edxahdlkim td, #edxahdlkim th {
  border-style: none;
}

#edxahdlkim p {
  margin: 0;
  padding: 0;
}

#edxahdlkim .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#edxahdlkim .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#edxahdlkim .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#edxahdlkim .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#edxahdlkim .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#edxahdlkim .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#edxahdlkim .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#edxahdlkim .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#edxahdlkim .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#edxahdlkim .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#edxahdlkim .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#edxahdlkim .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#edxahdlkim .gt_spanner_row {
  border-bottom-style: hidden;
}

#edxahdlkim .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#edxahdlkim .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#edxahdlkim .gt_from_md > :first-child {
  margin-top: 0;
}

#edxahdlkim .gt_from_md > :last-child {
  margin-bottom: 0;
}

#edxahdlkim .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#edxahdlkim .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#edxahdlkim .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#edxahdlkim .gt_row_group_first td {
  border-top-width: 2px;
}

#edxahdlkim .gt_row_group_first th {
  border-top-width: 2px;
}

#edxahdlkim .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#edxahdlkim .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#edxahdlkim .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#edxahdlkim .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#edxahdlkim .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#edxahdlkim .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#edxahdlkim .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#edxahdlkim .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#edxahdlkim .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#edxahdlkim .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#edxahdlkim .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#edxahdlkim .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#edxahdlkim .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#edxahdlkim .gt_left {
  text-align: left;
}

#edxahdlkim .gt_center {
  text-align: center;
}

#edxahdlkim .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#edxahdlkim .gt_font_normal {
  font-weight: normal;
}

#edxahdlkim .gt_font_bold {
  font-weight: bold;
}

#edxahdlkim .gt_font_italic {
  font-style: italic;
}

#edxahdlkim .gt_super {
  font-size: 65%;
}

#edxahdlkim .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#edxahdlkim .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#edxahdlkim .gt_indent_1 {
  text-indent: 5px;
}

#edxahdlkim .gt_indent_2 {
  text-indent: 10px;
}

#edxahdlkim .gt_indent_3 {
  text-indent: 15px;
}

#edxahdlkim .gt_indent_4 {
  text-indent: 20px;
}

#edxahdlkim .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <caption><span id="tab:stattest-chi-ex2-prop1">TABLE 6.1: </span>Estimates of proportion of people 
              by levels of trust in people and government, 
              ANES 2020</caption>
  <thead>
    
    <tr class="gt_col_headings gt_spanner_row">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col" id="Trust in Government">Trust in Government</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="5" scope="colgroup" id="Trust in People">
        <span class="gt_column_spanner">Trust in People</span>
      </th>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Always">Always</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Most of&lt;br /&gt;the time">Most of<br />the time</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="About half&lt;br /&gt;the time">About half<br />the time</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Some of&lt;br /&gt;the time">Some of<br />the time</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Never">Never</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><th id="stub_1_1" scope="row" class="gt_row gt_left gt_stub">Always</th>
<td headers="stub_1_1 Always" class="gt_row gt_right">0.277</td>
<td headers="stub_1_1 Most of the time" class="gt_row gt_right">0.008</td>
<td headers="stub_1_1 About half the time" class="gt_row gt_right">0.015</td>
<td headers="stub_1_1 Some of the time" class="gt_row gt_right">0.020</td>
<td headers="stub_1_1 Never" class="gt_row gt_right">0.015</td></tr>
    <tr><th id="stub_1_2" scope="row" class="gt_row gt_left gt_stub">Most of the time</th>
<td headers="stub_1_2 Always" class="gt_row gt_right">0.185</td>
<td headers="stub_1_2 Most of the time" class="gt_row gt_right">0.175</td>
<td headers="stub_1_2 About half the time" class="gt_row gt_right">0.093</td>
<td headers="stub_1_2 Some of the time" class="gt_row gt_right">0.113</td>
<td headers="stub_1_2 Never" class="gt_row gt_right">0.072</td></tr>
    <tr><th id="stub_1_3" scope="row" class="gt_row gt_left gt_stub">About half the time</th>
<td headers="stub_1_3 Always" class="gt_row gt_right">0.198</td>
<td headers="stub_1_3 Most of the time" class="gt_row gt_right">0.303</td>
<td headers="stub_1_3 About half the time" class="gt_row gt_right">0.410</td>
<td headers="stub_1_3 Some of the time" class="gt_row gt_right">0.235</td>
<td headers="stub_1_3 Never" class="gt_row gt_right">0.173</td></tr>
    <tr><th id="stub_1_4" scope="row" class="gt_row gt_left gt_stub">Some of the time</th>
<td headers="stub_1_4 Always" class="gt_row gt_right">0.286</td>
<td headers="stub_1_4 Most of the time" class="gt_row gt_right">0.438</td>
<td headers="stub_1_4 About half the time" class="gt_row gt_right">0.399</td>
<td headers="stub_1_4 Some of the time" class="gt_row gt_right">0.512</td>
<td headers="stub_1_4 Never" class="gt_row gt_right">0.238</td></tr>
    <tr><th id="stub_1_5" scope="row" class="gt_row gt_left gt_stub">Never</th>
<td headers="stub_1_5 Always" class="gt_row gt_right">0.053</td>
<td headers="stub_1_5 Most of the time" class="gt_row gt_right">0.077</td>
<td headers="stub_1_5 About half the time" class="gt_row gt_right">0.083</td>
<td headers="stub_1_5 Some of the time" class="gt_row gt_right">0.120</td>
<td headers="stub_1_5 Never" class="gt_row gt_right">0.503</td></tr>
  </tbody>
  
  
</table>
</div>
<p>The second option is to use <code>group_by()</code> and <code>survey_mean()</code> functions to calculate the proportions from the ANES design object. A reminder that with more than one variable listed in the <code>group_by()</code> statement, the proportions are within the first variable listed. As mentioned above, we are looking at the distribution of <code>TrustGovernment</code> for each level of <code>TrustPeople</code>.</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="c06-statistical-testing.html#cb295-1" aria-hidden="true" tabindex="-1"></a>chi_ex2_obs <span class="ot">&lt;-</span> anes_des <span class="sc">%&gt;%</span></span>
<span id="cb295-2"><a href="c06-statistical-testing.html#cb295-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(TrustPeople, TrustGovernment) <span class="sc">%&gt;%</span></span>
<span id="cb295-3"><a href="c06-statistical-testing.html#cb295-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TrustPeople, TrustGovernment) <span class="sc">%&gt;%</span></span>
<span id="cb295-4"><a href="c06-statistical-testing.html#cb295-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Observed =</span> <span class="fu">round</span>(<span class="fu">survey_mean</span>(<span class="at">vartype =</span> <span class="st">&quot;ci&quot;</span>), <span class="dv">3</span>),</span>
<span id="cb295-5"><a href="c06-statistical-testing.html#cb295-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups=</span><span class="st">&quot;drop&quot;</span>) </span>
<span id="cb295-6"><a href="c06-statistical-testing.html#cb295-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb295-7"><a href="c06-statistical-testing.html#cb295-7" aria-hidden="true" tabindex="-1"></a>chi_ex2_obs <span class="sc">%&gt;%</span></span>
<span id="cb295-8"><a href="c06-statistical-testing.html#cb295-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> <span class="fu">paste0</span>(Observed, <span class="st">&quot; (&quot;</span>, Observed_low, <span class="st">&quot;, &quot;</span>,</span>
<span id="cb295-9"><a href="c06-statistical-testing.html#cb295-9" aria-hidden="true" tabindex="-1"></a>                       Observed_upp, <span class="st">&quot;)&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb295-10"><a href="c06-statistical-testing.html#cb295-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(TrustGovernment, TrustPeople, prop) <span class="sc">%&gt;%</span></span>
<span id="cb295-11"><a href="c06-statistical-testing.html#cb295-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> TrustPeople, <span class="at">values_from =</span> prop) <span class="sc">%&gt;%</span></span>
<span id="cb295-12"><a href="c06-statistical-testing.html#cb295-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>(<span class="at">rowname_col =</span> <span class="st">&quot;TrustGovernment&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb295-13"><a href="c06-statistical-testing.html#cb295-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_stubhead</span>(<span class="at">label =</span> <span class="st">&quot;Trust in Government&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb295-14"><a href="c06-statistical-testing.html#cb295-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_spanner</span>(<span class="at">label =</span> <span class="st">&quot;Trust in People&quot;</span>,</span>
<span id="cb295-15"><a href="c06-statistical-testing.html#cb295-15" aria-hidden="true" tabindex="-1"></a>              <span class="at">columns =</span> <span class="fu">everything</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb295-16"><a href="c06-statistical-testing.html#cb295-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_options</span>(<span class="at">page.orientation =</span> <span class="st">&quot;landscape&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb295-17"><a href="c06-statistical-testing.html#cb295-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_caption</span>(<span class="st">&quot;Estimates of proportion of people </span></span>
<span id="cb295-18"><a href="c06-statistical-testing.html#cb295-18" aria-hidden="true" tabindex="-1"></a><span class="st">              by levels of trust in people and government </span></span>
<span id="cb295-19"><a href="c06-statistical-testing.html#cb295-19" aria-hidden="true" tabindex="-1"></a><span class="st">              with confidence intervals, </span></span>
<span id="cb295-20"><a href="c06-statistical-testing.html#cb295-20" aria-hidden="true" tabindex="-1"></a><span class="st">              ANES 2020&quot;</span>)</span></code></pre></div>
<div id="jslvphoojc" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#jslvphoojc table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#jslvphoojc thead, #jslvphoojc tbody, #jslvphoojc tfoot, #jslvphoojc tr, #jslvphoojc td, #jslvphoojc th {
  border-style: none;
}

#jslvphoojc p {
  margin: 0;
  padding: 0;
}

#jslvphoojc .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#jslvphoojc .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#jslvphoojc .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#jslvphoojc .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#jslvphoojc .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jslvphoojc .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jslvphoojc .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jslvphoojc .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#jslvphoojc .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#jslvphoojc .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#jslvphoojc .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#jslvphoojc .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#jslvphoojc .gt_spanner_row {
  border-bottom-style: hidden;
}

#jslvphoojc .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#jslvphoojc .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#jslvphoojc .gt_from_md > :first-child {
  margin-top: 0;
}

#jslvphoojc .gt_from_md > :last-child {
  margin-bottom: 0;
}

#jslvphoojc .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#jslvphoojc .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#jslvphoojc .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#jslvphoojc .gt_row_group_first td {
  border-top-width: 2px;
}

#jslvphoojc .gt_row_group_first th {
  border-top-width: 2px;
}

#jslvphoojc .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jslvphoojc .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#jslvphoojc .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#jslvphoojc .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jslvphoojc .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jslvphoojc .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#jslvphoojc .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#jslvphoojc .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#jslvphoojc .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jslvphoojc .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jslvphoojc .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jslvphoojc .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jslvphoojc .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jslvphoojc .gt_left {
  text-align: left;
}

#jslvphoojc .gt_center {
  text-align: center;
}

#jslvphoojc .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#jslvphoojc .gt_font_normal {
  font-weight: normal;
}

#jslvphoojc .gt_font_bold {
  font-weight: bold;
}

#jslvphoojc .gt_font_italic {
  font-style: italic;
}

#jslvphoojc .gt_super {
  font-size: 65%;
}

#jslvphoojc .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#jslvphoojc .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#jslvphoojc .gt_indent_1 {
  text-indent: 5px;
}

#jslvphoojc .gt_indent_2 {
  text-indent: 10px;
}

#jslvphoojc .gt_indent_3 {
  text-indent: 15px;
}

#jslvphoojc .gt_indent_4 {
  text-indent: 20px;
}

#jslvphoojc .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <caption><span id="tab:stattest-chi-ex2-prop2">TABLE 6.2: </span>Estimates of proportion of people 
              by levels of trust in people and government 
              with confidence intervals, 
              ANES 2020</caption>
  <thead>
    
    <tr class="gt_col_headings gt_spanner_row">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col" id="Trust in Government">Trust in Government</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="5" scope="colgroup" id="Trust in People">
        <span class="gt_column_spanner">Trust in People</span>
      </th>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Always">Always</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Most of the time">Most of the time</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="About half the time">About half the time</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Some of the time">Some of the time</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Never">Never</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><th id="stub_1_1" scope="row" class="gt_row gt_center gt_stub">Always</th>
<td headers="stub_1_1 Always" class="gt_row gt_right">0.277 (0.11, 0.444)</td>
<td headers="stub_1_1 Most of the time" class="gt_row gt_right">0.008 (0.004, 0.012)</td>
<td headers="stub_1_1 About half the time" class="gt_row gt_right">0.015 (0.006, 0.024)</td>
<td headers="stub_1_1 Some of the time" class="gt_row gt_right">0.02 (0.008, 0.033)</td>
<td headers="stub_1_1 Never" class="gt_row gt_right">0.015 (0, 0.029)</td></tr>
    <tr><th id="stub_1_2" scope="row" class="gt_row gt_center gt_stub">Most of the time</th>
<td headers="stub_1_2 Always" class="gt_row gt_right">0.185 (-0.009, 0.38)</td>
<td headers="stub_1_2 Most of the time" class="gt_row gt_right">0.175 (0.157, 0.192)</td>
<td headers="stub_1_2 About half the time" class="gt_row gt_right">0.093 (0.078, 0.109)</td>
<td headers="stub_1_2 Some of the time" class="gt_row gt_right">0.113 (0.085, 0.141)</td>
<td headers="stub_1_2 Never" class="gt_row gt_right">0.072 (0.021, 0.123)</td></tr>
    <tr><th id="stub_1_3" scope="row" class="gt_row gt_center gt_stub">About half the time</th>
<td headers="stub_1_3 Always" class="gt_row gt_right">0.198 (0.046, 0.35)</td>
<td headers="stub_1_3 Most of the time" class="gt_row gt_right">0.303 (0.281, 0.324)</td>
<td headers="stub_1_3 About half the time" class="gt_row gt_right">0.41 (0.378, 0.441)</td>
<td headers="stub_1_3 Some of the time" class="gt_row gt_right">0.235 (0.2, 0.271)</td>
<td headers="stub_1_3 Never" class="gt_row gt_right">0.173 (0.099, 0.246)</td></tr>
    <tr><th id="stub_1_4" scope="row" class="gt_row gt_center gt_stub">Some of the time</th>
<td headers="stub_1_4 Always" class="gt_row gt_right">0.286 (0.069, 0.503)</td>
<td headers="stub_1_4 Most of the time" class="gt_row gt_right">0.438 (0.415, 0.462)</td>
<td headers="stub_1_4 About half the time" class="gt_row gt_right">0.399 (0.365, 0.433)</td>
<td headers="stub_1_4 Some of the time" class="gt_row gt_right">0.512 (0.481, 0.543)</td>
<td headers="stub_1_4 Never" class="gt_row gt_right">0.238 (0.178, 0.298)</td></tr>
    <tr><th id="stub_1_5" scope="row" class="gt_row gt_center gt_stub">Never</th>
<td headers="stub_1_5 Always" class="gt_row gt_right">0.053 (-0.01, 0.117)</td>
<td headers="stub_1_5 Most of the time" class="gt_row gt_right">0.077 (0.064, 0.089)</td>
<td headers="stub_1_5 About half the time" class="gt_row gt_right">0.083 (0.063, 0.103)</td>
<td headers="stub_1_5 Some of the time" class="gt_row gt_right">0.12 (0.097, 0.142)</td>
<td headers="stub_1_5 Never" class="gt_row gt_right">0.503 (0.422, 0.583)</td></tr>
  </tbody>
  
  
</table>
</div>
<p>Both methods produce the same output as the <code>svychisq()</code> function does account for the survey design. However, calculating the proportions directly from the design object means we can also obtain the variance information. In this case, the table output displays the survey estimate followed by the confidence intervals. Based on the output, we can see that of those who never trust people, 50.3% also never trust the government, while the proportions of never trusting the government are much lower for each of the other levels of trusting people.</p>
<p>We may find it easier to look at these proportions graphically. We can use <code>ggplot()</code> and facets to provide an overview:</p>
<!--Perhaps a mosaic plot instead?-->
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="c06-statistical-testing.html#cb296-1" aria-hidden="true" tabindex="-1"></a>chi_ex2_obs <span class="sc">%&gt;%</span></span>
<span id="cb296-2"><a href="c06-statistical-testing.html#cb296-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">TrustPeople=</span><span class="fu">str_c</span>(<span class="st">&quot;Trust in People:</span><span class="sc">\n</span><span class="st">&quot;</span>, TrustPeople)) <span class="sc">%&gt;%</span></span>
<span id="cb296-3"><a href="c06-statistical-testing.html#cb296-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> TrustGovernment, <span class="at">y =</span> Observed, <span class="at">color =</span> TrustGovernment)) <span class="sc">+</span></span>
<span id="cb296-4"><a href="c06-statistical-testing.html#cb296-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>( <span class="sc">~</span> TrustPeople, <span class="at">ncol =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb296-5"><a href="c06-statistical-testing.html#cb296-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb296-6"><a href="c06-statistical-testing.html#cb296-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> Observed_low, <span class="at">ymax =</span> Observed_upp)) <span class="sc">+</span></span>
<span id="cb296-7"><a href="c06-statistical-testing.html#cb296-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Proportion&quot;</span>) <span class="sc">+</span></span>
<span id="cb296-8"><a href="c06-statistical-testing.html#cb296-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb296-9"><a href="c06-statistical-testing.html#cb296-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb296-10"><a href="c06-statistical-testing.html#cb296-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name=</span><span class="st">&quot;Trust in Government&quot;</span>, <span class="at">values=</span>book_colors) <span class="sc">+</span></span>
<span id="cb296-11"><a href="c06-statistical-testing.html#cb296-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb296-12"><a href="c06-statistical-testing.html#cb296-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb296-13"><a href="c06-statistical-testing.html#cb296-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>) <span class="sc">+</span></span>
<span id="cb296-14"><a href="c06-statistical-testing.html#cb296-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">col =</span> <span class="fu">guide_legend</span>(<span class="at">nrow=</span><span class="dv">2</span>))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:stattest-chi-ex2-graph"></span>
<img src="bookdown_files/figure-html/stattest-chi-ex2-graph-1.png" alt="Estimates of proportion of people by levels of trust in people and government with confidence intervals, ANES 2020. This presents the same information as previous table in graphical form." width="672" />
<p class="caption">
FIGURE 6.2: Estimates of proportion of people by levels of trust in people and government with confidence intervals, ANES 2020
</p>
</div>
</div>
<div id="stattest-chi-ex3" class="section level4 unnumbered hasAnchor">
<h4>Example 3: Test of Homogeneity<a href="c06-statistical-testing.html#stattest-chi-ex3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Researchers and politicians often look at specific demographics each election cycle to understand how each group is leaning or voting toward candidates. The ANES data is post-election, but we can still see if there are differences in how specific demographic groups voted.</p>
<p>If we want to see if there is a difference in how each age group voted for the 2020 candidates, this would be a test of homogeneity, and we can set up the hypothesis as follows:</p>
<p><span class="math display">\[\begin{align*}
H_0: p_{1_{Biden}} &amp;= p_{1_{Trump}} = p_{1_{Other}},\\
    p_{2_{Biden}} &amp;= p_{2_{Trump}} = p_{2_{Other}},\\
    p_{3_{Biden}} &amp;= p_{3_{Trump}} = p_{3_{Other}},\\
    p_{4_{Biden}} &amp;= p_{4_{Trump}} = p_{4_{Other}},\\
    p_{5_{Biden}} &amp;= p_{5_{Trump}} = p_{5_{Other}},\\
    p_{6_{Biden}} &amp;= p_{6_{Trump}} = p_{6_{Other}}
  \end{align*}\]</span>
where <span class="math inline">\(p_{i_{Biden}}\)</span> is the observed proportion of each age group (<span class="math inline">\(i\)</span>) that voted for Biden, <span class="math inline">\(p_{i_{Trump}}\)</span> is the observed proportion of each age group (<span class="math inline">\(i\)</span>) that voted for Trump, and <span class="math inline">\(p_{i_{Other}}\)</span> is the observed proportion of each age group (<span class="math inline">\(i\)</span>) that voted for another candidate</p>
<ul>
<li><span class="math inline">\(H_A:\)</span> at least one category of <span class="math inline">\(p_{i_{Biden}}\)</span> does not match <span class="math inline">\(p_{i_{Trump}}\)</span> or <span class="math inline">\(p_{i_{Other}}\)</span></li>
</ul>
<p>To conduct this in R, we use the <code>svychisq()</code> function to compare the two variables:</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="c06-statistical-testing.html#cb297-1" aria-hidden="true" tabindex="-1"></a>chi_ex3 <span class="ot">&lt;-</span> anes_des <span class="sc">%&gt;%</span></span>
<span id="cb297-2"><a href="c06-statistical-testing.html#cb297-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(VotedPres2020_selection, AgeGroup) <span class="sc">%&gt;%</span></span>
<span id="cb297-3"><a href="c06-statistical-testing.html#cb297-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svychisq</span>(</span>
<span id="cb297-4"><a href="c06-statistical-testing.html#cb297-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span>  <span class="sc">~</span> AgeGroup <span class="sc">+</span> VotedPres2020_selection,</span>
<span id="cb297-5"><a href="c06-statistical-testing.html#cb297-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb297-6"><a href="c06-statistical-testing.html#cb297-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="st">&quot;Chisq&quot;</span>,</span>
<span id="cb297-7"><a href="c06-statistical-testing.html#cb297-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb297-8"><a href="c06-statistical-testing.html#cb297-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb297-9"><a href="c06-statistical-testing.html#cb297-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb297-10"><a href="c06-statistical-testing.html#cb297-10" aria-hidden="true" tabindex="-1"></a>chi_ex3</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s X^2: Rao &amp; Scott adjustment
## 
## data:  NextMethod()
## X-squared = 169, df = 10, p-value &lt;2e-16</code></pre>
<p>The output from <code>svychisq()</code> indicates a difference in how each age group voted in the 2020 election. To get a better idea of the different distributions, let’s output proportions to see the relationship. As we learned in Example 2 above, we can use <code>chi_ex3$observed</code>, or if we want to get the variance information (which is crucial with survey data), we can use <code>survey_mean()</code>. Remember, when we have two variables in <code>group_by()</code>, we obtain the proportions within each level of the variable listed. In this case, we are looking at the distribution of <code>AgeGroup</code> for each level of <code>VotedPres2020_selection</code>.</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="c06-statistical-testing.html#cb299-1" aria-hidden="true" tabindex="-1"></a>chi_ex3_obs <span class="ot">&lt;-</span> anes_des <span class="sc">%&gt;%</span></span>
<span id="cb299-2"><a href="c06-statistical-testing.html#cb299-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(VotedPres2020 <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb299-3"><a href="c06-statistical-testing.html#cb299-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(VotedPres2020_selection, AgeGroup) <span class="sc">%&gt;%</span></span>
<span id="cb299-4"><a href="c06-statistical-testing.html#cb299-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(VotedPres2020_selection, AgeGroup) <span class="sc">%&gt;%</span></span>
<span id="cb299-5"><a href="c06-statistical-testing.html#cb299-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Observed =</span> <span class="fu">round</span>(<span class="fu">survey_mean</span>(<span class="at">vartype =</span> <span class="st">&quot;ci&quot;</span>), <span class="dv">3</span>)) </span>
<span id="cb299-6"><a href="c06-statistical-testing.html#cb299-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb299-7"><a href="c06-statistical-testing.html#cb299-7" aria-hidden="true" tabindex="-1"></a>chi_ex3_obs <span class="sc">%&gt;%</span></span>
<span id="cb299-8"><a href="c06-statistical-testing.html#cb299-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> <span class="fu">paste0</span>(Observed, <span class="st">&quot; (&quot;</span>, Observed_low, <span class="st">&quot;, &quot;</span>,</span>
<span id="cb299-9"><a href="c06-statistical-testing.html#cb299-9" aria-hidden="true" tabindex="-1"></a>                       Observed_upp, <span class="st">&quot;)&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb299-10"><a href="c06-statistical-testing.html#cb299-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(AgeGroup, VotedPres2020_selection, prop) <span class="sc">%&gt;%</span></span>
<span id="cb299-11"><a href="c06-statistical-testing.html#cb299-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> VotedPres2020_selection, </span>
<span id="cb299-12"><a href="c06-statistical-testing.html#cb299-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> prop) <span class="sc">%&gt;%</span></span>
<span id="cb299-13"><a href="c06-statistical-testing.html#cb299-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>(<span class="at">rowname_col =</span> <span class="st">&quot;AgeGroup&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb299-14"><a href="c06-statistical-testing.html#cb299-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_stubhead</span>(<span class="at">label =</span> <span class="st">&quot;Age Group&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb299-15"><a href="c06-statistical-testing.html#cb299-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_caption</span>(<span class="st">&quot;Distribution of age group </span></span>
<span id="cb299-16"><a href="c06-statistical-testing.html#cb299-16" aria-hidden="true" tabindex="-1"></a><span class="st">              by presidential candidate selection </span></span>
<span id="cb299-17"><a href="c06-statistical-testing.html#cb299-17" aria-hidden="true" tabindex="-1"></a><span class="st">              with confidence intervals&quot;</span>)</span></code></pre></div>
<div id="uphlolqabb" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#uphlolqabb table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#uphlolqabb thead, #uphlolqabb tbody, #uphlolqabb tfoot, #uphlolqabb tr, #uphlolqabb td, #uphlolqabb th {
  border-style: none;
}

#uphlolqabb p {
  margin: 0;
  padding: 0;
}

#uphlolqabb .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#uphlolqabb .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#uphlolqabb .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#uphlolqabb .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#uphlolqabb .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#uphlolqabb .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uphlolqabb .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#uphlolqabb .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#uphlolqabb .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#uphlolqabb .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#uphlolqabb .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#uphlolqabb .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#uphlolqabb .gt_spanner_row {
  border-bottom-style: hidden;
}

#uphlolqabb .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#uphlolqabb .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#uphlolqabb .gt_from_md > :first-child {
  margin-top: 0;
}

#uphlolqabb .gt_from_md > :last-child {
  margin-bottom: 0;
}

#uphlolqabb .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#uphlolqabb .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#uphlolqabb .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#uphlolqabb .gt_row_group_first td {
  border-top-width: 2px;
}

#uphlolqabb .gt_row_group_first th {
  border-top-width: 2px;
}

#uphlolqabb .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#uphlolqabb .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#uphlolqabb .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#uphlolqabb .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uphlolqabb .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#uphlolqabb .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#uphlolqabb .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#uphlolqabb .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#uphlolqabb .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uphlolqabb .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#uphlolqabb .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#uphlolqabb .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#uphlolqabb .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#uphlolqabb .gt_left {
  text-align: left;
}

#uphlolqabb .gt_center {
  text-align: center;
}

#uphlolqabb .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#uphlolqabb .gt_font_normal {
  font-weight: normal;
}

#uphlolqabb .gt_font_bold {
  font-weight: bold;
}

#uphlolqabb .gt_font_italic {
  font-style: italic;
}

#uphlolqabb .gt_super {
  font-size: 65%;
}

#uphlolqabb .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#uphlolqabb .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#uphlolqabb .gt_indent_1 {
  text-indent: 5px;
}

#uphlolqabb .gt_indent_2 {
  text-indent: 10px;
}

#uphlolqabb .gt_indent_3 {
  text-indent: 15px;
}

#uphlolqabb .gt_indent_4 {
  text-indent: 20px;
}

#uphlolqabb .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <caption><span id="tab:stattest-chi-ex3-table">TABLE 6.3: </span>Distribution of age group 
              by presidential candidate selection 
              with confidence intervals</caption>
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Age Group">Age Group</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Biden">Biden</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Trump">Trump</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Other">Other</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><th id="stub_1_1" scope="row" class="gt_row gt_center gt_stub">18-29</th>
<td headers="stub_1_1 Biden" class="gt_row gt_right">0.204 (0.177, 0.231)</td>
<td headers="stub_1_1 Trump" class="gt_row gt_right">0.114 (0.095, 0.133)</td>
<td headers="stub_1_1 Other" class="gt_row gt_right">0.227 (0.15, 0.304)</td></tr>
    <tr><th id="stub_1_2" scope="row" class="gt_row gt_center gt_stub">30-39</th>
<td headers="stub_1_2 Biden" class="gt_row gt_right">0.169 (0.153, 0.185)</td>
<td headers="stub_1_2 Trump" class="gt_row gt_right">0.147 (0.123, 0.17)</td>
<td headers="stub_1_2 Other" class="gt_row gt_right">0.306 (0.214, 0.398)</td></tr>
    <tr><th id="stub_1_3" scope="row" class="gt_row gt_center gt_stub">40-49</th>
<td headers="stub_1_3 Biden" class="gt_row gt_right">0.163 (0.146, 0.18)</td>
<td headers="stub_1_3 Trump" class="gt_row gt_right">0.157 (0.136, 0.178)</td>
<td headers="stub_1_3 Other" class="gt_row gt_right">0.209 (0.128, 0.29)</td></tr>
    <tr><th id="stub_1_4" scope="row" class="gt_row gt_center gt_stub">50-59</th>
<td headers="stub_1_4 Biden" class="gt_row gt_right">0.154 (0.136, 0.173)</td>
<td headers="stub_1_4 Trump" class="gt_row gt_right">0.234 (0.207, 0.261)</td>
<td headers="stub_1_4 Other" class="gt_row gt_right">0.107 (0.041, 0.172)</td></tr>
    <tr><th id="stub_1_5" scope="row" class="gt_row gt_center gt_stub">60-69</th>
<td headers="stub_1_5 Biden" class="gt_row gt_right">0.179 (0.16, 0.199)</td>
<td headers="stub_1_5 Trump" class="gt_row gt_right">0.192 (0.172, 0.213)</td>
<td headers="stub_1_5 Other" class="gt_row gt_right">0.102 (0.025, 0.178)</td></tr>
    <tr><th id="stub_1_6" scope="row" class="gt_row gt_center gt_stub">70 or older</th>
<td headers="stub_1_6 Biden" class="gt_row gt_right">0.13 (0.118, 0.143)</td>
<td headers="stub_1_6 Trump" class="gt_row gt_right">0.156 (0.139, 0.174)</td>
<td headers="stub_1_6 Other" class="gt_row gt_right">0.049 (0, 0.098)</td></tr>
  </tbody>
  
  
</table>
</div>
<p>We can see that the age group distribution was younger for Biden and other candidates and older for Trump. For example, of those who voted for Biden, 20.4% were in the 18-29 age group, compared to only 11.4% of those who voted for Trump were in that age group. On the other side, 23.4% of those who voted for Trump were in the 50-59 age group compared to only 15.4% of those who voted for Biden.</p>
</div>
</div>
</div>
<div id="stattest-exercises" class="section level2 hasAnchor" number="6.5">
<h2><span class="header-section-number">6.5</span> Exercises<a href="c06-statistical-testing.html#stattest-exercises" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The exercises use the design objects <code>anes_des</code> and <code>recs_des</code> as provided in the Prerequisites box in the beginning of the chapter. Here are some exercises for practicing conducting t-tests using <code>svyttest()</code>:</p>
<ol style="list-style-type: decimal">
<li>Using the RECS data, do more than 50% of U.S. households use AC (<code>ACUsed</code>)?</li>
</ol>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="c06-statistical-testing.html#cb300-1" aria-hidden="true" tabindex="-1"></a>ttest_solution1 <span class="ot">&lt;-</span> recs_des <span class="sc">%&gt;%</span></span>
<span id="cb300-2"><a href="c06-statistical-testing.html#cb300-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyttest</span>(<span class="at">design =</span> .,</span>
<span id="cb300-3"><a href="c06-statistical-testing.html#cb300-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">formula =</span> ((ACUsed <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">-</span> <span class="fl">0.5</span>) <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb300-4"><a href="c06-statistical-testing.html#cb300-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb300-5"><a href="c06-statistical-testing.html#cb300-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb300-6"><a href="c06-statistical-testing.html#cb300-6" aria-hidden="true" tabindex="-1"></a>ttest_solution1</span></code></pre></div>
<pre><code>## 
##  Design-based one-sample t-test
## 
## data:  ((ACUsed == TRUE) - 0.5) ~ 0
## t = 45, df = 94, p-value &lt;2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  0.3533 0.3861
## sample estimates:
##   mean 
## 0.3697</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Using the RECS data, does the average temperature that U.S. households set their thermostats to differ between the day and night in the winter (<code>WinterTempDay</code> and <code>WinterTempNight</code>)?</li>
</ol>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="c06-statistical-testing.html#cb302-1" aria-hidden="true" tabindex="-1"></a>ttest_solution2 <span class="ot">&lt;-</span> recs_des <span class="sc">%&gt;%</span></span>
<span id="cb302-2"><a href="c06-statistical-testing.html#cb302-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyttest</span>(</span>
<span id="cb302-3"><a href="c06-statistical-testing.html#cb302-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb302-4"><a href="c06-statistical-testing.html#cb302-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> WinterTempDay <span class="sc">-</span> WinterTempNight <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb302-5"><a href="c06-statistical-testing.html#cb302-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb302-6"><a href="c06-statistical-testing.html#cb302-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb302-7"><a href="c06-statistical-testing.html#cb302-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb302-8"><a href="c06-statistical-testing.html#cb302-8" aria-hidden="true" tabindex="-1"></a>ttest_solution2</span></code></pre></div>
<pre><code>## 
##  Design-based one-sample t-test
## 
## data:  WinterTempDay - WinterTempNight ~ 0
## t = 31, df = 94, p-value &lt;2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  1.787 2.028
## sample estimates:
##  mean 
## 1.907</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Using the ANES data, does the average age (<code>Age</code>) of those who voted for Biden in 2020 (<code>VotedPres2020_selection</code>) differ from those who voted for another candidate?</li>
</ol>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="c06-statistical-testing.html#cb304-1" aria-hidden="true" tabindex="-1"></a>ttest_solution3 <span class="ot">&lt;-</span> anes_des <span class="sc">%&gt;%</span></span>
<span id="cb304-2"><a href="c06-statistical-testing.html#cb304-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyttest</span>(</span>
<span id="cb304-3"><a href="c06-statistical-testing.html#cb304-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb304-4"><a href="c06-statistical-testing.html#cb304-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> Age <span class="sc">~</span> VotedPres2020_selection <span class="sc">==</span> <span class="st">&quot;Biden&quot;</span>,</span>
<span id="cb304-5"><a href="c06-statistical-testing.html#cb304-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb304-6"><a href="c06-statistical-testing.html#cb304-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb304-7"><a href="c06-statistical-testing.html#cb304-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb304-8"><a href="c06-statistical-testing.html#cb304-8" aria-hidden="true" tabindex="-1"></a>ttest_solution3</span></code></pre></div>
<pre><code>## 
##  Design-based t-test
## 
## data:  Age ~ VotedPres2020_selection == &quot;Biden&quot;
## t = -6, df = 50, p-value = 2e-07
## alternative hypothesis: true difference in mean is not equal to 0
## 95 percent confidence interval:
##  -4.824 -2.395
## sample estimates:
## difference in mean 
##              -3.61</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>If you wanted to determine if the political party affiliation differed for males and females, what test would you use?</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>Goodness of fit test (<code>svygofchisq()</code>)</li>
<li>Test of independence (<code>svychisq()</code>)</li>
<li>Test of homogeneity (<code>svychisq()</code>)</li>
</ol>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="c06-statistical-testing.html#cb306-1" aria-hidden="true" tabindex="-1"></a>chisq_solution1 <span class="ot">&lt;-</span> <span class="st">&quot;c. Test of homogeneity (`svychisq()`)&quot;</span></span>
<span id="cb306-2"><a href="c06-statistical-testing.html#cb306-2" aria-hidden="true" tabindex="-1"></a>chisq_solution1</span></code></pre></div>
<pre><code>## [1] &quot;c. Test of homogeneity (`svychisq()`)&quot;</code></pre>
<ol start="5" style="list-style-type: decimal">
<li>In the RECS data, is there a relationship between the type of housing unit (<code>HousingUnitType</code>) and the year the house was built (<code>YearMade</code>)?</li>
</ol>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="c06-statistical-testing.html#cb308-1" aria-hidden="true" tabindex="-1"></a>chisq_solution2 <span class="ot">&lt;-</span> recs_des <span class="sc">%&gt;%</span></span>
<span id="cb308-2"><a href="c06-statistical-testing.html#cb308-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svychisq</span>(</span>
<span id="cb308-3"><a href="c06-statistical-testing.html#cb308-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span>  <span class="sc">~</span> HousingUnitType <span class="sc">+</span> YearMade,</span>
<span id="cb308-4"><a href="c06-statistical-testing.html#cb308-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb308-5"><a href="c06-statistical-testing.html#cb308-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="st">&quot;Wald&quot;</span>,</span>
<span id="cb308-6"><a href="c06-statistical-testing.html#cb308-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb308-7"><a href="c06-statistical-testing.html#cb308-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb308-8"><a href="c06-statistical-testing.html#cb308-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb308-9"><a href="c06-statistical-testing.html#cb308-9" aria-hidden="true" tabindex="-1"></a>chisq_solution2</span></code></pre></div>
<pre><code>## 
##  Design-based Wald test of association
## 
## data:  NextMethod()
## F = 32, ndf = 28, ddf = 95, p-value &lt;2e-16</code></pre>
<ol start="6" style="list-style-type: decimal">
<li>In the ANES data, is there a difference in the distribution of gender (<code>Gender</code>) across early voting status in 2020 (<code>EarlyVote2020</code>)?</li>
</ol>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="c06-statistical-testing.html#cb310-1" aria-hidden="true" tabindex="-1"></a>chisq_solution3 <span class="ot">&lt;-</span> anes_des <span class="sc">%&gt;%</span></span>
<span id="cb310-2"><a href="c06-statistical-testing.html#cb310-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svychisq</span>(</span>
<span id="cb310-3"><a href="c06-statistical-testing.html#cb310-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span>  <span class="sc">~</span> Gender <span class="sc">+</span> EarlyVote2020,</span>
<span id="cb310-4"><a href="c06-statistical-testing.html#cb310-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb310-5"><a href="c06-statistical-testing.html#cb310-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="st">&quot;F&quot;</span>,</span>
<span id="cb310-6"><a href="c06-statistical-testing.html#cb310-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb310-7"><a href="c06-statistical-testing.html#cb310-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb310-8"><a href="c06-statistical-testing.html#cb310-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb310-9"><a href="c06-statistical-testing.html#cb310-9" aria-hidden="true" tabindex="-1"></a>chisq_solution3</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s X^2: Rao &amp; Scott adjustment
## 
## data:  NextMethod()
## F = 0.27, ndf = 1, ddf = 51, p-value = 0.6</code></pre>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-lumley2010complex" class="csl-entry">
Lumley, Thomas. 2010. <em>Complex Surveys: A Guide to Analysis Using r: A Guide to Analysis Using r</em>. John Wiley; Sons.
</div>
<div id="ref-Scott2007" class="csl-entry">
Scott, Alastair. 2007. <em>Rao-Scott Corrections and Their Impact</em>. Section on Survey Research Methods. <a href="http://www.asasrms.org/Proceedings/y2007/Files/JSM2007-000874.pdf" class="uri">http://www.asasrms.org/Proceedings/y2007/Files/JSM2007-000874.pdf</a>; ASA.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="20">
<li id="fn20"><p>During the summer, what is your home’s typical indoor temperature inside your home at night?<a href="c06-statistical-testing.html#fnref20" class="footnote-back">↩︎</a></p></li>
<li id="fn21"><p>This question is not about the primary elections and caucuses that were held a few months ago. Instead, we’d like to ask you about the election for President to be held on November 3, in which (Donald Trump / Joe Biden) is running against (Joe Biden / Donald Trump). Have you already voted in that election, or have you not voted?<a href="c06-statistical-testing.html#fnref21" class="footnote-back">↩︎</a></p></li>
<li id="fn22"><p>Is any air conditioning equipment used in your home?<a href="c06-statistical-testing.html#fnref22" class="footnote-back">↩︎</a></p></li>
<li id="fn23"><p>During the summer, what is your home’s typical indoor temperature inside your home at night?<a href="c06-statistical-testing.html#fnref23" class="footnote-back">↩︎</a></p></li>
<li id="fn24"><p>During the winter, what is your home’s typical indoor temperature inside your home at night?<a href="c06-statistical-testing.html#fnref24" class="footnote-back">↩︎</a></p></li>
<li id="fn25"><p>These two statistics can also be used for goodness of fit tests if the <code>svygofchisq()</code> function is not used.<a href="c06-statistical-testing.html#fnref25" class="footnote-back">↩︎</a></p></li>
<li id="fn26"><p>What is the highest level of school you have completed or the highest degree you have received?<a href="c06-statistical-testing.html#fnref26" class="footnote-back">↩︎</a></p></li>
<li id="fn27"><p>Data was pulled from data.census.gov using the S1501 Education Attainment 2020: ACS 5-Year Estimates Subject Tables<a href="c06-statistical-testing.html#fnref27" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="c05-descriptive-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="c07-modeling.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/06-statistical-testing.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
