<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Descriptive analyses in srvyr | Tidy Survey Book</title>
  <meta name="description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Descriptive analyses in srvyr | Tidy Survey Book" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  <meta name="github-repo" content="tidy-survey-r/tidy-survey-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Descriptive analyses in srvyr | Tidy Survey Book" />
  
  <meta name="twitter:description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  

<meta name="author" content="Stephanie Zimmer, Rebecca J. Powell, and Isabella Velásquez" />


<meta name="date" content="2023-06-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="c05.html"/>
<link rel="next" href="c07.html"/>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#why-read-this-book"><i class="fa fa-check"></i>Why read this book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#structure-of-the-book"><i class="fa fa-check"></i>Structure of the book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-information-and-conventions"><i class="fa fa-check"></i>Software information and conventions</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="c01.html"><a href="c01.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="c02.html"><a href="c02.html"><i class="fa fa-check"></i><b>2</b> Overview of Surveys</a>
<ul>
<li class="chapter" data-level="2.1" data-path="c02.html"><a href="c02.html#overview-design"><i class="fa fa-check"></i><b>2.1</b> Study Design</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="c02.html"><a href="c02.html#overview-design-sampdesign"><i class="fa fa-check"></i><b>2.1.1</b> Sampling Design</a></li>
<li class="chapter" data-level="2.1.2" data-path="c02.html"><a href="c02.html#overview-design-dcplanning"><i class="fa fa-check"></i><b>2.1.2</b> Data Collection Planning</a></li>
<li class="chapter" data-level="2.1.3" data-path="c02.html"><a href="c02.html#overview-design-questionnaire"><i class="fa fa-check"></i><b>2.1.3</b> Questionnaire Design</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="c02.html"><a href="c02.html#overview-datacollection"><i class="fa fa-check"></i><b>2.2</b> Data Collection</a></li>
<li class="chapter" data-level="2.3" data-path="c02.html"><a href="c02.html#overview-post"><i class="fa fa-check"></i><b>2.3</b> Post Survey Processing</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="c02.html"><a href="c02.html#overview-post-cleaning"><i class="fa fa-check"></i><b>2.3.1</b> Data Cleaning and Imputation</a></li>
<li class="chapter" data-level="2.3.2" data-path="c02.html"><a href="c02.html#overview-post-weighting"><i class="fa fa-check"></i><b>2.3.2</b> Weighting</a></li>
<li class="chapter" data-level="2.3.3" data-path="c02.html"><a href="c02.html#overview-post-disclosure"><i class="fa fa-check"></i><b>2.3.3</b> Disclosure</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="c02.html"><a href="c02.html#this-book"><i class="fa fa-check"></i><b>2.4</b> This book</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="understanding-survey-data-documentation.html"><a href="understanding-survey-data-documentation.html"><i class="fa fa-check"></i><b>3</b> Understanding survey data documentation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="understanding-survey-data-documentation.html"><a href="understanding-survey-data-documentation.html#types-of-survey-documentation"><i class="fa fa-check"></i><b>3.1</b> Types of survey documentation</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="understanding-survey-data-documentation.html"><a href="understanding-survey-data-documentation.html#technical-documentation"><i class="fa fa-check"></i><b>3.1.1</b> Technical documentation</a></li>
<li class="chapter" data-level="3.1.2" data-path="understanding-survey-data-documentation.html"><a href="understanding-survey-data-documentation.html#questionnaires"><i class="fa fa-check"></i><b>3.1.2</b> Questionnaires</a></li>
<li class="chapter" data-level="3.1.3" data-path="understanding-survey-data-documentation.html"><a href="understanding-survey-data-documentation.html#codebooks"><i class="fa fa-check"></i><b>3.1.3</b> Codebooks</a></li>
<li class="chapter" data-level="3.1.4" data-path="understanding-survey-data-documentation.html"><a href="understanding-survey-data-documentation.html#errata"><i class="fa fa-check"></i><b>3.1.4</b> Errata</a></li>
<li class="chapter" data-level="3.1.5" data-path="understanding-survey-data-documentation.html"><a href="understanding-survey-data-documentation.html#additional-resources"><i class="fa fa-check"></i><b>3.1.5</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="understanding-survey-data-documentation.html"><a href="understanding-survey-data-documentation.html#working-with-missing-data"><i class="fa fa-check"></i><b>3.2</b> Working with missing data</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="understanding-survey-data-documentation.html"><a href="understanding-survey-data-documentation.html#accounting-for-questionnaire-skip-patterns"><i class="fa fa-check"></i><b>3.2.1</b> Accounting for questionnaire skip patterns</a></li>
<li class="chapter" data-level="3.2.2" data-path="understanding-survey-data-documentation.html"><a href="understanding-survey-data-documentation.html#accounting-for-mcar-mar-and-mnar-missingness"><i class="fa fa-check"></i><b>3.2.2</b> Accounting for MCAR, MAR, and MNAR missingness</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="understanding-survey-data-documentation.html"><a href="understanding-survey-data-documentation.html#example-american-national-election-studies-anes-2020-survey-documentation"><i class="fa fa-check"></i><b>3.3</b> Example: American National Election Studies (ANES) 2020 survey documentation</a></li>
<li class="chapter" data-level="3.4" data-path="understanding-survey-data-documentation.html"><a href="understanding-survey-data-documentation.html#searching-for-public-use-survey-data"><i class="fa fa-check"></i><b>3.4</b> Searching for public-use survey data</a></li>
<li class="chapter" data-level="3.5" data-path="understanding-survey-data-documentation.html"><a href="understanding-survey-data-documentation.html#exercises"><i class="fa fa-check"></i><b>3.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="c04.html"><a href="c04.html"><i class="fa fa-check"></i><b>4</b> Introducing the srvyr package</a></li>
<li class="chapter" data-level="5" data-path="c05.html"><a href="c05.html"><i class="fa fa-check"></i><b>5</b> Specifying sample designs and replicate weights in srvyr</a>
<ul>
<li class="chapter" data-level="5.1" data-path="c05.html"><a href="c05.html#common-sampling-designs"><i class="fa fa-check"></i><b>5.1</b> Common sampling designs</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="c05.html"><a href="c05.html#simple-random-sample-without-replacement"><i class="fa fa-check"></i><b>5.1.1</b> Simple random sample without replacement</a></li>
<li class="chapter" data-level="5.1.2" data-path="c05.html"><a href="c05.html#simple-random-sample-with-replacement"><i class="fa fa-check"></i><b>5.1.2</b> Simple random sample with replacement</a></li>
<li class="chapter" data-level="5.1.3" data-path="c05.html"><a href="c05.html#stratified-sampling"><i class="fa fa-check"></i><b>5.1.3</b> Stratified sampling</a></li>
<li class="chapter" data-level="5.1.4" data-path="c05.html"><a href="c05.html#clustered-sampling"><i class="fa fa-check"></i><b>5.1.4</b> Clustered sampling</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="c05.html"><a href="c05.html#replicate-weights"><i class="fa fa-check"></i><b>5.2</b> Replicate weights</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="c05.html"><a href="c05.html#brr-method"><i class="fa fa-check"></i><b>5.2.1</b> BRR method</a></li>
<li class="chapter" data-level="5.2.2" data-path="c05.html"><a href="c05.html#fays-brr-method"><i class="fa fa-check"></i><b>5.2.2</b> Fay’s BRR Method</a></li>
<li class="chapter" data-level="5.2.3" data-path="c05.html"><a href="c05.html#jackknife-method"><i class="fa fa-check"></i><b>5.2.3</b> Jackknife method</a></li>
<li class="chapter" data-level="5.2.4" data-path="c05.html"><a href="c05.html#bootstrap-method"><i class="fa fa-check"></i><b>5.2.4</b> Bootstrap method</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="c05.html"><a href="c05.html#und-surv-doc"><i class="fa fa-check"></i><b>5.3</b> Understanding survey design documentation</a></li>
<li class="chapter" data-level="5.4" data-path="c05.html"><a href="c05.html#exercises-1"><i class="fa fa-check"></i><b>5.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="c06.html"><a href="c06.html"><i class="fa fa-check"></i><b>6</b> Descriptive analyses in srvyr</a>
<ul>
<li class="chapter" data-level="6.1" data-path="c06.html"><a href="c06.html#types-of-descriptive-analyses"><i class="fa fa-check"></i><b>6.1</b> Types of descriptive analyses</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="c06.html"><a href="c06.html#univariate-analysis"><i class="fa fa-check"></i><b>6.1.1</b> Univariate analysis</a></li>
<li class="chapter" data-level="6.1.2" data-path="c06.html"><a href="c06.html#bivariatemultivariate-analysis"><i class="fa fa-check"></i><b>6.1.2</b> Bivariate/multivariate analysis</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="c06.html"><a href="c06.html#deciding-on-descriptive-analyses"><i class="fa fa-check"></i><b>6.2</b> Deciding on descriptive analyses</a></li>
<li class="chapter" data-level="6.3" data-path="c06.html"><a href="c06.html#descriptive-analysis-using-the-srvyr-package"><i class="fa fa-check"></i><b>6.3</b> Descriptive analysis using the {srvyr} package</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="c06.html"><a href="c06.html#setup"><i class="fa fa-check"></i><b>6.3.1</b> Setup</a></li>
<li class="chapter" data-level="6.3.2" data-path="c06.html"><a href="c06.html#count-observations-using-survey-methods-with-survey_count"><i class="fa fa-check"></i><b>6.3.2</b> Count observations using survey methods with <code>survey_count()</code></a></li>
<li class="chapter" data-level="6.3.3" data-path="c06.html"><a href="c06.html#calculate-total-sums-using-survey-methods-using-survey_total"><i class="fa fa-check"></i><b>6.3.3</b> Calculate total sums using survey methods using <code>survey_total()</code></a></li>
<li class="chapter" data-level="6.3.4" data-path="c06.html"><a href="c06.html#calculate-meanproportion-using-survey-methods-with-survey_mean-and-survey_prop"><i class="fa fa-check"></i><b>6.3.4</b> Calculate mean/proportion using survey methods with <code>survey_mean()</code> and <code>survey_prop()</code></a></li>
<li class="chapter" data-level="6.3.5" data-path="c06.html"><a href="c06.html#the-proportion-argument"><i class="fa fa-check"></i><b>6.3.5</b> The <code>proportion</code> argument</a></li>
<li class="chapter" data-level="6.3.6" data-path="c06.html"><a href="c06.html#print-total-overall-numbers-in-our-output"><i class="fa fa-check"></i><b>6.3.6</b> Print total overall numbers in our output</a></li>
<li class="chapter" data-level="6.3.7" data-path="c06.html"><a href="c06.html#removing-na-for-calculating-results"><i class="fa fa-check"></i><b>6.3.7</b> Removing <code>NA</code> for calculating results</a></li>
<li class="chapter" data-level="6.3.8" data-path="c06.html"><a href="c06.html#calculate-proportions-with-confidence-intervals"><i class="fa fa-check"></i><b>6.3.8</b> Calculate proportions with confidence intervals</a></li>
<li class="chapter" data-level="6.3.9" data-path="c06.html"><a href="c06.html#other-functions-that-use-survey-methods"><i class="fa fa-check"></i><b>6.3.9</b> Other functions that use survey methods</a></li>
<li class="chapter" data-level="6.3.10" data-path="c06.html"><a href="c06.html#calculate-conditional-proportions-with-more-than-one-group"><i class="fa fa-check"></i><b>6.3.10</b> Calculate conditional proportions with more than one group</a></li>
<li class="chapter" data-level="6.3.11" data-path="c06.html"><a href="c06.html#calculate-joint-proportions-with-more-than-one-group"><i class="fa fa-check"></i><b>6.3.11</b> Calculate joint proportions with more than one group</a></li>
<li class="chapter" data-level="6.3.12" data-path="c06.html"><a href="c06.html#calculate-proportions-with-design-effects"><i class="fa fa-check"></i><b>6.3.12</b> Calculate proportions with design effects</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="c06.html"><a href="c06.html#exercises-2"><i class="fa fa-check"></i><b>6.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="c07.html"><a href="c07.html"><i class="fa fa-check"></i><b>7</b> Statistical testing</a>
<ul>
<li class="chapter" data-level="7.1" data-path="c07.html"><a href="c07.html#stattest-setup"><i class="fa fa-check"></i><b>7.1</b> Chapter Set-Up</a></li>
<li class="chapter" data-level="7.2" data-path="c07.html"><a href="c07.html#stattest-ttest"><i class="fa fa-check"></i><b>7.2</b> Comparison of Proportions and Means</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="c07.html"><a href="c07.html#stattest-ttest-syntax"><i class="fa fa-check"></i><b>7.2.1</b> Syntax</a></li>
<li class="chapter" data-level="7.2.2" data-path="c07.html"><a href="c07.html#stattest-ttest-examples"><i class="fa fa-check"></i><b>7.2.2</b> Examples</a></li>
<li class="chapter" data-level="7.2.3" data-path="c07.html"><a href="c07.html#stattest-ttest-exercises"><i class="fa fa-check"></i><b>7.2.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="c07.html"><a href="c07.html#stattest-chi"><i class="fa fa-check"></i><b>7.3</b> Chi-Square Tests</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="c07.html"><a href="c07.html#stattest-chi-syntax"><i class="fa fa-check"></i><b>7.3.1</b> Syntax</a></li>
<li class="chapter" data-level="7.3.2" data-path="c07.html"><a href="c07.html#stattest-chi-examples"><i class="fa fa-check"></i><b>7.3.2</b> Examples</a></li>
<li class="chapter" data-level="7.3.3" data-path="c07.html"><a href="c07.html#stattest-chi-exercises"><i class="fa fa-check"></i><b>7.3.3</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="c08.html"><a href="c08.html"><i class="fa fa-check"></i><b>8</b> Modeling</a>
<ul>
<li class="chapter" data-level="8.1" data-path="c08.html"><a href="c08.html#chapter-set-up"><i class="fa fa-check"></i><b>8.1</b> Chapter Set-Up</a></li>
<li class="chapter" data-level="8.2" data-path="c08.html"><a href="c08.html#linear-modeling"><i class="fa fa-check"></i><b>8.2</b> Linear modeling</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="c08.html"><a href="c08.html#anova"><i class="fa fa-check"></i><b>8.2.1</b> ANOVA</a></li>
<li class="chapter" data-level="8.2.2" data-path="c08.html"><a href="c08.html#linear-regression"><i class="fa fa-check"></i><b>8.2.2</b> Linear regression</a></li>
<li class="chapter" data-level="8.2.3" data-path="c08.html"><a href="c08.html#exercises-3"><i class="fa fa-check"></i><b>8.2.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="c08.html"><a href="c08.html#logistic-regression"><i class="fa fa-check"></i><b>8.3</b> Logistic regression</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="c08.html"><a href="c08.html#exercises-4"><i class="fa fa-check"></i><b>8.3.1</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="c09.html"><a href="c09.html"><i class="fa fa-check"></i><b>9</b> Presenting results</a></li>
<li class="chapter" data-level="10" data-path="c10-ncvs-vignette.html"><a href="c10-ncvs-vignette.html"><i class="fa fa-check"></i><b>10</b> National Crime Victimization Survey Vignette</a>
<ul>
<li class="chapter" data-level="10.1" data-path="c10-ncvs-vignette.html"><a href="c10-ncvs-vignette.html#data-structure"><i class="fa fa-check"></i><b>10.1</b> Data structure</a></li>
<li class="chapter" data-level="10.2" data-path="c10-ncvs-vignette.html"><a href="c10-ncvs-vignette.html#data-file-preparation"><i class="fa fa-check"></i><b>10.2</b> Data file preparation</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="c10-ncvs-vignette.html"><a href="c10-ncvs-vignette.html#preparing-files-for-estimation-of-victimization-rates"><i class="fa fa-check"></i><b>10.2.1</b> Preparing files for estimation of victimization rates</a></li>
<li class="chapter" data-level="10.2.2" data-path="c10-ncvs-vignette.html"><a href="c10-ncvs-vignette.html#derived-demographic-variables"><i class="fa fa-check"></i><b>10.2.2</b> Derived demographic variables</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="c10-ncvs-vignette.html"><a href="c10-ncvs-vignette.html#survey-design-objects"><i class="fa fa-check"></i><b>10.3</b> Survey design objects</a></li>
<li class="chapter" data-level="10.4" data-path="c10-ncvs-vignette.html"><a href="c10-ncvs-vignette.html#calculating-estimates"><i class="fa fa-check"></i><b>10.4</b> Calculating estimates</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="c10-ncvs-vignette.html"><a href="c10-ncvs-vignette.html#victimization-totals"><i class="fa fa-check"></i><b>10.4.1</b> Victimization totals</a></li>
<li class="chapter" data-level="10.4.2" data-path="c10-ncvs-vignette.html"><a href="c10-ncvs-vignette.html#victimization-proportions"><i class="fa fa-check"></i><b>10.4.2</b> Victimization proportions</a></li>
<li class="chapter" data-level="10.4.3" data-path="c10-ncvs-vignette.html"><a href="c10-ncvs-vignette.html#victimization-rates"><i class="fa fa-check"></i><b>10.4.3</b> Victimization rates</a></li>
<li class="chapter" data-level="10.4.4" data-path="c10-ncvs-vignette.html"><a href="c10-ncvs-vignette.html#prevalence-rates"><i class="fa fa-check"></i><b>10.4.4</b> Prevalence rates</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="c10-ncvs-vignette.html"><a href="c10-ncvs-vignette.html#exercises-5"><i class="fa fa-check"></i><b>10.5</b> Exercises</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="more-to-say.html"><a href="more-to-say.html"><i class="fa fa-check"></i><b>A</b> More to Say</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tidy Survey Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="c06" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Chapter 6</span> Descriptive analyses in srvyr<a href="c06.html#c06" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Descriptive analyses describes and summarizes the basic quantitative information of survey data. Common descriptive analyses include the frequency of observations, distributions of responses, or the mean of a numeric variable. These analyses present large amounts of quantitative data in an understandable way and form the basis of every survey analysis.</p>
<p>In addition to describing our data, we can use these analyses to compare across people or other units. Descriptive analyses help us identify potential errors and assess outliers. We gain crucial information for deciding on deeper analysis.</p>
<p>In complex survey analysis, we must consider the available design and sampling elements when conducting descriptive analysis. This requires reading the survey documentation (as described in Chapter <a href="c05.html#c05">5</a>) to apply the appropriate sampling weights, PSUs, strata, and replicate weights. Neglecting to incorporate these elements can lead to inaccurate descriptive analyses.</p>
<p>The functions in the {srvyr} package allow us to run descriptive analyses while applying design and sampling elements. We can run multiple calculations in the same command thanks to the ‘pipe-able’ functions. The package also provides consistent return types so we can use outputs with other packages like {ggplot2}.</p>
<p>This chapter describes the types of descriptive analytics and the steps involved in running descriptive analysis with {srvyr}.</p>
<!-- TODO: Put this in a callout box -->
<div id="similarities-between-dplyr-and-srvyr-functions" class="section level4 unnumbered hasAnchor">
<h4>Similarities between {dplyr} and {srvyr} functions<a href="c06.html#similarities-between-dplyr-and-srvyr-functions" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>One of the major advantages of using {srvyr} is that it applies {dplyr}-like syntax to the {survey} package. We can use pipes to specify a <code>tbl_svy</code> object, apply a function, and then take that output and feed it into the first argument of the next function. Functions follow the ‘tidy’ convention of snake_case functions names.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="c06.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example data manipulation using {srvyr} and pipes</span></span>
<span id="cb83-2"><a href="c06.html#cb83-2" aria-hidden="true" tabindex="-1"></a>dstrata <span class="sc">%&gt;%</span> <span class="co"># A `tbl_svy` object</span></span>
<span id="cb83-3"><a href="c06.html#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">api99_var =</span> <span class="fu">survey_var</span>(api00),</span>
<span id="cb83-4"><a href="c06.html#cb83-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">api99_sd =</span> <span class="fu">survey_sd</span>(api00))</span></code></pre></div>
<p>The functions in {srvyr} also play nicely with other tidyverse functions. If we wanted to create our survey object by selecting specific columns, we could use <code>dplyr::select()</code>’s special selection functions (such as <code>starts_with()</code>, <code>one_of()</code>, etc.).</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="c06.html#cb84-1" aria-hidden="true" tabindex="-1"></a>dstrata <span class="ot">&lt;-</span> dstrata <span class="sc">%&gt;%</span></span>
<span id="cb84-2"><a href="c06.html#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(</span>
<span id="cb84-3"><a href="c06.html#cb84-3" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span>,</span>
<span id="cb84-4"><a href="c06.html#cb84-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">strata =</span> stype,</span>
<span id="cb84-5"><a href="c06.html#cb84-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">fpc =</span> fpc,</span>
<span id="cb84-6"><a href="c06.html#cb84-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">weight =</span> pw,</span>
<span id="cb84-7"><a href="c06.html#cb84-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">variables =</span> <span class="fu">c</span>(stype, <span class="fu">starts_with</span>(<span class="st">&quot;api&quot;</span>))</span>
<span id="cb84-8"><a href="c06.html#cb84-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>We can use {dplyr} verbs such as <code>mutate()</code>, <code>filter()</code>, etc. on our survey object.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="c06.html#cb85-1" aria-hidden="true" tabindex="-1"></a>dstrata <span class="ot">&lt;-</span> dstrata <span class="sc">%&gt;%</span></span>
<span id="cb85-2"><a href="c06.html#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">api_diff =</span> api00 <span class="sc">-</span> api99) <span class="sc">%&gt;%</span></span>
<span id="cb85-3"><a href="c06.html#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">api_students =</span> api.stu)</span></code></pre></div>
<p>Instead of data frames or tibbles, {srvyr} functions are meant for <code>tbl_svy</code> objects. Attempting to run data manipulation on non-<code>tbl_svy</code> objects will result in an error:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="c06.html#cb86-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="co"># An object of the type &#39;list&#39;</span></span>
<span id="cb86-2"><a href="c06.html#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">survey_total</span>())</span></code></pre></div>
<pre><code>## Error in `summarize()`:
## ℹ In argument: `survey_total()`.
## Caused by error in `cur_svy()`:
## ! Survey context not set</code></pre>
<p>A few functions in {srvyr} parallel functions available in {dplyr}, such as <code>srvyr::summarize()</code> and <code>srvyr::group_by()</code>. Unlike {srvyr}-specific verbs, the package recognizes if you attempt to run these parallel functions on a non-survey object. It will not error and instead give you the equivalent output from {dplyr}:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="c06.html#cb88-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb88-2"><a href="c06.html#cb88-2" aria-hidden="true" tabindex="-1"></a>  srvyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">mean_hp =</span> <span class="fu">mean</span>(hp))</span></code></pre></div>
<pre><code>##   mean_hp
## 1   146.7</code></pre>
<p>Because this book focuses on survey analysis, most of our pipes will stem from a survey object. We will not be including the namespace for each function (e.g., <code>srvyr::summarize()</code>).</p>
<p>Several functions in {srvyr} must be called within <code>srvyr::summarize()</code>. Recall that <code>dplyr::summarize()</code> collapses many values down to a single summary:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="c06.html#cb90-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb90-2"><a href="c06.html#cb90-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">mean_hp =</span> <span class="fu">mean</span>(hp))</span></code></pre></div>
<pre><code>##   mean_hp
## 1   146.7</code></pre>
<p>These verbs can be used in conjunction with <code>group_by()</code> or <code>by/.by</code>, applying the functions on a group-by-group basis to create grouped summaries.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="c06.html#cb92-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span></span>
<span id="cb92-2"><a href="c06.html#cb92-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cyl) <span class="sc">%&gt;%</span></span>
<span id="cb92-3"><a href="c06.html#cb92-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">mean_hp =</span> <span class="fu">mean</span>(hp),</span>
<span id="cb92-4"><a href="c06.html#cb92-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 2
##     cyl mean_hp
##   &lt;dbl&gt;   &lt;dbl&gt;
## 1     4    82.6
## 2     6   122. 
## 3     8   209.</code></pre>
<p>We use a similar setup to summarize data in {srvyr}.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="c06.html#cb94-1" aria-hidden="true" tabindex="-1"></a>dstrata <span class="sc">%&gt;%</span></span>
<span id="cb94-2"><a href="c06.html#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(stype) <span class="sc">%&gt;%</span></span>
<span id="cb94-3"><a href="c06.html#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">api00_mean =</span> <span class="fu">survey_mean</span>(api00),</span>
<span id="cb94-4"><a href="c06.html#cb94-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">api00_median =</span> <span class="fu">survey_median</span>(api00))</span></code></pre></div>
<pre><code>## # A tibble: 3 × 5
##   stype api00_mean api00_mean_se api00_median api00_median_se
##   &lt;fct&gt;      &lt;dbl&gt;         &lt;dbl&gt;        &lt;dbl&gt;           &lt;dbl&gt;
## 1 E           674.          12.5          671            20.7
## 2 H           626.          15.5          635            21.6
## 3 M           637.          16.6          648            24.1</code></pre>
<p>Throughout the chapter, we’ll note when a {srvyr} function must be included within <code>summarize()</code>.</p>
<!--TODO: end callout note-->
</div>
<div id="types-of-descriptive-analyses" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Types of descriptive analyses<a href="c06.html#types-of-descriptive-analyses" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Descriptive analysis can be categorized into univariate and multivariate analysis, depending on the number of variables we include. Below, we describe the descriptive analysis for single or multiple variables and a description of the {srvyr} functions associated with the measures. In the next section, we will explain each of the functions in-depth.</p>
<div id="univariate-analysis" class="section level3 hasAnchor" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Univariate analysis<a href="c06.html#univariate-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Univariate analysis examines a single variable at a time. A single variable has three categories of characteristics: distribution, central tendency, and dispersion. Each characteristic simplifies our dataset. Therefore, it is important to look at multiple characteristics rather than rely on a single one to describe the data.</p>
<div id="measures-of-distribution" class="section level4 unnumbered hasAnchor">
<h4>Measures of distribution<a href="c06.html#measures-of-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Measures of distribution describe how often an event or response occurs. These measures include proportions and quantiles.</p>
<ul>
<li>Examples: the proportion of students in California who did or did not receive an award based on their Academic Performance score; the proportion of U.S. citizens who voted in the last election; the distribution of household income in India divided into quantiles</li>
</ul>
<p>The {srvyr} package includes several functions for determining measures of distribution.</p>
<ul>
<li>The <code>survey_total()</code> function calculates totals</li>
<li>The <code>survey_count()</code> and <code>survey_tally()</code> functions calculate weighted observations by group</li>
<li>The <code>survey_prop()</code> function calculates proportions</li>
<li>The <code>survey_quantile()</code> function calculates quantiles</li>
<li>The <code>survey_ratio()</code> function calculates ratios</li>
</ul>
</div>
<div id="measures-of-central-tendency" class="section level4 unnumbered hasAnchor">
<h4>Measures of central tendency<a href="c06.html#measures-of-central-tendency" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Measures of central tendency find the central (or average) responses. These include the mean, median, and mode.</p>
<ul>
<li>Examples: Average 2000 Academic Performance Index in California, the median house price in Canada</li>
</ul>
<p>The <code>survey_mean()</code> and <code>survey_median()</code> functions from {srvyr} calculate mean and median using survey data, respectively. These functions must be called from within <code>summarize()</code>.</p>
</div>
<div id="measures-of-dispersion" class="section level4 unnumbered hasAnchor">
<h4>Measures of dispersion<a href="c06.html#measures-of-dispersion" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Measures of dispersion describe how data spreads around the central tendency. These measures include the range and standard deviation.</p>
<ul>
<li>Examples: The standard deviation of the 2000 Academic Performance Index in California, the range between the minimum and maximum electricity expenditure in Ohio</li>
</ul>
<p>The <code>survey_var()</code> and <code>survey_sd()</code> functions from the {srvyr} package calculate population variance and standard deviation using survey methods, respectively.</p>
</div>
</div>
<div id="bivariatemultivariate-analysis" class="section level3 hasAnchor" number="6.1.2">
<h3><span class="header-section-number">6.1.2</span> Bivariate/multivariate analysis<a href="c06.html#bivariatemultivariate-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Bivariate analysis concerns the relationship between two variables. Multivariate analysis studies the relationship between multiple variables. A common analysis includes correlation, which is a number between -1 and +1 that denotes the strength of the linear relationship between two variables.</p>
<ul>
<li>Examples: Relationship between academic performance scores in 1999 and 2000; relationship between age and income</li>
</ul>
<p>We can use the {srvyr} package’s <code>survey_corr()</code> function to calculate correlation and its variation using survey methods.</p>
</div>
</div>
<div id="deciding-on-descriptive-analyses" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Deciding on descriptive analyses<a href="c06.html#deciding-on-descriptive-analyses" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We select measures based on the type of variable we are analyzing. Variables are classified as categorical/nominal, ordinal, and interval/ratio.</p>
<ul>
<li>Categorical/nominal data: variables with levels or descriptions that cannot be ordered, such as region of the country (North, South, East, and West)</li>
<li>Ordinal data: variables that can be ordered, such as those from a Likert scale (strongly disagree, disagree, agree, and strongly agree)</li>
<li>Interval/ratio: variables that are counted or measured, such as the total cost of electricity
<ul>
<li>Within interval/ratio data are <em>discrete</em> variables, whose values are whole numbers, such as number of children, and <em>continuous</em> variables, whose values can lie anywhere on an interval, such as weight.</li>
</ul></li>
</ul>
<p>If our variable is categorical, such as gender or occupation, we might use frequency counts or percentages, while if the variable is continuous, such as income or age, we might use mean, median, or standard deviation.</p>
<p>Choosing appropriate measures is important to reach valid conclusions. Different variable types have distinct properties and levels of measurement, and we cannot apply all measures to all variables.</p>
<p>Our survey data may represent categorical variables using numeric codes. For example, the North, South, East, and West regions of the United States might be coded as 1, 2, 3, and 4, respectively. Though this is a categorical variable, this variable might be automatically read as numeric values when we import our data. This can lead to the common mistake of applying <code>survey_mean()</code> to all numeric columns in the dataset, including categorical values.</p>
<p>This practice can lead to incorrect inferences because categorical variables lack a natural zero point or linear ordering, making measures like mean inappropriate. Instead, it is crucial to inspect the codebook, understand the type of variable, and choose appropriate measures such as frequency counts or percentages to describe the data across regions.</p>
</div>
<div id="descriptive-analysis-using-the-srvyr-package" class="section level2 hasAnchor" number="6.3">
<h2><span class="header-section-number">6.3</span> Descriptive analysis using the {srvyr} package<a href="c06.html#descriptive-analysis-using-the-srvyr-package" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="setup" class="section level3 hasAnchor" number="6.3.1">
<h3><span class="header-section-number">6.3.1</span> Setup<a href="c06.html#setup" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall from <a href="c05.html#c05">Chapter 05</a> the general process for estimation with the {srvyr} package:</p>
<ol style="list-style-type: decimal">
<li>Create a <code>tbl_svy</code> object using <code>srvyr::as_survey_design()</code> or <code>srvyr::as_survey_rep()</code>.</li>
<li>Subset the data for subpopulations using <code>dplyr::filter()</code>, if needed.</li>
<li>Specify domains of analysis using <code>dplyr::group_by()</code>, if needed.</li>
<li>Within <code>srvyr::summarize()</code>, specify variables to calculate ,means, totals, proportions, quantiles, and more.</li>
</ol>
<p>Filtering should be done after creating the <code>tbl_svy</code> object using <code>srvyr::as_survey_design()</code> or <code>srvyr::as_survey_rep()</code> because these functions incorporate the survey design information into the resulting object.</p>
<!-- TODO: edit this depending on how much we've talked about it in earlier chapters-->
<p>The Residential Energy Consumption Survey (RECS) provides data on energy consumption and expenditures. It is funded by Energy Information Administration and collects information through energy suppliers through in-person, phone, and web interviews. It has been fielded 14 times between 1950 and 2020. Topics include appliances, electronics, heating, air conditioning (A/C), temperatures, water heating, lighting, energy bills, respondent demographics, and energy assistance.</p>
<p>The survey targets primary occupied housing units in the US. RECS uses Balanced Repeated Replication (BRR) to estimate the variances. The full sample information is available on the <a href="https://www.eia.gov/consumption/residential/index.php">EIA website</a>.</p>
<p>To begin analyzing RECS, we create a <code>tbl_svy</code> object using <code>srvyr::as_survey_design()</code>:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="c06.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey) <span class="co"># for survey analysis</span></span>
<span id="cb96-2"><a href="c06.html#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(srvyr) <span class="co"># for tidy survey analysis</span></span>
<span id="cb96-3"><a href="c06.html#cb96-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb96-4"><a href="c06.html#cb96-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(osfr)</span>
<span id="cb96-5"><a href="c06.html#cb96-5" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;helper-fun/helper-functions.R&quot;</span>)</span>
<span id="cb96-6"><a href="c06.html#cb96-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-7"><a href="c06.html#cb96-7" aria-hidden="true" tabindex="-1"></a>recs <span class="ot">&lt;-</span></span>
<span id="cb96-8"><a href="c06.html#cb96-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_rds_tsr</span>(<span class="st">&quot;recs_2015.rds&quot;</span>)</span>
<span id="cb96-9"><a href="c06.html#cb96-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-10"><a href="c06.html#cb96-10" aria-hidden="true" tabindex="-1"></a>recs_des <span class="ot">&lt;-</span> recs <span class="sc">%&gt;%</span></span>
<span id="cb96-11"><a href="c06.html#cb96-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(</span>
<span id="cb96-12"><a href="c06.html#cb96-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> NWEIGHT,</span>
<span id="cb96-13"><a href="c06.html#cb96-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">repweights =</span> <span class="fu">starts_with</span>(<span class="st">&quot;BRRWT&quot;</span>),</span>
<span id="cb96-14"><a href="c06.html#cb96-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">&quot;Fay&quot;</span>,</span>
<span id="cb96-15"><a href="c06.html#cb96-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">rho =</span> <span class="fl">0.5</span>,</span>
<span id="cb96-16"><a href="c06.html#cb96-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">mse =</span> <span class="cn">TRUE</span></span>
<span id="cb96-17"><a href="c06.html#cb96-17" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<div id="count-observations-using-survey-methods-with-survey_count" class="section level3 hasAnchor" number="6.3.2">
<h3><span class="header-section-number">6.3.2</span> Count observations using survey methods with <code>survey_count()</code><a href="c06.html#count-observations-using-survey-methods-with-survey_count" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>With <code>srvyr::survey_count()</code>, we can calculate the number of observations or cases for a given variable or combination of variables. The syntax is very similar to the <code>dplyr::count()</code> syntax; however, as noted above, it can only be called on <code>tbl_srvy()</code> objects. Let’s explore the syntax:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="c06.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">survey_count</span>(</span>
<span id="cb97-2"><a href="c06.html#cb97-2" aria-hidden="true" tabindex="-1"></a>  x,</span>
<span id="cb97-3"><a href="c06.html#cb97-3" aria-hidden="true" tabindex="-1"></a>  ...,</span>
<span id="cb97-4"><a href="c06.html#cb97-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">wt =</span> <span class="cn">NULL</span>,</span>
<span id="cb97-5"><a href="c06.html#cb97-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sort =</span> <span class="cn">FALSE</span>,</span>
<span id="cb97-6"><a href="c06.html#cb97-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">name =</span> <span class="st">&quot;n&quot;</span>,</span>
<span id="cb97-7"><a href="c06.html#cb97-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">.drop =</span> dplyr<span class="sc">::</span><span class="fu">group_by_drop_default</span>(x),</span>
<span id="cb97-8"><a href="c06.html#cb97-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>, <span class="st">&quot;var&quot;</span>, <span class="st">&quot;cv&quot;</span>)</span>
<span id="cb97-9"><a href="c06.html#cb97-9" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>The arguments are:</p>
<ul>
<li><code>x</code>: a <code>tbl_svy</code> object created by <code>as_survey</code></li>
<li><code>...</code>: variables to group by, passed to <code>group_by</code></li>
<li><code>wt</code>: a variable to weight on in addition to the survey weights, defaults to <code>NULL</code></li>
<li><code>sort</code>: how to sort the variables, defaults to <code>FALSE</code></li>
<li><code>name</code>: the name of the count variable, defaults to <code>n</code></li>
<li><code>.drop</code>: whether to drop empty groups</li>
<li><code>vartype</code>: type(s) of variation estimate to calculate, defaults to <code>se</code> (standard error)</li>
</ul>
<p>The steps to use <code>survey_count()</code> are:</p>
<ul>
<li>Specify the sample design,</li>
<li>Filter subsets using <code>dplyr::filter()</code>, if needed,</li>
<li>Run <code>survey_count()</code>, specifying the required arguments within the function</li>
</ul>
<p>Let’s see the weighted count of responses in RECS:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="c06.html#cb98-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span> <span class="co">#  Specify the sample design</span></span>
<span id="cb98-2"><a href="c06.html#cb98-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">survey_count</span>() <span class="co"># Run `survey_count()`</span></span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##            n   n_se
##        &lt;dbl&gt;  &lt;dbl&gt;
## 1 118208250. 0.0320</code></pre>
<p>There are 118,208,250 observations in the survey.</p>
<p><code>srvyr::count()</code> can take one or many variables. To calculate the number of observations for a combination of variables, such as Region and Division, we run the below:</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="c06.html#cb100-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb100-2"><a href="c06.html#cb100-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Specify the required arguments within the function</span></span>
<span id="cb100-3"><a href="c06.html#cb100-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">survey_count</span>(Region, Division, <span class="at">name =</span> <span class="st">&quot;N&quot;</span>) </span></code></pre></div>
<pre><code>## # A tibble: 10 × 4
##    Region    Division                   N     N_se
##    &lt;fct&gt;     &lt;fct&gt;                  &lt;dbl&gt;    &lt;dbl&gt;
##  1 Northeast New England         5628844. 0.00642 
##  2 Northeast Middle Atlantic    15377694. 0.000130
##  3 Midwest   East North Central 18094391. 0.000274
##  4 Midwest   West North Central  8277344. 0.000113
##  5 South     South Atlantic     23474851. 0.00555 
##  6 South     East South Central  7197189. 0.0240  
##  7 South     West South Central 13769934. 0.000423
##  8 West      Mountain North      4246877. 0.000147
##  9 West      Mountain South      4266870. 0.0193  
## 10 West      Pacific            17874256. 0.000481</code></pre>
<p>When we run the crosstab, we see that there are 5,638,844 observations from the Northeast’s New England division, 15,377,694 from the Northeast’s Middle Atlantic division, and so on.</p>
</div>
<div id="calculate-total-sums-using-survey-methods-using-survey_total" class="section level3 hasAnchor" number="6.3.3">
<h3><span class="header-section-number">6.3.3</span> Calculate total sums using survey methods using <code>survey_total()</code><a href="c06.html#calculate-total-sums-using-survey-methods-using-survey_total" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>With <code>srvyr::survey_total()</code>, we can calculate the sum of numeric variable values. Let’s explore the syntax:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="c06.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">survey_total</span>(</span>
<span id="cb102-2"><a href="c06.html#cb102-2" aria-hidden="true" tabindex="-1"></a>  x,</span>
<span id="cb102-3"><a href="c06.html#cb102-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.rm =</span> <span class="cn">FALSE</span>,</span>
<span id="cb102-4"><a href="c06.html#cb102-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>, <span class="st">&quot;var&quot;</span>, <span class="st">&quot;cv&quot;</span>),</span>
<span id="cb102-5"><a href="c06.html#cb102-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">level =</span> <span class="fl">0.95</span>,</span>
<span id="cb102-6"><a href="c06.html#cb102-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">deff =</span> <span class="cn">FALSE</span>,</span>
<span id="cb102-7"><a href="c06.html#cb102-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">df =</span> <span class="cn">NULL</span>,</span>
<span id="cb102-8"><a href="c06.html#cb102-8" aria-hidden="true" tabindex="-1"></a>  ...</span>
<span id="cb102-9"><a href="c06.html#cb102-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<ul>
<li><code>x</code>: a variable, expression, or empty</li>
<li><code>na.rm</code>: an indicator of whether missing values should be dropped, defaults to <code>FALSE</code></li>
<li><code>vartype</code>: type(s) of variation estimate to calculate, defaults to <code>se</code> (standard error)</li>
<li><code>level</code>: a number or a vector indicating the confidence level, defaults to 0.95</li>
<li><code>deff</code>: a logical value stating whether the design effect should be returned, defaults to FALSE</li>
<li><code>df</code>: for <code>vartype = 'ci'</code>), a numeric value indicating degrees of freedom for the t-distribution
<ul>
<li>For the {srvyr} package, this defaults to <code>NULL</code> whereas the {survey} package defaults to <code>Inf</code></li>
</ul></li>
</ul>
<p>The steps to use <code>survey_total()</code> are:</p>
<ul>
<li>Specify the sample design,</li>
<li>Specify the cross tab in <code>group_by()</code>,</li>
<li>Within <code>summarize</code>, run <code>survey_total()</code>, specifying the required arguments within the function</li>
</ul>
<p>To calculate a population count estimate with <code>survey_total()</code>, we can run the below:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="c06.html#cb103-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb103-2"><a href="c06.html#cb103-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">survey_total</span>(),</span>
<span id="cb103-3"><a href="c06.html#cb103-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##         coef  `_se`
##        &lt;dbl&gt;  &lt;dbl&gt;
## 1 118208250. 0.0320</code></pre>
<p>Note that the result from <code>recs_des %&gt;% summarize(survey_total(), .groups = "drop")</code> is equivalent to the <code>survey_count()</code> call. However, the <code>survey_total()</code> function is called within <code>summarize</code>, where as <code>survey_count()</code>, like <code>dplyr::count()</code>, is not.</p>
<p>The differences between <code>survey_total()</code> and <code>survey_count()</code> is more evident when specifying numeric variables to sum. Let’s sum the total cost of electricity in whole dollars from variable <code>DOLLAREL</code>. We also calculate an unweighted estimate using <code>unweighted</code>.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="c06.html#cb105-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb105-2"><a href="c06.html#cb105-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb105-3"><a href="c06.html#cb105-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">elec_bill =</span> <span class="fu">survey_total</span>(DOLLAREL),</span>
<span id="cb105-4"><a href="c06.html#cb105-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">elec_unweight =</span> <span class="fu">unweighted</span>(<span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(DOLLAREL))),</span>
<span id="cb105-5"><a href="c06.html#cb105-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb105-6"><a href="c06.html#cb105-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##       elec_bill elec_bill_se elec_unweight
##           &lt;dbl&gt;        &lt;dbl&gt;         &lt;int&gt;
## 1 162495237023.  1666895091.          5686</code></pre>
<p>$162,495,237,023 was spent on electricity. The unweighted sum is $5686.</p>
<p>Since we are using the {srvyr} package, we can use <code>group_by()</code> to calculate the cost of electricity by different groups. Let’s see how much the cost of electricity in whole dollars differed between regions:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="c06.html#cb107-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb107-2"><a href="c06.html#cb107-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Region) <span class="sc">%&gt;%</span></span>
<span id="cb107-3"><a href="c06.html#cb107-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cascade</span>(<span class="at">elec_bill =</span> <span class="fu">survey_total</span>(<span class="sc">!</span><span class="fu">is.na</span>(DOLLAREL)))</span></code></pre></div>
<pre><code>## # A tibble: 5 × 3
##   Region     elec_bill elec_bill_se
##   &lt;fct&gt;          &lt;dbl&gt;        &lt;dbl&gt;
## 1 Northeast  21006538.     0.00644 
## 2 Midwest    26371735.     0.000251
## 3 South      44441974.     0.0252  
## 4 West       26388003.     0.0191  
## 5 &lt;NA&gt;      118208250.     0.0320</code></pre>
<p>The Northeast spent $28,271,369,286 on electricity, the Midwest spent $31,527,659,004, the South spent $72,463,508,778, and the West spent $30,232,699,955.</p>
</div>
<div id="calculate-meanproportion-using-survey-methods-with-survey_mean-and-survey_prop" class="section level3 hasAnchor" number="6.3.4">
<h3><span class="header-section-number">6.3.4</span> Calculate mean/proportion using survey methods with <code>survey_mean()</code> and <code>survey_prop()</code><a href="c06.html#calculate-meanproportion-using-survey-methods-with-survey_mean-and-survey_prop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <code>srvyr::survey_mean()</code> and <code>survey_prop()</code> functions calculate the means (of continuous variables) and proportions (of categorical variables) of survey data while accounting for complex survey design. Like <code>survey_total()</code>, they are called within <code>summarize()</code>. Let’s explore the syntax:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="c06.html#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">survey_mean</span>(</span>
<span id="cb109-2"><a href="c06.html#cb109-2" aria-hidden="true" tabindex="-1"></a>  x,</span>
<span id="cb109-3"><a href="c06.html#cb109-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.rm =</span> <span class="cn">FALSE</span>,</span>
<span id="cb109-4"><a href="c06.html#cb109-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>, <span class="st">&quot;var&quot;</span>, <span class="st">&quot;cv&quot;</span>),</span>
<span id="cb109-5"><a href="c06.html#cb109-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">level =</span> <span class="fl">0.95</span>,</span>
<span id="cb109-6"><a href="c06.html#cb109-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">proportion =</span> <span class="cn">FALSE</span>,</span>
<span id="cb109-7"><a href="c06.html#cb109-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">prop_method =</span> <span class="fu">c</span>(<span class="st">&quot;logit&quot;</span>, <span class="st">&quot;likelihood&quot;</span>, <span class="st">&quot;asin&quot;</span>, <span class="st">&quot;beta&quot;</span>, <span class="st">&quot;mean&quot;</span>),</span>
<span id="cb109-8"><a href="c06.html#cb109-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">deff =</span> <span class="cn">FALSE</span>,</span>
<span id="cb109-9"><a href="c06.html#cb109-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">df =</span> <span class="cn">NULL</span>,</span>
<span id="cb109-10"><a href="c06.html#cb109-10" aria-hidden="true" tabindex="-1"></a>  ...</span>
<span id="cb109-11"><a href="c06.html#cb109-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb109-12"><a href="c06.html#cb109-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-13"><a href="c06.html#cb109-13" aria-hidden="true" tabindex="-1"></a><span class="fu">survey_prop</span>(</span>
<span id="cb109-14"><a href="c06.html#cb109-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>, <span class="st">&quot;var&quot;</span>, <span class="st">&quot;cv&quot;</span>),</span>
<span id="cb109-15"><a href="c06.html#cb109-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">level =</span> <span class="fl">0.95</span>,</span>
<span id="cb109-16"><a href="c06.html#cb109-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">proportion =</span> <span class="cn">FALSE</span>,</span>
<span id="cb109-17"><a href="c06.html#cb109-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">prop_method =</span> <span class="fu">c</span>(<span class="st">&quot;logit&quot;</span>, <span class="st">&quot;likelihood&quot;</span>, <span class="st">&quot;asin&quot;</span>, <span class="st">&quot;beta&quot;</span>, <span class="st">&quot;mean&quot;</span>),</span>
<span id="cb109-18"><a href="c06.html#cb109-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">deff =</span> <span class="cn">FALSE</span>,</span>
<span id="cb109-19"><a href="c06.html#cb109-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">df =</span> <span class="cn">NULL</span>,</span>
<span id="cb109-20"><a href="c06.html#cb109-20" aria-hidden="true" tabindex="-1"></a>  ...</span>
<span id="cb109-21"><a href="c06.html#cb109-21" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>The steps involved are:</p>
<ul>
<li>Specify the sample design,</li>
<li>Specify the cross tab in <code>group_by()</code>,</li>
<li>Run <code>survey_mean()</code> or <code>survey_prop()</code> within <code>summarize()</code></li>
</ul>
<p>We can calculate the weighted average cost of electricity for each region in the U.S.:</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="c06.html#cb110-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb110-2"><a href="c06.html#cb110-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Region) <span class="sc">%&gt;%</span></span>
<span id="cb110-3"><a href="c06.html#cb110-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">elec_bill =</span> <span class="fu">survey_mean</span>(DOLLAREL),</span>
<span id="cb110-4"><a href="c06.html#cb110-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
##   Region    elec_bill elec_bill_se
##   &lt;fct&gt;         &lt;dbl&gt;        &lt;dbl&gt;
## 1 Northeast     1346.         34.2
## 2 Midwest       1196.         20.2
## 3 South         1631.         25.3
## 4 West          1146.         32.3</code></pre>
<p>On average, respondents from the Northeast spent $1346 on electricity. In the Midwest, they spent $1196, in the South they spent $1631, and finally, $1146 in the West.</p>
<p>We use <code>srvyr::survey_prop()</code> to estimate the proportion of categorical variables in a survey.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="c06.html#cb112-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb112-2"><a href="c06.html#cb112-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Region) <span class="sc">%&gt;%</span></span>
<span id="cb112-3"><a href="c06.html#cb112-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">survey_prop</span>(),</span>
<span id="cb112-4"><a href="c06.html#cb112-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span>)</span></code></pre></div>
<pre><code>## When `proportion` is unspecified, `survey_prop()` now defaults to `proportion = TRUE`.
## ℹ This should improve confidence interval coverage.
## This message is displayed once per session.</code></pre>
<pre><code>## # A tibble: 4 × 3
##   Region     coef    `_se`
##   &lt;fct&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 Northeast 0.178 6.84e-11
## 2 Midwest   0.223 6.07e-11
## 3 South     0.376 1.43e-10
## 4 West      0.223 1.37e-10</code></pre>
<p>17.8% of the observations are in the Northeast, 22.3% in the Midwest, and so on.</p>
<p><code>survey_prop()</code> is essentially the same as using <code>survey_mean()</code> with a categorical variable and without specifying a numeric variable in the <code>x</code> argument. The following code will give us the same results as above:</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="c06.html#cb115-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb115-2"><a href="c06.html#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Region) <span class="sc">%&gt;%</span></span>
<span id="cb115-3"><a href="c06.html#cb115-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">survey_mean</span>(),</span>
<span id="cb115-4"><a href="c06.html#cb115-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
##   Region     coef    `_se`
##   &lt;fct&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 Northeast 0.178 6.84e-11
## 2 Midwest   0.223 6.07e-11
## 3 South     0.376 1.43e-10
## 4 West      0.223 1.37e-10</code></pre>
</div>
<div id="the-proportion-argument" class="section level3 hasAnchor" number="6.3.5">
<h3><span class="header-section-number">6.3.5</span> The <code>proportion</code> argument<a href="c06.html#the-proportion-argument" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Note that when we run <code>survey_prop()</code>, we see a message that says:</p>
<pre><code>When `proportion` is unspecified, `survey_prop()` now defaults to `proportion = TRUE`.
ℹ This should improve confidence interval coverage.</code></pre>
<p>If the <code>proportion</code> argument is not specified in the function call, <code>survey_prop()</code> defaults to <code>proportion = TRUE</code>. This change was made to improve the accuracy of the confidence intervals calculated by the function since the function defaulted to <code>proportion = FALSE</code> in the past. The warning message is intended to alert users to this change, and to suggest that any code relying on the previous default setting may need to be updated.</p>
</div>
<div id="print-total-overall-numbers-in-our-output" class="section level3 hasAnchor" number="6.3.6">
<h3><span class="header-section-number">6.3.6</span> Print total overall numbers in our output<a href="c06.html#print-total-overall-numbers-in-our-output" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If we want to see the total overall numbers from our <code>survey_mean()</code> function, we can use <code>cascade</code>. <code>cascade</code> is similar to <code>summarize</code> but calculates summary statistics for the total of a group in addition to each group.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="c06.html#cb118-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb118-2"><a href="c06.html#cb118-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ACUsed) <span class="sc">%&gt;%</span></span>
<span id="cb118-3"><a href="c06.html#cb118-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cascade</span>(<span class="at">ElBill =</span> <span class="fu">survey_mean</span>(DOLLAREL,</span>
<span id="cb118-4"><a href="c06.html#cb118-4" aria-hidden="true" tabindex="-1"></a>                               <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   ACUsed ElBill ElBill_se
##   &lt;lgl&gt;   &lt;dbl&gt;     &lt;dbl&gt;
## 1 FALSE    972.      25.8
## 2 TRUE    1435.      15.8
## 3 NA      1375.      14.1</code></pre>
<p>Note that the overall average electricity cost appears as <code>NA</code>. The average electricity cost for those who do not use AC is $972. For those who do use AC, it is $1435. Overall, it is $1375.</p>
</div>
<div id="removing-na-for-calculating-results" class="section level3 hasAnchor" number="6.3.7">
<h3><span class="header-section-number">6.3.7</span> Removing <code>NA</code> for calculating results<a href="c06.html#removing-na-for-calculating-results" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If we run the example below, we get an error:</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="c06.html#cb120-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb120-2"><a href="c06.html#cb120-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">TD_mean =</span> <span class="fu">survey_mean</span>(<span class="at">x =</span> SummerTempDay))</span></code></pre></div>
<pre><code>## Error in `dplyr::summarise()`:
## ℹ In argument: `TD_mean = survey_mean(x = SummerTempDay)`.
## Caused by error in `svrVar()`:
## ! All replicates contained NAs</code></pre>
<p>Because of the <code>NA</code> in <code>SummerTempDay</code>, <code>survey_mean()</code> cannot calculate the average temperature. We can fix this with the argument <code>na.rm = TRUE</code>:</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="c06.html#cb122-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb122-2"><a href="c06.html#cb122-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">TD_mean =</span> <span class="fu">survey_mean</span>(<span class="at">x =</span> SummerTempDay,</span>
<span id="cb122-3"><a href="c06.html#cb122-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   TD_mean TD_mean_se
##     &lt;dbl&gt;      &lt;dbl&gt;
## 1    72.4     0.0793</code></pre>
<p>The mean temperature set in a summer day in 72.4 degrees.</p>
</div>
<div id="calculate-proportions-with-confidence-intervals" class="section level3 hasAnchor" number="6.3.8">
<h3><span class="header-section-number">6.3.8</span> Calculate proportions with confidence intervals<a href="c06.html#calculate-proportions-with-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We calculate confidence intervals by setting the <code>vartype</code> to <code>ci</code> within <code>summarize</code> when using <code>survey_mean()</code> or <code>survey_mean()</code>. The confidence intervals provide us with an upper and lower column for each method.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="c06.html#cb124-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb124-2"><a href="c06.html#cb124-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Urbanicity) <span class="sc">%&gt;%</span></span>
<span id="cb124-3"><a href="c06.html#cb124-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">pd =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span> <span class="st">&quot;ci&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb124-4"><a href="c06.html#cb124-4" aria-hidden="true" tabindex="-1"></a>              <span class="fu">round</span>(<span class="dv">4</span>))</span></code></pre></div>
<pre><code>## # A tibble: 3 × 4
##   Urbanicity       pd pd_low pd_upp
##   &lt;fct&gt;         &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 Urban Area    0.696  0.652  0.736
## 2 Urban Cluster 0.106  0.082  0.136
## 3 Rural         0.198  0.171  0.229</code></pre>
<p>69.6% of the responses are from people in urban areas, with a lower confidence interval bound of 65.2% and a upper confidence interval bound of 73.62%.</p>
<p>We can change the proportion method by adding <code>prop_method</code>. The available options are <code>"logit"</code>, <code>"likelihood"</code>, <code>"asin"</code>, <code>"beta"</code>, and <code>"mean"</code>.</p>
<p>As noted above, <code>svy_prop()</code> defaults to <code>proportion = TRUE</code>. Here, we rerun the previous function using the logit proportion method and with <code>proportion = FALSE</code>.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="c06.html#cb126-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb126-2"><a href="c06.html#cb126-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Urbanicity) <span class="sc">%&gt;%</span></span>
<span id="cb126-3"><a href="c06.html#cb126-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">pl =</span> <span class="fu">survey_prop</span>(</span>
<span id="cb126-4"><a href="c06.html#cb126-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">proportion =</span> <span class="cn">FALSE</span>,</span>
<span id="cb126-5"><a href="c06.html#cb126-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">prop_method =</span> <span class="st">&quot;xlogit&quot;</span>,</span>
<span id="cb126-6"><a href="c06.html#cb126-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">vartype =</span> <span class="st">&quot;ci&quot;</span></span>
<span id="cb126-7"><a href="c06.html#cb126-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">4</span>))</span></code></pre></div>
<pre><code>## # A tibble: 3 × 4
##   Urbanicity       pl pl_low pl_upp
##   &lt;fct&gt;         &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 Urban Area    0.696 0.653   0.738
## 2 Urban Cluster 0.106 0.0792  0.133
## 3 Rural         0.198 0.169   0.228</code></pre>
<p>Our results have changed slightly: 69.6% of the responses are from people in urban areas, with a lower confidence interval bound of 65.3% and a upper confidence interval bound of 73.8%.</p>
</div>
<div id="other-functions-that-use-survey-methods" class="section level3 hasAnchor" number="6.3.9">
<h3><span class="header-section-number">6.3.9</span> Other functions that use survey methods<a href="c06.html#other-functions-that-use-survey-methods" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The {srvyr} package includes other functions for summarizing datasets, as mentioned in the section on types of descriptive analysis.</p>
<ul>
<li>Center: <code>survey_mean()</code>, <code>survey_median()</code></li>
<li>Count: <code>survey_count()</code>, <code>survey_total()</code></li>
<li>Distribution: <code>survey_ratio()</code>, <code>survey_prop()</code></li>
<li>Range: <code>survey_quantile()</code></li>
<li>Variance: <code>survey_var()</code>, <code>survey_sd()</code></li>
</ul>
<p>We will not cover each one in depth; however, the same principles that we covered above apply.</p>
</div>
<div id="calculate-conditional-proportions-with-more-than-one-group" class="section level3 hasAnchor" number="6.3.10">
<h3><span class="header-section-number">6.3.10</span> Calculate conditional proportions with more than one group<a href="c06.html#calculate-conditional-proportions-with-more-than-one-group" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Specifying more than one group calculates conditional proportions. Say we wanted to know the proportion of respondents who live in rural regions in the Northeast. After the <code>tbl_svy</code> object, we specify the two variables we want to calculate proportions for:</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="c06.html#cb128-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb128-2"><a href="c06.html#cb128-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Region, Urbanicity) <span class="sc">%&gt;%</span></span>
<span id="cb128-3"><a href="c06.html#cb128-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb128-4"><a href="c06.html#cb128-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">p =</span> <span class="fu">survey_mean</span>(),</span>
<span id="cb128-5"><a href="c06.html#cb128-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="fu">survey_total</span>(),</span>
<span id="cb128-6"><a href="c06.html#cb128-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">unweighted</span>(<span class="fu">n</span>()),</span>
<span id="cb128-7"><a href="c06.html#cb128-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb128-8"><a href="c06.html#cb128-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 12 × 7
##    Region    Urbanicity         p   p_se         N     N_se     n
##    &lt;fct&gt;     &lt;fct&gt;          &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;
##  1 Northeast Urban Area    0.742  0.0578 15595476. 1215149.   551
##  2 Northeast Urban Cluster 0.103  0.0363  2153686.  763191.    86
##  3 Northeast Rural         0.155  0.0310  3257375.  651505.   157
##  4 Midwest   Urban Area    0.652  0.0510 17198016. 1343922.   844
##  5 Midwest   Urban Cluster 0.135  0.0344  3549498.  907055.   194
##  6 Midwest   Rural         0.213  0.0292  5624221.  771356.   289
##  7 South     Urban Area    0.631  0.0337 28064377. 1495982.  1277
##  8 South     Urban Cluster 0.120  0.0216  5350796.  962050.   223
##  9 South     Rural         0.248  0.0287 11026801. 1274124.   510
## 10 West      Urban Area    0.810  0.0374 21376390.  987240.  1256
## 11 West      Urban Cluster 0.0554 0.0168  1460669.  444588.    95
## 12 West      Rural         0.135  0.0264  3550944.  696556.   204</code></pre>
<p>From the table, we see that the weighted proportion is 15.5%. Note that column <code>p</code> is the proportion of <strong>respondents in rural areas by region</strong>. That is, it is the weighted number of people in rural areas in the Northeast (3,257,375), divided by the weighted number of respondents in the Northeast (15,595,476 + 2,153,686 + 3,257,375).</p>
</div>
<div id="calculate-joint-proportions-with-more-than-one-group" class="section level3 hasAnchor" number="6.3.11">
<h3><span class="header-section-number">6.3.11</span> Calculate joint proportions with more than one group<a href="c06.html#calculate-joint-proportions-with-more-than-one-group" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When we want to calculate proportions for multiple variables together as if they were a single variable, we use {srvyr}’s <code>interact</code>. We use <code>interact</code> within <code>group_by()</code> to calculate the joint proportions of two or more variables.</p>
<p>For example, if we have a survey dataset with variables such as age, gender, and income, we could use <code>interact</code> to create summary statistics for each combination of age and gender, or for each combination of income and gender. We can examine how these variables are related to each other, and whether there are any differences or similarities between different groups.</p>
<p>In the example below, we calculate Region and Urbanicity together:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="c06.html#cb130-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb130-2"><a href="c06.html#cb130-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">interact</span>(Region, Urbanicity)) <span class="sc">%&gt;%</span></span>
<span id="cb130-3"><a href="c06.html#cb130-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">p =</span> <span class="fu">survey_mean</span>(),</span>
<span id="cb130-4"><a href="c06.html#cb130-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">N =</span> <span class="fu">survey_total</span>(),</span>
<span id="cb130-5"><a href="c06.html#cb130-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 12 × 6
##    Region    Urbanicity         p    p_se         N     N_se
##    &lt;fct&gt;     &lt;fct&gt;          &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
##  1 Northeast Urban Area    0.132  0.0103  15595476. 1215149.
##  2 Northeast Urban Cluster 0.0182 0.00646  2153686.  763191.
##  3 Northeast Rural         0.0276 0.00551  3257375.  651505.
##  4 Midwest   Urban Area    0.145  0.0114  17198016. 1343922.
##  5 Midwest   Urban Cluster 0.0300 0.00767  3549498.  907055.
##  6 Midwest   Rural         0.0476 0.00653  5624221.  771356.
##  7 South     Urban Area    0.237  0.0127  28064377. 1495982.
##  8 South     Urban Cluster 0.0453 0.00814  5350796.  962050.
##  9 South     Rural         0.0933 0.0108  11026801. 1274124.
## 10 West      Urban Area    0.181  0.00835 21376390.  987240.
## 11 West      Urban Cluster 0.0124 0.00376  1460669.  444588.
## 12 West      Rural         0.0300 0.00589  3550944.  696556.</code></pre>
<p>Running <code>survey_mean()</code> with <code>interact</code>, we see that 13.2% of the dataset is from the Northeast Urban Area, wherewas 0.182% is from the Northeast Urban Cluster.</p>
<p>Since <code>interact</code> groups by multiple variables as if they were a single variable, the proportions in column <code>p</code> sum to 100% across more than a single grouping variable.</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="c06.html#cb132-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb132-2"><a href="c06.html#cb132-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">interact</span>(Region, Urbanicity)) <span class="sc">%&gt;%</span></span>
<span id="cb132-3"><a href="c06.html#cb132-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">p =</span> <span class="fu">survey_mean</span>(),</span>
<span id="cb132-4"><a href="c06.html#cb132-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">N =</span> <span class="fu">survey_total</span>(),</span>
<span id="cb132-5"><a href="c06.html#cb132-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb132-6"><a href="c06.html#cb132-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">p_sum =</span> <span class="fu">sum</span>(p))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   p_sum
##   &lt;dbl&gt;
## 1     1</code></pre>
</div>
<div id="calculate-proportions-with-design-effects" class="section level3 hasAnchor" number="6.3.12">
<h3><span class="header-section-number">6.3.12</span> Calculate proportions with design effects<a href="c06.html#calculate-proportions-with-design-effects" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Note above that functions <code>survey_total()</code>, <code>survey_mean()</code>, and <code>survey_prop()</code> have the argument <code>deff</code>. <code>deff</code> stands for Design Effect, the ratio of two variances. Use <code>deff = TRUE</code> argument to specify whether to return the design effect.</p>
<p>Calculating proportions with design effects is important when analyzing survey data that has been collected using a complex sampling design. Since a complex sampling design means that the probability of selecting each individual in the sample is different, this can lead to the observations in the sample being correlated with each other.</p>
<p>Design effects account for this correlation and adjust the standard errors of estimates, which in turn can affect the significance of test statistics and the accuracy of confidence intervals. Calculating proportions with design effects is important because it helps to produce accurate estimates of population proportions that account for the complex nature of the survey data.</p>
<p>Deff compares the variance of the current samplng, including its design elements, to the variance of a hypothetical simple random sample (SRS) of the same size. A Deff value less than 1 indicates that the sample design is more efficient than an SRS of the same size.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="c06.html#cb134-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb134-2"><a href="c06.html#cb134-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">interact</span>(Region, Urbanicity)) <span class="sc">%&gt;%</span></span>
<span id="cb134-3"><a href="c06.html#cb134-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">p =</span> <span class="fu">survey_mean</span>(<span class="at">deff =</span> <span class="cn">TRUE</span>),</span>
<span id="cb134-4"><a href="c06.html#cb134-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">N =</span> <span class="fu">survey_total</span>(),</span>
<span id="cb134-5"><a href="c06.html#cb134-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 12 × 7
##    Region    Urbanicity         p    p_se p_deff         N     N_se
##    &lt;fct&gt;     &lt;fct&gt;          &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
##  1 Northeast Urban Area    0.132  0.0103    5.25 15595476. 1215149.
##  2 Northeast Urban Cluster 0.0182 0.00646  13.2   2153686.  763191.
##  3 Northeast Rural         0.0276 0.00551   6.44  3257375.  651505.
##  4 Midwest   Urban Area    0.145  0.0114    5.91 17198016. 1343922.
##  5 Midwest   Urban Cluster 0.0300 0.00767  11.5   3549498.  907055.
##  6 Midwest   Rural         0.0476 0.00653   5.34  5624221.  771356.
##  7 South     Urban Area    0.237  0.0127    5.03 28064377. 1495982.
##  8 South     Urban Cluster 0.0453 0.00814   8.71  5350796.  962050.
##  9 South     Rural         0.0933 0.0108    7.81 11026801. 1274124.
## 10 West      Urban Area    0.181  0.00835   2.68 21376390.  987240.
## 11 West      Urban Cluster 0.0124 0.00376   6.59  1460669.  444588.
## 12 West      Rural         0.0300 0.00589   6.78  3550944.  696556.</code></pre>
<p>Rerunning <code>survey_mean()</code>, we see that <code>p_deff</code> is greater than 1 for the proportions. It is common for Deff to be greater than 1 when using complex sampling designs (such as in the case of RECS). A high Deff can occur due to various factors, such as stratification, clustering, or unequal selection probabilities, which are often used to improve the precision of estimates or to reduce sampling costs. These design features can increase the complexity of the sample design and lead to a higher Deff, but they can also improve the accuracy and representativeness of the survey estimates.</p>
</div>
</div>
<div id="exercises-2" class="section level2 hasAnchor" number="6.4">
<h2><span class="header-section-number">6.4</span> Exercises<a href="c06.html#exercises-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="c05.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="c07.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/06-descriptive-analysis-in-srvyr.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
