<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Modeling | Tidy Survey Book</title>
  <meta name="description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Modeling | Tidy Survey Book" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  <meta name="github-repo" content="tidy-survey-r/tidy-survey-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Modeling | Tidy Survey Book" />
  
  <meta name="twitter:description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  

<meta name="author" content="Stephanie Zimmer, Rebecca J. Powell, and Isabella Velásquez" />


<meta name="date" content="2023-08-22" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="c06-statistical-testing.html"/>
<link rel="next" href="c08-communicating-results.html"/>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="c01-intro.html"><a href="c01-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="c01-intro.html"><a href="c01-intro.html#what-to-expect"><i class="fa fa-check"></i><b>1.1</b> What to expect</a></li>
<li class="chapter" data-level="1.2" data-path="c01-intro.html"><a href="c01-intro.html#book-datasets"><i class="fa fa-check"></i><b>1.2</b> Datasets used in this book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html"><i class="fa fa-check"></i><b>2</b> Overview of Surveys</a>
<ul>
<li class="chapter" data-level="2.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#pre-survey-planning"><i class="fa fa-check"></i><b>2.1</b> Pre-Survey Planning</a></li>
<li class="chapter" data-level="2.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design"><i class="fa fa-check"></i><b>2.2</b> Study Design</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-sampdesign"><i class="fa fa-check"></i><b>2.2.1</b> Sampling Design</a></li>
<li class="chapter" data-level="2.2.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-dcplanning"><i class="fa fa-check"></i><b>2.2.2</b> Data Collection Planning</a></li>
<li class="chapter" data-level="2.2.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-questionnaire"><i class="fa fa-check"></i><b>2.2.3</b> Questionnaire Design</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-datacollection"><i class="fa fa-check"></i><b>2.3</b> Data Collection</a></li>
<li class="chapter" data-level="2.4" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post"><i class="fa fa-check"></i><b>2.4</b> Post-Survey Processing</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-cleaning"><i class="fa fa-check"></i><b>2.4.1</b> Data Cleaning and Imputation</a></li>
<li class="chapter" data-level="2.4.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-weighting"><i class="fa fa-check"></i><b>2.4.2</b> Weighting</a></li>
<li class="chapter" data-level="2.4.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-disclosure"><i class="fa fa-check"></i><b>2.4.3</b> Disclosure</a></li>
<li class="chapter" data-level="2.4.4" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-documentation"><i class="fa fa-check"></i><b>2.4.4</b> Documentation</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#post-survey-data-analysis-and-reporting"><i class="fa fa-check"></i><b>2.5</b> Post-survey data analysis and reporting</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html"><i class="fa fa-check"></i><b>3</b> Specifying sample designs and replicate weights in {srvyr}</a>
<ul>
<li class="chapter" data-level="" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#prereq3"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="3.1" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#introduction"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#common-sampling-designs"><i class="fa fa-check"></i><b>3.2</b> Common sampling designs</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#simple-random-sample-without-replacement"><i class="fa fa-check"></i><b>3.2.1</b> Simple random sample without replacement</a></li>
<li class="chapter" data-level="3.2.2" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#simple-random-sample-with-replacement"><i class="fa fa-check"></i><b>3.2.2</b> Simple random sample with replacement</a></li>
<li class="chapter" data-level="3.2.3" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#stratified-sampling"><i class="fa fa-check"></i><b>3.2.3</b> Stratified sampling</a></li>
<li class="chapter" data-level="3.2.4" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#clustered-sampling"><i class="fa fa-check"></i><b>3.2.4</b> Clustered sampling</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#replicate-weights"><i class="fa fa-check"></i><b>3.3</b> Replicate weights</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#balanced-repeated-replication-brr-method"><i class="fa fa-check"></i><b>3.3.1</b> Balanced Repeated Replication (BRR) Method</a></li>
<li class="chapter" data-level="3.3.2" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#fays-brr-method"><i class="fa fa-check"></i><b>3.3.2</b> Fay’s BRR Method</a></li>
<li class="chapter" data-level="3.3.3" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#jackknife-method"><i class="fa fa-check"></i><b>3.3.3</b> Jackknife method</a></li>
<li class="chapter" data-level="3.3.4" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#bootstrap-method"><i class="fa fa-check"></i><b>3.3.4</b> Bootstrap Method</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#und-surv-doc"><i class="fa fa-check"></i><b>3.4</b> Understanding survey design documentation</a></li>
<li class="chapter" data-level="3.5" data-path="c03-specifying-sample-designs.html"><a href="c03-specifying-sample-designs.html#exercises"><i class="fa fa-check"></i><b>3.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html"><i class="fa fa-check"></i><b>4</b> Understanding survey data documentation</a>
<ul>
<li class="chapter" data-level="" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#prereq4"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="4.1" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#introduction-1"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#types-of-survey-documentation"><i class="fa fa-check"></i><b>4.2</b> Types of survey documentation</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#technical-documentation"><i class="fa fa-check"></i><b>4.2.1</b> Technical documentation</a></li>
<li class="chapter" data-level="4.2.2" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#questionnaires"><i class="fa fa-check"></i><b>4.2.2</b> Questionnaires</a></li>
<li class="chapter" data-level="4.2.3" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#codebooks"><i class="fa fa-check"></i><b>4.2.3</b> Codebooks</a></li>
<li class="chapter" data-level="4.2.4" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#errata"><i class="fa fa-check"></i><b>4.2.4</b> Errata</a></li>
<li class="chapter" data-level="4.2.5" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#additional-resources"><i class="fa fa-check"></i><b>4.2.5</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#working-with-missing-data"><i class="fa fa-check"></i><b>4.3</b> Working with missing data</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#accounting-for-questionnaire-skip-patterns"><i class="fa fa-check"></i><b>4.3.1</b> Accounting for questionnaire skip patterns</a></li>
<li class="chapter" data-level="4.3.2" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#accounting-for-missing-completely-at-random-mcar-missing-at-random-mar-and-missing-not-at-random-mnar-missingness"><i class="fa fa-check"></i><b>4.3.2</b> Accounting for Missing Completely at Random (MCAR), Missing at Random (MAR), and Missing not at Random (MNAR) missingness</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#example-american-national-election-studies-anes-2020-survey-documentation"><i class="fa fa-check"></i><b>4.4</b> Example: American National Election Studies (ANES) 2020 survey documentation</a></li>
<li class="chapter" data-level="4.5" data-path="c04-understanding-survey-data-documentation.html"><a href="c04-understanding-survey-data-documentation.html#searching-for-public-use-survey-data"><i class="fa fa-check"></i><b>4.5</b> Searching for public-use survey data</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html"><i class="fa fa-check"></i><b>5</b> Descriptive analyses in srvyr</a>
<ul>
<li class="chapter" data-level="" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#prereq5"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="5.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#introduction-3"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#similarities-between-dplyr-and-srvyr-functions"><i class="fa fa-check"></i><b>5.2</b> Similarities between {dplyr} and {srvyr} functions</a></li>
<li class="chapter" data-level="5.3" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#deciding-on-descriptive-analyses"><i class="fa fa-check"></i><b>5.3</b> Deciding on descriptive analyses</a></li>
<li class="chapter" data-level="5.4" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#measures-of-distribution"><i class="fa fa-check"></i><b>5.4</b> Measures of distribution</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#counts-and-cross-tabulations"><i class="fa fa-check"></i><b>5.4.1</b> Counts and cross-tabulations</a></li>
<li class="chapter" data-level="5.4.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#totals-and-sums"><i class="fa fa-check"></i><b>5.4.2</b> Totals and sums</a></li>
<li class="chapter" data-level="5.4.3" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#proportions"><i class="fa fa-check"></i><b>5.4.3</b> Proportions</a></li>
<li class="chapter" data-level="5.4.4" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#quantiles"><i class="fa fa-check"></i><b>5.4.4</b> Quantiles</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>5.5</b> Measures of central tendency</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#means"><i class="fa fa-check"></i><b>5.5.1</b> Means</a></li>
<li class="chapter" data-level="5.5.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#medians"><i class="fa fa-check"></i><b>5.5.2</b> Medians</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#measures-of-dispersion"><i class="fa fa-check"></i><b>5.6</b> Measures of dispersion</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#standard-deviation-and-variance"><i class="fa fa-check"></i><b>5.6.1</b> Standard deviation and variance</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#measures-of-relationship"><i class="fa fa-check"></i><b>5.7</b> Measures of relationship</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#correlations"><i class="fa fa-check"></i><b>5.7.1</b> Correlations</a></li>
<li class="chapter" data-level="5.7.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#ratios"><i class="fa fa-check"></i><b>5.7.2</b> Ratios</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#additional-topics"><i class="fa fa-check"></i><b>5.8</b> Additional topics</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#subpopulation-analysis"><i class="fa fa-check"></i><b>5.8.1</b> Subpopulation analysis</a></li>
<li class="chapter" data-level="5.8.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#Var-types"><i class="fa fa-check"></i><b>5.8.2</b> Variability types</a></li>
<li class="chapter" data-level="5.8.3" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#design-effects"><i class="fa fa-check"></i><b>5.8.3</b> Design effects</a></li>
<li class="chapter" data-level="5.8.4" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#creating-summary-rows"><i class="fa fa-check"></i><b>5.8.4</b> Creating summary rows</a></li>
<li class="chapter" data-level="5.8.5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#calculating-estimates-for-many-outcomes"><i class="fa fa-check"></i><b>5.8.5</b> Calculating estimates for many outcomes</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#exercises-1"><i class="fa fa-check"></i><b>5.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html"><i class="fa fa-check"></i><b>6</b> Statistical testing</a>
<ul>
<li class="chapter" data-level="" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#prereq6"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="6.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#introduction-4"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest"><i class="fa fa-check"></i><b>6.2</b> Comparison of Proportions and Means</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest-syntax"><i class="fa fa-check"></i><b>6.2.1</b> Syntax</a></li>
<li class="chapter" data-level="6.2.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest-examples"><i class="fa fa-check"></i><b>6.2.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi"><i class="fa fa-check"></i><b>6.3</b> Chi-Square Tests</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi-syntax"><i class="fa fa-check"></i><b>6.3.1</b> Syntax</a></li>
<li class="chapter" data-level="6.3.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi-examples"><i class="fa fa-check"></i><b>6.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-exercises"><i class="fa fa-check"></i><b>6.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="c07-modeling.html"><a href="c07-modeling.html"><i class="fa fa-check"></i><b>7</b> Modeling</a>
<ul>
<li class="chapter" data-level="" data-path="c07-modeling.html"><a href="c07-modeling.html#prereq7"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="7.1" data-path="c07-modeling.html"><a href="c07-modeling.html#introduction-5"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="c07-modeling.html"><a href="c07-modeling.html#analysis-of-variance-anova"><i class="fa fa-check"></i><b>7.2</b> Analysis of Variance (ANOVA)</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-10"><i class="fa fa-check"></i><b>7.2.1</b> Syntax</a></li>
<li class="chapter" data-level="7.2.2" data-path="c07-modeling.html"><a href="c07-modeling.html#example-10"><i class="fa fa-check"></i><b>7.2.2</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="c07-modeling.html"><a href="c07-modeling.html#gaussian-linear-regression"><i class="fa fa-check"></i><b>7.3</b> Gaussian Linear regression</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-11"><i class="fa fa-check"></i><b>7.3.1</b> Syntax</a></li>
<li class="chapter" data-level="7.3.2" data-path="c07-modeling.html"><a href="c07-modeling.html#example-11"><i class="fa fa-check"></i><b>7.3.2</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="c07-modeling.html"><a href="c07-modeling.html#logistic-regression"><i class="fa fa-check"></i><b>7.4</b> Logistic regression</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-12"><i class="fa fa-check"></i><b>7.4.1</b> Syntax</a></li>
<li class="chapter" data-level="7.4.2" data-path="c07-modeling.html"><a href="c07-modeling.html#example-12"><i class="fa fa-check"></i><b>7.4.2</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="c07-modeling.html"><a href="c07-modeling.html#exercises-2"><i class="fa fa-check"></i><b>7.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html"><i class="fa fa-check"></i><b>8</b> Communicating Results</a>
<ul>
<li class="chapter" data-level="" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#prereq8"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="8.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#introduction-6"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#describing-results-through-text"><i class="fa fa-check"></i><b>8.2</b> Describing Results through Text</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#methodology"><i class="fa fa-check"></i><b>8.2.1</b> Methodology</a></li>
<li class="chapter" data-level="8.2.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#analysis"><i class="fa fa-check"></i><b>8.2.2</b> Analysis</a></li>
<li class="chapter" data-level="8.2.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#results"><i class="fa fa-check"></i><b>8.2.3</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#visualizing-data"><i class="fa fa-check"></i><b>8.3</b> Visualizing Data</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#tables"><i class="fa fa-check"></i><b>8.3.1</b> Tables</a></li>
<li class="chapter" data-level="8.3.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#charts-and-plots"><i class="fa fa-check"></i><b>8.3.2</b> Charts and Plots</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#reproducibility"><i class="fa fa-check"></i><b>8.4</b> Reproducibility</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#setting-random-number-seeds"><i class="fa fa-check"></i><b>8.4.1</b> Setting Random Number Seeds</a></li>
<li class="chapter" data-level="8.4.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#git"><i class="fa fa-check"></i><b>8.4.2</b> Git</a></li>
<li class="chapter" data-level="8.4.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#renv"><i class="fa fa-check"></i><b>8.4.3</b> {renv}</a></li>
<li class="chapter" data-level="8.4.4" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#quartor-markdown"><i class="fa fa-check"></i><b>8.4.4</b> Quarto/R Markdown</a></li>
<li class="chapter" data-level="8.4.5" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#the-targets-package"><i class="fa fa-check"></i><b>8.4.5</b> The {targets} package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html"><i class="fa fa-check"></i><b>9</b> National Crime Victimization Survey Vignette</a>
<ul>
<li class="chapter" data-level="" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#prereq9"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="9.1" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#introduction-7"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#data-structure"><i class="fa fa-check"></i><b>9.2</b> Data structure</a></li>
<li class="chapter" data-level="9.3" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#survey-notation"><i class="fa fa-check"></i><b>9.3</b> Survey notation</a></li>
<li class="chapter" data-level="9.4" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#data-file-preparation"><i class="fa fa-check"></i><b>9.4</b> Data file preparation</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#preparing-files-for-estimation-of-victimization-rates"><i class="fa fa-check"></i><b>9.4.1</b> Preparing files for estimation of victimization rates</a></li>
<li class="chapter" data-level="9.4.2" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#derived-demographic-variables"><i class="fa fa-check"></i><b>9.4.2</b> Derived demographic variables</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#survey-design-objects"><i class="fa fa-check"></i><b>9.5</b> Survey design objects</a></li>
<li class="chapter" data-level="9.6" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#calculating-estimates"><i class="fa fa-check"></i><b>9.6</b> Calculating estimates</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#victimization-totals"><i class="fa fa-check"></i><b>9.6.1</b> Victimization totals</a></li>
<li class="chapter" data-level="9.6.2" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#victimization-proportions"><i class="fa fa-check"></i><b>9.6.2</b> Victimization proportions</a></li>
<li class="chapter" data-level="9.6.3" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#victimization-rates"><i class="fa fa-check"></i><b>9.6.3</b> Victimization rates</a></li>
<li class="chapter" data-level="9.6.4" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#prevalence-rates"><i class="fa fa-check"></i><b>9.6.4</b> Prevalence rates</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="c09-ncvs-vignette.html"><a href="c09-ncvs-vignette.html#exercises-3"><i class="fa fa-check"></i><b>9.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html"><i class="fa fa-check"></i><b>10</b> AmericasBarometer Vignette</a>
<ul>
<li class="chapter" data-level="" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#prereq10"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="10.1" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#introduction-8"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#data-structure-1"><i class="fa fa-check"></i><b>10.2</b> Data Structure</a></li>
<li class="chapter" data-level="10.3" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#preparing-files"><i class="fa fa-check"></i><b>10.3</b> Preparing files</a></li>
<li class="chapter" data-level="10.4" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#survey-design-objects-1"><i class="fa fa-check"></i><b>10.4</b> Survey design objects</a></li>
<li class="chapter" data-level="10.5" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#calculating-estimates-and-making-tables"><i class="fa fa-check"></i><b>10.5</b> Calculating estimates and making tables</a></li>
<li class="chapter" data-level="10.6" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#mapping-survey-data"><i class="fa fa-check"></i><b>10.6</b> Mapping survey data</a></li>
<li class="chapter" data-level="10.7" data-path="c10-ambarom-vignette.html"><a href="c10-ambarom-vignette.html#exercises-4"><i class="fa fa-check"></i><b>10.7</b> Exercises</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tidy Survey Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="c07-modeling" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Modeling<a href="c07-modeling.html#c07-modeling" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="prereq7" class="section level3 unnumbered hasAnchor prereqbox-header">
<h3>Prerequisites<a href="c07-modeling.html#prereq7" class="anchor-section" aria-label="Anchor link to header"></a></h3>
</div>
<div class="prereqbox">
<p>For this chapter, here are the libraries and helper functions we will need:</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="c07-modeling.html#cb296-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb296-2"><a href="c07-modeling.html#cb296-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey) </span>
<span id="cb296-3"><a href="c07-modeling.html#cb296-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(srvyr) </span>
<span id="cb296-4"><a href="c07-modeling.html#cb296-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb296-5"><a href="c07-modeling.html#cb296-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(osfr)</span>
<span id="cb296-6"><a href="c07-modeling.html#cb296-6" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;helper-fun/helper-functions.R&quot;</span>)</span></code></pre></div>
<p>We will be using data from ANES and RECS. Here is the code to create the design objects for each to use throughout this chapter. For ANES, we need to adjust the weight so it sums to the population instead of the sample (see the ANES documentation and Chapter <a href="c04-understanding-survey-data-documentation.html#c04-understanding-survey-data-documentation">4</a> for more information).</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="c07-modeling.html#cb297-1" aria-hidden="true" tabindex="-1"></a>anes_in <span class="ot">&lt;-</span> <span class="fu">read_osf</span>(<span class="st">&quot;anes_2020.rds&quot;</span>) </span>
<span id="cb297-2"><a href="c07-modeling.html#cb297-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb297-3"><a href="c07-modeling.html#cb297-3" aria-hidden="true" tabindex="-1"></a>anes_adjwgt <span class="ot">&lt;-</span> anes_in <span class="sc">%&gt;%</span></span>
<span id="cb297-4"><a href="c07-modeling.html#cb297-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Weight =</span> Weight <span class="sc">/</span> <span class="fu">sum</span>(Weight) <span class="sc">*</span> targetpop)</span>
<span id="cb297-5"><a href="c07-modeling.html#cb297-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb297-6"><a href="c07-modeling.html#cb297-6" aria-hidden="true" tabindex="-1"></a>anes_des <span class="ot">&lt;-</span> anes_adjwgt <span class="sc">%&gt;%</span></span>
<span id="cb297-7"><a href="c07-modeling.html#cb297-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(</span>
<span id="cb297-8"><a href="c07-modeling.html#cb297-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> Weight,</span>
<span id="cb297-9"><a href="c07-modeling.html#cb297-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">strata =</span> Stratum,</span>
<span id="cb297-10"><a href="c07-modeling.html#cb297-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">ids =</span> VarUnit,</span>
<span id="cb297-11"><a href="c07-modeling.html#cb297-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">nest =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>For RECS, details are included in the RECS documentation and Chapter <a href="c03-specifying-sample-designs.html#c03-specifying-sample-designs">3</a>.</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="c07-modeling.html#cb298-1" aria-hidden="true" tabindex="-1"></a>recs_in <span class="ot">&lt;-</span><span class="fu">read_osf</span>(<span class="st">&quot;recs_2015.rds&quot;</span>)</span>
<span id="cb298-2"><a href="c07-modeling.html#cb298-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb298-3"><a href="c07-modeling.html#cb298-3" aria-hidden="true" tabindex="-1"></a>recs_des <span class="ot">&lt;-</span> recs_in <span class="sc">%&gt;%</span></span>
<span id="cb298-4"><a href="c07-modeling.html#cb298-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(<span class="at">weights =</span> NWEIGHT,</span>
<span id="cb298-5"><a href="c07-modeling.html#cb298-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">repweights =</span> <span class="fu">starts_with</span>(<span class="st">&quot;BRRWT&quot;</span>),</span>
<span id="cb298-6"><a href="c07-modeling.html#cb298-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">&quot;Fay&quot;</span>,</span>
<span id="cb298-7"><a href="c07-modeling.html#cb298-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">rho =</span> <span class="fl">0.5</span>,</span>
<span id="cb298-8"><a href="c07-modeling.html#cb298-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">mse =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</div>
<div id="introduction-5" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Introduction<a href="c07-modeling.html#introduction-5" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Modeling data is a way for researchers to investigate the relationship between a single dependent variable and one or more independent variables. This builds upon the analyses conducted in Chapter <a href="c06-statistical-testing.html#c06-statistical-testing">6</a>, which looked at the relationships between just two variables. For example, in Example 3 in Section <a href="c06-statistical-testing.html#stattest-ttest-examples">6.2.2</a>, we investigated if there is a relationship between the electrical bill cost and whether or not the household used air-conditioning. However, there are potentially other elements that could go into what the cost of electrical bill is in a household (e.g., outside temperature, desired internal temperature, types and number of appliances, etc.). T-tests only allow us to investigate the relationship of one independent variable at a time, but using models we can look into multiple variables and even explore interactions between these variables. There are several types of models, but in this chapter we will cover Analysis of Variance (ANOVA) and linear regression models following common Gaussian and logit distributions. Jonas Kristoffer Lindeløv has an interesting <a href="https://lindeloev.github.io/tests-as-linear/">discussion</a> of many statistical tests and models being equivalent to a linear model. For example, a one-way ANOVA is a linear model with one categorical independent variable, and a two-sample t-test is an ANOVA where the independent variable has exactly two levels.</p>
<p>When modeling data, it is helpful to first create an equation that provides an overview as to what it is that we are modeling. The main structure of these models is as follows:</p>
<p><span class="math display">\[y_i=\beta_0 +\sum_{i=1}^p \beta_i x_i + \epsilon_i\]</span></p>
<p>where <span class="math inline">\(y_i\)</span> is the outcome, <span class="math inline">\(\beta_0\)</span> is an intercept, <span class="math inline">\(x_1, \cdots, x_n\)</span> are the predictors with <span class="math inline">\(\beta_1, \cdots, \beta_p\)</span> as the associated coefficients, and <span class="math inline">\(\epsilon_i\)</span> is the error. Different models may not include an intercept, have interactions between different independent variables (<span class="math inline">\(x_i\)</span>), or may have different underlying structures for the dependent variable (<span class="math inline">\(y_i\)</span>). However, all linear models have the independent variables related to the dependent variable in a linear form.</p>
<p>To specify these models in R, the formulas are the same with both raw data and survey data. The left side of the formula is the response/dependent variable, and the right side of the formula has the predictor/independent variable(s). There are many symbols used in R to specify the formula.</p>
<p>For example, a linear formula mathematically specified as</p>
<p><span class="math display">\[Y_i=\beta_0+\beta_1 X_i+\epsilon_i\]</span> would be specified in R as <code>y~x</code> where the intercept is not explicitly included. To fit a model with no intercept, that is,</p>
<p><span class="math display">\[Y_i=\beta_1 X_i+\epsilon_i\]</span>
it can be specified as <code>y~x-1</code>. Formula notation details in R can be found in the help file for formula<a href="#fn22" class="footnote-ref" id="fnref22"><sup>22</sup></a>. A quick overview of the common formula notation is in the following table:</p>
<table>
<caption>Common symbols in formula notation</caption>
<colgroup>
<col width="12%" />
<col width="16%" />
<col width="71%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Symbol</th>
<th align="center">Example</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">+</td>
<td align="center"><code>+X</code></td>
<td>include this variable</td>
</tr>
<tr class="even">
<td align="center">-</td>
<td align="center"><code>-X</code></td>
<td>delete this variable</td>
</tr>
<tr class="odd">
<td align="center">:</td>
<td align="center"><code>X:Z</code></td>
<td>include the interaction between these variables</td>
</tr>
<tr class="even">
<td align="center">*</td>
<td align="center"><code>X*Z</code></td>
<td>include these variables and the interactions between them</td>
</tr>
<tr class="odd">
<td align="center">^n</td>
<td align="center"><code>(X+Z+Y)^3</code></td>
<td>include these variables and all interactions up to n way</td>
</tr>
<tr class="even">
<td align="center">I</td>
<td align="center"><code>I(X-Z)</code></td>
<td>as-as: include a new variable which is the difference of these variables</td>
</tr>
</tbody>
</table>
<p>There are often multiple ways to specify the same formula. For example, consider the following equation using the mtcars data</p>
<p><span class="math display">\[mpg_i=\beta_0+\beta_1cyl_{i}+\beta_2disp_{i}+\beta_3hp_{i}+\beta_4cyl_{i}disp_{i}+\beta_5cyl_{i}hp_{i}+\beta_6disp_{i}hp_{i}+\epsilon_i\]</span></p>
<p>This could be specified as any of the following:</p>
<ul>
<li><code>mpg~(cyl+disp+hp)^2</code></li>
<li><code>mpg~cyl+disp+hp+cyl:disp+cyl:hp+disp:hp</code></li>
<li><code>mpg~cyl*disp+cyl*hp+disp*hp</code></li>
</ul>
<p>Note that the following two specifications are not the same:</p>
<ul>
<li><code>mpg~cyl:disp:hp</code> this only has the interactions and not the main effect</li>
<li><code>mpg~cyl*disp*hp</code> this also has the 3-way interaction in addition to the main effects and 2-way interactions</li>
</ul>
<p>When using raw data, researchers will use the <code>glm()</code> function. With survey data, however, we use <code>svyglm()</code> from the {survey} package to ensure that we account for the survey design and weights in modeling<a href="#fn23" class="footnote-ref" id="fnref23"><sup>23</sup></a>. This allows us to generalize a model to the target population and accounts for the fact that the observations in the survey data may not be independent. As discussed in Chapter <a href="c06-statistical-testing.html#c06-statistical-testing">6</a>, modeling survey data cannot be directly done in {srvyr}, but can be done in the {survey} <span class="citation">(<a href="#ref-lumley2010complex" role="doc-biblioref">Lumley 2010</a>, <a href="#ref-R-survey" role="doc-biblioref">2023</a>)</span> package. In this chapter, we will provide syntax and examples for linear models, including ANOVA, Gaussian linear regression, and logistic regression. For details on other types of regression, including ordinal regression, log-linear models, and survival analysis, refer to <span class="citation">Lumley (<a href="#ref-lumley2010complex" role="doc-biblioref">2010</a>)</span>. <span class="citation">Lumley (<a href="#ref-lumley2010complex" role="doc-biblioref">2010</a>)</span> also discusses custom models such as a negative binomial or Poisson model in Appendix E of his book.</p>
</div>
<div id="analysis-of-variance-anova" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Analysis of Variance (ANOVA)<a href="c07-modeling.html#analysis-of-variance-anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In ANOVA, we are testing whether the mean of an outcome is the same across two or more groups. Statistically, we set up this as follows:</p>
<ul>
<li><span class="math inline">\(H_0: \mu_1 = \mu_2= \dots = \mu_k\)</span> where <span class="math inline">\(\mu_i\)</span> is the mean outcome for group <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(H_A: \text{At least one mean is different}\)</span></li>
</ul>
<p>Some assumptions when using ANOVA on survey data include:</p>
<ul>
<li>The outcome variable is normally distributed within each group</li>
<li>The variances of the outcome variable between each group are approximately equal</li>
<li>We do NOT assume independence between the groups as with general ANOVA. The covariance is accounted for in the survey design</li>
</ul>
<div id="syntax-10" class="section level3 hasAnchor" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> Syntax<a href="c07-modeling.html#syntax-10" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To perform this type of test in R, the general syntax is as follows:</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="c07-modeling.html#cb299-1" aria-hidden="true" tabindex="-1"></a>des_obj <span class="sc">%&gt;%</span></span>
<span id="cb299-2"><a href="c07-modeling.html#cb299-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyglm</span>(</span>
<span id="cb299-3"><a href="c07-modeling.html#cb299-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb299-4"><a href="c07-modeling.html#cb299-4" aria-hidden="true" tabindex="-1"></a>    outcomevar <span class="sc">~</span> groupvar,</span>
<span id="cb299-5"><a href="c07-modeling.html#cb299-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.action =</span> na.omit,</span>
<span id="cb299-6"><a href="c07-modeling.html#cb299-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">df.resid =</span> <span class="fu">degf</span>(.)</span>
<span id="cb299-7"><a href="c07-modeling.html#cb299-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>where <code>des_obj</code> is a design object, <code>outcomevar</code> is the outcome variable, <code>groupvar</code> is the group variable, and <code>na.action=na.omit</code> is set so that records with missing data in the outcome or group variable are removed for prediction<a href="#fn24" class="footnote-ref" id="fnref24"><sup>24</sup></a>. The function <code>svyglm()</code> does not have the design as the first argument so the dot (<code>.</code>) notation is used to pass it with a pipe (see Chapter <a href="c06-statistical-testing.html#c06-statistical-testing">6</a> for more details).</p>
</div>
<div id="example-10" class="section level3 hasAnchor" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> Example<a href="c07-modeling.html#example-10" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Looking at an example will help us discuss the output and how to interpret the results. In RECS, respondents are asked what temperature they set their thermostat to during the day and evening when using the air-conditioning during the summer. To analyze this data, we filter the respondents to only those using AC (<code>ACUsed</code>). Then if we want to see if there are differences by region, we can use <code>group_by()</code>. A descriptive analysis of the temperature at night (<code>SummerTempNight</code>) set by region and the sample sizes is displayed below.</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="c07-modeling.html#cb300-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb300-2"><a href="c07-modeling.html#cb300-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ACUsed) <span class="sc">%&gt;%</span></span>
<span id="cb300-3"><a href="c07-modeling.html#cb300-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Region) <span class="sc">%&gt;%</span></span>
<span id="cb300-4"><a href="c07-modeling.html#cb300-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb300-5"><a href="c07-modeling.html#cb300-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">SMN =</span> <span class="fu">survey_mean</span>(SummerTempNight, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb300-6"><a href="c07-modeling.html#cb300-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">unweighted</span>(<span class="fu">n</span>()),</span>
<span id="cb300-7"><a href="c07-modeling.html#cb300-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_na =</span> <span class="fu">unweighted</span>(<span class="fu">sum</span>(<span class="fu">is.na</span>(SummerTempNight)))</span>
<span id="cb300-8"><a href="c07-modeling.html#cb300-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 4 × 5
##   Region      SMN SMN_se     n  n_na
##   &lt;fct&gt;     &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt; &lt;int&gt;
## 1 Northeast  70.5  0.197   682     0
## 2 Midwest    71.4  0.151  1235     0
## 3 South      72.0  0.118  1917     0
## 4 West       72.1  0.299  1115     0</code></pre>
<p>In the following code, we test whether this temperature varies by region by first using <code>svyglm()</code> to run the test and then using <code>broom::tidy()</code> to display the output. Note that the temperature setting is set to NA when the household does not use air-conditioning, and thus <code>na.action=na.omit</code> is specified to ignore these cases.</p>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="c07-modeling.html#cb302-1" aria-hidden="true" tabindex="-1"></a>anova_out <span class="ot">&lt;-</span> recs_des <span class="sc">%&gt;%</span></span>
<span id="cb302-2"><a href="c07-modeling.html#cb302-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyglm</span>(<span class="at">design =</span> .,</span>
<span id="cb302-3"><a href="c07-modeling.html#cb302-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">formula =</span> SummerTempNight <span class="sc">~</span> Region,</span>
<span id="cb302-4"><a href="c07-modeling.html#cb302-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">na.action =</span> na.omit)</span>
<span id="cb302-5"><a href="c07-modeling.html#cb302-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb302-6"><a href="c07-modeling.html#cb302-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(anova_out)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 5
##   term          estimate std.error statistic   p.value
##   &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)     70.5       0.197    358.   1.84e-146
## 2 RegionMidwest    0.874     0.253      3.46 8.18e-  4
## 3 RegionSouth      1.49      0.231      6.45 5.20e-  9
## 4 RegionWest       1.66      0.353      4.70 9.27e-  6</code></pre>
<p>In the output above, we can see the estimated coefficients (<code>estimate</code>), estimated standard errors of the coefficients (<code>std.error</code>), the t-statistic (<code>statistic</code>), and the p-value for each coefficient. In this output, the intercept represents the reference value of the Northeast region<a href="#fn25" class="footnote-ref" id="fnref25"><sup>25</sup></a>. The other coefficients indicate the difference in temperature relative to the Northeast region. For example, in the Midwest, temperatures are set, on average, 0.874 degrees higher than in the Northeast during summer nights.</p>
</div>
</div>
<div id="gaussian-linear-regression" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Gaussian Linear regression<a href="c07-modeling.html#gaussian-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Gaussian linear regression is a more generalized method than ANOVA where we fit a model of a continuous outcome with any number of categorical or continuous predictors, such that</p>
<p><span class="math display">\[y_i=\beta_0 +\sum_{i=1}^p \beta_i x_i + \epsilon_i\]</span></p>
<p>where <span class="math inline">\(y_i\)</span> is the outcome, <span class="math inline">\(\beta_0\)</span> is an intercept, <span class="math inline">\(x_1, \cdots, x_n\)</span> are the predictors with <span class="math inline">\(\beta_1, \cdots, \beta_p\)</span> as the associated coefficients, and <span class="math inline">\(\epsilon_i\)</span> is the error.</p>
<p>Assumptions in Gaussian linear regression using survey data include:</p>
<ul>
<li>The residuals (<span class="math inline">\(\epsilon_i\)</span>) are normally distributed, but there is not an assumption of independence, and the correlation structure is captured in the survey design object</li>
<li>There is a linear relationship between the outcome variable and the independent variables</li>
<li>The residuals are homoscedastic, that is, the error term is the same across all values of independent variables</li>
</ul>
<div id="syntax-11" class="section level3 hasAnchor" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> Syntax<a href="c07-modeling.html#syntax-11" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The syntax for linear regression uses the same function as ANOVA, but can have more than one variable listed on the right-hand side of the formula:</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="c07-modeling.html#cb304-1" aria-hidden="true" tabindex="-1"></a>des_obj <span class="sc">%&gt;%</span></span>
<span id="cb304-2"><a href="c07-modeling.html#cb304-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyglm</span>(</span>
<span id="cb304-3"><a href="c07-modeling.html#cb304-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb304-4"><a href="c07-modeling.html#cb304-4" aria-hidden="true" tabindex="-1"></a>    outcomevar <span class="sc">~</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x3,</span>
<span id="cb304-5"><a href="c07-modeling.html#cb304-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.action =</span> na.omit,</span>
<span id="cb304-6"><a href="c07-modeling.html#cb304-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">df.resid =</span> <span class="fu">degf</span>(.)</span>
<span id="cb304-7"><a href="c07-modeling.html#cb304-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>As discussed at the beginning of the chapter, the formula on the right-hand side can be specified in many ways, whether interactions are desired or not, for example.</p>
</div>
<div id="example-11" class="section level3 hasAnchor" number="7.3.2">
<h3><span class="header-section-number">7.3.2</span> Example<a href="c07-modeling.html#example-11" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>On RECS, we can obtain information on the square footage of homes and the electric bills. We assume that square footage is related to the amount of money spent on electricity and examine a model for this. Before any modeling, we first plot the data to determine whether it is reasonable to assume a linear relationship. In the plot below, each hexagon represents the weighted count of households in the bin and we can see a general positive linear trend (as the square footage increases so does the amount of money spent on electricity).</p>
<div class="figure"><span style="display:block;" id="fig:model-plot-sf-elbill"></span>
<img src="bookdown_files/figure-html/model-plot-sf-elbill-1.png" alt="Relationship between square footage and dollars spent on electricity, RECS 2015" width="672" />
<p class="caption">
FIGURE 7.1: Relationship between square footage and dollars spent on electricity, RECS 2015
</p>
</div>
<p>Given that the plot shows a potential relationship, fitting a model will allow us to determine if the relationship is statistically significant. The model is fit below with electricity expenditure as the outcome.</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="c07-modeling.html#cb305-1" aria-hidden="true" tabindex="-1"></a>m_electric_sqft <span class="ot">&lt;-</span> recs_des <span class="sc">%&gt;%</span></span>
<span id="cb305-2"><a href="c07-modeling.html#cb305-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyglm</span>(<span class="at">design =</span> .,</span>
<span id="cb305-3"><a href="c07-modeling.html#cb305-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">formula =</span> DOLLAREL <span class="sc">~</span> TOTSQFT_EN,</span>
<span id="cb305-4"><a href="c07-modeling.html#cb305-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">na.action =</span> na.omit)</span>
<span id="cb305-5"><a href="c07-modeling.html#cb305-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m_electric_sqft)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)  880.      26.3         33.4 5.51e-54
## 2 TOTSQFT_EN     0.246    0.0134      18.4 6.01e-33</code></pre>
<p>In the output above, we can see the estimated coefficients (<code>estimate</code>), estimated standard errors of the coefficients (<code>std.error</code>), the t-statistic (<code>statistic</code>), and the p-value for each coefficient. In these results, we can say that, on average, for every additional square foot of house size, the electricity bill increases by 24.6 cents and that square footage is significantly associated with electricity expenditure. This is a very simple model, and there are likely many more factors in electricity expenditure, including the type of cooling, number of appliances, location, and more. However, often starting with one variable models can help researchers understand what potential relationships there are between variables before fitting more complex models. Often researchers start with known relationships before building models to determine what impact additional variables have on the model.</p>
<p>In the following example, a model is fit to predict electricity expenditure, including Census region (factor/categorical), urbanicity (factor/categorical), square footage (double/numeric), and whether air-conditioning is used (logical/categorical) with all two-way interactions also included. As a reminder, using <code>-1</code> means that we are fitting this model without an intercept.</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="c07-modeling.html#cb307-1" aria-hidden="true" tabindex="-1"></a>m_electric_multi <span class="ot">&lt;-</span> recs_des <span class="sc">%&gt;%</span></span>
<span id="cb307-2"><a href="c07-modeling.html#cb307-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyglm</span>(</span>
<span id="cb307-3"><a href="c07-modeling.html#cb307-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb307-4"><a href="c07-modeling.html#cb307-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> DOLLAREL <span class="sc">~</span> (Region <span class="sc">+</span> Urbanicity <span class="sc">+</span> TOTSQFT_EN <span class="sc">+</span> ACUsed)<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="dv">1</span>, </span>
<span id="cb307-5"><a href="c07-modeling.html#cb307-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.action =</span> na.omit</span>
<span id="cb307-6"><a href="c07-modeling.html#cb307-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb307-7"><a href="c07-modeling.html#cb307-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb307-8"><a href="c07-modeling.html#cb307-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m_electric_multi) <span class="sc">%&gt;%</span> <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">50</span>) </span></code></pre></div>
<pre><code>## # A tibble: 25 × 5
##    term                            estimate std.error statistic  p.value
##    &lt;chr&gt;                              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
##  1 RegionNortheast                  6.19e+2   94.8       6.53   8.42e- 9
##  2 RegionMidwest                    4.98e+2   79.4       6.27   2.47e- 8
##  3 RegionSouth                      8.55e+2   97.4       8.78   6.01e-13
##  4 RegionWest                       4.76e+2   60.8       7.83   3.49e-11
##  5 UrbanicityUrban Cluster         -1.18e+2  116.       -1.02   3.12e- 1
##  6 UrbanicityRural                  2.22e+2  107.        2.07   4.16e- 2
##  7 TOTSQFT_EN                       1.96e-1    0.0474    4.13   9.69e- 5
##  8 ACUsedTRUE                       2.85e+2  105.        2.72   8.30e- 3
##  9 RegionMidwest:UrbanicityUrban …  3.16e+2  101.        3.13   2.51e- 3
## 10 RegionSouth:UrbanicityUrban Cl…  4.00e+1  107.        0.373  7.10e- 1
## 11 RegionWest:UrbanicityUrban Clu…  2.39e+2  112.        2.13   3.65e- 2
## 12 RegionMidwest:UrbanicityRural    4.68e+2   89.8       5.21   1.77e- 6
## 13 RegionSouth:UrbanicityRural      1.74e+2   99.2       1.76   8.31e- 2
## 14 RegionWest:UrbanicityRural       1.64e+2  105.        1.57   1.21e- 1
## 15 RegionMidwest:TOTSQFT_EN        -5.24e-2    0.0364   -1.44   1.55e- 1
## 16 RegionSouth:TOTSQFT_EN           6.08e-2    0.0426    1.43   1.58e- 1
## 17 RegionWest:TOTSQFT_EN            3.50e-2    0.0441    0.793  4.30e- 1
## 18 RegionMidwest:ACUsedTRUE        -1.34e+2  110.       -1.22   2.26e- 1
## 19 RegionSouth:ACUsedTRUE          -1.36e+2  106.       -1.29   2.02e- 1
## 20 RegionWest:ACUsedTRUE           -6.26e+1  100.       -0.625  5.34e- 1
## 21 UrbanicityUrban Cluster:TOTSQF… -2.09e-2    0.0337   -0.619  5.38e- 1
## 22 UrbanicityRural:TOTSQFT_EN      -7.89e-2    0.0269   -2.93   4.56e- 3
## 23 UrbanicityUrban Cluster:ACUsed… -3.37e+1   88.5      -0.380  7.05e- 1
## 24 UrbanicityRural:ACUsedTRUE       3.10e+0   89.7       0.0345 9.73e- 1
## 25 TOTSQFT_EN:ACUsedTRUE            5.20e-2    0.0371    1.40   1.65e- 1</code></pre>
<p>As shown above, there are many terms in this model. To test whether coefficients for a term are different from zero, the function <code>regTermTest()</code> can be used. For example, in the above regression, we can test whether the interaction of region and urbanicity is significant as follows:</p>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="c07-modeling.html#cb309-1" aria-hidden="true" tabindex="-1"></a>urb_reg_test <span class="ot">&lt;-</span> <span class="fu">regTermTest</span>(m_electric_multi, <span class="sc">~</span>Urbanicity<span class="sc">:</span>Region)</span>
<span id="cb309-2"><a href="c07-modeling.html#cb309-2" aria-hidden="true" tabindex="-1"></a>urb_reg_test</span></code></pre></div>
<pre><code>## Wald test for Urbanicity:Region
##  in svyglm(design = ., formula = DOLLAREL ~ (Region + Urbanicity + 
##     TOTSQFT_EN + ACUsed)^2 - 1, na.action = na.omit)
## F =  7.167  on  6  and  71  df: p= 5.3e-06</code></pre>
<p>As demonstrated above, there is a significant interaction between urbanicity and region (p-value=5.34^{-6}).</p>
<p>To examine the predictions, residuals and more from the model, the function <code>augment()</code> from {broom} can be used. The <code>augment()</code> function will return a tibble with the independent and dependent variables and other fit statistics. The <code>augment()</code> function has not been specifically written for objects of class <code>svyglm</code>, and as such, a warning will be displayed indicating this at this time. As it was not written exactly for this class of objects, a little tweaking needs to be done after using augment to get the predicted (<code>.fitted</code>) and standard error (<code>.se.fit</code>) values. To obtain the standard error of the fitted values we need to use the <code>attr()</code> function on the <code>.fitted</code> values created by <code>augment()</code>.</p>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="c07-modeling.html#cb311-1" aria-hidden="true" tabindex="-1"></a>fitstats <span class="ot">&lt;-</span></span>
<span id="cb311-2"><a href="c07-modeling.html#cb311-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(m_electric_multi) <span class="sc">%&gt;%</span></span>
<span id="cb311-3"><a href="c07-modeling.html#cb311-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">.se.fit =</span> <span class="fu">sqrt</span>(<span class="fu">attr</span>(.fitted, <span class="st">&quot;var&quot;</span>)), </span>
<span id="cb311-4"><a href="c07-modeling.html#cb311-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">.fitted =</span> <span class="fu">as.numeric</span>(.fitted)) </span></code></pre></div>
<pre><code>## Warning: The `augment()` method for objects of class `svrepglm` is not maintained by the broom team, and is only supported through the `glm` tidier method. Please be cautious in interpreting and reporting broom output.
## 
## This warning is displayed once per session.</code></pre>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb313-1"><a href="c07-modeling.html#cb313-1" aria-hidden="true" tabindex="-1"></a>fitstats</span></code></pre></div>
<pre><code>## # A tibble: 5,686 × 13
##    DOLLAREL Region    Urbanicity   TOTSQFT_EN ACUsed `(weights)` .fitted
##       &lt;dbl&gt; &lt;fct&gt;     &lt;fct&gt;             &lt;dbl&gt; &lt;lgl&gt;        &lt;dbl&gt;   &lt;dbl&gt;
##  1     967. West      Urban Area         1808 TRUE         0.581   1209.
##  2    1366  South     Rural               759 TRUE         0.693   1577.
##  3    2428. South     Urban Area         2288 TRUE         1.12    1710.
##  4    1313. Midwest   Urban Clust…       2573 TRUE         0.585   1261.
##  5     581. Northeast Urban Area         1024 TRUE         0.804   1157.
##  6     494  Northeast Urban Clust…        623 TRUE         1.25     893.
##  7     372. South     Urban Area          832 TRUE         2.21    1261.
##  8    1737. Midwest   Rural              2682 TRUE         0.735   1654.
##  9    1532. Northeast Urban Area         1900 TRUE         0.675   1375.
## 10    1974. South     Urban Area         1230 TRUE         2.09    1383.
## # ℹ 5,676 more rows
## # ℹ 6 more variables: .resid &lt;dbl&gt;, .hat &lt;dbl&gt;, .sigma &lt;dbl&gt;,
## #   .cooksd &lt;dbl&gt;, .std.resid &lt;dbl&gt;, .se.fit &lt;dbl&gt;</code></pre>
<p>These results can then be used in a variety of ways, including examining residual plots as illustrated below:</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="c07-modeling.html#cb315-1" aria-hidden="true" tabindex="-1"></a>fitstats <span class="sc">%&gt;%</span></span>
<span id="cb315-2"><a href="c07-modeling.html#cb315-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .fitted, .resid)) <span class="sc">+</span></span>
<span id="cb315-3"><a href="c07-modeling.html#cb315-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb315-4"><a href="c07-modeling.html#cb315-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">colour =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb315-5"><a href="c07-modeling.html#cb315-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb315-6"><a href="c07-modeling.html#cb315-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Fitted value of electricity cost&quot;</span>) <span class="sc">+</span></span>
<span id="cb315-7"><a href="c07-modeling.html#cb315-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Residual of model&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:model-aug-examp-plot"></span>
<img src="bookdown_files/figure-html/model-aug-examp-plot-1.png" alt="Residual plot of electric cost model with covariates Region, Urbanicity, TOTSQFT_EN, and ACUsed" width="672" />
<p class="caption">
FIGURE 7.2: Residual plot of electric cost model with covariates Region, Urbanicity, TOTSQFT_EN, and ACUsed
</p>
</div>
<p>Additionally, <code>augment()</code> can be used to predict outcomes for data not used in modeling. Perhaps, we would like to predict the energy expenditure for a home in an urban area in the south that uses air-conditioning and is 2,500 square feet. First, make a tibble including that additional data and then use the <code>newdata</code> argument in the augment function. As before, to obtain the standard error of the predicted values we need to use the <code>attr()</code> function.</p>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="c07-modeling.html#cb316-1" aria-hidden="true" tabindex="-1"></a>add_data <span class="ot">&lt;-</span></span>
<span id="cb316-2"><a href="c07-modeling.html#cb316-2" aria-hidden="true" tabindex="-1"></a>  recs_in <span class="sc">%&gt;%</span> <span class="fu">select</span>(DOEID,</span>
<span id="cb316-3"><a href="c07-modeling.html#cb316-3" aria-hidden="true" tabindex="-1"></a>                     Region,</span>
<span id="cb316-4"><a href="c07-modeling.html#cb316-4" aria-hidden="true" tabindex="-1"></a>                     Urbanicity,</span>
<span id="cb316-5"><a href="c07-modeling.html#cb316-5" aria-hidden="true" tabindex="-1"></a>                     TOTSQFT_EN,</span>
<span id="cb316-6"><a href="c07-modeling.html#cb316-6" aria-hidden="true" tabindex="-1"></a>                     ACUsed,</span>
<span id="cb316-7"><a href="c07-modeling.html#cb316-7" aria-hidden="true" tabindex="-1"></a>                     DOLLAREL) <span class="sc">%&gt;%</span></span>
<span id="cb316-8"><a href="c07-modeling.html#cb316-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbind</span>(</span>
<span id="cb316-9"><a href="c07-modeling.html#cb316-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tibble</span>(</span>
<span id="cb316-10"><a href="c07-modeling.html#cb316-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">DOEID =</span> <span class="cn">NA</span>,</span>
<span id="cb316-11"><a href="c07-modeling.html#cb316-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">Region =</span> <span class="st">&quot;South&quot;</span>,</span>
<span id="cb316-12"><a href="c07-modeling.html#cb316-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">Urbanicity =</span> <span class="st">&quot;Urban Area&quot;</span>,</span>
<span id="cb316-13"><a href="c07-modeling.html#cb316-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">TOTSQFT_EN =</span> <span class="dv">2500</span>,</span>
<span id="cb316-14"><a href="c07-modeling.html#cb316-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">ACUsed =</span> <span class="cn">TRUE</span>,</span>
<span id="cb316-15"><a href="c07-modeling.html#cb316-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">DOLLAREL =</span> <span class="cn">NA</span></span>
<span id="cb316-16"><a href="c07-modeling.html#cb316-16" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb316-17"><a href="c07-modeling.html#cb316-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb316-18"><a href="c07-modeling.html#cb316-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tail</span>(<span class="dv">1</span>)</span>
<span id="cb316-19"><a href="c07-modeling.html#cb316-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb316-20"><a href="c07-modeling.html#cb316-20" aria-hidden="true" tabindex="-1"></a>pred_data <span class="ot">&lt;-</span> <span class="fu">augment</span>(m_electric_multi, <span class="at">newdata =</span> add_data) <span class="sc">%&gt;%</span></span>
<span id="cb316-21"><a href="c07-modeling.html#cb316-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">.se.fit =</span> <span class="fu">sqrt</span>(<span class="fu">attr</span>(.fitted, <span class="st">&quot;var&quot;</span>)), </span>
<span id="cb316-22"><a href="c07-modeling.html#cb316-22" aria-hidden="true" tabindex="-1"></a>         <span class="at">.fitted =</span> <span class="fu">as.numeric</span>(.fitted)) </span>
<span id="cb316-23"><a href="c07-modeling.html#cb316-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb316-24"><a href="c07-modeling.html#cb316-24" aria-hidden="true" tabindex="-1"></a>pred_data </span></code></pre></div>
<pre><code>## # A tibble: 1 × 8
##   DOEID Region Urbanicity TOTSQFT_EN ACUsed DOLLAREL .fitted .se.fit
##   &lt;dbl&gt; &lt;fct&gt;  &lt;fct&gt;           &lt;dbl&gt; &lt;lgl&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1    NA South  Urban Area       2500 TRUE         NA   1775.    37.2</code></pre>
<p>In the above example, it is predicted that the energy expenditure would be $1775.48.</p>
</div>
</div>
<div id="logistic-regression" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Logistic regression<a href="c07-modeling.html#logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Logistic regression is used to model a binary outcome and is a specific generalized linear model (GLM). A GLM uses a link function to link the response variable to the linear model. In logistic regression, the link model is the logit function. Specifically, the model is specified as follows:</p>
<p><span class="math display">\[ y_i \sim \text{Bernoulli}(\pi_i)\]</span></p>
<span class="math display" id="eq:logoddlin">\[\begin{equation}
\log \left(\frac{\pi_i}{1-\pi_i} \right)=\beta_0 +\sum_{i=1}^p \beta_i x_i
\tag{7.1}
\end{equation}\]</span>
<p>which can be re-expressed as</p>
<p><span class="math display">\[ \pi_i=\frac{\exp \left(\beta_0 +\sum_{i=1}^p \beta_i x_i \right)}{1+\exp \left(\beta_0 +\sum_{i=1}^p \beta_i x_i \right)}.\]</span> where <span class="math inline">\(y_i\)</span> is the outcome, <span class="math inline">\(\beta_0\)</span> is an intercept, and <span class="math inline">\(x_1, \cdots, x_n\)</span> are the predictors with <span class="math inline">\(\beta_1, \cdots, \beta_n\)</span> as the associated coefficients.</p>
<p>Assumptions in logistic regression using survey data include:</p>
<ul>
<li>The outcome variable has two levels</li>
<li>There is a linear relationship between the independent variables and the log odds (Equation <a href="c07-modeling.html#eq:logoddlin">(7.1)</a>)</li>
<li>The residuals are homoscedastic, that is, the error term is the same across all values of independent variables</li>
</ul>
<div id="syntax-12" class="section level3 hasAnchor" number="7.4.1">
<h3><span class="header-section-number">7.4.1</span> Syntax<a href="c07-modeling.html#syntax-12" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The syntax for logistic regression is as follows:</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="c07-modeling.html#cb318-1" aria-hidden="true" tabindex="-1"></a>des_obj <span class="sc">%&gt;%</span></span>
<span id="cb318-2"><a href="c07-modeling.html#cb318-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyglm</span>(</span>
<span id="cb318-3"><a href="c07-modeling.html#cb318-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb318-4"><a href="c07-modeling.html#cb318-4" aria-hidden="true" tabindex="-1"></a>    outcomevar <span class="sc">~</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x3,</span>
<span id="cb318-5"><a href="c07-modeling.html#cb318-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.action =</span> na.omit,</span>
<span id="cb318-6"><a href="c07-modeling.html#cb318-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">df.resid =</span> <span class="fu">degf</span>(.),</span>
<span id="cb318-7"><a href="c07-modeling.html#cb318-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> quasibinomial  <span class="co">#use this to avoid warning about non-integers</span></span>
<span id="cb318-8"><a href="c07-modeling.html#cb318-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>Note <code>svyglm()</code> is the same function used in both ANOVA and linear regression. However, we’ve added the link function quasibinomial. While we can use the binomial link function, it is recommended to use the quasibinomial as our weights may not be integers, and the quasibinomial also allows for overdispersion. The quasibinomial family has a default logit link which is what is specified in the equations above. When specifying the outcome variable, it will likely be specified in one of two ways with survey data:</p>
<ul>
<li>A factor variable where not being the first level of the factor indicates a “success”</li>
<li>A numeric variable which is 1 or 0 where 1 indicates a success</li>
<li>A logical variable where TRUE indicates a success</li>
</ul>
</div>
<div id="example-12" class="section level3 hasAnchor" number="7.4.2">
<h3><span class="header-section-number">7.4.2</span> Example<a href="c07-modeling.html#example-12" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the following example, the ANES data is used, and we are modeling whether someone usually has trust in the government<a href="#fn26" class="footnote-ref" id="fnref26"><sup>26</sup></a> by who someone voted for in 2020. As a reminder, the leading candidates were Biden and Trump though people could vote for someone else not in the Democratic or Republican parties. Those votes are all grouped into an “Other” category. We first create a binary outcome for trusting in the government and plot the data. A scatter plot of the raw data is not useful as it is all 0 and 1 outcomes, so instead, we plot a summary of the data.</p>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb319-1"><a href="c07-modeling.html#cb319-1" aria-hidden="true" tabindex="-1"></a>anes_des_der <span class="ot">&lt;-</span> anes_des <span class="sc">%&gt;%</span></span>
<span id="cb319-2"><a href="c07-modeling.html#cb319-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">TrustGovernmentUsually =</span> <span class="fu">case_when</span>(</span>
<span id="cb319-3"><a href="c07-modeling.html#cb319-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">is.na</span>(TrustGovernment) <span class="sc">~</span> <span class="cn">NA</span>,</span>
<span id="cb319-4"><a href="c07-modeling.html#cb319-4" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> TrustGovernment <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Always&quot;</span>, <span class="st">&quot;Most of the time&quot;</span>)</span>
<span id="cb319-5"><a href="c07-modeling.html#cb319-5" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb319-6"><a href="c07-modeling.html#cb319-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb319-7"><a href="c07-modeling.html#cb319-7" aria-hidden="true" tabindex="-1"></a>anes_des_der <span class="sc">%&gt;%</span></span>
<span id="cb319-8"><a href="c07-modeling.html#cb319-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(VotedPres2020_selection) <span class="sc">%&gt;%</span></span>
<span id="cb319-9"><a href="c07-modeling.html#cb319-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb319-10"><a href="c07-modeling.html#cb319-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_trust =</span> <span class="fu">survey_mean</span>(</span>
<span id="cb319-11"><a href="c07-modeling.html#cb319-11" aria-hidden="true" tabindex="-1"></a>      TrustGovernmentUsually,</span>
<span id="cb319-12"><a href="c07-modeling.html#cb319-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">na.rm =</span> <span class="cn">TRUE</span>,</span>
<span id="cb319-13"><a href="c07-modeling.html#cb319-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">proportion =</span> <span class="cn">TRUE</span>,</span>
<span id="cb319-14"><a href="c07-modeling.html#cb319-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">vartype =</span> <span class="st">&quot;ci&quot;</span></span>
<span id="cb319-15"><a href="c07-modeling.html#cb319-15" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb319-16"><a href="c07-modeling.html#cb319-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb319-17"><a href="c07-modeling.html#cb319-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb319-18"><a href="c07-modeling.html#cb319-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">complete.cases</span>(.)) <span class="sc">%&gt;%</span></span>
<span id="cb319-19"><a href="c07-modeling.html#cb319-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> VotedPres2020_selection, <span class="at">y =</span> pct_trust, </span>
<span id="cb319-20"><a href="c07-modeling.html#cb319-20" aria-hidden="true" tabindex="-1"></a>             <span class="at">fill =</span> VotedPres2020_selection)) <span class="sc">+</span></span>
<span id="cb319-21"><a href="c07-modeling.html#cb319-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span></span>
<span id="cb319-22"><a href="c07-modeling.html#cb319-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> pct_trust_low, <span class="at">ymax =</span> pct_trust_upp), </span>
<span id="cb319-23"><a href="c07-modeling.html#cb319-23" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb319-24"><a href="c07-modeling.html#cb319-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;#0b3954&quot;</span>, <span class="st">&quot;#bfd7ea&quot;</span>, <span class="st">&quot;#8d6b94&quot;</span>)) <span class="sc">+</span></span>
<span id="cb319-25"><a href="c07-modeling.html#cb319-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Election choice (2022)&quot;</span>) <span class="sc">+</span></span>
<span id="cb319-26"><a href="c07-modeling.html#cb319-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Usually trust the government&quot;</span>) <span class="sc">+</span></span>
<span id="cb319-27"><a href="c07-modeling.html#cb319-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb319-28"><a href="c07-modeling.html#cb319-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb319-29"><a href="c07-modeling.html#cb319-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:model-logisticexamp-plot"></span>
<img src="bookdown_files/figure-html/model-logisticexamp-plot-1.png" alt="Relationship between candidate selection and trust in government, ANES 2020" width="672" />
<p class="caption">
FIGURE 7.3: Relationship between candidate selection and trust in government, ANES 2020
</p>
</div>
<p>Next, we fit the model.</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="c07-modeling.html#cb320-1" aria-hidden="true" tabindex="-1"></a>logistic_trust_vote <span class="ot">&lt;-</span> anes_des_der <span class="sc">%&gt;%</span></span>
<span id="cb320-2"><a href="c07-modeling.html#cb320-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyglm</span>(</span>
<span id="cb320-3"><a href="c07-modeling.html#cb320-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb320-4"><a href="c07-modeling.html#cb320-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> TrustGovernmentUsually <span class="sc">~</span> VotedPres2020_selection ,</span>
<span id="cb320-5"><a href="c07-modeling.html#cb320-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> quasibinomial</span>
<span id="cb320-6"><a href="c07-modeling.html#cb320-6" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb320-7"><a href="c07-modeling.html#cb320-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb320-8"><a href="c07-modeling.html#cb320-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(logistic_trust_vote)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 5
##   term                         estimate std.error statistic  p.value
##   &lt;chr&gt;                           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)                    -1.96     0.0740    -26.5  1.10e-30
## 2 VotedPres2020_selectionTrump    0.397    0.102       3.90 2.89e- 4
## 3 VotedPres2020_selectionOther   -0.768    0.462      -1.66 1.03e- 1</code></pre>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="c07-modeling.html#cb322-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(logistic_trust_vote, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(term, estimate)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 2
##   term                         estimate
##   &lt;chr&gt;                           &lt;dbl&gt;
## 1 (Intercept)                     0.141
## 2 VotedPres2020_selectionTrump    1.49 
## 3 VotedPres2020_selectionOther    0.464</code></pre>
<p>In the output above, we can see the estimated coefficients (<code>estimate</code>), estimated standard errors of the coefficients (<code>std.error</code>), the t-statistic (<code>statistic</code>), and the p-value for each coefficient when the <code>tidy()</code> function is run the first time. The second time the <code>tidy</code> function is used, the coefficients are exponentiated, which illustrates the odds. In this example, we can interpret this as saying that the odds of trusting in government for someone who voted for Trump is 149% as likely to trust the government compared to a person who voted for Biden (the reference level). In comparison, a person who voted for neither Biden nor Trump is 46.4% as likely to trust the government as someone who voted for Biden.</p>
<p>As with linear regression, the <code>augment()</code> can be used to predict values. By default, the prediction is the link function and not the probability. To predict the probability, add an argument of <code>type.predict="response"</code> as demonstrated below:</p>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb324-1"><a href="c07-modeling.html#cb324-1" aria-hidden="true" tabindex="-1"></a>logistic_trust_vote <span class="sc">%&gt;%</span></span>
<span id="cb324-2"><a href="c07-modeling.html#cb324-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(<span class="at">type.predict =</span> <span class="st">&quot;response&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb324-3"><a href="c07-modeling.html#cb324-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">.se.fit =</span> <span class="fu">sqrt</span>(<span class="fu">attr</span>(.fitted, <span class="st">&quot;var&quot;</span>)), <span class="co"># extract the variance of the fitted value </span></span>
<span id="cb324-4"><a href="c07-modeling.html#cb324-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">.fitted =</span> <span class="fu">as.numeric</span>(.fitted)) <span class="sc">%&gt;%</span></span>
<span id="cb324-5"><a href="c07-modeling.html#cb324-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(TrustGovernmentUsually,</span>
<span id="cb324-6"><a href="c07-modeling.html#cb324-6" aria-hidden="true" tabindex="-1"></a>         VotedPres2020_selection,</span>
<span id="cb324-7"><a href="c07-modeling.html#cb324-7" aria-hidden="true" tabindex="-1"></a>         .fitted,</span>
<span id="cb324-8"><a href="c07-modeling.html#cb324-8" aria-hidden="true" tabindex="-1"></a>         .se.fit) </span></code></pre></div>
<pre><code>## Warning: The `augment()` method for objects of class `svyglm` is not maintained by the broom team, and is only supported through the `glm` tidier method. Please be cautious in interpreting and reporting broom output.
## 
## This warning is displayed once per session.</code></pre>
<pre><code>## # A tibble: 5,860 × 4
##    TrustGovernmentUsually VotedPres2020_selection .fitted .se.fit
##    &lt;lgl&gt;                  &lt;fct&gt;                     &lt;dbl&gt;   &lt;dbl&gt;
##  1 FALSE                  Other                    0.0614 0.0266 
##  2 FALSE                  Biden                    0.124  0.00801
##  3 FALSE                  Biden                    0.124  0.00801
##  4 FALSE                  Trump                    0.173  0.00959
##  5 FALSE                  Biden                    0.124  0.00801
##  6 FALSE                  Trump                    0.173  0.00959
##  7 FALSE                  Biden                    0.124  0.00801
##  8 TRUE                   Biden                    0.124  0.00801
##  9 FALSE                  Biden                    0.124  0.00801
## 10 FALSE                  Trump                    0.173  0.00959
## # ℹ 5,850 more rows</code></pre>
</div>
</div>
<div id="exercises-2" class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> Exercises<a href="c07-modeling.html#exercises-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>The type of housing unit may have an impact on energy expenses. Is there any relationship between housing unit type (<code>HousingUnitType</code>) and total energy expenditure (<code>TOTALDOL</code>)? First, find the average energy expenditure by housing unit type as a descriptive analysis and then do the test. The reference level in the comparison should be the housing unit type that is most common.</li>
</ol>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb327-1"><a href="c07-modeling.html#cb327-1" aria-hidden="true" tabindex="-1"></a>recs_des <span class="sc">%&gt;%</span></span>
<span id="cb327-2"><a href="c07-modeling.html#cb327-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HousingUnitType) <span class="sc">%&gt;%</span></span>
<span id="cb327-3"><a href="c07-modeling.html#cb327-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Expense =</span> <span class="fu">survey_mean</span>(TOTALDOL, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb327-4"><a href="c07-modeling.html#cb327-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">HUs =</span> <span class="fu">survey_total</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb327-5"><a href="c07-modeling.html#cb327-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(HUs))</span></code></pre></div>
<pre><code>## # A tibble: 5 × 5
##   HousingUnitType            Expense Expense_se       HUs   HUs_se
##   &lt;fct&gt;                        &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 Single-family detached       2193.       22.0 73871041. 0.00645 
## 2 Apartment: 5 or more units   1048.       21.2 21147792. 0.00271 
## 3 Apartment: 2-4 Units         1332.       36.6  9392242. 0.000239
## 4 Single-family attached       1607.       33.8  7010132. 0.0253  
## 5 Mobile home                  1752.       60.2  6787043. 0.0183</code></pre>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="c07-modeling.html#cb329-1" aria-hidden="true" tabindex="-1"></a>exp_unit_out <span class="ot">&lt;-</span> recs_des <span class="sc">%&gt;%</span></span>
<span id="cb329-2"><a href="c07-modeling.html#cb329-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">HousingUnitType =</span> <span class="fu">fct_infreq</span>(HousingUnitType, NWEIGHT)) <span class="sc">%&gt;%</span></span>
<span id="cb329-3"><a href="c07-modeling.html#cb329-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyglm</span>(</span>
<span id="cb329-4"><a href="c07-modeling.html#cb329-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb329-5"><a href="c07-modeling.html#cb329-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> TOTALDOL <span class="sc">~</span> HousingUnitType,</span>
<span id="cb329-6"><a href="c07-modeling.html#cb329-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.action =</span> na.omit</span>
<span id="cb329-7"><a href="c07-modeling.html#cb329-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb329-8"><a href="c07-modeling.html#cb329-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb329-9"><a href="c07-modeling.html#cb329-9" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(exp_unit_out)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 5
##   term                             estimate std.error statistic  p.value
##   &lt;chr&gt;                               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)                         2193.      22.0     99.6  1.07e-94
## 2 HousingUnitTypeApartment: 5 or …   -1145.      30.6    -37.4  5.08e-57
## 3 HousingUnitTypeApartment: 2-4 U…    -861.      42.2    -20.4  1.06e-35
## 4 HousingUnitTypeSingle-family at…    -585.      41.2    -14.2  8.02e-25
## 5 HousingUnitTypeMobile home          -441.      61.8     -7.13 2.33e-10</code></pre>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="c07-modeling.html#cb331-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Single-family detached units are most common</span></span>
<span id="cb331-2"><a href="c07-modeling.html#cb331-2" aria-hidden="true" tabindex="-1"></a><span class="co"># There is a significant relationship between energy expenditure and housing unit type</span></span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Does temperature play a role in energy expenditure? Cooling degree days are a measure of how hot a place is. CDD65 for a given day indicates the number of degrees Fahrenheit warmer than 65°F (18.3°C) it is in a location. On a day that averages 65°F and below, CDD65=0. While a day that averages 85°F would have CDD80=20 because it is 20 degrees warmer. For each day in the year, this is summed to give an indicator of how hot the place is throughout the year. Similarly, HDD65 indicates the days colder than 65°F (18.3°C)<a href="#fn27" class="footnote-ref" id="fnref27"><sup>27</sup></a>. Can energy expenditure be predicted using these temperature indicators along with square footage? Is there a significant relationship? Include main effects and two-way interactions.</li>
</ol>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb332-1"><a href="c07-modeling.html#cb332-1" aria-hidden="true" tabindex="-1"></a>temps_sqft_exp <span class="ot">&lt;-</span> recs_des <span class="sc">%&gt;%</span></span>
<span id="cb332-2"><a href="c07-modeling.html#cb332-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyglm</span>(</span>
<span id="cb332-3"><a href="c07-modeling.html#cb332-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb332-4"><a href="c07-modeling.html#cb332-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> DOLLAREL <span class="sc">~</span> (TOTSQFT_EN <span class="sc">+</span> CDD65 <span class="sc">+</span> HDD65) <span class="sc">^</span> <span class="dv">2</span>,</span>
<span id="cb332-5"><a href="c07-modeling.html#cb332-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.action =</span> na.omit</span>
<span id="cb332-6"><a href="c07-modeling.html#cb332-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb332-7"><a href="c07-modeling.html#cb332-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb332-8"><a href="c07-modeling.html#cb332-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(temps_sqft_exp)</span></code></pre></div>
<pre><code>## # A tibble: 7 × 5
##   term                 estimate    std.error statistic       p.value
##   &lt;chr&gt;                   &lt;dbl&gt;        &lt;dbl&gt;     &lt;dbl&gt;         &lt;dbl&gt;
## 1 (Intercept)      353.         110.            3.20   0.00193      
## 2 TOTSQFT_EN         0.420        0.0643        6.53   0.00000000398
## 3 CDD65              0.128        0.0321        4.00   0.000128     
## 4 HDD65              0.0399       0.0172        2.32   0.0226       
## 5 TOTSQFT_EN:CDD65  -0.00000150   0.0000177    -0.0852 0.932        
## 6 TOTSQFT_EN:HDD65  -0.0000366    0.00000922   -3.97   0.000143     
## 7 CDD65:HDD65        0.0000232    0.00000835    2.78   0.00660</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Continuing with our results from question 2, create a plot between the actual and predicted expenditures and a residual plot for the predicted expenditures.</li>
</ol>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb334-1"><a href="c07-modeling.html#cb334-1" aria-hidden="true" tabindex="-1"></a>temps_sqft_exp_fit <span class="ot">&lt;-</span> temps_sqft_exp <span class="sc">%&gt;%</span></span>
<span id="cb334-2"><a href="c07-modeling.html#cb334-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span></span>
<span id="cb334-3"><a href="c07-modeling.html#cb334-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">.se.fit =</span> <span class="fu">sqrt</span>(<span class="fu">attr</span>(.fitted, <span class="st">&quot;var&quot;</span>)), </span>
<span id="cb334-4"><a href="c07-modeling.html#cb334-4" aria-hidden="true" tabindex="-1"></a>         <span class="co"># extract the variance of the fitted value</span></span>
<span id="cb334-5"><a href="c07-modeling.html#cb334-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">.fitted =</span> <span class="fu">as.numeric</span>(.fitted)) </span></code></pre></div>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="c07-modeling.html#cb335-1" aria-hidden="true" tabindex="-1"></a>temps_sqft_exp_fit <span class="sc">%&gt;%</span></span>
<span id="cb335-2"><a href="c07-modeling.html#cb335-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> DOLLAREL, <span class="at">y =</span> .fitted)) <span class="sc">+</span></span>
<span id="cb335-3"><a href="c07-modeling.html#cb335-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb335-4"><a href="c07-modeling.html#cb335-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>,</span>
<span id="cb335-5"><a href="c07-modeling.html#cb335-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">slope =</span> <span class="dv">1</span>,</span>
<span id="cb335-6"><a href="c07-modeling.html#cb335-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">colour =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb335-7"><a href="c07-modeling.html#cb335-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Actual expenditures&quot;</span>) <span class="sc">+</span></span>
<span id="cb335-8"><a href="c07-modeling.html#cb335-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Predicted expenditures&quot;</span>) <span class="sc">+</span></span>
<span id="cb335-9"><a href="c07-modeling.html#cb335-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:model-lin-sol-3-p1"></span>
<img src="bookdown_files/figure-html/model-lin-sol-3-p1-1.png" alt="Actual and predicted electricity expenditures" width="672" />
<p class="caption">
FIGURE 7.4: Actual and predicted electricity expenditures
</p>
</div>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="c07-modeling.html#cb336-1" aria-hidden="true" tabindex="-1"></a>temps_sqft_exp_fit <span class="sc">%&gt;%</span></span>
<span id="cb336-2"><a href="c07-modeling.html#cb336-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb336-3"><a href="c07-modeling.html#cb336-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb336-4"><a href="c07-modeling.html#cb336-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">colour =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb336-5"><a href="c07-modeling.html#cb336-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Predicted expenditure&quot;</span>) <span class="sc">+</span></span>
<span id="cb336-6"><a href="c07-modeling.html#cb336-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Residual value of expenditure&quot;</span>) <span class="sc">+</span></span>
<span id="cb336-7"><a href="c07-modeling.html#cb336-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:model-lin-sol-3-p2"></span>
<img src="bookdown_files/figure-html/model-lin-sol-3-p2-1.png" alt="Residual plot of electric cost model with covariates TOTSQFT_EN, CDD65, and HDD65" width="672" />
<p class="caption">
FIGURE 7.5: Residual plot of electric cost model with covariates TOTSQFT_EN, CDD65, and HDD65
</p>
</div>
<ol start="4" style="list-style-type: decimal">
<li>Early voting expanded in 2020<a href="#fn28" class="footnote-ref" id="fnref28"><sup>28</sup></a>. Build a logistic model predicting early voting in 2020 (<code>EarlyVote2020</code>) using age (<code>Age</code>), education (<code>Education</code>), and party identification (<code>PartyID</code>). Include two-way interactions.</li>
</ol>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="c07-modeling.html#cb337-1" aria-hidden="true" tabindex="-1"></a>earlyvote_mod <span class="ot">&lt;-</span> anes_des <span class="sc">%&gt;%</span></span>
<span id="cb337-2"><a href="c07-modeling.html#cb337-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(EarlyVote2020)) <span class="sc">%&gt;%</span></span>
<span id="cb337-3"><a href="c07-modeling.html#cb337-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">svyglm</span>(</span>
<span id="cb337-4"><a href="c07-modeling.html#cb337-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> .,</span>
<span id="cb337-5"><a href="c07-modeling.html#cb337-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> EarlyVote2020 <span class="sc">~</span> (Age <span class="sc">+</span> Education <span class="sc">+</span> PartyID) <span class="sc">^</span> <span class="dv">2</span> ,</span>
<span id="cb337-6"><a href="c07-modeling.html#cb337-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> quasibinomial</span>
<span id="cb337-7"><a href="c07-modeling.html#cb337-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb337-8"><a href="c07-modeling.html#cb337-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb337-9"><a href="c07-modeling.html#cb337-9" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(earlyvote_mod) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(p.value)</span></code></pre></div>
<pre><code>## # A tibble: 46 × 5
##    term                             estimate std.error statistic p.value
##    &lt;chr&gt;                               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
##  1 Age:PartyIDIndependent            -0.0585    0.0163     -3.58  0.0116
##  2 PartyIDIndependent                 4.99      1.62        3.09  0.0214
##  3 Age:PartyIDNot very strong repu…  -0.0494    0.0197     -2.51  0.0460
##  4 PartyIDNot very strong republic…   4.03      1.64        2.46  0.0488
##  5 (Intercept)                        1.57      0.870       1.80  0.121 
##  6 EducationGraduate                  1.47      0.973       1.51  0.183 
##  7 EducationHigh school:PartyIDStr…  -1.33      1.00       -1.32  0.235 
##  8 PartyIDStrong republican           1.63      1.28        1.27  0.253 
##  9 EducationGraduate:PartyIDStrong…  -1.21      0.998      -1.21  0.272 
## 10 EducationPost HS:PartyIDIndepen…  -1.50      1.35       -1.11  0.311 
## # ℹ 36 more rows</code></pre>
<ol start="5" style="list-style-type: decimal">
<li>Continuing from Exercise 1, predict the probability of early voting for two people. Both are 28 years old and have a graduate degree, but one person is a strong Democrat, and the other is a strong Republican.</li>
</ol>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="c07-modeling.html#cb339-1" aria-hidden="true" tabindex="-1"></a>add_vote_dat <span class="ot">&lt;-</span> anes_in <span class="sc">%&gt;%</span></span>
<span id="cb339-2"><a href="c07-modeling.html#cb339-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(EarlyVote2020, Age, Education, PartyID) <span class="sc">%&gt;%</span></span>
<span id="cb339-3"><a href="c07-modeling.html#cb339-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbind</span>(<span class="fu">tibble</span>(</span>
<span id="cb339-4"><a href="c07-modeling.html#cb339-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">EarlyVote2020 =</span> <span class="cn">NA</span>,</span>
<span id="cb339-5"><a href="c07-modeling.html#cb339-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Age =</span> <span class="dv">28</span>,</span>
<span id="cb339-6"><a href="c07-modeling.html#cb339-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Education =</span> <span class="st">&quot;Graduate&quot;</span>,</span>
<span id="cb339-7"><a href="c07-modeling.html#cb339-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">PartyID =</span> <span class="fu">c</span>(<span class="st">&quot;Strong democrat&quot;</span>, <span class="st">&quot;Strong republican&quot;</span>)</span>
<span id="cb339-8"><a href="c07-modeling.html#cb339-8" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb339-9"><a href="c07-modeling.html#cb339-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tail</span>(<span class="dv">2</span>)</span>
<span id="cb339-10"><a href="c07-modeling.html#cb339-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb339-11"><a href="c07-modeling.html#cb339-11" aria-hidden="true" tabindex="-1"></a>log_ex_2_out <span class="ot">&lt;-</span> earlyvote_mod <span class="sc">%&gt;%</span></span>
<span id="cb339-12"><a href="c07-modeling.html#cb339-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(<span class="at">newdata =</span> add_vote_dat, <span class="at">type.predict =</span> <span class="st">&quot;response&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb339-13"><a href="c07-modeling.html#cb339-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">.se.fit =</span> <span class="fu">sqrt</span>(<span class="fu">attr</span>(.fitted, <span class="st">&quot;var&quot;</span>)), </span>
<span id="cb339-14"><a href="c07-modeling.html#cb339-14" aria-hidden="true" tabindex="-1"></a>         <span class="co"># extract the variance of the fitted value</span></span>
<span id="cb339-15"><a href="c07-modeling.html#cb339-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">.fitted =</span> <span class="fu">as.numeric</span>(.fitted))</span></code></pre></div>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-bollen2016weightsreg" class="csl-entry">
Bollen, Kenneth A., Paul P. Biemer, Alan F. Karr, Stephen Tueller, and Marcus E. Berzofsky. 2016. <span>“Are Survey Weights Needed? A Review of Diagnostic Tests in Regression Analysis.”</span> <em>Annual Review of Statistics and Its Application</em> 3 (1): 375–92. <a href="https://doi.org/10.1146/annurev-statistics-011516-012958">https://doi.org/10.1146/annurev-statistics-011516-012958</a>.
</div>
<div id="ref-gelman2007weights" class="csl-entry">
Gelman, Andrew. 2007. <span>“<span class="nocase">Struggles with Survey Weighting and Regression Modeling</span>.”</span> <em>Statistical Science</em> 22 (2): 153–64. <a href="https://doi.org/10.1214/088342306000000691">https://doi.org/10.1214/088342306000000691</a>.
</div>
<div id="ref-lumley2010complex" class="csl-entry">
Lumley, Thomas. 2010. <em>Complex Surveys: A Guide to Analysis Using r: A Guide to Analysis Using r</em>. John Wiley; Sons.
</div>
<div id="ref-R-survey" class="csl-entry">
———. 2023. <em>Survey: Analysis of Complex Survey Samples</em>. <a href="http://r-survey.r-forge.r-project.org/survey/">http://r-survey.r-forge.r-project.org/survey/</a>.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="22">
<li id="fn22"><p>Use <code>help(formula)</code> in R or find the documentation online at <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/formula.html" class="uri">https://stat.ethz.ch/R-manual/R-devel/library/stats/html/formula.html</a><a href="c07-modeling.html#fnref22" class="footnote-back">↩︎</a></p></li>
<li id="fn23"><p>There is some debate about whether weights should be used in regression <span class="citation">(<a href="#ref-gelman2007weights" role="doc-biblioref">Gelman 2007</a>; <a href="#ref-bollen2016weightsreg" role="doc-biblioref">Bollen et al. 2016</a>)</span>. However, for the purposes of providing complete information on how to analyze complex survey data, this chapter will include weights.<a href="c07-modeling.html#fnref23" class="footnote-back">↩︎</a></p></li>
<li id="fn24"><p>See <code>help(na.omit)</code> for more information on options to use for <code>na.action</code>. For a discussion of how to handle missing data see Chapter <a href="c04-understanding-survey-data-documentation.html#c04-understanding-survey-data-documentation">4</a>.<a href="c07-modeling.html#fnref24" class="footnote-back">↩︎</a></p></li>
<li id="fn25"><p>To change the reference level, reorder the factor before modeling using the function <code>relevel()</code> from {stats} or using one of many factor ordering functions in {forcats} such as <code>fct_relevel()</code> or <code>fct_infreq()</code><a href="c07-modeling.html#fnref25" class="footnote-back">↩︎</a></p></li>
<li id="fn26"><p>Question: How often can you trust the federal government in Washington to do what is right?<a href="c07-modeling.html#fnref26" class="footnote-back">↩︎</a></p></li>
<li id="fn27"><p><a href="https://www.eia.gov/energyexplained/units-and-calculators/degree-days.php" class="uri">https://www.eia.gov/energyexplained/units-and-calculators/degree-days.php</a><a href="c07-modeling.html#fnref27" class="footnote-back">↩︎</a></p></li>
<li id="fn28"><p><a href="https://www.npr.org/2020/10/26/927803214/62-million-and-counting-americans-are-breaking-early-voting-records" class="uri">https://www.npr.org/2020/10/26/927803214/62-million-and-counting-americans-are-breaking-early-voting-records</a><a href="c07-modeling.html#fnref28" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="c06-statistical-testing.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="c08-communicating-results.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/07-modeling.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
