<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Sample designs and replicate weights | Exploring Complex Survey Data Analysis Using R</title>
  <meta name="description" content="Chapter 10 Sample designs and replicate weights | Exploring Complex Survey Data Analysis Using R: A Tidy Introduction with {srvyr} and {survey}" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Sample designs and replicate weights | Exploring Complex Survey Data Analysis Using R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/BookCover_Final.jpg" />
  <meta property="og:description" content="Chapter 10 Sample designs and replicate weights | Exploring Complex Survey Data Analysis Using R: A Tidy Introduction with {srvyr} and {survey}" />
  <meta name="github-repo" content="tidy-survey-r/tidy-survey-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Sample designs and replicate weights | Exploring Complex Survey Data Analysis Using R" />
  
  <meta name="twitter:description" content="Chapter 10 Sample designs and replicate weights | Exploring Complex Survey Data Analysis Using R: A Tidy Introduction with {srvyr} and {survey}" />
  <meta name="twitter:image" content="/images/BookCover_Final.jpg" />

<meta name="author" content="Stephanie A. Zimmer, Rebecca J. Powell, and Isabella C. Velásquez" />


<meta name="date" content="2024-09-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="c09-reprex-data.html"/>
<link rel="next" href="c11-missing-data.html"/>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>
<link href="libs/htmltools-fill/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets/htmlwidgets.js"></script>
<script src="libs/d3/d3.min.js"></script>
<script src="libs/dagre/dagre-d3.min.js"></script>
<link href="libs/mermaid/dist/mermaid.css" rel="stylesheet" />
<script src="libs/mermaid/dist/mermaid.slim.min.js"></script>
<link href="libs/DiagrammeR-styles/styles.css" rel="stylesheet" />
<script src="libs/chromatography/chromatography.js"></script>
<script src="libs/DiagrammeR-binding/DiagrammeR.js"></script>
<script defer data-domain="tidy-survey-r.github.io/tidy-survey-book" src="https://plausible.io/js/script.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Exploring Complex Survey Data Analysis Using R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#dedication"><i class="fa fa-check"></i>Dedication</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#citation"><i class="fa fa-check"></i>Citation</a></li>
</ul></li>
<li class="part"><span><b>I Introduction</b></span></li>
<li class="chapter" data-level="1" data-path="c01-intro.html"><a href="c01-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="c01-intro.html"><a href="c01-intro.html#survey-analysis-in-r"><i class="fa fa-check"></i><b>1.1</b> Survey analysis in R</a></li>
<li class="chapter" data-level="1.2" data-path="c01-intro.html"><a href="c01-intro.html#what-to-expect"><i class="fa fa-check"></i><b>1.2</b> What to expect</a></li>
<li class="chapter" data-level="1.3" data-path="c01-intro.html"><a href="c01-intro.html#prerequisites"><i class="fa fa-check"></i><b>1.3</b> Prerequisites</a></li>
<li class="chapter" data-level="1.4" data-path="c01-intro.html"><a href="c01-intro.html#datasets-used-in-this-book"><i class="fa fa-check"></i><b>1.4</b> Datasets used in this book</a></li>
<li class="chapter" data-level="1.5" data-path="c01-intro.html"><a href="c01-intro.html#conventions"><i class="fa fa-check"></i><b>1.5</b> Conventions</a></li>
<li class="chapter" data-level="1.6" data-path="c01-intro.html"><a href="c01-intro.html#getting-help"><i class="fa fa-check"></i><b>1.6</b> Getting help</a></li>
<li class="chapter" data-level="1.7" data-path="c01-intro.html"><a href="c01-intro.html#acknowledgments"><i class="fa fa-check"></i><b>1.7</b> Acknowledgments</a></li>
<li class="chapter" data-level="1.8" data-path="c01-intro.html"><a href="c01-intro.html#colophon"><i class="fa fa-check"></i><b>1.8</b> Colophon</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html"><i class="fa fa-check"></i><b>2</b> Overview of surveys</a>
<ul>
<li class="chapter" data-level="2.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#searching-for-public-use-survey-data"><i class="fa fa-check"></i><b>2.2</b> Searching for public-use survey data</a></li>
<li class="chapter" data-level="2.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#pre-survey-planning"><i class="fa fa-check"></i><b>2.3</b> Pre-survey planning</a></li>
<li class="chapter" data-level="2.4" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design"><i class="fa fa-check"></i><b>2.4</b> Study design</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-sampdesign"><i class="fa fa-check"></i><b>2.4.1</b> Sampling design</a></li>
<li class="chapter" data-level="2.4.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-dcplanning"><i class="fa fa-check"></i><b>2.4.2</b> Data collection planning</a></li>
<li class="chapter" data-level="2.4.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-questionnaire"><i class="fa fa-check"></i><b>2.4.3</b> Questionnaire design</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-datacollection"><i class="fa fa-check"></i><b>2.5</b> Data collection</a></li>
<li class="chapter" data-level="2.6" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post"><i class="fa fa-check"></i><b>2.6</b> Post-survey processing</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-cleaning"><i class="fa fa-check"></i><b>2.6.1</b> Data cleaning and imputation</a></li>
<li class="chapter" data-level="2.6.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-weighting"><i class="fa fa-check"></i><b>2.6.2</b> Weighting</a></li>
<li class="chapter" data-level="2.6.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-disclosure"><i class="fa fa-check"></i><b>2.6.3</b> Disclosure</a></li>
<li class="chapter" data-level="2.6.4" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-documentation"><i class="fa fa-check"></i><b>2.6.4</b> Documentation</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#post-survey-data-analysis-and-reporting"><i class="fa fa-check"></i><b>2.7</b> Post-survey data analysis and reporting</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html"><i class="fa fa-check"></i><b>3</b> Survey data documentation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#types-of-survey-documentation"><i class="fa fa-check"></i><b>3.2</b> Types of survey documentation</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#technical-documentation"><i class="fa fa-check"></i><b>3.2.1</b> Technical documentation</a></li>
<li class="chapter" data-level="3.2.2" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#questionnaires"><i class="fa fa-check"></i><b>3.2.2</b> Questionnaires</a></li>
<li class="chapter" data-level="3.2.3" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#codebooks"><i class="fa fa-check"></i><b>3.2.3</b> Codebooks</a></li>
<li class="chapter" data-level="3.2.4" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#errata"><i class="fa fa-check"></i><b>3.2.4</b> Errata</a></li>
<li class="chapter" data-level="3.2.5" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#additional-resources"><i class="fa fa-check"></i><b>3.2.5</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#missing-data-coding"><i class="fa fa-check"></i><b>3.3</b> Missing data coding</a></li>
<li class="chapter" data-level="3.4" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#example-anes-2020-survey-documentation"><i class="fa fa-check"></i><b>3.4</b> Example: ANES 2020 survey documentation</a>
<ul>
<li class="chapter" data-level="" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#methodology"><i class="fa fa-check"></i>Methodology</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Analysis</b></span></li>
<li class="chapter" data-level="4" data-path="c04-getting-started.html"><a href="c04-getting-started.html"><i class="fa fa-check"></i><b>4</b> Getting started</a>
<ul>
<li class="chapter" data-level="4.1" data-path="c04-getting-started.html"><a href="c04-getting-started.html#introduction-3"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="c04-getting-started.html"><a href="c04-getting-started.html#setup"><i class="fa fa-check"></i><b>4.2</b> Setup</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="c04-getting-started.html"><a href="c04-getting-started.html#setup-load-pkgs"><i class="fa fa-check"></i><b>4.2.1</b> Packages</a></li>
<li class="chapter" data-level="4.2.2" data-path="c04-getting-started.html"><a href="c04-getting-started.html#data"><i class="fa fa-check"></i><b>4.2.2</b> Data</a></li>
<li class="chapter" data-level="4.2.3" data-path="c04-getting-started.html"><a href="c04-getting-started.html#setup-des-obj"><i class="fa fa-check"></i><b>4.2.3</b> Design objects</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="c04-getting-started.html"><a href="c04-getting-started.html#survey-analysis-process"><i class="fa fa-check"></i><b>4.3</b> Survey analysis process</a></li>
<li class="chapter" data-level="4.4" data-path="c04-getting-started.html"><a href="c04-getting-started.html#similarities-dplyr-srvyr"><i class="fa fa-check"></i><b>4.4</b> Similarities between {dplyr} and {srvyr} functions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html"><i class="fa fa-check"></i><b>5</b> Descriptive analyses</a>
<ul>
<li class="chapter" data-level="" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#prereq5"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="5.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#introduction-4"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#counts-and-cross-tabulations"><i class="fa fa-check"></i><b>5.2</b> Counts and cross-tabulations</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-count-syntax"><i class="fa fa-check"></i><b>5.2.1</b> Syntax</a></li>
<li class="chapter" data-level="5.2.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples"><i class="fa fa-check"></i><b>5.2.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#totals-and-sums"><i class="fa fa-check"></i><b>5.3</b> Totals and sums </a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax"><i class="fa fa-check"></i><b>5.3.1</b> Syntax</a></li>
<li class="chapter" data-level="5.3.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-1"><i class="fa fa-check"></i><b>5.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-meanprop"><i class="fa fa-check"></i><b>5.4</b> Means and proportions</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-meanprop-syntax"><i class="fa fa-check"></i><b>5.4.1</b> Syntax</a></li>
<li class="chapter" data-level="5.4.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-2"><i class="fa fa-check"></i><b>5.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#quantiles-and-medians"><i class="fa fa-check"></i><b>5.5</b> Quantiles and medians</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-1"><i class="fa fa-check"></i><b>5.5.1</b> Syntax</a></li>
<li class="chapter" data-level="5.5.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-3"><i class="fa fa-check"></i><b>5.5.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#ratios"><i class="fa fa-check"></i><b>5.6</b> Ratios </a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-2"><i class="fa fa-check"></i><b>5.6.1</b> Syntax</a></li>
<li class="chapter" data-level="5.6.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-4"><i class="fa fa-check"></i><b>5.6.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#correlations"><i class="fa fa-check"></i><b>5.7</b> Correlations </a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-3"><i class="fa fa-check"></i><b>5.7.1</b> Syntax</a></li>
<li class="chapter" data-level="5.7.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-5"><i class="fa fa-check"></i><b>5.7.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#standard-deviation-and-variance"><i class="fa fa-check"></i><b>5.8</b> Standard deviation and variance </a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-4"><i class="fa fa-check"></i><b>5.8.1</b> Syntax</a></li>
<li class="chapter" data-level="5.8.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-6"><i class="fa fa-check"></i><b>5.8.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#additional-topics"><i class="fa fa-check"></i><b>5.9</b> Additional topics</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#unweighted-analysis"><i class="fa fa-check"></i><b>5.9.1</b> Unweighted analysis </a></li>
<li class="chapter" data-level="5.9.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#subpopulation-analysis"><i class="fa fa-check"></i><b>5.9.2</b> Subpopulation analysis </a></li>
<li class="chapter" data-level="5.9.3" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-deff"><i class="fa fa-check"></i><b>5.9.3</b> Design effects</a></li>
<li class="chapter" data-level="5.9.4" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#creating-summary-rows"><i class="fa fa-check"></i><b>5.9.4</b> Creating summary rows</a></li>
<li class="chapter" data-level="5.9.5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#calculating-estimates-for-many-outcomes"><i class="fa fa-check"></i><b>5.9.5</b> Calculating estimates for many outcomes</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#exercises"><i class="fa fa-check"></i><b>5.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html"><i class="fa fa-check"></i><b>6</b> Statistical testing</a>
<ul>
<li class="chapter" data-level="" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#prereq6"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="6.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#introduction-5"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#dot-notation"><i class="fa fa-check"></i><b>6.2</b> Dot notation</a></li>
<li class="chapter" data-level="6.3" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest"><i class="fa fa-check"></i><b>6.3</b> Comparison of proportions and means</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest-syntax"><i class="fa fa-check"></i><b>6.3.1</b> Syntax</a></li>
<li class="chapter" data-level="6.3.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest-examples"><i class="fa fa-check"></i><b>6.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi"><i class="fa fa-check"></i><b>6.4</b> Chi-squared tests</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi-syntax"><i class="fa fa-check"></i><b>6.4.1</b> Syntax</a></li>
<li class="chapter" data-level="6.4.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi-examples"><i class="fa fa-check"></i><b>6.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-exercises"><i class="fa fa-check"></i><b>6.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="c07-modeling.html"><a href="c07-modeling.html"><i class="fa fa-check"></i><b>7</b> Modeling</a>
<ul>
<li class="chapter" data-level="" data-path="c07-modeling.html"><a href="c07-modeling.html#prereq7"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="7.1" data-path="c07-modeling.html"><a href="c07-modeling.html#model-intro"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="c07-modeling.html"><a href="c07-modeling.html#analysis-of-variance"><i class="fa fa-check"></i><b>7.2</b> Analysis of variance</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-6"><i class="fa fa-check"></i><b>7.2.1</b> Syntax</a></li>
<li class="chapter" data-level="7.2.2" data-path="c07-modeling.html"><a href="c07-modeling.html#example-1"><i class="fa fa-check"></i><b>7.2.2</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="c07-modeling.html"><a href="c07-modeling.html#normal-linear-regression"><i class="fa fa-check"></i><b>7.3</b> Normal linear regression</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-7"><i class="fa fa-check"></i><b>7.3.1</b> Syntax</a></li>
<li class="chapter" data-level="7.3.2" data-path="c07-modeling.html"><a href="c07-modeling.html#examples-7"><i class="fa fa-check"></i><b>7.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="c07-modeling.html"><a href="c07-modeling.html#logistic-regression"><i class="fa fa-check"></i><b>7.4</b> Logistic regression</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-8"><i class="fa fa-check"></i><b>7.4.1</b> Syntax</a></li>
<li class="chapter" data-level="7.4.2" data-path="c07-modeling.html"><a href="c07-modeling.html#examples-8"><i class="fa fa-check"></i><b>7.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="c07-modeling.html"><a href="c07-modeling.html#exercises-1"><i class="fa fa-check"></i><b>7.5</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>III Reporting</b></span></li>
<li class="chapter" data-level="8" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html"><i class="fa fa-check"></i><b>8</b> Communication of results</a>
<ul>
<li class="chapter" data-level="" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#prereq8"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="8.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#introduction-6"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#describing-results-through-text"><i class="fa fa-check"></i><b>8.2</b> Describing results through text</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#methodology-1"><i class="fa fa-check"></i><b>8.2.1</b> Methodology</a></li>
<li class="chapter" data-level="8.2.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#analysis"><i class="fa fa-check"></i><b>8.2.2</b> Analysis</a></li>
<li class="chapter" data-level="8.2.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#results"><i class="fa fa-check"></i><b>8.2.3</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#visualizing-data"><i class="fa fa-check"></i><b>8.3</b> Visualizing data</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#tables"><i class="fa fa-check"></i><b>8.3.1</b> Tables</a></li>
<li class="chapter" data-level="8.3.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#charts-and-plots"><i class="fa fa-check"></i><b>8.3.2</b> Charts and plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html"><i class="fa fa-check"></i><b>9</b> Reproducible research</a>
<ul>
<li class="chapter" data-level="9.1" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#introduction-7"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#project-based-workflows"><i class="fa fa-check"></i><b>9.2</b> Project-based workflows</a></li>
<li class="chapter" data-level="9.3" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#functions-and-packages"><i class="fa fa-check"></i><b>9.3</b> Functions and packages</a></li>
<li class="chapter" data-level="9.4" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#version-control-with-git"><i class="fa fa-check"></i><b>9.4</b> Version control with Git</a></li>
<li class="chapter" data-level="9.5" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#package-management-with-renv"><i class="fa fa-check"></i><b>9.5</b> Package management with {renv}</a></li>
<li class="chapter" data-level="9.6" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#r-environments-with-docker"><i class="fa fa-check"></i><b>9.6</b> R environments with Docker</a></li>
<li class="chapter" data-level="9.7" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#workflow-management-with-targets"><i class="fa fa-check"></i><b>9.7</b> Workflow management with {targets}</a></li>
<li class="chapter" data-level="9.8" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#documentation-with-quarto-and-r-markdown"><i class="fa fa-check"></i><b>9.8</b> Documentation with Quarto and R Markdown</a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#parameterization"><i class="fa fa-check"></i><b>9.8.1</b> Parameterization</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#other-tips-for-reproducibility"><i class="fa fa-check"></i><b>9.9</b> Other tips for reproducibility</a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#random-number-seeds"><i class="fa fa-check"></i><b>9.9.1</b> Random number seeds</a></li>
<li class="chapter" data-level="9.9.2" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#descriptive-names-and-labels"><i class="fa fa-check"></i><b>9.9.2</b> Descriptive names and labels</a></li>
</ul></li>
<li class="chapter" data-level="9.10" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#additional-resources-1"><i class="fa fa-check"></i><b>9.10</b> Additional resources</a></li>
</ul></li>
<li class="part"><span><b>IV Real-life data</b></span></li>
<li class="chapter" data-level="10" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html"><i class="fa fa-check"></i><b>10</b> Sample designs and replicate weights</a>
<ul>
<li class="chapter" data-level="" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#prereq3"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="10.1" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#introduction-8"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#common-sampling-designs"><i class="fa fa-check"></i><b>10.2</b> Common sampling designs</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#simple-random-sample-without-replacement"><i class="fa fa-check"></i><b>10.2.1</b> Simple random sample without replacement</a></li>
<li class="chapter" data-level="10.2.2" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#simple-random-sample-with-replacement"><i class="fa fa-check"></i><b>10.2.2</b> Simple random sample with replacement</a></li>
<li class="chapter" data-level="10.2.3" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#stratified-sampling"><i class="fa fa-check"></i><b>10.2.3</b> Stratified sampling </a></li>
<li class="chapter" data-level="10.2.4" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#samp-cluster"><i class="fa fa-check"></i><b>10.2.4</b> Clustered sampling</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#samp-combo"><i class="fa fa-check"></i><b>10.3</b> Combining sampling methods</a>
<ul>
<li class="chapter" data-level="" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#example-6"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#replicate-weights"><i class="fa fa-check"></i><b>10.4</b> Replicate weights</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#balanced-repeated-replication-method"><i class="fa fa-check"></i><b>10.4.1</b> Balanced Repeated Replication method</a></li>
<li class="chapter" data-level="10.4.2" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#fays-brr-method"><i class="fa fa-check"></i><b>10.4.2</b> Fay’s BRR method</a></li>
<li class="chapter" data-level="10.4.3" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#samp-jackknife"><i class="fa fa-check"></i><b>10.4.3</b> Jackknife method</a></li>
<li class="chapter" data-level="10.4.4" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#bootstrap-method"><i class="fa fa-check"></i><b>10.4.4</b> Bootstrap method</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#exercises-2"><i class="fa fa-check"></i><b>10.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="c11-missing-data.html"><a href="c11-missing-data.html"><i class="fa fa-check"></i><b>11</b> Missing data</a>
<ul>
<li class="chapter" data-level="" data-path="c11-missing-data.html"><a href="c11-missing-data.html#prereq11"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="11.1" data-path="c11-missing-data.html"><a href="c11-missing-data.html#introduction-9"><i class="fa fa-check"></i><b>11.1</b> Introduction</a></li>
<li class="chapter" data-level="11.2" data-path="c11-missing-data.html"><a href="c11-missing-data.html#missing-data-mechanisms"><i class="fa fa-check"></i><b>11.2</b> Missing data mechanisms</a></li>
<li class="chapter" data-level="11.3" data-path="c11-missing-data.html"><a href="c11-missing-data.html#assessing-missing-data"><i class="fa fa-check"></i><b>11.3</b> Assessing missing data</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="c11-missing-data.html"><a href="c11-missing-data.html#summarize-data"><i class="fa fa-check"></i><b>11.3.1</b> Summarize data</a></li>
<li class="chapter" data-level="11.3.2" data-path="c11-missing-data.html"><a href="c11-missing-data.html#visualization-of-missing-data"><i class="fa fa-check"></i><b>11.3.2</b> Visualization of missing data</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="c11-missing-data.html"><a href="c11-missing-data.html#analysis-with-missing-data"><i class="fa fa-check"></i><b>11.4</b> Analysis with missing data</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="c11-missing-data.html"><a href="c11-missing-data.html#recoding-missing-data"><i class="fa fa-check"></i><b>11.4.1</b> Recoding missing data</a></li>
<li class="chapter" data-level="11.4.2" data-path="c11-missing-data.html"><a href="c11-missing-data.html#missing-skip-patt"><i class="fa fa-check"></i><b>11.4.2</b> Accounting for skip patterns</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="c12-recommendations.html"><a href="c12-recommendations.html"><i class="fa fa-check"></i><b>12</b> Successful survey analysis recommendations</a>
<ul>
<li class="chapter" data-level="" data-path="c12-recommendations.html"><a href="c12-recommendations.html#prereq12"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="12.1" data-path="c12-recommendations.html"><a href="c12-recommendations.html#introduction-10"><i class="fa fa-check"></i><b>12.1</b> Introduction</a></li>
<li class="chapter" data-level="12.2" data-path="c12-recommendations.html"><a href="c12-recommendations.html#recs-survey-process"><i class="fa fa-check"></i><b>12.2</b> Follow the survey analysis process</a></li>
<li class="chapter" data-level="12.3" data-path="c12-recommendations.html"><a href="c12-recommendations.html#begin-with-descriptive-analysis"><i class="fa fa-check"></i><b>12.3</b> Begin with descriptive analysis</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="c12-recommendations.html"><a href="c12-recommendations.html#table-review"><i class="fa fa-check"></i><b>12.3.1</b> Table review</a></li>
<li class="chapter" data-level="12.3.2" data-path="c12-recommendations.html"><a href="c12-recommendations.html#graphical-review"><i class="fa fa-check"></i><b>12.3.2</b> Graphical review</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="c12-recommendations.html"><a href="c12-recommendations.html#check-variable-types"><i class="fa fa-check"></i><b>12.4</b> Check variable types</a></li>
<li class="chapter" data-level="12.5" data-path="c12-recommendations.html"><a href="c12-recommendations.html#improve-debugging-skills"><i class="fa fa-check"></i><b>12.5</b> Improve debugging skills</a></li>
<li class="chapter" data-level="12.6" data-path="c12-recommendations.html"><a href="c12-recommendations.html#think-critically-about-conclusions"><i class="fa fa-check"></i><b>12.6</b> Think critically about conclusions</a></li>
</ul></li>
<li class="part"><span><b>V Vignettes</b></span></li>
<li class="chapter" data-level="13" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html"><i class="fa fa-check"></i><b>13</b> National Crime Victimization Survey vignette</a>
<ul>
<li class="chapter" data-level="" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#prereq9"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="13.1" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#introduction-11"><i class="fa fa-check"></i><b>13.1</b> Introduction</a></li>
<li class="chapter" data-level="13.2" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#data-structure"><i class="fa fa-check"></i><b>13.2</b> Data structure</a></li>
<li class="chapter" data-level="13.3" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#survey-notation"><i class="fa fa-check"></i><b>13.3</b> Survey notation</a></li>
<li class="chapter" data-level="13.4" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#data-file-preparation"><i class="fa fa-check"></i><b>13.4</b> Data file preparation</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#preparing-files-for-estimation-of-victimization-rates"><i class="fa fa-check"></i><b>13.4.1</b> Preparing files for estimation of victimization rates</a></li>
<li class="chapter" data-level="13.4.2" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#derived-demographic-variables"><i class="fa fa-check"></i><b>13.4.2</b> Derived demographic variables</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#survey-design-objects"><i class="fa fa-check"></i><b>13.5</b> Survey design objects</a></li>
<li class="chapter" data-level="13.6" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#calculating-estimates"><i class="fa fa-check"></i><b>13.6</b> Calculating estimates</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#vic-tot"><i class="fa fa-check"></i><b>13.6.1</b> Estimation 1: Victimization totals</a></li>
<li class="chapter" data-level="13.6.2" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#vic-prop"><i class="fa fa-check"></i><b>13.6.2</b> Estimation 2: Victimization proportions</a></li>
<li class="chapter" data-level="13.6.3" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#vic-rate"><i class="fa fa-check"></i><b>13.6.3</b> Estimation 3: Victimization rates</a></li>
<li class="chapter" data-level="13.6.4" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#prev-rate"><i class="fa fa-check"></i><b>13.6.4</b> Estimation 4: Prevalence rates</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#statistical-testing"><i class="fa fa-check"></i><b>13.7</b> Statistical testing</a></li>
<li class="chapter" data-level="13.8" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#exercises-3"><i class="fa fa-check"></i><b>13.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html"><i class="fa fa-check"></i><b>14</b> AmericasBarometer vignette</a>
<ul>
<li class="chapter" data-level="" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#prereq10"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="14.1" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#introduction-12"><i class="fa fa-check"></i><b>14.1</b> Introduction</a></li>
<li class="chapter" data-level="14.2" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#data-structure-1"><i class="fa fa-check"></i><b>14.2</b> Data structure</a></li>
<li class="chapter" data-level="14.3" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#preparing-files"><i class="fa fa-check"></i><b>14.3</b> Preparing files</a></li>
<li class="chapter" data-level="14.4" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#survey-design-objects-1"><i class="fa fa-check"></i><b>14.4</b> Survey design objects</a></li>
<li class="chapter" data-level="14.5" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#ambarom-estimates"><i class="fa fa-check"></i><b>14.5</b> Calculating estimates</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#example-worry-about-covid-19"><i class="fa fa-check"></i><b>14.5.1</b> Example: Worry about COVID-19</a></li>
<li class="chapter" data-level="14.5.2" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#example-education-affected-by-covid-19"><i class="fa fa-check"></i><b>14.5.2</b> Example: Education affected by COVID-19</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#ambarom-maps"><i class="fa fa-check"></i><b>14.6</b> Mapping survey data</a></li>
<li class="chapter" data-level="14.7" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#exercises-4"><i class="fa fa-check"></i><b>14.7</b> Exercises</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html"><i class="fa fa-check"></i><b>A</b> Importing survey data into R</a>
<ul>
<li class="chapter" data-level="A.1" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-delimiter-separated-files-into-r"><i class="fa fa-check"></i><b>A.1</b> Importing delimiter-separated files into R</a></li>
<li class="chapter" data-level="A.2" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-excel-files-into-r"><i class="fa fa-check"></i><b>A.2</b> Importing Excel files into R</a></li>
<li class="chapter" data-level="A.3" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-stata-sas-and-spss-files-into-r"><i class="fa fa-check"></i><b>A.3</b> Importing Stata, SAS, and SPSS files into R</a>
<ul>
<li class="chapter" data-level="A.3.1" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#syntax-9"><i class="fa fa-check"></i><b>A.3.1</b> Syntax</a></li>
<li class="chapter" data-level="A.3.2" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#working-with-labeled-data"><i class="fa fa-check"></i><b>A.3.2</b> Working with labeled data</a></li>
<li class="chapter" data-level="A.3.3" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#labeled-missing-data-values"><i class="fa fa-check"></i><b>A.3.3</b> Labeled missing data values</a></li>
</ul></li>
<li class="chapter" data-level="A.4" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-data-from-apis-into-r"><i class="fa fa-check"></i><b>A.4</b> Importing data from APIs into R</a></li>
<li class="chapter" data-level="A.5" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-data-from-databases-in-r"><i class="fa fa-check"></i><b>A.5</b> Importing data from databases in R</a></li>
<li class="chapter" data-level="A.6" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-data-from-other-formats"><i class="fa fa-check"></i><b>A.6</b> Importing data from other formats</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="anes-cb.html"><a href="anes-cb.html"><i class="fa fa-check"></i><b>B</b> ANES derived variable codebook</a>
<ul>
<li class="chapter" data-level="B.1" data-path="anes-cb.html"><a href="anes-cb.html#admin"><i class="fa fa-check"></i><b>B.1</b> ADMIN</a></li>
<li class="chapter" data-level="B.2" data-path="anes-cb.html"><a href="anes-cb.html#weights"><i class="fa fa-check"></i><b>B.2</b> WEIGHTS</a></li>
<li class="chapter" data-level="B.3" data-path="anes-cb.html"><a href="anes-cb.html#pre-election-survey-questionnaire"><i class="fa fa-check"></i><b>B.3</b> PRE-ELECTION SURVEY QUESTIONNAIRE</a></li>
<li class="chapter" data-level="B.4" data-path="anes-cb.html"><a href="anes-cb.html#post-election-survey-questionnaire"><i class="fa fa-check"></i><b>B.4</b> POST-ELECTION SURVEY QUESTIONNAIRE</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="recs-cb.html"><a href="recs-cb.html"><i class="fa fa-check"></i><b>C</b> RECS derived variable codebook</a>
<ul>
<li class="chapter" data-level="C.1" data-path="recs-cb.html"><a href="recs-cb.html#admin-1"><i class="fa fa-check"></i><b>C.1</b> ADMIN</a></li>
<li class="chapter" data-level="C.2" data-path="recs-cb.html"><a href="recs-cb.html#geography"><i class="fa fa-check"></i><b>C.2</b> GEOGRAPHY</a></li>
<li class="chapter" data-level="C.3" data-path="recs-cb.html"><a href="recs-cb.html#weather"><i class="fa fa-check"></i><b>C.3</b> WEATHER</a></li>
<li class="chapter" data-level="C.4" data-path="recs-cb.html"><a href="recs-cb.html#your-home"><i class="fa fa-check"></i><b>C.4</b> YOUR HOME</a></li>
<li class="chapter" data-level="C.5" data-path="recs-cb.html"><a href="recs-cb.html#space-heating"><i class="fa fa-check"></i><b>C.5</b> SPACE HEATING</a></li>
<li class="chapter" data-level="C.6" data-path="recs-cb.html"><a href="recs-cb.html#air-conditioning"><i class="fa fa-check"></i><b>C.6</b> AIR CONDITIONING</a></li>
<li class="chapter" data-level="C.7" data-path="recs-cb.html"><a href="recs-cb.html#thermostat"><i class="fa fa-check"></i><b>C.7</b> THERMOSTAT</a></li>
<li class="chapter" data-level="C.8" data-path="recs-cb.html"><a href="recs-cb.html#weights-1"><i class="fa fa-check"></i><b>C.8</b> WEIGHTS</a></li>
<li class="chapter" data-level="C.9" data-path="recs-cb.html"><a href="recs-cb.html#consumption-and-expenditure"><i class="fa fa-check"></i><b>C.9</b> CONSUMPTION AND EXPENDITURE</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="exercise-solutions.html"><a href="exercise-solutions.html"><i class="fa fa-check"></i><b>D</b> Exercise solutions</a>
<ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#descriptive-analysis"><i class="fa fa-check"></i>5 - Descriptive analysis</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#statistical-testing-1"><i class="fa fa-check"></i>6 - Statistical testing</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#modeling"><i class="fa fa-check"></i>7 - Modeling</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#specifying-sample-designs-and-replicate-weights-in-srvyr"><i class="fa fa-check"></i>10 - Specifying sample designs and replicate weights in {srvyr}</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#national-crime-victimization-survey-vignette"><i class="fa fa-check"></i>13 - National Crime Victimization Survey Vignette</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#americasbarometer-vignette"><i class="fa fa-check"></i>14 - AmericasBarometer Vignette</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Exploring Complex Survey Data Analysis Using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="c10-sample-designs-replicate-weights" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Chapter 10</span> Sample designs and replicate weights<a href="c10-sample-designs-replicate-weights.html#c10-sample-designs-replicate-weights" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="prereq3" class="section level3 unnumbered hasAnchor prereqbox-header">
<h3>Prerequisites<a href="c10-sample-designs-replicate-weights.html#prereq3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
</div>
<div class="prereqbox">
<p>For this chapter, load the following packages:</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="c10-sample-designs-replicate-weights.html#cb278-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb278-2"><a href="c10-sample-designs-replicate-weights.html#cb278-2" tabindex="-1"></a><span class="fu">library</span>(survey)</span>
<span id="cb278-3"><a href="c10-sample-designs-replicate-weights.html#cb278-3" tabindex="-1"></a><span class="fu">library</span>(srvyr)</span>
<span id="cb278-4"><a href="c10-sample-designs-replicate-weights.html#cb278-4" tabindex="-1"></a><span class="fu">library</span>(srvyrexploR)</span></code></pre></div>
<p>To help explain the different types of sample designs, this chapter uses the <code>api</code> and <code>scd</code> data that are included in the {survey} package <span class="citation">(<a href="#ref-lumley2010complex">Lumley 2010</a>)</span>:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="c10-sample-designs-replicate-weights.html#cb279-1" tabindex="-1"></a><span class="fu">data</span>(api)</span>
<span id="cb279-2"><a href="c10-sample-designs-replicate-weights.html#cb279-2" tabindex="-1"></a><span class="fu">data</span>(scd)</span></code></pre></div>
<p>This chapter uses data from the Residential Energy Consumption Survey (RECS), both 2015 and 2020, so we load the RECS data from the {srvyrexploR} package using their object names <code>recs_2015</code> and <code>recs_2020</code>, respectively <span class="citation">(<a href="#ref-R-srvyrexploR">Zimmer, Powell, and Velásquez 2024</a>)</span>.</p>
</div>
<div id="introduction-8" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Introduction<a href="c10-sample-designs-replicate-weights.html#introduction-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The primary reason for using packages like {survey} and {srvyr} is to account for the sampling design or replicate weights into point and uncertainty estimates <span class="citation">(<a href="#ref-R-srvyr">Freedman Ellis and Schneider 2024</a>; <a href="#ref-lumley2010complex">Lumley 2010</a>)</span>. By incorporating the sampling design or replicate weights, these estimates are appropriately calculated.</p>
<p>In this chapter, we introduce common sampling designs and common types of replicate weights, the mathematical methods for calculating estimates and standard errors for a given sampling design, and the R syntax to specify the sampling design or replicate weights. While we show the math behind the estimates, the functions in these packages handle the calculation. To deeply understand the math and the derivation, refer to <span class="citation">Penn State (<a href="#ref-pennstate506">2019</a>)</span>, <span class="citation">Särndal, Swensson, and Wretman (<a href="#ref-sarndal2003model">2003</a>)</span>, <span class="citation">Wolter (<a href="#ref-wolter2007introduction">2007</a>)</span>, or <span class="citation">Fuller (<a href="#ref-fuller2011sampling">2011</a>)</span> (these are listed in order of increasing statistical rigorousness).</p>
<p>The general process for estimation in the {srvyr} package is to:</p>
<ol style="list-style-type: decimal">
<li><p>Create a <code>tbl_svy</code> object (a survey object) using: <code>as_survey_design()</code> or <code>as_survey_rep()</code></p></li>
<li><p>Subset data (if needed) using <code>filter()</code> (subpopulations)</p></li>
<li><p>Specify domains of analysis using <code>group_by()</code></p></li>
<li><p>Within <code>summarize()</code>, specify variables to calculate, including means, totals, proportions, quantiles, and more</p></li>
</ol>
<p>This chapter includes details on the first step: creating the survey object. Once this survey object is created, it can be used in the other steps (detailed in Chapters <a href="c05-descriptive-analysis.html#c05-descriptive-analysis">5</a> through <a href="c07-modeling.html#c07-modeling">7</a>) to account for the complex survey design.</p>
</div>
<div id="common-sampling-designs" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Common sampling designs<a href="c10-sample-designs-replicate-weights.html#common-sampling-designs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A sampling design is the method used to draw a sample. Both logistical and statistical elements are considered when developing a sampling design. When specifying a sampling design in R, we specify the levels of sampling along with the weights. The weight for each record is constructed so that the particular record represents that many units in the population. For example, in a survey of 6th-grade students in the United States, the weight associated with each responding student reflects how many 6th-grade students across the country that record represents. Generally, the weights represent the inverse of the probability of selection, such that the sum of the weights corresponds to the total population size, although some studies may have the sum of the weights equal to the number of respondent records.</p>
<p>Some common terminology across the designs are:</p>
<ul>
<li>sample size, generally denoted as <span class="math inline">\(n\)</span>, is the number of units selected to be sampled</li>
<li>population size, generally denoted as <span class="math inline">\(N\)</span>, is the number of units in the population of interest</li>
<li>sampling frame, the list of units from which the sample is drawn (see Chapter <a href="c02-overview-surveys.html#c02-overview-surveys">2</a> for more information)</li>
</ul>
<div id="simple-random-sample-without-replacement" class="section level3 hasAnchor" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> Simple random sample without replacement<a href="c10-sample-designs-replicate-weights.html#simple-random-sample-without-replacement" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>
The simple random sample (SRS) without replacement is a sampling design in which a fixed sample size is selected from a sampling frame, and every possible subsample has an equal probability of selection. Without replacement refers to the fact that once a sampling unit has been selected, it is removed from the sample frame and cannot be selected again.</p>
<ul>
<li>Requirements: The sampling frame must include the entire population.</li>
<li>Advantages: SRS requires no information about the units apart from contact information.</li>
<li>Disadvantages: The sampling frame may not be available for the entire population.</li>
<li>Example: Randomly select students in a university from a roster provided by the registrar’s office.</li>
</ul>
<div id="the-math" class="section level4 unnumbered hasAnchor">
<h4>The math<a href="c10-sample-designs-replicate-weights.html#the-math" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The estimate for the population mean of variable <span class="math inline">\(y\)</span> is:</p>
<p><span class="math display">\[\bar{y}=\frac{1}{n}\sum_{i=1}^n y_i\]</span>
where <span class="math inline">\(\bar{y}\)</span> represents the sample mean, <span class="math inline">\(n\)</span> is the total number of respondents (or observations), and <span class="math inline">\(y_i\)</span> is each individual value of <span class="math inline">\(y\)</span>.</p>
<p>The estimate of the standard error of the mean is:</p>
<p><span class="math display">\[se(\bar{y})=\sqrt{\frac{s^2}{n}\left( 1-\frac{n}{N} \right)}\]</span> where</p>
<p><span class="math display">\[s^2=\frac{1}{n-1}\sum_{i=1}^n\left(y_i-\bar{y}\right)^2.\]</span></p>
<p>
and <span class="math inline">\(N\)</span> is the population size. This standard error estimate might look very similar to equations in other statistical applications except for the part on the right side of the equation: <span class="math inline">\(1-\frac{n}{N}\)</span>. This is called the finite population correction (FPC) factor. If the size of the frame, <span class="math inline">\(N\)</span>, is very large in comparison to the sample, the FPC is negligible, so it is often ignored. A common guideline is if the sample is less than 10% of the population, the FPC is negligible.</p>
<p>To estimate proportions, we define <span class="math inline">\(x_i\)</span> as the indicator if the outcome is observed. That is, <span class="math inline">\(x_i=1\)</span> if the outcome is observed, and <span class="math inline">\(x_i=0\)</span> if the outcome is not observed for respondent <span class="math inline">\(i\)</span>. Then the estimated proportion from an SRS design is:</p>
<p><span class="math display">\[\hat{p}=\frac{1}{n}\sum_{i=1}^n x_i \]</span>
and the estimated standard error of the proportion is:</p>
<p><span class="math display">\[se(\hat{p})=\sqrt{\frac{\hat{p}(1-\hat{p})}{n-1}\left(1-\frac{n}{N}\right)} \]</span></p>
</div>
<div id="the-syntax" class="section level4 unnumbered hasAnchor">
<h4>The syntax<a href="c10-sample-designs-replicate-weights.html#the-syntax" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>
If a sample was drawn through SRS and had no nonresponse or other weighting adjustments, we specify this design in R as:</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="c10-sample-designs-replicate-weights.html#cb280-1" tabindex="-1"></a>srs1_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb280-2"><a href="c10-sample-designs-replicate-weights.html#cb280-2" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">fpc =</span> fpcvar)</span></code></pre></div>
<p>where <code>dat</code> is a tibble or data.frame with the survey data, and <code>fpcvar</code> is a variable in the data indicating the sampling frame’s size (this variable has the same value for all cases in an SRS design). If the frame is very large, sometimes the frame size is not provided. In that case, the FPC is not needed, and we specify the design as:</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="c10-sample-designs-replicate-weights.html#cb281-1" tabindex="-1"></a>srs2_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb281-2"><a href="c10-sample-designs-replicate-weights.html#cb281-2" tabindex="-1"></a>  <span class="fu">as_survey_design</span>()</span></code></pre></div>
<p>If some post-survey adjustments were implemented and the weights are not all equal, we specify the design as:</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="c10-sample-designs-replicate-weights.html#cb282-1" tabindex="-1"></a>srs3_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb282-2"><a href="c10-sample-designs-replicate-weights.html#cb282-2" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">weights =</span> wtvar,</span>
<span id="cb282-3"><a href="c10-sample-designs-replicate-weights.html#cb282-3" tabindex="-1"></a>                   <span class="at">fpc =</span> fpcvar)</span></code></pre></div>
<p>where <code>wtvar</code> is a variable in the data indicating the weight for each case. Again, the FPC can be omitted if it is unnecessary because the frame is large compared to the sample size.</p>
</div>
<div id="example-2" class="section level4 unnumbered hasAnchor">
<h4>Example<a href="c10-sample-designs-replicate-weights.html#example-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The {survey} package in R provides some example datasets that we use throughout this chapter. One of the example datasets we use is from the Academic Performance Index Program (APIP). The APIP program administered by the California Department of Education, and the {survey} package includes a population file (sample frame) of all schools with at least 100 students and several different samples pulled from that data using different sampling methods. For this first example, we use the <code>apisrs</code> dataset, which contains an SRS of 200 schools. For printing purposes, we create a new dataset called <code>apisrs_slim</code>, which sorts the data by the school district and school ID and subsets the data to only a few columns. The SRS sample data are illustrated below:</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="c10-sample-designs-replicate-weights.html#cb283-1" tabindex="-1"></a>apisrs_slim <span class="ot">&lt;-</span></span>
<span id="cb283-2"><a href="c10-sample-designs-replicate-weights.html#cb283-2" tabindex="-1"></a>  apisrs <span class="sc">%&gt;%</span></span>
<span id="cb283-3"><a href="c10-sample-designs-replicate-weights.html#cb283-3" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb283-4"><a href="c10-sample-designs-replicate-weights.html#cb283-4" tabindex="-1"></a>  <span class="fu">arrange</span>(dnum, snum) <span class="sc">%&gt;%</span></span>
<span id="cb283-5"><a href="c10-sample-designs-replicate-weights.html#cb283-5" tabindex="-1"></a>  <span class="fu">select</span>(cds, dnum, snum, dname, sname, fpc, pw)</span>
<span id="cb283-6"><a href="c10-sample-designs-replicate-weights.html#cb283-6" tabindex="-1"></a></span>
<span id="cb283-7"><a href="c10-sample-designs-replicate-weights.html#cb283-7" tabindex="-1"></a>apisrs_slim</span></code></pre></div>
<pre><code>## # A tibble: 200 × 7
##    cds             dnum  snum dname                   sname    fpc    pw
##    &lt;chr&gt;          &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;                   &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 19642126061220     1  1121 ABC Unified             Haske…  6194  31.0
##  2 19642126066716     1  1124 ABC Unified             Stowe…  6194  31.0
##  3 36675876035174     5  3895 Adelanto Elementary     Adela…  6194  31.0
##  4 33669776031512    19  3347 Alvord Unified          Arlan…  6194  31.0
##  5 33669776031595    19  3352 Alvord Unified          Wells…  6194  31.0
##  6 31667876031033    39  3271 Auburn Union Elementary Cain …  6194  31.0
##  7 19642876011407    42  1169 Baldwin Park Unified    Deanz…  6194  31.0
##  8 19642876011464    42  1175 Baldwin Park Unified    Heath…  6194  31.0
##  9 19642956011589    48  1187 Bassett Unified         Erwin…  6194  31.0
## 10 41688586043392    49  4948 Bayshore Elementary     Baysh…  6194  31.0
## # ℹ 190 more rows</code></pre>
<p>Table <a href="c10-sample-designs-replicate-weights.html#tab:apidata">10.1</a> provides details on all the variables in this dataset.</p>
<table>
<caption><span id="tab:apidata">TABLE 10.1: </span> Overview of Variables in APIP Data</caption>
<thead>
<tr class="header">
<th align="center">Variable Name</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><code>cds</code></td>
<td>Unique identifier for each school</td>
</tr>
<tr class="even">
<td align="center"><code>dnum</code></td>
<td>School district identifier within county</td>
</tr>
<tr class="odd">
<td align="center"><code>snum</code></td>
<td>School identifier within district</td>
</tr>
<tr class="even">
<td align="center"><code>dname</code></td>
<td>District Name</td>
</tr>
<tr class="odd">
<td align="center"><code>sname</code></td>
<td>School Name</td>
</tr>
<tr class="even">
<td align="center"><code>fpc</code></td>
<td>Finite population correction factor</td>
</tr>
<tr class="odd">
<td align="center"><code>pw</code></td>
<td>Weight</td>
</tr>
</tbody>
</table>
<p>To create the <code>tbl_survey</code> object for the SRS data, we specify the design as:</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="c10-sample-designs-replicate-weights.html#cb285-1" tabindex="-1"></a>apisrs_des <span class="ot">&lt;-</span> apisrs_slim <span class="sc">%&gt;%</span></span>
<span id="cb285-2"><a href="c10-sample-designs-replicate-weights.html#cb285-2" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(</span>
<span id="cb285-3"><a href="c10-sample-designs-replicate-weights.html#cb285-3" tabindex="-1"></a>    <span class="at">weights =</span> pw,</span>
<span id="cb285-4"><a href="c10-sample-designs-replicate-weights.html#cb285-4" tabindex="-1"></a>    <span class="at">fpc =</span> fpc</span>
<span id="cb285-5"><a href="c10-sample-designs-replicate-weights.html#cb285-5" tabindex="-1"></a>  )</span>
<span id="cb285-6"><a href="c10-sample-designs-replicate-weights.html#cb285-6" tabindex="-1"></a></span>
<span id="cb285-7"><a href="c10-sample-designs-replicate-weights.html#cb285-7" tabindex="-1"></a>apisrs_des</span></code></pre></div>
<pre><code>## Independent Sampling design
## Called via srvyr
## Sampling variables:
##   - ids: `1` 
##   - fpc: fpc 
##   - weights: pw 
## Data variables: 
##   - cds (chr), dnum (int), snum (dbl), dname (chr), sname (chr), fpc
##     (dbl), pw (dbl)</code></pre>
<p>In the printed design object, the design is described as an “Independent Sampling design,” which is another term for SRS. The ids are specified as <code>1</code>, which means there is no clustering (a topic described in Section <a href="c10-sample-designs-replicate-weights.html#samp-cluster">10.2.4</a>), the FPC variable is indicated, and the weights are indicated. We can also look at the summary of the design object (<code>summary()</code>) and see the distribution of the probabilities (inverse of the weights) along with the population size and a list of the variables in the dataset.</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="c10-sample-designs-replicate-weights.html#cb287-1" tabindex="-1"></a><span class="fu">summary</span>(apisrs_des)</span></code></pre></div>
<pre><code>## Independent Sampling design
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0323  0.0323  0.0323  0.0323  0.0323  0.0323 
## Population size (PSUs): 6194 
## Data variables:
## [1] &quot;cds&quot;   &quot;dnum&quot;  &quot;snum&quot;  &quot;dname&quot; &quot;sname&quot; &quot;fpc&quot;   &quot;pw&quot;</code></pre>
<p></p>
</div>
</div>
<div id="simple-random-sample-with-replacement" class="section level3 hasAnchor" number="10.2.2">
<h3><span class="header-section-number">10.2.2</span> Simple random sample with replacement<a href="c10-sample-designs-replicate-weights.html#simple-random-sample-with-replacement" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Similar to the SRS design, the simple random sample with replacement (SRSWR) design randomly selects the sample from the entire sampling frame. However, while SRS removes sampled units before selecting again, the SRSWR instead replaces each sampled unit before drawing again, so units can be selected more than once.</p>
<ul>
<li>Requirements: The sampling frame must include the entire population.</li>
<li>Advantages: SRSWR requires no information about the units apart from contact information.</li>
<li>Disadvantages:
<ul>
<li>The sampling frame may not be available for the entire population.</li>
<li>Units can be selected more than once, resulting in a smaller realized sample size because receiving duplicate information from a single respondent does not provide additional information.</li>
<li>For small populations, SRSWR has larger standard errors than SRS designs.</li>
</ul></li>
<li>Example: A professor puts all students’ names on paper slips and selects them randomly to ask students questions, but the professor replaces the paper after calling on the student so they can be selected again at any time.</li>
</ul>
<p>In general for surveys, using an SRS design (without replacement) is preferred as we do not want respondents to answer a survey more than once.</p>
<div id="the-math-1" class="section level4 unnumbered hasAnchor">
<h4>The math<a href="c10-sample-designs-replicate-weights.html#the-math-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The estimate for the population mean of variable <span class="math inline">\(y\)</span> is:</p>
<p><span class="math display">\[\bar{y}=\frac{1}{n}\sum_{i=1}^n y_i\]</span></p>
<p>and the estimate of the standard error of mean is:</p>
<p><span class="math display">\[se(\bar{y})=\sqrt{\frac{s^2}{n}}\]</span> where</p>
<p><span class="math display">\[s^2=\frac{1}{n-1}\sum_{i=1}^n\left(y_i-\bar{y}\right)^2.\]</span>
To calculate the estimated proportion, we define <span class="math inline">\(x_i\)</span> as the indicator that the outcome is observed (as we did with SRS):</p>
<p><span class="math display">\[\hat{p}=\frac{1}{n}\sum_{i=1}^n x_i \]</span>
and the estimated standard error of the proportion is:</p>
<p><span class="math display">\[se(\hat{p})=\sqrt{\frac{\hat{p}(1-\hat{p})}{n}} \]</span></p>
</div>
<div id="the-syntax-1" class="section level4 unnumbered hasAnchor">
<h4>The syntax<a href="c10-sample-designs-replicate-weights.html#the-syntax-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If we had a sample that was drawn through SRSWR and had no nonresponse or other weighting adjustments, in R, we specify this design as:</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="c10-sample-designs-replicate-weights.html#cb289-1" tabindex="-1"></a>srswr1_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb289-2"><a href="c10-sample-designs-replicate-weights.html#cb289-2" tabindex="-1"></a> <span class="fu">as_survey_design</span>()</span></code></pre></div>
<p>
where <code>dat</code> is a tibble or data.frame containing our survey data. This syntax is the same as an SRS design, except an FPC is not included. This is because when calculating a sample with replacement, the population pool to select from is no longer finite, so a correction is not needed. Therefore, with large populations where the FPC is negligible, the underlying formulas for SRS and SRSWR designs are the same.</p>
<p>
If some post-survey adjustments were implemented and the weights are not all equal, we specify the design as:</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="c10-sample-designs-replicate-weights.html#cb290-1" tabindex="-1"></a>srswr2_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb290-2"><a href="c10-sample-designs-replicate-weights.html#cb290-2" tabindex="-1"></a> <span class="fu">as_survey_design</span>(<span class="at">weights =</span> wtvar)</span></code></pre></div>
<p>where <code>wtvar</code> is the variable for the weight of the data.</p>
</div>
<div id="example-3" class="section level4 unnumbered hasAnchor">
<h4>Example<a href="c10-sample-designs-replicate-weights.html#example-3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The {survey} package does not include an example of SRSWR. To illustrate this design, we need to create an example. We use the APIP population data provided by the {survey} package (<code>apipop</code>) and select a sample of 200 cases using the <code>slice_sample()</code> function from the tidyverse. One of the arguments in the <code>slice_sample()</code> function is <code>replace</code>. If <code>replace=TRUE</code>, then we are conducting an SRSWR. We then calculate selection weights as the inverse of the probability of selection and call this new dataset <code>apisrswr</code>.</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="c10-sample-designs-replicate-weights.html#cb291-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">409963</span>)</span>
<span id="cb291-2"><a href="c10-sample-designs-replicate-weights.html#cb291-2" tabindex="-1"></a></span>
<span id="cb291-3"><a href="c10-sample-designs-replicate-weights.html#cb291-3" tabindex="-1"></a>apisrswr <span class="ot">&lt;-</span> apipop <span class="sc">%&gt;%</span></span>
<span id="cb291-4"><a href="c10-sample-designs-replicate-weights.html#cb291-4" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb291-5"><a href="c10-sample-designs-replicate-weights.html#cb291-5" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">200</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb291-6"><a href="c10-sample-designs-replicate-weights.html#cb291-6" tabindex="-1"></a>  <span class="fu">select</span>(cds, dnum, snum, dname, sname) <span class="sc">%&gt;%</span></span>
<span id="cb291-7"><a href="c10-sample-designs-replicate-weights.html#cb291-7" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weight =</span> <span class="fu">nrow</span>(apipop) <span class="sc">/</span> <span class="dv">200</span>)</span>
<span id="cb291-8"><a href="c10-sample-designs-replicate-weights.html#cb291-8" tabindex="-1"></a></span>
<span id="cb291-9"><a href="c10-sample-designs-replicate-weights.html#cb291-9" tabindex="-1"></a><span class="fu">head</span>(apisrswr)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 6
##   cds             dnum  snum dname                    sname       weight
##   &lt;chr&gt;          &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;                    &lt;chr&gt;        &lt;dbl&gt;
## 1 43696416060065   533  5348 Palo Alto Unified        Jordan (Da…   31.0
## 2 07618046005060   650   509 San Ramon Valley Unified Alamo Elem…   31.0
## 3 19648086085674   457  2134 Montebello Unified       La Merced …   31.0
## 4 07617056003719   346   377 Knightsen Elementary     Knightsen …   31.0
## 5 19650606023022   744  2351 Torrance Unified         Carr (Evel…   31.0
## 6 01611196090120     6    13 Alameda City Unified     Paden (Wil…   31.0</code></pre>
<p>Because this is an SRS design with replacement, there may be duplicates in the data. It is important to keep the duplicates in the data for proper estimation. For reference, we can view the duplicates in the example data we just created.</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="c10-sample-designs-replicate-weights.html#cb293-1" tabindex="-1"></a>apisrswr <span class="sc">%&gt;%</span></span>
<span id="cb293-2"><a href="c10-sample-designs-replicate-weights.html#cb293-2" tabindex="-1"></a>  <span class="fu">group_by</span>(cds) <span class="sc">%&gt;%</span></span>
<span id="cb293-3"><a href="c10-sample-designs-replicate-weights.html#cb293-3" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">n</span>() <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb293-4"><a href="c10-sample-designs-replicate-weights.html#cb293-4" tabindex="-1"></a>  <span class="fu">arrange</span>(cds)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 6
## # Groups:   cds [2]
##   cds             dnum  snum dname                 sname          weight
##   &lt;chr&gt;          &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;                 &lt;chr&gt;           &lt;dbl&gt;
## 1 15633216008841    41   869 Bakersfield City Elem Chipman Junio…   31.0
## 2 15633216008841    41   869 Bakersfield City Elem Chipman Junio…   31.0
## 3 39686766042782   716  4880 Stockton City Unified Tyler Skills …   31.0
## 4 39686766042782   716  4880 Stockton City Unified Tyler Skills …   31.0</code></pre>
<p>We created a weight variable in this example data, which is the inverse of the probability of selection. We specify the sampling design for <code>apisrswr</code> as:</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="c10-sample-designs-replicate-weights.html#cb295-1" tabindex="-1"></a>apisrswr_des <span class="ot">&lt;-</span> apisrswr <span class="sc">%&gt;%</span></span>
<span id="cb295-2"><a href="c10-sample-designs-replicate-weights.html#cb295-2" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">weights =</span> weight)</span>
<span id="cb295-3"><a href="c10-sample-designs-replicate-weights.html#cb295-3" tabindex="-1"></a></span>
<span id="cb295-4"><a href="c10-sample-designs-replicate-weights.html#cb295-4" tabindex="-1"></a>apisrswr_des</span></code></pre></div>
<pre><code>## Independent Sampling design (with replacement)
## Called via srvyr
## Sampling variables:
##   - ids: `1` 
##   - weights: weight 
## Data variables: 
##   - cds (chr), dnum (int), snum (dbl), dname (chr), sname (chr), weight
##     (dbl)</code></pre>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="c10-sample-designs-replicate-weights.html#cb297-1" tabindex="-1"></a><span class="fu">summary</span>(apisrswr_des)</span></code></pre></div>
<pre><code>## Independent Sampling design (with replacement)
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0323  0.0323  0.0323  0.0323  0.0323  0.0323 
## Data variables:
## [1] &quot;cds&quot;    &quot;dnum&quot;   &quot;snum&quot;   &quot;dname&quot;  &quot;sname&quot;  &quot;weight&quot;</code></pre>
<p>
In the output above, the design object and the object summary are shown. Both note that the sampling is done “with replacement” because no FPC was specified. The probabilities, which are derived from the weights, are summarized in the summary function output.
</p>
</div>
</div>
<div id="stratified-sampling" class="section level3 hasAnchor" number="10.2.3">
<h3><span class="header-section-number">10.2.3</span> Stratified sampling <a href="c10-sample-designs-replicate-weights.html#stratified-sampling" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Stratified sampling occurs when a population is divided into mutually exclusive subpopulations (strata), and then samples are selected independently within each stratum.</p>
<ul>
<li>Requirements: The sampling frame must include the information to divide the population into strata for every unit.</li>
<li>Advantages:
<ul>
<li>This design ensures sample representation in all subpopulations.</li>
<li>If the strata are correlated with survey outcomes, a stratified sample has smaller standard errors compared to a SRS sample of the same size.</li>
<li>This results in a more efficient design.</li>
</ul></li>
<li>Disadvantages: Auxiliary data may not exist to divide the sampling frame into strata, or the data may be outdated.</li>
<li>Examples:
<ul>
<li>Example 1: A population of North Carolina residents could be stratified into urban and rural areas, and then an SRS of residents from both rural and urban areas is selected independently. This ensures there are residents from both areas in the sample.</li>
<li>Example 2: Law enforcement agencies could be stratified into the three primary general-purpose categories in the U.S.: local police, sheriff’s departments, and state police. An SRS of agencies from each of the three types is then selected independently to ensure all three types of agencies are represented.</li>
</ul></li>
</ul>
<div id="the-math-2" class="section level4 unnumbered hasAnchor">
<h4>The math<a href="c10-sample-designs-replicate-weights.html#the-math-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let <span class="math inline">\(\bar{y}_h\)</span> be the sample mean for stratum <span class="math inline">\(h\)</span>, <span class="math inline">\(N_h\)</span> be the population size of stratum <span class="math inline">\(h\)</span>, <span class="math inline">\(n_h\)</span> be the sample size of stratum <span class="math inline">\(h\)</span>, and <span class="math inline">\(H\)</span> be the total number of strata. Then, the estimate for the population mean under stratified SRS sampling is:</p>
<p><span class="math display">\[\bar{y}=\frac{1}{N}\sum_{h=1}^H N_h\bar{y}_h\]</span>
and the estimate of the standard error of <span class="math inline">\(\bar{y}\)</span> is:</p>
<p><span class="math display">\[se(\bar{y})=\sqrt{\frac{1}{N^2} \sum_{h=1}^H N_h^2 \frac{s_h^2}{n_h}\left(1-\frac{n_h}{N_h}\right)} \]</span></p>
<p>where
<span class="math display">\[s_h^2=\frac{1}{n_h-1}\sum_{i=1}^{n_h}\left(y_{i,h}-\bar{y}_h\right)^2\]</span></p>
<p>For estimates of proportions, let <span class="math inline">\(\hat{p}_h\)</span> be the estimated proportion in stratum <span class="math inline">\(h\)</span>. Then, the population proportion estimate is:</p>
<p><span class="math display">\[\hat{p}= \frac{1}{N}\sum_{h=1}^H N_h \hat{p}_h\]</span></p>
<p>The standard error of the proportion is:</p>
<p><span class="math display">\[se(\hat{p}) = \frac{1}{N} \sqrt{ \sum_{h=1}^H N_h^2 \frac{\hat{p}_h(1-\hat{p}_h)}{n_h-1} \left(1-\frac{n_h}{N_h}\right)}\]</span></p>
</div>
<div id="the-syntax-2" class="section level4 unnumbered hasAnchor">
<h4>The syntax<a href="c10-sample-designs-replicate-weights.html#the-syntax-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>
In addition to the <code>fpc</code> and <code>weights</code> arguments discussed in the types above, stratified designs require the addition of the <code>strata</code> argument. For example, to specify a stratified SRS design in {srvyr} when using the FPC, that is, where the population sizes of the strata are not too large and are known, we specify the design as:</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="c10-sample-designs-replicate-weights.html#cb299-1" tabindex="-1"></a>stsrs1_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb299-2"><a href="c10-sample-designs-replicate-weights.html#cb299-2" tabindex="-1"></a> <span class="fu">as_survey_design</span>(<span class="at">fpc =</span> fpcvar, </span>
<span id="cb299-3"><a href="c10-sample-designs-replicate-weights.html#cb299-3" tabindex="-1"></a>                  <span class="at">strata =</span> stratavar)</span></code></pre></div>
<p>where <code>fpcvar</code> is a variable on our data that indicates <span class="math inline">\(N_h\)</span> for each row, and <code>stratavar</code> is a variable indicating the stratum for each row. We can omit the FPC if it is not applicable. Additionally, we can indicate the weight variable if it is present where <code>wtvar</code> is a variable on our data with a numeric weight.</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="c10-sample-designs-replicate-weights.html#cb300-1" tabindex="-1"></a>stsrs2_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb300-2"><a href="c10-sample-designs-replicate-weights.html#cb300-2" tabindex="-1"></a> <span class="fu">as_survey_design</span>(<span class="at">weights =</span> wtvar, </span>
<span id="cb300-3"><a href="c10-sample-designs-replicate-weights.html#cb300-3" tabindex="-1"></a>                  <span class="at">strata =</span> stratavar)</span></code></pre></div>
</div>
<div id="example-4" class="section level4 unnumbered hasAnchor">
<h4>Example<a href="c10-sample-designs-replicate-weights.html#example-4" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In the example APIP data, <code>apistrat</code> is a stratified random sample, stratified by school type (<code>stype</code>) with three levels: <code>E</code> for elementary school, <code>M</code> for middle school, and <code>H</code> for high school. As with the SRS example above, we sort and select specific variables for use in printing. The data are illustrated below, including a count of the number of cases per stratum:</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="c10-sample-designs-replicate-weights.html#cb301-1" tabindex="-1"></a>apistrat_slim <span class="ot">&lt;-</span></span>
<span id="cb301-2"><a href="c10-sample-designs-replicate-weights.html#cb301-2" tabindex="-1"></a>  apistrat <span class="sc">%&gt;%</span></span>
<span id="cb301-3"><a href="c10-sample-designs-replicate-weights.html#cb301-3" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb301-4"><a href="c10-sample-designs-replicate-weights.html#cb301-4" tabindex="-1"></a>  <span class="fu">arrange</span>(dnum, snum) <span class="sc">%&gt;%</span></span>
<span id="cb301-5"><a href="c10-sample-designs-replicate-weights.html#cb301-5" tabindex="-1"></a>  <span class="fu">select</span>(cds, dnum, snum, dname, sname, stype, fpc, pw)</span>
<span id="cb301-6"><a href="c10-sample-designs-replicate-weights.html#cb301-6" tabindex="-1"></a></span>
<span id="cb301-7"><a href="c10-sample-designs-replicate-weights.html#cb301-7" tabindex="-1"></a>apistrat_slim <span class="sc">%&gt;%</span></span>
<span id="cb301-8"><a href="c10-sample-designs-replicate-weights.html#cb301-8" tabindex="-1"></a>  <span class="fu">count</span>(stype, fpc)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   stype   fpc     n
##   &lt;fct&gt; &lt;dbl&gt; &lt;int&gt;
## 1 E      4421   100
## 2 H       755    50
## 3 M      1018    50</code></pre>
<p>The FPC is the same for each case within each stratum. This output also shows that 100 elementary schools, 50 middle schools, and 50 high schools were sampled. It is often common for the number of units sampled from each strata to be different based on the goals of the project, or to mirror the size of each strata in the population. We specify the design as:</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="c10-sample-designs-replicate-weights.html#cb303-1" tabindex="-1"></a>apistrat_des <span class="ot">&lt;-</span> apistrat_slim <span class="sc">%&gt;%</span></span>
<span id="cb303-2"><a href="c10-sample-designs-replicate-weights.html#cb303-2" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(</span>
<span id="cb303-3"><a href="c10-sample-designs-replicate-weights.html#cb303-3" tabindex="-1"></a>    <span class="at">strata =</span> stype,</span>
<span id="cb303-4"><a href="c10-sample-designs-replicate-weights.html#cb303-4" tabindex="-1"></a>    <span class="at">weights =</span> pw,</span>
<span id="cb303-5"><a href="c10-sample-designs-replicate-weights.html#cb303-5" tabindex="-1"></a>    <span class="at">fpc =</span> fpc</span>
<span id="cb303-6"><a href="c10-sample-designs-replicate-weights.html#cb303-6" tabindex="-1"></a>  )</span>
<span id="cb303-7"><a href="c10-sample-designs-replicate-weights.html#cb303-7" tabindex="-1"></a></span>
<span id="cb303-8"><a href="c10-sample-designs-replicate-weights.html#cb303-8" tabindex="-1"></a>apistrat_des</span></code></pre></div>
<pre><code>## Stratified Independent Sampling design
## Called via srvyr
## Sampling variables:
##   - ids: `1` 
##   - strata: stype 
##   - fpc: fpc 
##   - weights: pw 
## Data variables: 
##   - cds (chr), dnum (int), snum (dbl), dname (chr), sname (chr), stype
##     (fct), fpc (dbl), pw (dbl)</code></pre>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="c10-sample-designs-replicate-weights.html#cb305-1" tabindex="-1"></a><span class="fu">summary</span>(apistrat_des)</span></code></pre></div>
<pre><code>## Stratified Independent Sampling design
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0226  0.0226  0.0359  0.0401  0.0534  0.0662 
## Stratum Sizes: 
##              E  H  M
## obs        100 50 50
## design.PSU 100 50 50
## actual.PSU 100 50 50
## Population stratum sizes (PSUs): 
##    E    H    M 
## 4421  755 1018 
## Data variables:
## [1] &quot;cds&quot;   &quot;dnum&quot;  &quot;snum&quot;  &quot;dname&quot; &quot;sname&quot; &quot;stype&quot; &quot;fpc&quot;   &quot;pw&quot;</code></pre>
<p>When printing the object, it is specified as a “Stratified Independent Sampling design,” also known as a stratified SRS, and the strata variable is included. Printing the summary, we see a distribution of probabilities, as we saw with SRS; but we also see the sample and population sizes by stratum. </p>
</div>
</div>
<div id="samp-cluster" class="section level3 hasAnchor" number="10.2.4">
<h3><span class="header-section-number">10.2.4</span> Clustered sampling<a href="c10-sample-designs-replicate-weights.html#samp-cluster" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>
Clustered sampling occurs when a population is divided into mutually exclusive subgroups called clusters or primary sampling units (PSUs). A random selection of PSUs is sampled, and then another level of sampling is done within these clusters. There can be multiple levels of this selection. Clustered sampling is often used when a list of the entire population is not available or data collection involves interviewers needing direct contact with respondents.</p>
<ul>
<li>Requirements: There must be a way to divide the population into clusters. Clusters are commonly structural, such as institutions (e.g., schools, prisons) or geography (e.g., states, counties).</li>
<li>Advantages:
<ul>
<li>Clustered sampling is advantageous when data collection is done in person, so interviewers are sent to specific sampled areas rather than completely at random across a country. </li>
<li>With clustered sampling, a list of the entire population is not necessary. For example, if sampling students, we do not need a list of all students, but only a list of all schools. Once the schools are sampled, lists of students can be obtained within the sampled schools.</li>
</ul></li>
<li>Disadvantages: Compared to a simple random sample for the same sample size, clustered samples generally have larger standard errors of estimates.</li>
<li>Examples:
<ul>
<li>Example 1: Consider a study needing a sample of 6th-grade students in the United States. No list likely exists of all these students. However, it is more likely to obtain a list of schools that enroll 6th graders, so a study design could select a random sample of schools that enroll 6th graders. The selected schools can then provide a list of students to do a second stage of sampling where 6th-grade students are randomly sampled within each of the sampled schools. This is a one-stage sample design (the one representing the number of clusters) and is the type of design we discuss in the formulas below.</li>
<li>Example 2: Consider a study sending interviewers to households for a survey. This is a more complicated example that requires two levels of clustering (two-stage sample design) to efficiently use interviewers in geographic clusters. First, in the U.S., counties could be selected as the PSU and then census block groups within counties could be selected as the secondary sampling unit (SSU). Households could then be randomly sampled within the block groups. This type of design is popular for in-person surveys, as it reduces the travel necessary for interviewers.</li>
</ul></li>
</ul>
<div id="the-math-3" class="section level4 unnumbered hasAnchor">
<h4>The math<a href="c10-sample-designs-replicate-weights.html#the-math-3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Consider a survey where <span class="math inline">\(a\)</span> clusters are sampled from a population of <span class="math inline">\(A\)</span> clusters via SRS. Within each sampled cluster, <span class="math inline">\(i\)</span>, there are <span class="math inline">\(B_i\)</span> units in the population, and <span class="math inline">\(b_i\)</span> units are sampled via SRS. Let <span class="math inline">\(\bar{y}_{i}\)</span> be the sample mean of cluster <span class="math inline">\(i\)</span>. Then, a ratio estimator of the population mean is:</p>
<p><span class="math display">\[\bar{y}=\frac{\sum_{i=1}^a B_i \bar{y}_{i}}{ \sum_{i=1}^a B_i}\]</span>
Note this is a consistent but biased estimator. Often the population size is not known, so this is a method to estimate a mean without knowing the population size. The estimated standard error of the mean is:</p>
<p><span class="math display">\[se(\bar{y})= \frac{1}{\hat{N}}\sqrt{\left(1-\frac{a}{A}\right)\frac{s_a^2}{a} + \frac{A}{a} \sum_{i=1}^a \left(1-\frac{b_i}{B_i}\right) \frac{s_i^2}{b_i} }\]</span>
where <span class="math inline">\(\hat{N}\)</span> is the estimated population size, <span class="math inline">\(s_a^2\)</span> is the between-cluster variance, and <span class="math inline">\(s_i^2\)</span> is the within-cluster variance.</p>
<p>The formula for the between-cluster variance (<span class="math inline">\(s_a^2\)</span>) is:</p>
<p><span class="math display">\[s_a^2=\frac{1}{a-1}\sum_{i=1}^a \left( \hat{y}_i - \frac{\sum_{i=1}^a \hat{y}_{i} }{a}\right)^2\]</span>
where <span class="math inline">\(\hat{y}_i =B_i\bar{y_i}\)</span>.</p>
<p>The formula for the within-cluster variance (<span class="math inline">\(s_i^2\)</span>) is:</p>
<p><span class="math display">\[s_i^2=\frac{1}{a(b_i-1)} \sum_{j=1}^{b_i} \left(y_{ij}-\bar{y}_i\right)^2\]</span>
where <span class="math inline">\(y_{ij}\)</span> is the outcome for sampled unit <span class="math inline">\(j\)</span> within cluster <span class="math inline">\(i\)</span>.</p>
</div>
<div id="the-syntax-3" class="section level4 unnumbered hasAnchor">
<h4>The syntax<a href="c10-sample-designs-replicate-weights.html#the-syntax-3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>
Clustered sampling designs require the addition of the <code>ids</code> argument, which specifies the cluster level variable(s). To specify a two-stage clustered design without replacement, we specify the design as:</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="c10-sample-designs-replicate-weights.html#cb307-1" tabindex="-1"></a>clus2_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb307-2"><a href="c10-sample-designs-replicate-weights.html#cb307-2" tabindex="-1"></a> <span class="fu">as_survey_design</span>(<span class="at">weights =</span> wtvar, </span>
<span id="cb307-3"><a href="c10-sample-designs-replicate-weights.html#cb307-3" tabindex="-1"></a>                  <span class="at">ids =</span> <span class="fu">c</span>(PSU, SSU), </span>
<span id="cb307-4"><a href="c10-sample-designs-replicate-weights.html#cb307-4" tabindex="-1"></a>                  <span class="at">fpc =</span> <span class="fu">c</span>(A, B))</span></code></pre></div>
<p>where <code>PSU</code> and <code>SSU</code> are the variables indicating the PSU and SSU identifiers, and <code>A</code> and <code>B</code> are the variables indicating the population sizes for each level (i.e., <code>A</code> is the number of clusters, and <code>B</code> is the number of units within each cluster). Note that <code>A</code> is the same for all records, and <code>B</code> is the same for all records within the same cluster.</p>
<p>If clusters were sampled with replacement or from a very large population, the FPC is unnecessary. Additionally, only the first stage of selection is necessary regardless of whether the units were selected with replacement at any stage. The subsequent stages of selection are ignored in computation as their contribution to the variance is overpowered by the first stage (see <span class="citation">Särndal, Swensson, and Wretman (<a href="#ref-sarndal2003model">2003</a>)</span> or <span class="citation">Wolter (<a href="#ref-wolter2007introduction">2007</a>)</span> for a more in-depth discussion). Therefore, the two design objects specified below yield the same estimates in the end:
</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="c10-sample-designs-replicate-weights.html#cb308-1" tabindex="-1"></a>clus2ex1_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb308-2"><a href="c10-sample-designs-replicate-weights.html#cb308-2" tabindex="-1"></a> <span class="fu">as_survey_design</span>(<span class="at">weights =</span> wtvar, </span>
<span id="cb308-3"><a href="c10-sample-designs-replicate-weights.html#cb308-3" tabindex="-1"></a>                  <span class="at">ids =</span> <span class="fu">c</span>(PSU, SSU))</span>
<span id="cb308-4"><a href="c10-sample-designs-replicate-weights.html#cb308-4" tabindex="-1"></a></span>
<span id="cb308-5"><a href="c10-sample-designs-replicate-weights.html#cb308-5" tabindex="-1"></a>clus2ex2_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb308-6"><a href="c10-sample-designs-replicate-weights.html#cb308-6" tabindex="-1"></a> <span class="fu">as_survey_design</span>(<span class="at">weights =</span> wtvar, </span>
<span id="cb308-7"><a href="c10-sample-designs-replicate-weights.html#cb308-7" tabindex="-1"></a>                  <span class="at">ids =</span> PSU)</span></code></pre></div>
<p>
Note that there is one additional argument that is sometimes necessary, which is <code>nest = TRUE</code>. This option relabels cluster IDs to enforce nesting within strata. Sometimes, as an example, there may be a cluster <code>1</code> within each stratum, but cluster <code>1</code> in stratum <code>1</code> is a different cluster than cluster <code>1</code> in stratum <code>2</code>. These are actually different clusters. This option indicates that repeated numbering does not mean it is the same cluster. If this option is not used and there are repeated cluster IDs across different strata, an error is generated.
</p>
</div>
<div id="example-5" class="section level4 unnumbered hasAnchor">
<h4>Example<a href="c10-sample-designs-replicate-weights.html#example-5" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>
The <code>survey</code> package includes a two-stage cluster sample data, <code>apiclus2</code>, in which school districts were sampled, and then a random sample of five schools was selected within each district. For districts with fewer than five schools, all schools were sampled. School districts are identified by <code>dnum</code>, and schools are identified by <code>snum</code>. The variable <code>fpc1</code> indicates how many districts there are in California (the total number of PSUs or <code>A</code>), and <code>fpc2</code> indicates how many schools were in a given district with at least 100 students (the total number of SSUs or <code>B</code>). The data include a row for each school. In the data printed below, there are 757 school districts, as indicated by <code>fpc1</code>, and there are nine schools in District 731, one school in District 742, two schools in District 768, and so on as indicated by <code>fpc2</code>. For illustration purposes, the object <code>apiclus2_slim</code> has been created from <code>apiclus2</code>, which subsets the data to only the necessary columns and sorts the data.</p>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="c10-sample-designs-replicate-weights.html#cb309-1" tabindex="-1"></a>apiclus2_slim <span class="ot">&lt;-</span></span>
<span id="cb309-2"><a href="c10-sample-designs-replicate-weights.html#cb309-2" tabindex="-1"></a>  apiclus2 <span class="sc">%&gt;%</span></span>
<span id="cb309-3"><a href="c10-sample-designs-replicate-weights.html#cb309-3" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb309-4"><a href="c10-sample-designs-replicate-weights.html#cb309-4" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(dnum), snum) <span class="sc">%&gt;%</span></span>
<span id="cb309-5"><a href="c10-sample-designs-replicate-weights.html#cb309-5" tabindex="-1"></a>  <span class="fu">select</span>(cds, dnum, snum, fpc1, fpc2, pw)</span>
<span id="cb309-6"><a href="c10-sample-designs-replicate-weights.html#cb309-6" tabindex="-1"></a></span>
<span id="cb309-7"><a href="c10-sample-designs-replicate-weights.html#cb309-7" tabindex="-1"></a>apiclus2_slim</span></code></pre></div>
<pre><code>## # A tibble: 126 × 6
##    cds             dnum  snum  fpc1      fpc2    pw
##    &lt;chr&gt;          &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int[1d]&gt; &lt;dbl&gt;
##  1 47704826050942   795  5552   757         1  18.9
##  2 07618126005169   781   530   757         6  22.7
##  3 07618126005177   781   531   757         6  22.7
##  4 07618126005185   781   532   757         6  22.7
##  5 07618126005193   781   533   757         6  22.7
##  6 07618126005243   781   535   757         6  22.7
##  7 19650786023337   768  2371   757         2  18.9
##  8 19650786023345   768  2372   757         2  18.9
##  9 54722076054423   742  5898   757         1  18.9
## 10 50712906053086   731  5781   757         9  34.1
## # ℹ 116 more rows</code></pre>
<p>To specify this design in R, we use the following:</p>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="c10-sample-designs-replicate-weights.html#cb311-1" tabindex="-1"></a>apiclus2_des <span class="ot">&lt;-</span> apiclus2_slim <span class="sc">%&gt;%</span></span>
<span id="cb311-2"><a href="c10-sample-designs-replicate-weights.html#cb311-2" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(</span>
<span id="cb311-3"><a href="c10-sample-designs-replicate-weights.html#cb311-3" tabindex="-1"></a>    <span class="at">ids =</span> <span class="fu">c</span>(dnum, snum),</span>
<span id="cb311-4"><a href="c10-sample-designs-replicate-weights.html#cb311-4" tabindex="-1"></a>    <span class="at">fpc =</span> <span class="fu">c</span>(fpc1, fpc2),</span>
<span id="cb311-5"><a href="c10-sample-designs-replicate-weights.html#cb311-5" tabindex="-1"></a>    <span class="at">weights =</span> pw</span>
<span id="cb311-6"><a href="c10-sample-designs-replicate-weights.html#cb311-6" tabindex="-1"></a>  )</span>
<span id="cb311-7"><a href="c10-sample-designs-replicate-weights.html#cb311-7" tabindex="-1"></a></span>
<span id="cb311-8"><a href="c10-sample-designs-replicate-weights.html#cb311-8" tabindex="-1"></a>apiclus2_des</span></code></pre></div>
<pre><code>## 2 - level Cluster Sampling design
## With (40, 126) clusters.
## Called via srvyr
## Sampling variables:
##   - ids: `dnum + snum` 
##   - fpc: `fpc1 + fpc2` 
##   - weights: pw 
## Data variables: 
##   - cds (chr), dnum (int), snum (dbl), fpc1 (dbl), fpc2 (int[1d]), pw
##     (dbl)</code></pre>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb313-1"><a href="c10-sample-designs-replicate-weights.html#cb313-1" tabindex="-1"></a><span class="fu">summary</span>(apiclus2_des)</span></code></pre></div>
<pre><code>## 2 - level Cluster Sampling design
## With (40, 126) clusters.
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 0.00367 0.03774 0.05284 0.04239 0.05284 0.05284 
## Population size (PSUs): 757 
## Data variables:
## [1] &quot;cds&quot;  &quot;dnum&quot; &quot;snum&quot; &quot;fpc1&quot; &quot;fpc2&quot; &quot;pw&quot;</code></pre>
<p>The design objects are described as “2 - level Cluster Sampling design,” and include the ids (cluster), FPC, and weight variables. The summary notes that the sample includes 40 first-level clusters (PSUs), which are school districts, and 126 second-level clusters (SSUs), which are schools. Additionally, the summary includes a numeric summary of the probabilities of selection and the population size (number of PSUs) as 757.
</p>
</div>
</div>
</div>
<div id="samp-combo" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Combining sampling methods<a href="c10-sample-designs-replicate-weights.html#samp-combo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p> </p>
<p>SRS, stratified, and clustered designs are the backbone of sampling designs, and the features are often combined in one design. Additionally, rather than using SRS for selection, other sampling mechanisms are commonly used, such as probability proportional to size (PPS), systematic sampling, or selection with unequal probabilities, which are briefly described here. In PPS sampling, a size measure is constructed for each unit (e.g., the population of the PSU or the number of occupied housing units), and units with larger size measures are more likely to be sampled. Systematic sampling is commonly used to ensure representation across a population. Units are sorted by a feature, and then every <span class="math inline">\(k\)</span> units is selected from a random start point so the sample is spread across the population. In addition to PPS, other unequal probabilities of selection may be used. For example, in a study of establishments (e.g., businesses or public institutions) that conducts a survey every year, an establishment that recently participated (e.g., participated last year) may have a reduced chance of selection in a subsequent round to reduce the burden on the establishment. To learn more about sampling designs, refer to <span class="citation">Valliant, Dever, and Kreuter (<a href="#ref-valliant2013practical">2013</a>)</span>, <span class="citation">Cox et al. (<a href="#ref-cox2011business">2011</a>)</span>, <span class="citation">Cochran (<a href="#ref-cochran1977sampling">1977</a>)</span>, and <span class="citation">Deming (<a href="#ref-deming1991sample">1991</a>)</span>.</p>
<p>A common method of sampling is to stratify PSUs, select PSUs within the stratum using PPS selection, and then select units within the PSUs either with SRS or PPS. Reading survey documentation is an important first step in survey analysis to understand the design of the survey we are using and variables necessary to specify the design. Good documentation highlights the variables necessary to specify the design. This is often found in the user guide, methodology report, analysis guide, or technical documentation (see Chapter <a href="c03-survey-data-documentation.html#c03-survey-data-documentation">3</a> for more details).
</p>
<div id="example-6" class="section level3 unnumbered hasAnchor">
<h3>Example<a href="c10-sample-designs-replicate-weights.html#example-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>
For example, the <a href="https://www.cdc.gov/nchs/data/nsfg/NSFG-2017-2019-Sample-Design-Documentation-508.pdf">2017-2019 National Survey of Family Growth</a> had a stratified multi-stage area probability sample:</p>
<ol style="list-style-type: decimal">
<li>In the first stage, PSUs are counties or collections of counties and are stratified by Census region/division, size (population), and MSA status. Within each stratum, PSUs were selected via PPS.</li>
<li>In the second stage, neighborhoods were selected within the sampled PSUs using PPS selection.</li>
<li>In the third stage, housing units were selected within the sampled neighborhoods.</li>
<li>In the fourth stage, a person was randomly chosen among eligible persons within the selected housing units using unequal probabilities based on the person’s age and sex.</li>
</ol>
<p>The public use file does not include all these levels of selection and instead has pseudo-strata and pseudo-clusters, which are the variables used in R to specify the design. As specified on page 4 of the documentation, the stratum variable is <code>SEST</code>, the cluster variable is <code>SECU</code>, and the weight variable is <code>WGT2017_2019</code>. Thus, to specify this design in R, we use the following syntax:</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="c10-sample-designs-replicate-weights.html#cb315-1" tabindex="-1"></a>nsfg_des <span class="ot">&lt;-</span> nsfgdata <span class="sc">%&gt;%</span></span>
<span id="cb315-2"><a href="c10-sample-designs-replicate-weights.html#cb315-2" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">ids =</span> SECU,</span>
<span id="cb315-3"><a href="c10-sample-designs-replicate-weights.html#cb315-3" tabindex="-1"></a>                   <span class="at">strata =</span> SEST,</span>
<span id="cb315-4"><a href="c10-sample-designs-replicate-weights.html#cb315-4" tabindex="-1"></a>                   <span class="at">weights =</span> WGT2017_2019)</span></code></pre></div>
<p> </p>
</div>
</div>
<div id="replicate-weights" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> Replicate weights<a href="c10-sample-designs-replicate-weights.html#replicate-weights" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>
Replicate weights are often included on analysis files instead of, or in addition to, the design variables (strata and PSUs). Replicate weights are used as another method to estimate variability. Often, researchers choose to use replicate weights to avoid publishing design variables (strata or clustering variables) as a measure to reduce the risk of disclosure. There are several types of replicate weights, including balanced repeated replication (BRR), Fay’s BRR, jackknife, and bootstrap methods. An overview of the process for using replicate weights is as follows:</p>
<ol style="list-style-type: decimal">
<li>Divide the sample into subsample replicates that mirror the design of the sample</li>
<li>Calculate weights for each replicate using the same procedures for the full-sample weight (i.e., nonresponse and post-stratification)</li>
<li>Calculate estimates for each replicate using the same method as the full-sample estimate</li>
<li>Calculate the estimated variance, which is proportional to the variance of the replicate estimates</li>
</ol>
<p>The different types of replicate weights largely differ between step 1 (how the sample is divided into subsamples) and step 4 (which multiplication factors, scales, are used to multiply the variance). The general format for the standard error is:</p>
<p><span class="math display">\[ \sqrt{\alpha \sum_{r=1}^R \alpha_r (\hat{\theta}_r - \hat{\theta})^2 }\]</span></p>
<p>where <span class="math inline">\(R\)</span> is the number of replicates, <span class="math inline">\(\alpha\)</span> is a constant that depends on the replication method, <span class="math inline">\(\alpha_r\)</span> is a factor associated with each replicate, <span class="math inline">\(\hat{\theta}\)</span> is the weighted estimate based on the full sample, and <span class="math inline">\(\hat{\theta}_r\)</span> is the weighted estimate of <span class="math inline">\(\theta\)</span> based on the <span class="math inline">\(r^{\text{th}}\)</span> replicate.</p>
<p>To create the design object for surveys with replicate weights, we use <code>as_survey_rep()</code> instead of <code>as_survey_design()</code>, which we use for the common sampling designs in the sections above.</p>
<div id="balanced-repeated-replication-method" class="section level3 hasAnchor" number="10.4.1">
<h3><span class="header-section-number">10.4.1</span> Balanced Repeated Replication method<a href="c10-sample-designs-replicate-weights.html#balanced-repeated-replication-method" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>
The balanced repeated replication (BRR) method requires a stratified sample design with two PSUs in each stratum. Each replicate is constructed by deleting one PSU per stratum using a Hadamard matrix. For the PSU that is included, the weight is generally multiplied by two but may have other adjustments, such as post-stratification. A Hadamard matrix is a special square matrix with entries of +1 or –1 with mutually orthogonal rows. Hadamard matrices must have one row, two rows, or a multiple of four rows. The size of the Hadamard matrix is determined by the first multiple of 4 greater than or equal to the number of strata. For example, if a survey had seven strata, the Hadamard matrix would be an <span class="math inline">\(8\times8\)</span> matrix. Additionally, a survey with eight strata would also have an <span class="math inline">\(8\times8\)</span> Hadamard matrix. The columns in the matrix specify the strata, and the rows specify the replicate. In each replicate (row), a +1 means to use the first PSU, and a –1 means to use the second PSU in the estimate. For example, here is a <span class="math inline">\(4\times4\)</span> Hadamard matrix:</p>
<p><span class="math display">\[ \begin{array}{rrrr} +1 &amp;+1 &amp;+1 &amp;+1\\ +1&amp;-1&amp;+1&amp;-1\\ +1&amp;+1&amp;-1&amp;-1\\ +1 &amp;-1&amp;-1&amp;+1 \end{array} \]</span>
In the first replicate (row), all the values are +1; so in each stratum, the first PSU would be used in the estimate. In the second replicate, the first PSU would be used in strata 1 and 3, while the second PSU would be used in strata 2 and 4. In the third replicate, the first PSU would be used in strata 1 and 2, while the second PSU would be used in strata 3 and 4. Finally, in the fourth replicate, the first PSU would be used in strata 1 and 4, while the second PSU would be used in strata 2 and 3. For more information about Hadamard matrices, see <span class="citation">Wolter (<a href="#ref-wolter2007introduction">2007</a>)</span>. Note that supplied BRR weights from a data provider already incorporate this adjustment, and the {survey} package generates the Hadamard matrix, if necessary, for calculating BRR weights; so an analyst does not need to create or provide the matrix.
</p>
<div id="the-math-4" class="section level4 unnumbered hasAnchor">
<h4>The math<a href="c10-sample-designs-replicate-weights.html#the-math-4" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A weighted estimate for the full sample is calculated as <span class="math inline">\(\hat{\theta}\)</span>, and then a weighted estimate for each replicate is calculated as <span class="math inline">\(\hat{\theta}_r\)</span> for <span class="math inline">\(R\)</span> replicates. Using the generic notation above, <span class="math inline">\(\alpha=\frac{1}{R}\)</span> and <span class="math inline">\(\alpha_r=1\)</span> for each <span class="math inline">\(r\)</span>. The standard error of the estimate is calculated as follows:</p>
<p><span class="math display">\[se(\hat{\theta})=\sqrt{\frac{1}{R} \sum_{r=1}^R \left( \hat{\theta}_r-\hat{\theta}\right)^2}\]</span></p>
<p>Specifying replicate weights in R requires specifying the type of replicate weights, the main weight variable, the replicate weight variables, and other options. One of the key options is for the mean squared error (MSE). If <code>mse=TRUE</code>, variances are computed around the point estimate <span class="math inline">\((\hat{\theta})\)</span>; whereas if <code>mse=FALSE</code>, variances are computed around the mean of the replicates <span class="math inline">\((\bar{\theta})\)</span> instead, which looks like this:</p>
<p><span class="math display">\[se(\hat{\theta})=\sqrt{\frac{1}{R} \sum_{r=1}^R \left( \hat{\theta}_r-\bar{\theta}\right)^2}\]</span> where <span class="math display">\[\bar{\theta}=\frac{1}{R}\sum_{r=1}^R \hat{\theta}_r\]</span></p>
<p>The default option for <code>mse</code> is to use the global option of “survey.replicates.mse,” which is set to <code>FALSE</code> initially unless a user changes it. To determine if <code>mse</code> should be set to <code>TRUE</code> or <code>FALSE</code>, read the survey documentation. If there is no indication in the survey documentation for BRR, we recommend setting <code>mse</code> to <code>TRUE</code>, as this is the default in other software (e.g., SAS, SUDAAN).</p>
</div>
<div id="the-syntax-4" class="section level4 unnumbered hasAnchor">
<h4>The syntax<a href="c10-sample-designs-replicate-weights.html#the-syntax-4" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>
Replicate weights generally come in groups and are sequentially numbered, such as PWGTP1, PWGTP2, …, PWGTP80 for the person weights in the American Community Survey (ACS) <span class="citation">(<a href="#ref-acs-pums-2021">U.S. Census Bureau 2021</a>)</span> or BRRWT1, BRRWT2, …, BRRWT96 in the 2015 Residential Energy Consumption Survey (RECS) <span class="citation">(<a href="#ref-recs-2015-micro">U.S. Energy Information Administration 2017</a>)</span>. This makes it easy to use some of the <a href="https://dplyr.tidyverse.org/reference/dplyr_tidy_select.html">tidy selection</a> functions in R.
</p>
<p>To specify a BRR design, we need to specify the weight variable (<code>weights</code>), the replicate weight variables (<code>repweights</code>), the type of replicate weights as BRR (<code>type = BRR</code>), and whether the mean squared error should be used (<code>mse = TRUE</code>) or not (<code>mse = FALSE</code>). For example, if a dataset had WT0 for the main weight and had 20 BRR weights indicated WT1, WT2, …, WT20, we can use the following syntax (both are equivalent):</p>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="c10-sample-designs-replicate-weights.html#cb316-1" tabindex="-1"></a>brr_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb316-2"><a href="c10-sample-designs-replicate-weights.html#cb316-2" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(<span class="at">weights =</span> WT0,</span>
<span id="cb316-3"><a href="c10-sample-designs-replicate-weights.html#cb316-3" tabindex="-1"></a>                <span class="at">repweights =</span> <span class="fu">all_of</span>(<span class="fu">str_c</span>(<span class="st">&quot;WT&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>)), </span>
<span id="cb316-4"><a href="c10-sample-designs-replicate-weights.html#cb316-4" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">&quot;BRR&quot;</span>,</span>
<span id="cb316-5"><a href="c10-sample-designs-replicate-weights.html#cb316-5" tabindex="-1"></a>                <span class="at">mse =</span> <span class="cn">TRUE</span>)</span>
<span id="cb316-6"><a href="c10-sample-designs-replicate-weights.html#cb316-6" tabindex="-1"></a></span>
<span id="cb316-7"><a href="c10-sample-designs-replicate-weights.html#cb316-7" tabindex="-1"></a>brr_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb316-8"><a href="c10-sample-designs-replicate-weights.html#cb316-8" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(<span class="at">weights =</span> WT0,</span>
<span id="cb316-9"><a href="c10-sample-designs-replicate-weights.html#cb316-9" tabindex="-1"></a>                <span class="at">repweights =</span> <span class="fu">num_range</span>(<span class="st">&quot;WT&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>),</span>
<span id="cb316-10"><a href="c10-sample-designs-replicate-weights.html#cb316-10" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">&quot;BRR&quot;</span>,</span>
<span id="cb316-11"><a href="c10-sample-designs-replicate-weights.html#cb316-11" tabindex="-1"></a>                <span class="at">mse =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>If a dataset had WT for the main weight and had 20 BRR weights indicated REPWT1, REPWT2, …, REPWT20, we can use the following syntax (both are equivalent):</p>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="c10-sample-designs-replicate-weights.html#cb317-1" tabindex="-1"></a>brr_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb317-2"><a href="c10-sample-designs-replicate-weights.html#cb317-2" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(<span class="at">weights =</span> WT,</span>
<span id="cb317-3"><a href="c10-sample-designs-replicate-weights.html#cb317-3" tabindex="-1"></a>                <span class="at">repweights =</span> <span class="fu">all_of</span>(<span class="fu">str_c</span>(<span class="st">&quot;REPWT&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>)),</span>
<span id="cb317-4"><a href="c10-sample-designs-replicate-weights.html#cb317-4" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">&quot;BRR&quot;</span>,</span>
<span id="cb317-5"><a href="c10-sample-designs-replicate-weights.html#cb317-5" tabindex="-1"></a>                <span class="at">mse =</span> <span class="cn">TRUE</span>)</span>
<span id="cb317-6"><a href="c10-sample-designs-replicate-weights.html#cb317-6" tabindex="-1"></a></span>
<span id="cb317-7"><a href="c10-sample-designs-replicate-weights.html#cb317-7" tabindex="-1"></a>brr_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb317-8"><a href="c10-sample-designs-replicate-weights.html#cb317-8" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(<span class="at">weights =</span> WT,</span>
<span id="cb317-9"><a href="c10-sample-designs-replicate-weights.html#cb317-9" tabindex="-1"></a>                <span class="at">repweights =</span> <span class="fu">starts_with</span>(<span class="st">&quot;REPWT&quot;</span>),</span>
<span id="cb317-10"><a href="c10-sample-designs-replicate-weights.html#cb317-10" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">&quot;BRR&quot;</span>,</span>
<span id="cb317-11"><a href="c10-sample-designs-replicate-weights.html#cb317-11" tabindex="-1"></a>                <span class="at">mse =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>If the replicate weight variables are in the file consecutively, we can also use the following syntax:</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="c10-sample-designs-replicate-weights.html#cb318-1" tabindex="-1"></a>brr_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb318-2"><a href="c10-sample-designs-replicate-weights.html#cb318-2" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(<span class="at">weights =</span> WT,</span>
<span id="cb318-3"><a href="c10-sample-designs-replicate-weights.html#cb318-3" tabindex="-1"></a>                <span class="at">repweights =</span> REPWT1<span class="sc">:</span>REPWT20,</span>
<span id="cb318-4"><a href="c10-sample-designs-replicate-weights.html#cb318-4" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">&quot;BRR&quot;</span>,</span>
<span id="cb318-5"><a href="c10-sample-designs-replicate-weights.html#cb318-5" tabindex="-1"></a>                <span class="at">mse =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>Typically, each replicate weight sums to a value similar to the main weight, as both the replicate weights and the main weight are supposed to provide population estimates. Rarely, an alternative method is used where the replicate weights have values of 0 or 2 in the case of BRR weights. This would be indicated in the documentation (see Chapter <a href="c03-survey-data-documentation.html#c03-survey-data-documentation">3</a> for more information on reading documentation). In this case, the replicate weights are not combined, and the option <code>combined_weights = FALSE</code> should be indicated, as the default value for this argument is <code>TRUE</code>. This specific syntax is shown below:</p>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb319-1"><a href="c10-sample-designs-replicate-weights.html#cb319-1" tabindex="-1"></a>brr_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb319-2"><a href="c10-sample-designs-replicate-weights.html#cb319-2" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(<span class="at">weights =</span> WT,</span>
<span id="cb319-3"><a href="c10-sample-designs-replicate-weights.html#cb319-3" tabindex="-1"></a>                <span class="at">repweights =</span> <span class="fu">starts_with</span>(<span class="st">&quot;REPWT&quot;</span>),</span>
<span id="cb319-4"><a href="c10-sample-designs-replicate-weights.html#cb319-4" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">&quot;BRR&quot;</span>,</span>
<span id="cb319-5"><a href="c10-sample-designs-replicate-weights.html#cb319-5" tabindex="-1"></a>                <span class="at">combined_weights =</span> <span class="cn">FALSE</span>,</span>
<span id="cb319-6"><a href="c10-sample-designs-replicate-weights.html#cb319-6" tabindex="-1"></a>                <span class="at">mse =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</div>
<div id="example-7" class="section level4 unnumbered hasAnchor">
<h4>Example<a href="c10-sample-designs-replicate-weights.html#example-7" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>
The {survey} package includes a data example from section 12.2 of <span class="citation">Levy and Lemeshow (<a href="#ref-levy2013sampling">2013</a>)</span>. In this fictional data, two out of five ambulance stations were sampled from each of three emergency service areas (ESAs); thus BRR weights are appropriate with two PSUs (stations) sampled in each stratum (ESA). In the code below, we create BRR weights as was done by <span class="citation">Levy and Lemeshow (<a href="#ref-levy2013sampling">2013</a>)</span>.</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="c10-sample-designs-replicate-weights.html#cb320-1" tabindex="-1"></a>scdbrr <span class="ot">&lt;-</span> scd <span class="sc">%&gt;%</span></span>
<span id="cb320-2"><a href="c10-sample-designs-replicate-weights.html#cb320-2" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb320-3"><a href="c10-sample-designs-replicate-weights.html#cb320-3" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb320-4"><a href="c10-sample-designs-replicate-weights.html#cb320-4" tabindex="-1"></a>    <span class="at">wt =</span> <span class="dv">5</span> <span class="sc">/</span> <span class="dv">2</span>,</span>
<span id="cb320-5"><a href="c10-sample-designs-replicate-weights.html#cb320-5" tabindex="-1"></a>    <span class="at">rep1 =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb320-6"><a href="c10-sample-designs-replicate-weights.html#cb320-6" tabindex="-1"></a>    <span class="at">rep2 =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb320-7"><a href="c10-sample-designs-replicate-weights.html#cb320-7" tabindex="-1"></a>    <span class="at">rep3 =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb320-8"><a href="c10-sample-designs-replicate-weights.html#cb320-8" tabindex="-1"></a>    <span class="at">rep4 =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb320-9"><a href="c10-sample-designs-replicate-weights.html#cb320-9" tabindex="-1"></a>  )</span>
<span id="cb320-10"><a href="c10-sample-designs-replicate-weights.html#cb320-10" tabindex="-1"></a></span>
<span id="cb320-11"><a href="c10-sample-designs-replicate-weights.html#cb320-11" tabindex="-1"></a>scdbrr</span></code></pre></div>
<pre><code>## # A tibble: 6 × 9
##     ESA ambulance arrests alive    wt  rep1  rep2  rep3  rep4
##   &lt;int&gt;     &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1         1     120    25   2.5     2     2     0     0
## 2     1         2      78    24   2.5     0     0     2     2
## 3     2         1     185    30   2.5     2     0     2     0
## 4     2         2     228    49   2.5     0     2     0     2
## 5     3         1     670    80   2.5     2     0     0     2
## 6     3         2     530    70   2.5     0     2     2     0</code></pre>
<p>To specify the BRR weights, we use the following syntax:</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="c10-sample-designs-replicate-weights.html#cb322-1" tabindex="-1"></a>scdbrr_des <span class="ot">&lt;-</span> scdbrr <span class="sc">%&gt;%</span></span>
<span id="cb322-2"><a href="c10-sample-designs-replicate-weights.html#cb322-2" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(</span>
<span id="cb322-3"><a href="c10-sample-designs-replicate-weights.html#cb322-3" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">&quot;BRR&quot;</span>,</span>
<span id="cb322-4"><a href="c10-sample-designs-replicate-weights.html#cb322-4" tabindex="-1"></a>    <span class="at">repweights =</span> <span class="fu">starts_with</span>(<span class="st">&quot;rep&quot;</span>),</span>
<span id="cb322-5"><a href="c10-sample-designs-replicate-weights.html#cb322-5" tabindex="-1"></a>    <span class="at">combined_weights =</span> <span class="cn">FALSE</span>,</span>
<span id="cb322-6"><a href="c10-sample-designs-replicate-weights.html#cb322-6" tabindex="-1"></a>    <span class="at">weight =</span> wt</span>
<span id="cb322-7"><a href="c10-sample-designs-replicate-weights.html#cb322-7" tabindex="-1"></a>  )</span>
<span id="cb322-8"><a href="c10-sample-designs-replicate-weights.html#cb322-8" tabindex="-1"></a></span>
<span id="cb322-9"><a href="c10-sample-designs-replicate-weights.html#cb322-9" tabindex="-1"></a>scdbrr_des</span></code></pre></div>
<pre><code>## Call: Called via srvyr
## Balanced Repeated Replicates with 4 replicates.
## Sampling variables:
##   - repweights: `rep1 + rep2 + rep3 + rep4` 
##   - weights: wt 
## Data variables: 
##   - ESA (int), ambulance (int), arrests (dbl), alive (dbl), wt (dbl),
##     rep1 (dbl), rep2 (dbl), rep3 (dbl), rep4 (dbl)</code></pre>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb324-1"><a href="c10-sample-designs-replicate-weights.html#cb324-1" tabindex="-1"></a><span class="fu">summary</span>(scdbrr_des)</span></code></pre></div>
<pre><code>## Call: Called via srvyr
## Balanced Repeated Replicates with 4 replicates.
## Sampling variables:
##   - repweights: `rep1 + rep2 + rep3 + rep4` 
##   - weights: wt 
## Data variables: 
##   - ESA (int), ambulance (int), arrests (dbl), alive (dbl), wt (dbl),
##     rep1 (dbl), rep2 (dbl), rep3 (dbl), rep4 (dbl)
## Variables: 
## [1] &quot;ESA&quot;       &quot;ambulance&quot; &quot;arrests&quot;   &quot;alive&quot;     &quot;wt&quot;       
## [6] &quot;rep1&quot;      &quot;rep2&quot;      &quot;rep3&quot;      &quot;rep4&quot;</code></pre>
<p>Note that <code>combined_weights</code> was specified as <code>FALSE</code> because these weights are simply specified as 0 and 2 and do not incorporate the overall weight. When printing the object, the type of replication is noted as Balanced Repeated Replicates, and the replicate weights and the weight variable are specified. Additionally, the summary lists the variables included in the data and design object.
</p>
</div>
</div>
<div id="fays-brr-method" class="section level3 hasAnchor" number="10.4.2">
<h3><span class="header-section-number">10.4.2</span> Fay’s BRR method<a href="c10-sample-designs-replicate-weights.html#fays-brr-method" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Fay’s BRR method for replicate weights is similar to the BRR method in that it uses a Hadamard matrix to construct replicate weights. However, rather than deleting PSUs for each replicate, with Fay’s BRR, half of the PSUs have a replicate weight, which is the main weight multiplied by <span class="math inline">\(\rho\)</span>, and the other half have the main weight multiplied by <span class="math inline">\((2-\rho)\)</span>, where <span class="math inline">\(0 \le \rho &lt; 1\)</span>. Note that when <span class="math inline">\(\rho=0\)</span>, this is equivalent to the standard BRR weights, and as <span class="math inline">\(\rho\)</span> becomes closer to 1, this method is more similar to jackknife discussed in Section <a href="c10-sample-designs-replicate-weights.html#samp-jackknife">10.4.3</a>. To obtain the value of <span class="math inline">\(\rho\)</span>, it is necessary to read the survey documentation (see Chapter <a href="c03-survey-data-documentation.html#c03-survey-data-documentation">3</a>).</p>
<div id="the-math-5" class="section level4 unnumbered hasAnchor">
<h4>The math<a href="c10-sample-designs-replicate-weights.html#the-math-5" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The standard error estimate for <span class="math inline">\(\hat{\theta}\)</span> is slightly different than the BRR, due to the addition of the multiplier of <span class="math inline">\(\rho\)</span>. Using the generic notation above, <span class="math inline">\(\alpha=\frac{1}{R \left(1-\rho\right)^2}\)</span> and <span class="math inline">\(\alpha_r=1 \text{ for all } r\)</span>. The standard error is calculated as:</p>
<p><span class="math display">\[se(\hat{\theta})=\sqrt{\frac{1}{R (1-\rho)^2} \sum_{r=1}^R \left( \hat{\theta}_r-\hat{\theta}\right)^2}\]</span></p>
</div>
<div id="the-syntax-5" class="section level4 unnumbered hasAnchor">
<h4>The syntax<a href="c10-sample-designs-replicate-weights.html#the-syntax-5" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The syntax is very similar for BRR and Fay’s BRR. To specify a Fay’s BRR design, we need to specify the weight variable (<code>weights</code>), the replicate weight variables (<code>repweights</code>), the type of replicate weights as Fay’s BRR (<code>type = Fay</code>), whether the mean squared error should be used (<code>mse = TRUE</code>) or not (<code>mse = FALSE</code>), and Fay’s multiplier (<code>rho</code>). For example, if a dataset had WT0 for the main weight and had 20 BRR weights indicated as WT1, WT2, …, WT20, and Fay’s multiplier is 0.3, we use the following syntax:</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="c10-sample-designs-replicate-weights.html#cb326-1" tabindex="-1"></a>fay_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb326-2"><a href="c10-sample-designs-replicate-weights.html#cb326-2" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(<span class="at">weights =</span> WT0,</span>
<span id="cb326-3"><a href="c10-sample-designs-replicate-weights.html#cb326-3" tabindex="-1"></a>                <span class="at">repweights =</span> <span class="fu">num_range</span>(<span class="st">&quot;WT&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>),</span>
<span id="cb326-4"><a href="c10-sample-designs-replicate-weights.html#cb326-4" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">&quot;Fay&quot;</span>,</span>
<span id="cb326-5"><a href="c10-sample-designs-replicate-weights.html#cb326-5" tabindex="-1"></a>                <span class="at">mse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb326-6"><a href="c10-sample-designs-replicate-weights.html#cb326-6" tabindex="-1"></a>                <span class="at">rho =</span> <span class="fl">0.3</span>)</span></code></pre></div>
</div>
<div id="example-8" class="section level4 unnumbered hasAnchor">
<h4>Example<a href="c10-sample-designs-replicate-weights.html#example-8" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>
The 2015 RECS <span class="citation">(<a href="#ref-recs-2015-micro">U.S. Energy Information Administration 2017</a>)</span> uses Fay’s BRR weights with the final weight as NWEIGHT and replicate weights as BRRWT1 - BRRWT96, and the documentation specifies a Fay’s multiplier of 0.5. On the file, DOEID is a unique identifier for each respondent, TOTALDOL is the total energy cost, TOTSQFT_EN is the total square footage of the residence, and REGOINC is the census region. We use the 2015 RECS data from the {srvyrexploR} package that provides data for this book (see the Prerequisites box at the beginning of this chapter). To specify the design for the <code>recs_2015</code> data, we use the following syntax:</p>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb327-1"><a href="c10-sample-designs-replicate-weights.html#cb327-1" tabindex="-1"></a>recs_2015_des <span class="ot">&lt;-</span> recs_2015 <span class="sc">%&gt;%</span></span>
<span id="cb327-2"><a href="c10-sample-designs-replicate-weights.html#cb327-2" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(</span>
<span id="cb327-3"><a href="c10-sample-designs-replicate-weights.html#cb327-3" tabindex="-1"></a>    <span class="at">weights =</span> NWEIGHT,</span>
<span id="cb327-4"><a href="c10-sample-designs-replicate-weights.html#cb327-4" tabindex="-1"></a>    <span class="at">repweights =</span> BRRWT1<span class="sc">:</span>BRRWT96,</span>
<span id="cb327-5"><a href="c10-sample-designs-replicate-weights.html#cb327-5" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">&quot;Fay&quot;</span>,</span>
<span id="cb327-6"><a href="c10-sample-designs-replicate-weights.html#cb327-6" tabindex="-1"></a>    <span class="at">rho =</span> <span class="fl">0.5</span>,</span>
<span id="cb327-7"><a href="c10-sample-designs-replicate-weights.html#cb327-7" tabindex="-1"></a>    <span class="at">mse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb327-8"><a href="c10-sample-designs-replicate-weights.html#cb327-8" tabindex="-1"></a>    <span class="at">variables =</span> <span class="fu">c</span>(DOEID, TOTALDOL, TOTSQFT_EN, REGIONC)</span>
<span id="cb327-9"><a href="c10-sample-designs-replicate-weights.html#cb327-9" tabindex="-1"></a>  )</span>
<span id="cb327-10"><a href="c10-sample-designs-replicate-weights.html#cb327-10" tabindex="-1"></a></span>
<span id="cb327-11"><a href="c10-sample-designs-replicate-weights.html#cb327-11" tabindex="-1"></a>recs_2015_des</span></code></pre></div>
<pre><code>## Call: Called via srvyr
## Fay&#39;s variance method (rho= 0.5 ) with 96 replicates and MSE variances.
## Sampling variables:
##   - repweights: `BRRWT1 + BRRWT2 + BRRWT3 + BRRWT4 + BRRWT5 + BRRWT6 +
##     BRRWT7 + BRRWT8 + BRRWT9 + BRRWT10 + BRRWT11 + BRRWT12 + BRRWT13 +
##     BRRWT14 + BRRWT15 + BRRWT16 + BRRWT17 + BRRWT18 + BRRWT19 + BRRWT20
##     + BRRWT21 + BRRWT22 + BRRWT23 + BRRWT24 + BRRWT25 + BRRWT26 +
##     BRRWT27 + BRRWT28 + BRRWT29 + BRRWT30 + BRRWT31 + BRRWT32 + BRRWT33
##     + BRRWT34 + BRRWT35 + BRRWT36 + BRRWT37 + BRRWT38 + BRRWT39 +
##     BRRWT40 + BRRWT41 + BRRWT42 + BRRWT43 + BRRWT44 + BRRWT45 + BRRWT46
##     + BRRWT47 + BRRWT48 + BRRWT49 + BRRWT50 + BRRWT51 + BRRWT52 +
##     BRRWT53 + BRRWT54 + BRRWT55 + BRRWT56 + BRRWT57 + BRRWT58 + BRRWT59
##     + BRRWT60 + BRRWT61 + BRRWT62 + BRRWT63 + BRRWT64 + BRRWT65 +
##     BRRWT66 + BRRWT67 + BRRWT68 + BRRWT69 + BRRWT70 + BRRWT71 + BRRWT72
##     + BRRWT73 + BRRWT74 + BRRWT75 + BRRWT76 + BRRWT77 + BRRWT78 +
##     BRRWT79 + BRRWT80 + BRRWT81 + BRRWT82 + BRRWT83 + BRRWT84 + BRRWT85
##     + BRRWT86 + BRRWT87 + BRRWT88 + BRRWT89 + BRRWT90 + BRRWT91 +
##     BRRWT92 + BRRWT93 + BRRWT94 + BRRWT95 + BRRWT96` 
##   - weights: NWEIGHT 
## Data variables: 
##   - DOEID (dbl), TOTALDOL (dbl), TOTSQFT_EN (dbl), REGIONC (dbl)</code></pre>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="c10-sample-designs-replicate-weights.html#cb329-1" tabindex="-1"></a><span class="fu">summary</span>(recs_2015_des)</span></code></pre></div>
<pre><code>## Call: Called via srvyr
## Fay&#39;s variance method (rho= 0.5 ) with 96 replicates and MSE variances.
## Sampling variables:
##   - repweights: `BRRWT1 + BRRWT2 + BRRWT3 + BRRWT4 + BRRWT5 + BRRWT6 +
##     BRRWT7 + BRRWT8 + BRRWT9 + BRRWT10 + BRRWT11 + BRRWT12 + BRRWT13 +
##     BRRWT14 + BRRWT15 + BRRWT16 + BRRWT17 + BRRWT18 + BRRWT19 + BRRWT20
##     + BRRWT21 + BRRWT22 + BRRWT23 + BRRWT24 + BRRWT25 + BRRWT26 +
##     BRRWT27 + BRRWT28 + BRRWT29 + BRRWT30 + BRRWT31 + BRRWT32 + BRRWT33
##     + BRRWT34 + BRRWT35 + BRRWT36 + BRRWT37 + BRRWT38 + BRRWT39 +
##     BRRWT40 + BRRWT41 + BRRWT42 + BRRWT43 + BRRWT44 + BRRWT45 + BRRWT46
##     + BRRWT47 + BRRWT48 + BRRWT49 + BRRWT50 + BRRWT51 + BRRWT52 +
##     BRRWT53 + BRRWT54 + BRRWT55 + BRRWT56 + BRRWT57 + BRRWT58 + BRRWT59
##     + BRRWT60 + BRRWT61 + BRRWT62 + BRRWT63 + BRRWT64 + BRRWT65 +
##     BRRWT66 + BRRWT67 + BRRWT68 + BRRWT69 + BRRWT70 + BRRWT71 + BRRWT72
##     + BRRWT73 + BRRWT74 + BRRWT75 + BRRWT76 + BRRWT77 + BRRWT78 +
##     BRRWT79 + BRRWT80 + BRRWT81 + BRRWT82 + BRRWT83 + BRRWT84 + BRRWT85
##     + BRRWT86 + BRRWT87 + BRRWT88 + BRRWT89 + BRRWT90 + BRRWT91 +
##     BRRWT92 + BRRWT93 + BRRWT94 + BRRWT95 + BRRWT96` 
##   - weights: NWEIGHT 
## Data variables: 
##   - DOEID (dbl), TOTALDOL (dbl), TOTSQFT_EN (dbl), REGIONC (dbl)
## Variables: 
## [1] &quot;DOEID&quot;      &quot;TOTALDOL&quot;   &quot;TOTSQFT_EN&quot; &quot;REGIONC&quot;</code></pre>
<p>In specifying the design, the <code>variables</code> option was also used to include which variables might be used in analyses. This is optional but can make our object smaller and easier to work with. When printing the design object or looking at the summary, the replicate weight type is re-iterated as <code>Fay's variance method (rho= 0.5) with 96 replicates and MSE variances</code>, and the variables are included. No weight or probability summary is included in this output, as we have seen in some other design objects. </p>
</div>
</div>
<div id="samp-jackknife" class="section level3 hasAnchor" number="10.4.3">
<h3><span class="header-section-number">10.4.3</span> Jackknife method<a href="c10-sample-designs-replicate-weights.html#samp-jackknife" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>
There are three jackknife estimators implemented in {srvyr}: jackknife 1 (JK1), jackknife n (JKn), and jackknife 2 (JK2). The JK1 method can be used for unstratified designs, and replicates are created by removing one PSU at a time so the number of replicates is the same as the number of PSUs. If there is no clustering, then the PSU is the ultimate sampling unit (e.g., students).</p>
<p>
The JKn method is used for stratified designs and requires two or more PSUs per stratum. In this case, each replicate is created by deleting one PSU from a single stratum, so the number of replicates is the number of total PSUs across all strata. The JK2 method is a special case of JKn when there are exactly 2 PSUs sampled per stratum. For variance estimation, we also need to specify the scaling constants.
</p>
<div id="the-math-6" class="section level4 unnumbered hasAnchor">
<h4>The math<a href="c10-sample-designs-replicate-weights.html#the-math-6" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Using the generic notation above, <span class="math inline">\(\alpha=\frac{R-1}{R}\)</span> and <span class="math inline">\(\alpha_r=1 \text{ for all } r\)</span>. For the JK1 method, the standard error estimate for <span class="math inline">\(\hat{\theta}\)</span> is calculated as:</p>
<p><span class="math display">\[se(\hat{\theta})=\sqrt{\frac{R-1}{R} \sum_{r=1}^R \left( \hat{\theta}_r-\hat{\theta}\right)^2}\]</span>
The JKn method is a bit more complex, but the coefficients are generally provided with restricted and public-use files. For each replicate, one stratum has a PSU removed, and the weights are adjusted by <span class="math inline">\(n_h/(n_h-1)\)</span> where <span class="math inline">\(n_h\)</span> is the number of PSUs in stratum <span class="math inline">\(h\)</span>. The coefficients in other strata are set to 1. Denote the coefficient that results from this process for replicate <span class="math inline">\(r\)</span> as <span class="math inline">\(\alpha_r\)</span>, then the standard error estimate for <span class="math inline">\(\hat{\theta}\)</span> is calculated as:</p>
<p><span class="math display">\[se(\hat{\theta})=\sqrt{\sum_{r=1}^R \alpha_r \left( \hat{\theta}_r-\hat{\theta}\right)^2}\]</span></p>
<p></p>
</div>
<div id="the-syntax-6" class="section level4 unnumbered hasAnchor">
<h4>The syntax<a href="c10-sample-designs-replicate-weights.html#the-syntax-6" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To specify the jackknife method, we use the survey documentation to understand the type of jackknife (1, n, or 2) and the multiplier. In the syntax, we need to specify the weight variable (<code>weights</code>), the replicate weight variables (<code>repweights</code>), the type of replicate weights as jackknife 1 (<code>type = "JK1"</code>), n (<code>type = "JKN"</code>), or 2 (<code>type = "JK2"</code>), whether the mean squared error should be used (<code>mse = TRUE</code>) or not (<code>mse = FALSE</code>), and the multiplier (<code>scale</code>). For example, if the survey is a jackknife 1 method with a multiplier of <span class="math inline">\(\alpha_r=(R-1)/R=19/20=0.95\)</span>, the dataset has WT0 for the main weight and 20 replicate weights indicated as WT1, WT2, …, WT20, we use the following syntax:</p>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="c10-sample-designs-replicate-weights.html#cb331-1" tabindex="-1"></a>jk1_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb331-2"><a href="c10-sample-designs-replicate-weights.html#cb331-2" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(</span>
<span id="cb331-3"><a href="c10-sample-designs-replicate-weights.html#cb331-3" tabindex="-1"></a>    <span class="at">weights =</span> WT0,</span>
<span id="cb331-4"><a href="c10-sample-designs-replicate-weights.html#cb331-4" tabindex="-1"></a>    <span class="at">repweights =</span> <span class="fu">num_range</span>(<span class="st">&quot;WT&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>),</span>
<span id="cb331-5"><a href="c10-sample-designs-replicate-weights.html#cb331-5" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">&quot;JK1&quot;</span>,</span>
<span id="cb331-6"><a href="c10-sample-designs-replicate-weights.html#cb331-6" tabindex="-1"></a>    <span class="at">mse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb331-7"><a href="c10-sample-designs-replicate-weights.html#cb331-7" tabindex="-1"></a>    <span class="at">scale =</span> <span class="fl">0.95</span></span>
<span id="cb331-8"><a href="c10-sample-designs-replicate-weights.html#cb331-8" tabindex="-1"></a>  )</span></code></pre></div>
<p>For a jackknife n method, we need to specify the multiplier for all replicates. In this case, we use the <code>rscales</code> argument to specify each one. The documentation provides details on what the multipliers (<span class="math inline">\(\alpha_r\)</span>) are, and they may be the same for all replicates. For example, consider a case where <span class="math inline">\(\alpha_r=0.1\)</span> for all replicates, and the dataset had WT0 for the main weight and had 20 replicate weights indicated as WT1, WT2, …, WT20. We specify the type as <code>type = "JKN"</code>, and the multiplier as <code>rscales=rep(0.1,20)</code>:</p>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb332-1"><a href="c10-sample-designs-replicate-weights.html#cb332-1" tabindex="-1"></a>jkn_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb332-2"><a href="c10-sample-designs-replicate-weights.html#cb332-2" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(</span>
<span id="cb332-3"><a href="c10-sample-designs-replicate-weights.html#cb332-3" tabindex="-1"></a>    <span class="at">weights =</span> WT0,</span>
<span id="cb332-4"><a href="c10-sample-designs-replicate-weights.html#cb332-4" tabindex="-1"></a>    <span class="at">repweights =</span> <span class="fu">num_range</span>(<span class="st">&quot;WT&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>),</span>
<span id="cb332-5"><a href="c10-sample-designs-replicate-weights.html#cb332-5" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">&quot;JKN&quot;</span>,</span>
<span id="cb332-6"><a href="c10-sample-designs-replicate-weights.html#cb332-6" tabindex="-1"></a>    <span class="at">mse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb332-7"><a href="c10-sample-designs-replicate-weights.html#cb332-7" tabindex="-1"></a>    <span class="at">rscales =</span> <span class="fu">rep</span>(<span class="fl">0.1</span>, <span class="dv">20</span>)</span>
<span id="cb332-8"><a href="c10-sample-designs-replicate-weights.html#cb332-8" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<div id="example-9" class="section level4 unnumbered hasAnchor">
<h4>Example<a href="c10-sample-designs-replicate-weights.html#example-9" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>
The 2020 RECS <span class="citation">(<a href="#ref-recs-2020-micro">U.S. Energy Information Administration 2023c</a>)</span> uses jackknife weights with the final weight as NWEIGHT and replicate weights as NWEIGHT1 - NWEIGHT60 with a scale of <span class="math inline">\((R-1)/R=59/60\)</span>. On the file, DOEID is a unique identifier for each respondent, TOTALDOL is the total cost of energy, TOTSQFT_EN is the total square footage of the residence, and REGOINC is the census region. We use the 2020 RECS data from the {srvyrexploR} package that provides data for this book (see the Prerequisites box at the beginning of this chapter).</p>
<p>To specify this design, we use the following syntax:</p>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="c10-sample-designs-replicate-weights.html#cb333-1" tabindex="-1"></a>recs_des <span class="ot">&lt;-</span> recs_2020 <span class="sc">%&gt;%</span></span>
<span id="cb333-2"><a href="c10-sample-designs-replicate-weights.html#cb333-2" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(</span>
<span id="cb333-3"><a href="c10-sample-designs-replicate-weights.html#cb333-3" tabindex="-1"></a>    <span class="at">weights =</span> NWEIGHT,</span>
<span id="cb333-4"><a href="c10-sample-designs-replicate-weights.html#cb333-4" tabindex="-1"></a>    <span class="at">repweights =</span> NWEIGHT1<span class="sc">:</span>NWEIGHT60,</span>
<span id="cb333-5"><a href="c10-sample-designs-replicate-weights.html#cb333-5" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">&quot;JK1&quot;</span>,</span>
<span id="cb333-6"><a href="c10-sample-designs-replicate-weights.html#cb333-6" tabindex="-1"></a>    <span class="at">scale =</span> <span class="dv">59</span> <span class="sc">/</span> <span class="dv">60</span>,</span>
<span id="cb333-7"><a href="c10-sample-designs-replicate-weights.html#cb333-7" tabindex="-1"></a>    <span class="at">mse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb333-8"><a href="c10-sample-designs-replicate-weights.html#cb333-8" tabindex="-1"></a>    <span class="at">variables =</span> <span class="fu">c</span>(DOEID, TOTALDOL, TOTSQFT_EN, REGIONC)</span>
<span id="cb333-9"><a href="c10-sample-designs-replicate-weights.html#cb333-9" tabindex="-1"></a>  )</span>
<span id="cb333-10"><a href="c10-sample-designs-replicate-weights.html#cb333-10" tabindex="-1"></a></span>
<span id="cb333-11"><a href="c10-sample-designs-replicate-weights.html#cb333-11" tabindex="-1"></a>recs_des</span></code></pre></div>
<pre><code>## Call: Called via srvyr
## Unstratified cluster jacknife (JK1) with 60 replicates and MSE variances.
## Sampling variables:
##   - repweights: `NWEIGHT1 + NWEIGHT2 + NWEIGHT3 + NWEIGHT4 + NWEIGHT5 +
##     NWEIGHT6 + NWEIGHT7 + NWEIGHT8 + NWEIGHT9 + NWEIGHT10 + NWEIGHT11 +
##     NWEIGHT12 + NWEIGHT13 + NWEIGHT14 + NWEIGHT15 + NWEIGHT16 +
##     NWEIGHT17 + NWEIGHT18 + NWEIGHT19 + NWEIGHT20 + NWEIGHT21 +
##     NWEIGHT22 + NWEIGHT23 + NWEIGHT24 + NWEIGHT25 + NWEIGHT26 +
##     NWEIGHT27 + NWEIGHT28 + NWEIGHT29 + NWEIGHT30 + NWEIGHT31 +
##     NWEIGHT32 + NWEIGHT33 + NWEIGHT34 + NWEIGHT35 + NWEIGHT36 +
##     NWEIGHT37 + NWEIGHT38 + NWEIGHT39 + NWEIGHT40 + NWEIGHT41 +
##     NWEIGHT42 + NWEIGHT43 + NWEIGHT44 + NWEIGHT45 + NWEIGHT46 +
##     NWEIGHT47 + NWEIGHT48 + NWEIGHT49 + NWEIGHT50 + NWEIGHT51 +
##     NWEIGHT52 + NWEIGHT53 + NWEIGHT54 + NWEIGHT55 + NWEIGHT56 +
##     NWEIGHT57 + NWEIGHT58 + NWEIGHT59 + NWEIGHT60` 
##   - weights: NWEIGHT 
## Data variables: 
##   - DOEID (dbl), TOTALDOL (dbl), TOTSQFT_EN (dbl), REGIONC (chr)</code></pre>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="c10-sample-designs-replicate-weights.html#cb335-1" tabindex="-1"></a><span class="fu">summary</span>(recs_des)</span></code></pre></div>
<pre><code>## Call: Called via srvyr
## Unstratified cluster jacknife (JK1) with 60 replicates and MSE variances.
## Sampling variables:
##   - repweights: `NWEIGHT1 + NWEIGHT2 + NWEIGHT3 + NWEIGHT4 + NWEIGHT5 +
##     NWEIGHT6 + NWEIGHT7 + NWEIGHT8 + NWEIGHT9 + NWEIGHT10 + NWEIGHT11 +
##     NWEIGHT12 + NWEIGHT13 + NWEIGHT14 + NWEIGHT15 + NWEIGHT16 +
##     NWEIGHT17 + NWEIGHT18 + NWEIGHT19 + NWEIGHT20 + NWEIGHT21 +
##     NWEIGHT22 + NWEIGHT23 + NWEIGHT24 + NWEIGHT25 + NWEIGHT26 +
##     NWEIGHT27 + NWEIGHT28 + NWEIGHT29 + NWEIGHT30 + NWEIGHT31 +
##     NWEIGHT32 + NWEIGHT33 + NWEIGHT34 + NWEIGHT35 + NWEIGHT36 +
##     NWEIGHT37 + NWEIGHT38 + NWEIGHT39 + NWEIGHT40 + NWEIGHT41 +
##     NWEIGHT42 + NWEIGHT43 + NWEIGHT44 + NWEIGHT45 + NWEIGHT46 +
##     NWEIGHT47 + NWEIGHT48 + NWEIGHT49 + NWEIGHT50 + NWEIGHT51 +
##     NWEIGHT52 + NWEIGHT53 + NWEIGHT54 + NWEIGHT55 + NWEIGHT56 +
##     NWEIGHT57 + NWEIGHT58 + NWEIGHT59 + NWEIGHT60` 
##   - weights: NWEIGHT 
## Data variables: 
##   - DOEID (dbl), TOTALDOL (dbl), TOTSQFT_EN (dbl), REGIONC (chr)
## Variables: 
## [1] &quot;DOEID&quot;      &quot;TOTALDOL&quot;   &quot;TOTSQFT_EN&quot; &quot;REGIONC&quot;</code></pre>
<p>When printing the design object or looking at the summary, the replicate weight type is reiterated as <code>Unstratified cluster jacknife (JK1) with 60 replicates and MSE variances</code>, and the variables are included. No weight or probability summary is included. </p>
</div>
</div>
<div id="bootstrap-method" class="section level3 hasAnchor" number="10.4.4">
<h3><span class="header-section-number">10.4.4</span> Bootstrap method<a href="c10-sample-designs-replicate-weights.html#bootstrap-method" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>
In bootstrap resampling, replicates are created by selecting random samples of the PSUs with replacement (SRSWR). If there are <span class="math inline">\(A\)</span> PSUs in the sample, then each replicate is created by selecting a random sample of <span class="math inline">\(A\)</span> PSUs with replacement. Each replicate is created independently, and the weights for each replicate are adjusted to reflect the population, generally using the same method as how the analysis weight was adjusted.<br />
</p>
<div id="the-math-7" class="section level4 unnumbered hasAnchor">
<h4>The math<a href="c10-sample-designs-replicate-weights.html#the-math-7" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A weighted estimate for the full sample is calculated as <span class="math inline">\(\hat{\theta}\)</span>, and then a weighted estimate for each replicate is calculated as <span class="math inline">\(\hat{\theta}_r\)</span> for <span class="math inline">\(R\)</span> replicates. Then the standard error of the estimate is calculated as follows:</p>
<p><span class="math display">\[se(\hat{\theta})=\sqrt{\alpha \sum_{r=1}^R \left( \hat{\theta}_r-\hat{\theta}\right)^2}\]</span></p>
<p>where <span class="math inline">\(\alpha\)</span> is the scaling constant. Note that the scaling constant (<span class="math inline">\(\alpha\)</span>) is provided in the survey documentation, as there are many types of bootstrap methods that generate custom scaling constants.</p>
</div>
<div id="the-syntax-7" class="section level4 unnumbered hasAnchor">
<h4>The syntax<a href="c10-sample-designs-replicate-weights.html#the-syntax-7" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To specify a bootstrap method, we need to specify the weight variable (<code>weights</code>), the replicate weight variables (<code>repweights</code>), the type of replicate weights as bootstrap (<code>type = "bootstrap"</code>), whether the mean squared error should be used (<code>mse = TRUE</code>) or not (<code>mse = FALSE</code>), and the multiplier (<code>scale</code>). For example, if a dataset had WT0 for the main weight, 20 bootstrap weights indicated WT1, WT2, …, WT20, and a multiplier of <span class="math inline">\(\alpha=.02\)</span>, we use the following syntax:</p>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="c10-sample-designs-replicate-weights.html#cb337-1" tabindex="-1"></a>bs_des <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb337-2"><a href="c10-sample-designs-replicate-weights.html#cb337-2" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(</span>
<span id="cb337-3"><a href="c10-sample-designs-replicate-weights.html#cb337-3" tabindex="-1"></a>    <span class="at">weights =</span> WT0,</span>
<span id="cb337-4"><a href="c10-sample-designs-replicate-weights.html#cb337-4" tabindex="-1"></a>    <span class="at">repweights =</span> <span class="fu">num_range</span>(<span class="st">&quot;WT&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>),</span>
<span id="cb337-5"><a href="c10-sample-designs-replicate-weights.html#cb337-5" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">&quot;bootstrap&quot;</span>,</span>
<span id="cb337-6"><a href="c10-sample-designs-replicate-weights.html#cb337-6" tabindex="-1"></a>    <span class="at">mse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb337-7"><a href="c10-sample-designs-replicate-weights.html#cb337-7" tabindex="-1"></a>    <span class="at">scale =</span> .<span class="dv">02</span></span>
<span id="cb337-8"><a href="c10-sample-designs-replicate-weights.html#cb337-8" tabindex="-1"></a>  )</span></code></pre></div>
<p></p>
</div>
<div id="example-10" class="section level4 unnumbered hasAnchor">
<h4>Example<a href="c10-sample-designs-replicate-weights.html#example-10" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>
Returning to the APIP example, we are going to create a dataset with bootstrap weights to use as an example. In this example, we construct a one-cluster design with 50 replicate weights<a href="#fn28" class="footnote-ref" id="fnref28"><sup>28</sup></a>.</p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="c10-sample-designs-replicate-weights.html#cb338-1" tabindex="-1"></a>apiclus1_slim <span class="ot">&lt;-</span></span>
<span id="cb338-2"><a href="c10-sample-designs-replicate-weights.html#cb338-2" tabindex="-1"></a>  apiclus1 <span class="sc">%&gt;%</span></span>
<span id="cb338-3"><a href="c10-sample-designs-replicate-weights.html#cb338-3" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb338-4"><a href="c10-sample-designs-replicate-weights.html#cb338-4" tabindex="-1"></a>  <span class="fu">arrange</span>(dnum) <span class="sc">%&gt;%</span></span>
<span id="cb338-5"><a href="c10-sample-designs-replicate-weights.html#cb338-5" tabindex="-1"></a>  <span class="fu">select</span>(cds, dnum, fpc, pw)</span>
<span id="cb338-6"><a href="c10-sample-designs-replicate-weights.html#cb338-6" tabindex="-1"></a></span>
<span id="cb338-7"><a href="c10-sample-designs-replicate-weights.html#cb338-7" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">662152</span>)</span>
<span id="cb338-8"><a href="c10-sample-designs-replicate-weights.html#cb338-8" tabindex="-1"></a>apibw <span class="ot">&lt;-</span></span>
<span id="cb338-9"><a href="c10-sample-designs-replicate-weights.html#cb338-9" tabindex="-1"></a>  <span class="fu">bootweights</span>(</span>
<span id="cb338-10"><a href="c10-sample-designs-replicate-weights.html#cb338-10" tabindex="-1"></a>    <span class="at">psu =</span> apiclus1_slim<span class="sc">$</span>dnum,</span>
<span id="cb338-11"><a href="c10-sample-designs-replicate-weights.html#cb338-11" tabindex="-1"></a>    <span class="at">strata =</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(apiclus1_slim)),</span>
<span id="cb338-12"><a href="c10-sample-designs-replicate-weights.html#cb338-12" tabindex="-1"></a>    <span class="at">fpc =</span> apiclus1_slim<span class="sc">$</span>fpc,</span>
<span id="cb338-13"><a href="c10-sample-designs-replicate-weights.html#cb338-13" tabindex="-1"></a>    <span class="at">replicates =</span> <span class="dv">50</span></span>
<span id="cb338-14"><a href="c10-sample-designs-replicate-weights.html#cb338-14" tabindex="-1"></a>  )</span>
<span id="cb338-15"><a href="c10-sample-designs-replicate-weights.html#cb338-15" tabindex="-1"></a></span>
<span id="cb338-16"><a href="c10-sample-designs-replicate-weights.html#cb338-16" tabindex="-1"></a>bwmata <span class="ot">&lt;-</span></span>
<span id="cb338-17"><a href="c10-sample-designs-replicate-weights.html#cb338-17" tabindex="-1"></a>  apibw<span class="sc">$</span>repweights<span class="sc">$</span>weights[apibw<span class="sc">$</span>repweights<span class="sc">$</span>index, ] <span class="sc">*</span> apiclus1_slim<span class="sc">$</span>pw</span>
<span id="cb338-18"><a href="c10-sample-designs-replicate-weights.html#cb338-18" tabindex="-1"></a></span>
<span id="cb338-19"><a href="c10-sample-designs-replicate-weights.html#cb338-19" tabindex="-1"></a>apiclus1_slim <span class="ot">&lt;-</span> bwmata <span class="sc">%&gt;%</span></span>
<span id="cb338-20"><a href="c10-sample-designs-replicate-weights.html#cb338-20" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb338-21"><a href="c10-sample-designs-replicate-weights.html#cb338-21" tabindex="-1"></a>  <span class="fu">set_names</span>(<span class="fu">str_c</span>(<span class="st">&quot;pw&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb338-22"><a href="c10-sample-designs-replicate-weights.html#cb338-22" tabindex="-1"></a>  <span class="fu">cbind</span>(apiclus1_slim) <span class="sc">%&gt;%</span></span>
<span id="cb338-23"><a href="c10-sample-designs-replicate-weights.html#cb338-23" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb338-24"><a href="c10-sample-designs-replicate-weights.html#cb338-24" tabindex="-1"></a>  <span class="fu">select</span>(cds, dnum, fpc, pw, <span class="fu">everything</span>())</span>
<span id="cb338-25"><a href="c10-sample-designs-replicate-weights.html#cb338-25" tabindex="-1"></a></span>
<span id="cb338-26"><a href="c10-sample-designs-replicate-weights.html#cb338-26" tabindex="-1"></a>apiclus1_slim</span></code></pre></div>
<pre><code>## # A tibble: 183 × 54
##    cds        dnum   fpc    pw   pw1   pw2   pw3   pw4   pw5   pw6   pw7
##    &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 43693776…    61   757  33.8  33.8     0     0  33.8     0  33.8     0
##  2 43693776…    61   757  33.8  33.8     0     0  33.8     0  33.8     0
##  3 43693776…    61   757  33.8  33.8     0     0  33.8     0  33.8     0
##  4 43693776…    61   757  33.8  33.8     0     0  33.8     0  33.8     0
##  5 43693776…    61   757  33.8  33.8     0     0  33.8     0  33.8     0
##  6 43693776…    61   757  33.8  33.8     0     0  33.8     0  33.8     0
##  7 43693776…    61   757  33.8  33.8     0     0  33.8     0  33.8     0
##  8 43693776…    61   757  33.8  33.8     0     0  33.8     0  33.8     0
##  9 43693776…    61   757  33.8  33.8     0     0  33.8     0  33.8     0
## 10 43693776…    61   757  33.8  33.8     0     0  33.8     0  33.8     0
## # ℹ 173 more rows
## # ℹ 43 more variables: pw8 &lt;dbl&gt;, pw9 &lt;dbl&gt;, pw10 &lt;dbl&gt;, pw11 &lt;dbl&gt;,
## #   pw12 &lt;dbl&gt;, pw13 &lt;dbl&gt;, pw14 &lt;dbl&gt;, pw15 &lt;dbl&gt;, pw16 &lt;dbl&gt;,
## #   pw17 &lt;dbl&gt;, pw18 &lt;dbl&gt;, pw19 &lt;dbl&gt;, pw20 &lt;dbl&gt;, pw21 &lt;dbl&gt;,
## #   pw22 &lt;dbl&gt;, pw23 &lt;dbl&gt;, pw24 &lt;dbl&gt;, pw25 &lt;dbl&gt;, pw26 &lt;dbl&gt;,
## #   pw27 &lt;dbl&gt;, pw28 &lt;dbl&gt;, pw29 &lt;dbl&gt;, pw30 &lt;dbl&gt;, pw31 &lt;dbl&gt;,
## #   pw32 &lt;dbl&gt;, pw33 &lt;dbl&gt;, pw34 &lt;dbl&gt;, pw35 &lt;dbl&gt;, pw36 &lt;dbl&gt;, …</code></pre>
<p>The output of <code>apiclus1_slim</code> includes the same variables we have seen in other APIP examples (see Table <a href="c10-sample-designs-replicate-weights.html#tab:apidata">10.1</a>), but now it additionally includes bootstrap weights <code>pw1</code>, …, <code>pw50</code>. When creating the survey design object, we use the bootstrap weights as the replicate weights. Additionally, with replicate weights we need to include the scale (<span class="math inline">\(\alpha\)</span>). For this example, we created:</p>
<p><span class="math display">\[\alpha=\frac{A}{(A-1)(R-1)}=\frac{15}{(15-1)*(50-1)}=0.02186589\]</span></p>
<p>where <span class="math inline">\(A\)</span> is the average number of PSUs per stratum, and <span class="math inline">\(R\)</span> is the number of replicates. There is only 1 stratum and the number of clusters/PSUs is 15 so <span class="math inline">\(A=15\)</span>. Using this information, we specify the design object as:
</p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="c10-sample-designs-replicate-weights.html#cb340-1" tabindex="-1"></a>api1_bs_des <span class="ot">&lt;-</span> apiclus1_slim <span class="sc">%&gt;%</span></span>
<span id="cb340-2"><a href="c10-sample-designs-replicate-weights.html#cb340-2" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(</span>
<span id="cb340-3"><a href="c10-sample-designs-replicate-weights.html#cb340-3" tabindex="-1"></a>    <span class="at">weights =</span> pw,</span>
<span id="cb340-4"><a href="c10-sample-designs-replicate-weights.html#cb340-4" tabindex="-1"></a>    <span class="at">repweights =</span> pw1<span class="sc">:</span>pw50,</span>
<span id="cb340-5"><a href="c10-sample-designs-replicate-weights.html#cb340-5" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">&quot;bootstrap&quot;</span>,</span>
<span id="cb340-6"><a href="c10-sample-designs-replicate-weights.html#cb340-6" tabindex="-1"></a>    <span class="at">scale =</span> <span class="fl">0.02186589</span>,</span>
<span id="cb340-7"><a href="c10-sample-designs-replicate-weights.html#cb340-7" tabindex="-1"></a>    <span class="at">mse =</span> <span class="cn">TRUE</span></span>
<span id="cb340-8"><a href="c10-sample-designs-replicate-weights.html#cb340-8" tabindex="-1"></a>  )</span>
<span id="cb340-9"><a href="c10-sample-designs-replicate-weights.html#cb340-9" tabindex="-1"></a></span>
<span id="cb340-10"><a href="c10-sample-designs-replicate-weights.html#cb340-10" tabindex="-1"></a>api1_bs_des</span></code></pre></div>
<pre><code>## Call: Called via srvyr
## Survey bootstrap with 50 replicates and MSE variances.
## Sampling variables:
##   - repweights: `pw1 + pw2 + pw3 + pw4 + pw5 + pw6 + pw7 + pw8 + pw9 +
##     pw10 + pw11 + pw12 + pw13 + pw14 + pw15 + pw16 + pw17 + pw18 + pw19
##     + pw20 + pw21 + pw22 + pw23 + pw24 + pw25 + pw26 + pw27 + pw28 +
##     pw29 + pw30 + pw31 + pw32 + pw33 + pw34 + pw35 + pw36 + pw37 + pw38
##     + pw39 + pw40 + pw41 + pw42 + pw43 + pw44 + pw45 + pw46 + pw47 +
##     pw48 + pw49 + pw50` 
##   - weights: pw 
## Data variables: 
##   - cds (chr), dnum (int), fpc (dbl), pw (dbl), pw1 (dbl), pw2 (dbl),
##     pw3 (dbl), pw4 (dbl), pw5 (dbl), pw6 (dbl), pw7 (dbl), pw8 (dbl),
##     pw9 (dbl), pw10 (dbl), pw11 (dbl), pw12 (dbl), pw13 (dbl), pw14
##     (dbl), pw15 (dbl), pw16 (dbl), pw17 (dbl), pw18 (dbl), pw19 (dbl),
##     pw20 (dbl), pw21 (dbl), pw22 (dbl), pw23 (dbl), pw24 (dbl), pw25
##     (dbl), pw26 (dbl), pw27 (dbl), pw28 (dbl), pw29 (dbl), pw30 (dbl),
##     pw31 (dbl), pw32 (dbl), pw33 (dbl), pw34 (dbl), pw35 (dbl), pw36
##     (dbl), pw37 (dbl), pw38 (dbl), pw39 (dbl), pw40 (dbl), pw41 (dbl),
##     pw42 (dbl), pw43 (dbl), pw44 (dbl), pw45 (dbl), pw46 (dbl), pw47
##     (dbl), pw48 (dbl), pw49 (dbl), pw50 (dbl)</code></pre>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="c10-sample-designs-replicate-weights.html#cb342-1" tabindex="-1"></a><span class="fu">summary</span>(api1_bs_des)</span></code></pre></div>
<pre><code>## Call: Called via srvyr
## Survey bootstrap with 50 replicates and MSE variances.
## Sampling variables:
##   - repweights: `pw1 + pw2 + pw3 + pw4 + pw5 + pw6 + pw7 + pw8 + pw9 +
##     pw10 + pw11 + pw12 + pw13 + pw14 + pw15 + pw16 + pw17 + pw18 + pw19
##     + pw20 + pw21 + pw22 + pw23 + pw24 + pw25 + pw26 + pw27 + pw28 +
##     pw29 + pw30 + pw31 + pw32 + pw33 + pw34 + pw35 + pw36 + pw37 + pw38
##     + pw39 + pw40 + pw41 + pw42 + pw43 + pw44 + pw45 + pw46 + pw47 +
##     pw48 + pw49 + pw50` 
##   - weights: pw 
## Data variables: 
##   - cds (chr), dnum (int), fpc (dbl), pw (dbl), pw1 (dbl), pw2 (dbl),
##     pw3 (dbl), pw4 (dbl), pw5 (dbl), pw6 (dbl), pw7 (dbl), pw8 (dbl),
##     pw9 (dbl), pw10 (dbl), pw11 (dbl), pw12 (dbl), pw13 (dbl), pw14
##     (dbl), pw15 (dbl), pw16 (dbl), pw17 (dbl), pw18 (dbl), pw19 (dbl),
##     pw20 (dbl), pw21 (dbl), pw22 (dbl), pw23 (dbl), pw24 (dbl), pw25
##     (dbl), pw26 (dbl), pw27 (dbl), pw28 (dbl), pw29 (dbl), pw30 (dbl),
##     pw31 (dbl), pw32 (dbl), pw33 (dbl), pw34 (dbl), pw35 (dbl), pw36
##     (dbl), pw37 (dbl), pw38 (dbl), pw39 (dbl), pw40 (dbl), pw41 (dbl),
##     pw42 (dbl), pw43 (dbl), pw44 (dbl), pw45 (dbl), pw46 (dbl), pw47
##     (dbl), pw48 (dbl), pw49 (dbl), pw50 (dbl)
## Variables: 
##  [1] &quot;cds&quot;  &quot;dnum&quot; &quot;fpc&quot;  &quot;pw&quot;   &quot;pw1&quot;  &quot;pw2&quot;  &quot;pw3&quot;  &quot;pw4&quot;  &quot;pw5&quot; 
## [10] &quot;pw6&quot;  &quot;pw7&quot;  &quot;pw8&quot;  &quot;pw9&quot;  &quot;pw10&quot; &quot;pw11&quot; &quot;pw12&quot; &quot;pw13&quot; &quot;pw14&quot;
## [19] &quot;pw15&quot; &quot;pw16&quot; &quot;pw17&quot; &quot;pw18&quot; &quot;pw19&quot; &quot;pw20&quot; &quot;pw21&quot; &quot;pw22&quot; &quot;pw23&quot;
## [28] &quot;pw24&quot; &quot;pw25&quot; &quot;pw26&quot; &quot;pw27&quot; &quot;pw28&quot; &quot;pw29&quot; &quot;pw30&quot; &quot;pw31&quot; &quot;pw32&quot;
## [37] &quot;pw33&quot; &quot;pw34&quot; &quot;pw35&quot; &quot;pw36&quot; &quot;pw37&quot; &quot;pw38&quot; &quot;pw39&quot; &quot;pw40&quot; &quot;pw41&quot;
## [46] &quot;pw42&quot; &quot;pw43&quot; &quot;pw44&quot; &quot;pw45&quot; &quot;pw46&quot; &quot;pw47&quot; &quot;pw48&quot; &quot;pw49&quot; &quot;pw50&quot;</code></pre>
<p>As with other replicate design objects, when printing the object or looking at the summary, the replicate weights are provided along with the data variables. </p>
</div>
</div>
</div>
<div id="exercises-2" class="section level2 hasAnchor" number="10.5">
<h2><span class="header-section-number">10.5</span> Exercises<a href="c10-sample-designs-replicate-weights.html#exercises-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For this chapter, the exercises entail reading public documentation to determine how to specify the survey design. While reading the documentation, be on the lookout for description of the weights and the survey design variables or replicate weights.</p>
<ol style="list-style-type: decimal">
<li><p>The National Health Interview Survey (NHIS) is an annual household survey conducted by the National Center for Health Statistics (NCHS). The NHIS includes a wide variety of health topics for adults including health status and conditions, functioning and disability, health care access and health service utilization, health-related behaviors, health promotion, mental health, barriers to receiving care, and community engagement. Like many national in-person surveys, the sampling design is a stratified clustered design with details included in the Survey Description <span class="citation">(<a href="#ref-nhis-svy-des">National Center for Health Statistics 2023</a>)</span>. The Survey Description provides information on setting up syntax in SUDAAN, Stata, SPSS, SAS, and R ({survey} package implementation). We have imported the data and the variable containing the data as: <code>nhis_adult_data</code>. How would we specify the design using either <code>as_survey_design()</code> or <code>as_survey_rep()</code>?</p></li>
<li><p>The General Social Survey (GSS) is a survey that has been administered since 1972 on social, behavioral, and attitudinal topics. The 2016-2020 GSS Panel codebook provides examples of setting up syntax in SAS and Stata but not R <span class="citation">(<a href="#ref-gss-codebook">Davern et al. 2021</a>)</span>. We have imported the data and the variable containing the data as: <code>gss_data</code>. How would we specify the design in R using either <code>as_survey_design()</code> or <code>as_survey_rep()</code>?</p></li>
</ol>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-cochran1977sampling" class="csl-entry">
Cochran, William G. 1977. <em>Sampling Techniques</em>. John Wiley &amp; Sons.
</div>
<div id="ref-cox2011business" class="csl-entry">
Cox, Brenda G, David A Binder, B Nanjamma Chinnappa, Anders Christianson, Michael J Colledge, and Phillip S Kott. 2011. <em>Business Survey Methods</em>. John Wiley &amp; Sons.
</div>
<div id="ref-gss-codebook" class="csl-entry">
Davern, Michael, Rene Bautista, Jeremy Freese, Stephen L. Morgan, and Tom W. Smith. 2021. <span>“<span>General Social Survey 2016-2020 Panel Codebook</span>.”</span> Edited by Chicago NORC. <a href="https://gss.norc.org/Documents/codebook/2016-2020%20GSS%20Panel%20Codebook%20-%20R1a.pdf" class="uri">https://gss.norc.org/Documents/codebook/2016-2020%20GSS%20Panel%20Codebook%20-%20R1a.pdf</a>.
</div>
<div id="ref-deming1991sample" class="csl-entry">
Deming, W Edwards. 1991. <em>Sample Design in Business Research</em>. Vol. 23. John Wiley &amp; Sons.
</div>
<div id="ref-R-srvyr" class="csl-entry">
Freedman Ellis, Greg, and Ben Schneider. 2024. <em><span class="nocase">srvyr</span>: ’<span class="nocase">dplyr</span>’-Like Syntax for Summary Statistics of Survey Data</em>. <a href="http://gdfe.co/srvyr/">http://gdfe.co/srvyr/</a>.
</div>
<div id="ref-fuller2011sampling" class="csl-entry">
Fuller, Wayne A. 2011. <em>Sampling Statistics</em>. John Wiley &amp; Sons.
</div>
<div id="ref-levy2013sampling" class="csl-entry">
Levy, Paul S, and Stanley Lemeshow. 2013. <em>Sampling of Populations: Methods and Applications</em>. John Wiley &amp; Sons.
</div>
<div id="ref-lumley2010complex" class="csl-entry">
Lumley, Thomas. 2010. <em>Complex Surveys: A Guide to Analysis Using <span>R</span></em>. John Wiley &amp; Sons.
</div>
<div id="ref-nhis-svy-des" class="csl-entry">
National Center for Health Statistics. 2023. <span>“<span class="nocase">National Health Interview Survey, 2022 survey description</span>.”</span> <a href="https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/NHIS/2022/srvydesc-508.pdf" class="uri">https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/NHIS/2022/srvydesc-508.pdf</a>.
</div>
<div id="ref-pennstate506" class="csl-entry">
Penn State. 2019. <span>“STAT 506: Sampling Theory and Methods [Online Course].”</span> <a href="https://online.stat.psu.edu/stat506/" class="uri">https://online.stat.psu.edu/stat506/</a>.
</div>
<div id="ref-sarndal2003model" class="csl-entry">
Särndal, Carl-Erik, Bengt Swensson, and Jan Wretman. 2003. <em>Model Assisted Survey Sampling</em>. Springer Science &amp; Business Media.
</div>
<div id="ref-acs-pums-2021" class="csl-entry">
U.S. Census Bureau. 2021. <span>“<span class="nocase">Understanding and Using the American Community Survey Public Use Microdata Sample Files What Data Users Need to Know</span>.”</span> U.S. Government Printing Office; <a href="https://www.census.gov/content/dam/Census/library/publications/2021/acs/acs_pums_handbook_2021.pdf" class="uri">https://www.census.gov/content/dam/Census/library/publications/2021/acs/acs_pums_handbook_2021.pdf</a>.
</div>
<div id="ref-recs-2015-micro" class="csl-entry">
U.S. Energy Information Administration. 2017. <span>“<span class="nocase">Residential Energy Consumption Survey (RECS): Using the 2015 microdata file to compute estimates and standard errors (RSEs)</span>.”</span> <a href="https://www.eia.gov/consumption/residential/data/2015/pdf/microdata_v3.pdf" class="uri">https://www.eia.gov/consumption/residential/data/2015/pdf/microdata_v3.pdf</a>.
</div>
<div id="ref-recs-2020-micro" class="csl-entry">
———. 2023c. <span>“<span class="nocase">2020 Residential Energy Consumption Survey: Using the microdata file to compute estimates and relative standard errors (RSEs)</span>.”</span> <a href="https://www.eia.gov/consumption/residential/data/2020/pdf/microdata-guide.pdf" class="uri">https://www.eia.gov/consumption/residential/data/2020/pdf/microdata-guide.pdf</a>.
</div>
<div id="ref-valliant2013practical" class="csl-entry">
Valliant, Richard, Jill A Dever, and Frauke Kreuter. 2013. <em>Practical Tools for Designing and Weighting Survey Samples</em>. Vol. 1. Springer.
</div>
<div id="ref-wolter2007introduction" class="csl-entry">
Wolter, Kirk M. 2007. <em>Introduction to Variance Estimation</em>. Vol. 53. Springer.
</div>
<div id="ref-R-srvyrexploR" class="csl-entry">
Zimmer, Stephanie, Rebecca Powell, and Isabella Velásquez. 2024. <em><span class="nocase">srvyrexploR</span>: Data Supplement for Exploring Complex Survey Data Analysis Using <span>R</span></em>. <a href="https://github.com/tidy-survey-r/srvyrexploR">https://github.com/tidy-survey-r/srvyrexploR</a>.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="28">
<li id="fn28"><p>We provide the code here to replicate this example but are not focusing on the creation of the weights, as that is outside the scope of this book. We recommend referencing <span class="citation">Wolter (<a href="#ref-wolter2007introduction">2007</a>)</span> for more information on creating bootstrap weights.<a href="c10-sample-designs-replicate-weights.html#fnref28" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="c09-reprex-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="c11-missing-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": true,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "github"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/tidy-survey-r/tidy-survey-book/blob/main/10-sample-designs-replicate-weights.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
