<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Missing data | Exploring Complex Survey Data Analysis Using R</title>
  <meta name="description" content="Bookdown for CRC Press book on Exploring Complex Survey Data Analysis Using R." />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Missing data | Exploring Complex Survey Data Analysis Using R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/BookCover_Final.jpg" />
  <meta property="og:description" content="Bookdown for CRC Press book on Exploring Complex Survey Data Analysis Using R." />
  <meta name="github-repo" content="tidy-survey-r/tidy-survey-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Missing data | Exploring Complex Survey Data Analysis Using R" />
  
  <meta name="twitter:description" content="Bookdown for CRC Press book on Exploring Complex Survey Data Analysis Using R." />
  <meta name="twitter:image" content="/images/BookCover_Final.jpg" />

<meta name="author" content="Stephanie A. Zimmer, Rebecca J. Powell, and Isabella C. Velásquez" />


<meta name="date" content="2024-08-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="c10-sample-designs-replicate-weights.html"/>
<link rel="next" href="c12-recommendations.html"/>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>
<link href="libs/htmltools-fill/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets/htmlwidgets.js"></script>
<script src="libs/d3/d3.min.js"></script>
<script src="libs/dagre/dagre-d3.min.js"></script>
<link href="libs/mermaid/dist/mermaid.css" rel="stylesheet" />
<script src="libs/mermaid/dist/mermaid.slim.min.js"></script>
<link href="libs/DiagrammeR-styles/styles.css" rel="stylesheet" />
<script src="libs/chromatography/chromatography.js"></script>
<script src="libs/DiagrammeR-binding/DiagrammeR.js"></script>
<script defer data-domain="tidy-survey-r.github.io/tidy-survey-book" src="https://plausible.io/js/script.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Exploring Complex Survey Data Analysis Using R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#dedication"><i class="fa fa-check"></i>Dedication</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#citation"><i class="fa fa-check"></i>Citation</a></li>
</ul></li>
<li class="part"><span><b>I Introduction</b></span></li>
<li class="chapter" data-level="1" data-path="c01-intro.html"><a href="c01-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="c01-intro.html"><a href="c01-intro.html#survey-analysis-in-r"><i class="fa fa-check"></i><b>1.1</b> Survey analysis in R</a></li>
<li class="chapter" data-level="1.2" data-path="c01-intro.html"><a href="c01-intro.html#what-to-expect"><i class="fa fa-check"></i><b>1.2</b> What to expect</a></li>
<li class="chapter" data-level="1.3" data-path="c01-intro.html"><a href="c01-intro.html#prerequisites"><i class="fa fa-check"></i><b>1.3</b> Prerequisites</a></li>
<li class="chapter" data-level="1.4" data-path="c01-intro.html"><a href="c01-intro.html#datasets-used-in-this-book"><i class="fa fa-check"></i><b>1.4</b> Datasets used in this book</a></li>
<li class="chapter" data-level="1.5" data-path="c01-intro.html"><a href="c01-intro.html#conventions"><i class="fa fa-check"></i><b>1.5</b> Conventions</a></li>
<li class="chapter" data-level="1.6" data-path="c01-intro.html"><a href="c01-intro.html#getting-help"><i class="fa fa-check"></i><b>1.6</b> Getting help</a></li>
<li class="chapter" data-level="1.7" data-path="c01-intro.html"><a href="c01-intro.html#acknowledgements"><i class="fa fa-check"></i><b>1.7</b> Acknowledgements</a></li>
<li class="chapter" data-level="1.8" data-path="c01-intro.html"><a href="c01-intro.html#colophon"><i class="fa fa-check"></i><b>1.8</b> Colophon</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html"><i class="fa fa-check"></i><b>2</b> Overview of surveys</a>
<ul>
<li class="chapter" data-level="2.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#searching-for-public-use-survey-data"><i class="fa fa-check"></i><b>2.2</b> Searching for public-use survey data</a></li>
<li class="chapter" data-level="2.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#pre-survey-planning"><i class="fa fa-check"></i><b>2.3</b> Pre-survey planning</a></li>
<li class="chapter" data-level="2.4" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design"><i class="fa fa-check"></i><b>2.4</b> Study design</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-sampdesign"><i class="fa fa-check"></i><b>2.4.1</b> Sampling design</a></li>
<li class="chapter" data-level="2.4.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-dcplanning"><i class="fa fa-check"></i><b>2.4.2</b> Data collection planning</a></li>
<li class="chapter" data-level="2.4.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-design-questionnaire"><i class="fa fa-check"></i><b>2.4.3</b> Questionnaire design</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-datacollection"><i class="fa fa-check"></i><b>2.5</b> Data collection</a></li>
<li class="chapter" data-level="2.6" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post"><i class="fa fa-check"></i><b>2.6</b> Post-survey processing</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#data-cleaning-and-imputation-overview-post-cleaning"><i class="fa fa-check"></i><b>2.6.1</b> Data cleaning and imputation {#overview-post-cleaning} </a></li>
<li class="chapter" data-level="2.6.2" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-weighting"><i class="fa fa-check"></i><b>2.6.2</b> Weighting</a></li>
<li class="chapter" data-level="2.6.3" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-disclosure"><i class="fa fa-check"></i><b>2.6.3</b> Disclosure</a></li>
<li class="chapter" data-level="2.6.4" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#overview-post-documentation"><i class="fa fa-check"></i><b>2.6.4</b> Documentation</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="c02-overview-surveys.html"><a href="c02-overview-surveys.html#post-survey-data-analysis-and-reporting"><i class="fa fa-check"></i><b>2.7</b> Post-survey data analysis and reporting</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html"><i class="fa fa-check"></i><b>3</b> Survey data documentation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#types-of-survey-documentation"><i class="fa fa-check"></i><b>3.2</b> Types of survey documentation</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#technical-documentation"><i class="fa fa-check"></i><b>3.2.1</b> Technical documentation</a></li>
<li class="chapter" data-level="3.2.2" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#questionnaires"><i class="fa fa-check"></i><b>3.2.2</b> Questionnaires</a></li>
<li class="chapter" data-level="3.2.3" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#codebooks"><i class="fa fa-check"></i><b>3.2.3</b> Codebooks</a></li>
<li class="chapter" data-level="3.2.4" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#errata"><i class="fa fa-check"></i><b>3.2.4</b> Errata</a></li>
<li class="chapter" data-level="3.2.5" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#additional-resources"><i class="fa fa-check"></i><b>3.2.5</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#missing-data-coding"><i class="fa fa-check"></i><b>3.3</b> Missing data coding</a></li>
<li class="chapter" data-level="3.4" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#example-american-national-election-studies-anes-2020-survey-documentation"><i class="fa fa-check"></i><b>3.4</b> Example: American National Election Studies (ANES) 2020 survey documentation</a>
<ul>
<li class="chapter" data-level="" data-path="c03-survey-data-documentation.html"><a href="c03-survey-data-documentation.html#methodology"><i class="fa fa-check"></i>Methodology</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Analysis</b></span></li>
<li class="chapter" data-level="4" data-path="c04-getting-started.html"><a href="c04-getting-started.html"><i class="fa fa-check"></i><b>4</b> Getting started</a>
<ul>
<li class="chapter" data-level="4.1" data-path="c04-getting-started.html"><a href="c04-getting-started.html#introduction-3"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="c04-getting-started.html"><a href="c04-getting-started.html#setup"><i class="fa fa-check"></i><b>4.2</b> Setup</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="c04-getting-started.html"><a href="c04-getting-started.html#setup-load-pkgs"><i class="fa fa-check"></i><b>4.2.1</b> Packages</a></li>
<li class="chapter" data-level="4.2.2" data-path="c04-getting-started.html"><a href="c04-getting-started.html#data"><i class="fa fa-check"></i><b>4.2.2</b> Data</a></li>
<li class="chapter" data-level="4.2.3" data-path="c04-getting-started.html"><a href="c04-getting-started.html#setup-des-obj"><i class="fa fa-check"></i><b>4.2.3</b> Design objects</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="c04-getting-started.html"><a href="c04-getting-started.html#survey-analysis-process"><i class="fa fa-check"></i><b>4.3</b> Survey analysis process</a></li>
<li class="chapter" data-level="4.4" data-path="c04-getting-started.html"><a href="c04-getting-started.html#similarities-dplyr-srvyr"><i class="fa fa-check"></i><b>4.4</b> Similarities between {dplyr} and {srvyr} functions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html"><i class="fa fa-check"></i><b>5</b> Descriptive analyses</a>
<ul>
<li class="chapter" data-level="" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#prereq5"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="5.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#introduction-4"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#counts-and-cross-tabulations"><i class="fa fa-check"></i><b>5.2</b> Counts and cross-tabulations</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-count-syntax"><i class="fa fa-check"></i><b>5.2.1</b> Syntax</a></li>
<li class="chapter" data-level="5.2.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples"><i class="fa fa-check"></i><b>5.2.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#totals-and-sums"><i class="fa fa-check"></i><b>5.3</b> Totals and sums </a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax"><i class="fa fa-check"></i><b>5.3.1</b> Syntax</a></li>
<li class="chapter" data-level="5.3.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-1"><i class="fa fa-check"></i><b>5.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-meanprop"><i class="fa fa-check"></i><b>5.4</b> Means and proportions</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-meanprop-syntax"><i class="fa fa-check"></i><b>5.4.1</b> Syntax</a></li>
<li class="chapter" data-level="5.4.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-2"><i class="fa fa-check"></i><b>5.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#quantiles-and-medians"><i class="fa fa-check"></i><b>5.5</b> Quantiles and medians</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-1"><i class="fa fa-check"></i><b>5.5.1</b> Syntax</a></li>
<li class="chapter" data-level="5.5.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-3"><i class="fa fa-check"></i><b>5.5.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#ratios"><i class="fa fa-check"></i><b>5.6</b> Ratios </a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-2"><i class="fa fa-check"></i><b>5.6.1</b> Syntax</a></li>
<li class="chapter" data-level="5.6.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-4"><i class="fa fa-check"></i><b>5.6.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#correlations"><i class="fa fa-check"></i><b>5.7</b> Correlations </a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-3"><i class="fa fa-check"></i><b>5.7.1</b> Syntax</a></li>
<li class="chapter" data-level="5.7.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-5"><i class="fa fa-check"></i><b>5.7.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#standard-deviation-and-variance"><i class="fa fa-check"></i><b>5.8</b> Standard deviation and variance </a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#syntax-4"><i class="fa fa-check"></i><b>5.8.1</b> Syntax</a></li>
<li class="chapter" data-level="5.8.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#examples-6"><i class="fa fa-check"></i><b>5.8.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#additional-topics"><i class="fa fa-check"></i><b>5.9</b> Additional topics</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#unweighted-analysis"><i class="fa fa-check"></i><b>5.9.1</b> Unweighted analysis </a></li>
<li class="chapter" data-level="5.9.2" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#subpopulation-analysis"><i class="fa fa-check"></i><b>5.9.2</b> Subpopulation analysis </a></li>
<li class="chapter" data-level="5.9.3" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#desc-deff"><i class="fa fa-check"></i><b>5.9.3</b> Design effects</a></li>
<li class="chapter" data-level="5.9.4" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#creating-summary-rows"><i class="fa fa-check"></i><b>5.9.4</b> Creating summary rows</a></li>
<li class="chapter" data-level="5.9.5" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#calculating-estimates-for-many-outcomes"><i class="fa fa-check"></i><b>5.9.5</b> Calculating estimates for many outcomes</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="c05-descriptive-analysis.html"><a href="c05-descriptive-analysis.html#exercises"><i class="fa fa-check"></i><b>5.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html"><i class="fa fa-check"></i><b>6</b> Statistical testing</a>
<ul>
<li class="chapter" data-level="" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#prereq6"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="6.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#introduction-5"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#dot-notation"><i class="fa fa-check"></i><b>6.2</b> Dot notation</a></li>
<li class="chapter" data-level="6.3" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest"><i class="fa fa-check"></i><b>6.3</b> Comparison of proportions and means</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest-syntax"><i class="fa fa-check"></i><b>6.3.1</b> Syntax</a></li>
<li class="chapter" data-level="6.3.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-ttest-examples"><i class="fa fa-check"></i><b>6.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi"><i class="fa fa-check"></i><b>6.4</b> Chi-squared tests</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi-syntax"><i class="fa fa-check"></i><b>6.4.1</b> Syntax</a></li>
<li class="chapter" data-level="6.4.2" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-chi-examples"><i class="fa fa-check"></i><b>6.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="c06-statistical-testing.html"><a href="c06-statistical-testing.html#stattest-exercises"><i class="fa fa-check"></i><b>6.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="c07-modeling.html"><a href="c07-modeling.html"><i class="fa fa-check"></i><b>7</b> Modeling</a>
<ul>
<li class="chapter" data-level="" data-path="c07-modeling.html"><a href="c07-modeling.html#prereq7"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="7.1" data-path="c07-modeling.html"><a href="c07-modeling.html#model-intro"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="c07-modeling.html"><a href="c07-modeling.html#analysis-of-variance-anova"><i class="fa fa-check"></i><b>7.2</b> Analysis of variance (ANOVA)</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-6"><i class="fa fa-check"></i><b>7.2.1</b> Syntax</a></li>
<li class="chapter" data-level="7.2.2" data-path="c07-modeling.html"><a href="c07-modeling.html#example-1"><i class="fa fa-check"></i><b>7.2.2</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="c07-modeling.html"><a href="c07-modeling.html#normal-linear-regression"><i class="fa fa-check"></i><b>7.3</b> Normal linear regression</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-7"><i class="fa fa-check"></i><b>7.3.1</b> Syntax</a></li>
<li class="chapter" data-level="7.3.2" data-path="c07-modeling.html"><a href="c07-modeling.html#examples-7"><i class="fa fa-check"></i><b>7.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="c07-modeling.html"><a href="c07-modeling.html#logistic-regression"><i class="fa fa-check"></i><b>7.4</b> Logistic regression</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="c07-modeling.html"><a href="c07-modeling.html#syntax-8"><i class="fa fa-check"></i><b>7.4.1</b> Syntax</a></li>
<li class="chapter" data-level="7.4.2" data-path="c07-modeling.html"><a href="c07-modeling.html#examples-8"><i class="fa fa-check"></i><b>7.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="c07-modeling.html"><a href="c07-modeling.html#exercises-1"><i class="fa fa-check"></i><b>7.5</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>III Reporting</b></span></li>
<li class="chapter" data-level="8" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html"><i class="fa fa-check"></i><b>8</b> Communication of results</a>
<ul>
<li class="chapter" data-level="" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#prereq8"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="8.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#introduction-6"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#describing-results-through-text"><i class="fa fa-check"></i><b>8.2</b> Describing results through text</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#methodology-1"><i class="fa fa-check"></i><b>8.2.1</b> Methodology</a></li>
<li class="chapter" data-level="8.2.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#analysis"><i class="fa fa-check"></i><b>8.2.2</b> Analysis</a></li>
<li class="chapter" data-level="8.2.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#results"><i class="fa fa-check"></i><b>8.2.3</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#visualizing-data"><i class="fa fa-check"></i><b>8.3</b> Visualizing data</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#tables"><i class="fa fa-check"></i><b>8.3.1</b> Tables</a></li>
<li class="chapter" data-level="8.3.2" data-path="c08-communicating-results.html"><a href="c08-communicating-results.html#charts-and-plots"><i class="fa fa-check"></i><b>8.3.2</b> Charts and plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html"><i class="fa fa-check"></i><b>9</b> Reproducible research</a>
<ul>
<li class="chapter" data-level="9.1" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#introduction-7"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#project-based-workflows"><i class="fa fa-check"></i><b>9.2</b> Project-based workflows</a></li>
<li class="chapter" data-level="9.3" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#functions-and-packages"><i class="fa fa-check"></i><b>9.3</b> Functions and packages</a></li>
<li class="chapter" data-level="9.4" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#version-control-with-git"><i class="fa fa-check"></i><b>9.4</b> Version control with Git</a></li>
<li class="chapter" data-level="9.5" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#package-management-with-renv"><i class="fa fa-check"></i><b>9.5</b> Package management with {renv}</a></li>
<li class="chapter" data-level="9.6" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#r-environments-with-docker"><i class="fa fa-check"></i><b>9.6</b> R environments with Docker</a></li>
<li class="chapter" data-level="9.7" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#workflow-management-with-targets"><i class="fa fa-check"></i><b>9.7</b> Workflow management with {targets}</a></li>
<li class="chapter" data-level="9.8" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#documentation-with-quarto-and-r-markdown"><i class="fa fa-check"></i><b>9.8</b> Documentation with Quarto and R Markdown</a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#parameterization"><i class="fa fa-check"></i><b>9.8.1</b> Parameterization</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#other-tips-for-reproducibility"><i class="fa fa-check"></i><b>9.9</b> Other tips for reproducibility</a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#random-number-seeds"><i class="fa fa-check"></i><b>9.9.1</b> Random number seeds</a></li>
<li class="chapter" data-level="9.9.2" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#descriptive-names-and-labels"><i class="fa fa-check"></i><b>9.9.2</b> Descriptive names and labels</a></li>
</ul></li>
<li class="chapter" data-level="9.10" data-path="c09-reprex-data.html"><a href="c09-reprex-data.html#additional-resources-1"><i class="fa fa-check"></i><b>9.10</b> Additional resources</a></li>
</ul></li>
<li class="part"><span><b>IV Real life data</b></span></li>
<li class="chapter" data-level="10" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html"><i class="fa fa-check"></i><b>10</b> Sample designs and replicate weights</a>
<ul>
<li class="chapter" data-level="" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#prereq3"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="10.1" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#introduction-8"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#common-sampling-designs"><i class="fa fa-check"></i><b>10.2</b> Common sampling designs</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#simple-random-sample-without-replacement"><i class="fa fa-check"></i><b>10.2.1</b> Simple random sample without replacement</a></li>
<li class="chapter" data-level="10.2.2" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#simple-random-sample-with-replacement"><i class="fa fa-check"></i><b>10.2.2</b> Simple random sample with replacement</a></li>
<li class="chapter" data-level="10.2.3" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#stratified-sampling"><i class="fa fa-check"></i><b>10.2.3</b> Stratified sampling </a></li>
<li class="chapter" data-level="10.2.4" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#samp-cluster"><i class="fa fa-check"></i><b>10.2.4</b> Clustered sampling</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#samp-combo"><i class="fa fa-check"></i><b>10.3</b> Combining sampling methods</a>
<ul>
<li class="chapter" data-level="" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#example-6"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#replicate-weights"><i class="fa fa-check"></i><b>10.4</b> Replicate weights</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#balanced-repeated-replication-brr-method"><i class="fa fa-check"></i><b>10.4.1</b> Balanced Repeated Replication (BRR) method</a></li>
<li class="chapter" data-level="10.4.2" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#fays-brr-method"><i class="fa fa-check"></i><b>10.4.2</b> Fay’s BRR method</a></li>
<li class="chapter" data-level="10.4.3" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#samp-jackknife"><i class="fa fa-check"></i><b>10.4.3</b> Jackknife method</a></li>
<li class="chapter" data-level="10.4.4" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#bootstrap-method"><i class="fa fa-check"></i><b>10.4.4</b> Bootstrap method</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="c10-sample-designs-replicate-weights.html"><a href="c10-sample-designs-replicate-weights.html#exercises-2"><i class="fa fa-check"></i><b>10.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="c11-missing-data.html"><a href="c11-missing-data.html"><i class="fa fa-check"></i><b>11</b> Missing data</a>
<ul>
<li class="chapter" data-level="" data-path="c11-missing-data.html"><a href="c11-missing-data.html#prereq11"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="11.1" data-path="c11-missing-data.html"><a href="c11-missing-data.html#introduction-9"><i class="fa fa-check"></i><b>11.1</b> Introduction</a></li>
<li class="chapter" data-level="11.2" data-path="c11-missing-data.html"><a href="c11-missing-data.html#missing-data-mechanisms"><i class="fa fa-check"></i><b>11.2</b> Missing data mechanisms</a></li>
<li class="chapter" data-level="11.3" data-path="c11-missing-data.html"><a href="c11-missing-data.html#assessing-missing-data"><i class="fa fa-check"></i><b>11.3</b> Assessing missing data</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="c11-missing-data.html"><a href="c11-missing-data.html#summarize-data"><i class="fa fa-check"></i><b>11.3.1</b> Summarize data</a></li>
<li class="chapter" data-level="11.3.2" data-path="c11-missing-data.html"><a href="c11-missing-data.html#visualization-of-missing-data"><i class="fa fa-check"></i><b>11.3.2</b> Visualization of missing data</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="c11-missing-data.html"><a href="c11-missing-data.html#analysis-with-missing-data"><i class="fa fa-check"></i><b>11.4</b> Analysis with missing data</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="c11-missing-data.html"><a href="c11-missing-data.html#recoding-missing-data"><i class="fa fa-check"></i><b>11.4.1</b> Recoding missing data</a></li>
<li class="chapter" data-level="11.4.2" data-path="c11-missing-data.html"><a href="c11-missing-data.html#missing-skip-patt"><i class="fa fa-check"></i><b>11.4.2</b> Accounting for skip patterns</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="c12-recommendations.html"><a href="c12-recommendations.html"><i class="fa fa-check"></i><b>12</b> Successful survey analysis recommendations</a>
<ul>
<li class="chapter" data-level="" data-path="c12-recommendations.html"><a href="c12-recommendations.html#prereq12"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="12.1" data-path="c12-recommendations.html"><a href="c12-recommendations.html#introduction-10"><i class="fa fa-check"></i><b>12.1</b> Introduction</a></li>
<li class="chapter" data-level="12.2" data-path="c12-recommendations.html"><a href="c12-recommendations.html#recs-survey-process"><i class="fa fa-check"></i><b>12.2</b> Follow the survey analysis process</a></li>
<li class="chapter" data-level="12.3" data-path="c12-recommendations.html"><a href="c12-recommendations.html#begin-with-descriptive-analysis"><i class="fa fa-check"></i><b>12.3</b> Begin with descriptive analysis</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="c12-recommendations.html"><a href="c12-recommendations.html#table-review"><i class="fa fa-check"></i><b>12.3.1</b> Table review</a></li>
<li class="chapter" data-level="12.3.2" data-path="c12-recommendations.html"><a href="c12-recommendations.html#graphical-review"><i class="fa fa-check"></i><b>12.3.2</b> Graphical review</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="c12-recommendations.html"><a href="c12-recommendations.html#check-variable-types"><i class="fa fa-check"></i><b>12.4</b> Check variable types</a></li>
<li class="chapter" data-level="12.5" data-path="c12-recommendations.html"><a href="c12-recommendations.html#improve-debugging-skills"><i class="fa fa-check"></i><b>12.5</b> Improve debugging skills</a></li>
<li class="chapter" data-level="12.6" data-path="c12-recommendations.html"><a href="c12-recommendations.html#think-critically-about-conclusions"><i class="fa fa-check"></i><b>12.6</b> Think critically about conclusions</a></li>
</ul></li>
<li class="part"><span><b>V Vignettes</b></span></li>
<li class="chapter" data-level="13" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html"><i class="fa fa-check"></i><b>13</b> National Crime Victimization Survey Vignette</a>
<ul>
<li class="chapter" data-level="" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#prereq9"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="13.1" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#introduction-11"><i class="fa fa-check"></i><b>13.1</b> Introduction</a></li>
<li class="chapter" data-level="13.2" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#data-structure"><i class="fa fa-check"></i><b>13.2</b> Data structure</a></li>
<li class="chapter" data-level="13.3" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#survey-notation"><i class="fa fa-check"></i><b>13.3</b> Survey notation</a></li>
<li class="chapter" data-level="13.4" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#data-file-preparation"><i class="fa fa-check"></i><b>13.4</b> Data file preparation</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#preparing-files-for-estimation-of-victimization-rates"><i class="fa fa-check"></i><b>13.4.1</b> Preparing files for estimation of victimization rates</a></li>
<li class="chapter" data-level="13.4.2" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#derived-demographic-variables"><i class="fa fa-check"></i><b>13.4.2</b> Derived demographic variables</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#survey-design-objects"><i class="fa fa-check"></i><b>13.5</b> Survey design objects</a></li>
<li class="chapter" data-level="13.6" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#calculating-estimates"><i class="fa fa-check"></i><b>13.6</b> Calculating estimates</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#vic-tot"><i class="fa fa-check"></i><b>13.6.1</b> Estimation 1: Victimization totals</a></li>
<li class="chapter" data-level="13.6.2" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#vic-prop"><i class="fa fa-check"></i><b>13.6.2</b> Estimation 2: Victimization proportions</a></li>
<li class="chapter" data-level="13.6.3" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#vic-rate"><i class="fa fa-check"></i><b>13.6.3</b> Estimation 3: Victimization rates</a></li>
<li class="chapter" data-level="13.6.4" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#prev-rate"><i class="fa fa-check"></i><b>13.6.4</b> Estimation 4: Prevalence rates</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#statistical-testing"><i class="fa fa-check"></i><b>13.7</b> Statistical testing</a></li>
<li class="chapter" data-level="13.8" data-path="c13-ncvs-vignette.html"><a href="c13-ncvs-vignette.html#exercises-3"><i class="fa fa-check"></i><b>13.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html"><i class="fa fa-check"></i><b>14</b> AmericasBarometer Vignette</a>
<ul>
<li class="chapter" data-level="" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#prereq10"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="14.1" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#introduction-12"><i class="fa fa-check"></i><b>14.1</b> Introduction</a></li>
<li class="chapter" data-level="14.2" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#data-structure-1"><i class="fa fa-check"></i><b>14.2</b> Data structure</a></li>
<li class="chapter" data-level="14.3" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#preparing-files"><i class="fa fa-check"></i><b>14.3</b> Preparing files</a></li>
<li class="chapter" data-level="14.4" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#survey-design-objects-1"><i class="fa fa-check"></i><b>14.4</b> Survey design objects</a></li>
<li class="chapter" data-level="14.5" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#ambarom-estimates"><i class="fa fa-check"></i><b>14.5</b> Calculating estimates</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#example-worried-about-covid-19"><i class="fa fa-check"></i><b>14.5.1</b> Example: Worried about COVID-19</a></li>
<li class="chapter" data-level="14.5.2" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#example-education-affected-by-covid-19"><i class="fa fa-check"></i><b>14.5.2</b> Example: Education affected by COVID-19</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#ambarom-maps"><i class="fa fa-check"></i><b>14.6</b> Mapping survey data</a></li>
<li class="chapter" data-level="14.7" data-path="c14-ambarom-vignette.html"><a href="c14-ambarom-vignette.html#exercises-4"><i class="fa fa-check"></i><b>14.7</b> Exercises</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html"><i class="fa fa-check"></i><b>A</b> Importing survey data into R</a>
<ul>
<li class="chapter" data-level="A.1" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-delimiter-separated-files-into-r"><i class="fa fa-check"></i><b>A.1</b> Importing delimiter-separated files into R</a></li>
<li class="chapter" data-level="A.2" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-excel-files-into-r"><i class="fa fa-check"></i><b>A.2</b> Importing Excel files into R</a></li>
<li class="chapter" data-level="A.3" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-stata-sas-and-spss-files-into-r"><i class="fa fa-check"></i><b>A.3</b> Importing Stata, SAS, and SPSS files into R</a>
<ul>
<li class="chapter" data-level="A.3.1" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#syntax-9"><i class="fa fa-check"></i><b>A.3.1</b> Syntax</a></li>
<li class="chapter" data-level="A.3.2" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#working-with-labeled-data"><i class="fa fa-check"></i><b>A.3.2</b> Working with labeled data</a></li>
<li class="chapter" data-level="A.3.3" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#labeled-missing-data-values"><i class="fa fa-check"></i><b>A.3.3</b> Labeled missing data values</a></li>
</ul></li>
<li class="chapter" data-level="A.4" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-data-from-apis-into-r"><i class="fa fa-check"></i><b>A.4</b> Importing data from APIs into R</a></li>
<li class="chapter" data-level="A.5" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-data-from-databases-in-r"><i class="fa fa-check"></i><b>A.5</b> Importing data from databases in R</a></li>
<li class="chapter" data-level="A.6" data-path="importing-survey-data-into-r.html"><a href="importing-survey-data-into-r.html#importing-data-from-other-formats"><i class="fa fa-check"></i><b>A.6</b> Importing data from other formats</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="anes-cb.html"><a href="anes-cb.html"><i class="fa fa-check"></i><b>B</b> ANES derived variable codebook</a>
<ul>
<li class="chapter" data-level="B.1" data-path="anes-cb.html"><a href="anes-cb.html#admin"><i class="fa fa-check"></i><b>B.1</b> ADMIN</a></li>
<li class="chapter" data-level="B.2" data-path="anes-cb.html"><a href="anes-cb.html#weights"><i class="fa fa-check"></i><b>B.2</b> WEIGHTS</a></li>
<li class="chapter" data-level="B.3" data-path="anes-cb.html"><a href="anes-cb.html#pre-election-survey-questionnaire"><i class="fa fa-check"></i><b>B.3</b> PRE-ELECTION SURVEY QUESTIONNAIRE</a></li>
<li class="chapter" data-level="B.4" data-path="anes-cb.html"><a href="anes-cb.html#post-election-survey-questionnaire"><i class="fa fa-check"></i><b>B.4</b> POST-ELECTION SURVEY QUESTIONNAIRE</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="recs-cb.html"><a href="recs-cb.html"><i class="fa fa-check"></i><b>C</b> RECS derived variable codebook</a>
<ul>
<li class="chapter" data-level="C.1" data-path="recs-cb.html"><a href="recs-cb.html#admin-1"><i class="fa fa-check"></i><b>C.1</b> ADMIN</a></li>
<li class="chapter" data-level="C.2" data-path="recs-cb.html"><a href="recs-cb.html#geography"><i class="fa fa-check"></i><b>C.2</b> GEOGRAPHY</a></li>
<li class="chapter" data-level="C.3" data-path="recs-cb.html"><a href="recs-cb.html#weather"><i class="fa fa-check"></i><b>C.3</b> WEATHER</a></li>
<li class="chapter" data-level="C.4" data-path="recs-cb.html"><a href="recs-cb.html#your-home"><i class="fa fa-check"></i><b>C.4</b> YOUR HOME</a></li>
<li class="chapter" data-level="C.5" data-path="recs-cb.html"><a href="recs-cb.html#space-heating"><i class="fa fa-check"></i><b>C.5</b> SPACE HEATING</a></li>
<li class="chapter" data-level="C.6" data-path="recs-cb.html"><a href="recs-cb.html#air-conditioning"><i class="fa fa-check"></i><b>C.6</b> AIR CONDITIONING</a></li>
<li class="chapter" data-level="C.7" data-path="recs-cb.html"><a href="recs-cb.html#thermostat"><i class="fa fa-check"></i><b>C.7</b> THERMOSTAT</a></li>
<li class="chapter" data-level="C.8" data-path="recs-cb.html"><a href="recs-cb.html#weights-1"><i class="fa fa-check"></i><b>C.8</b> WEIGHTS</a></li>
<li class="chapter" data-level="C.9" data-path="recs-cb.html"><a href="recs-cb.html#consumption-and-expenditure"><i class="fa fa-check"></i><b>C.9</b> CONSUMPTION AND EXPENDITURE</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="exercise-solutions.html"><a href="exercise-solutions.html"><i class="fa fa-check"></i><b>D</b> Exercise solutions</a>
<ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#descriptive-analysis"><i class="fa fa-check"></i>5 - Descriptive analysis</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#statistical-testing-1"><i class="fa fa-check"></i>6 - Statistical testing</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#modeling"><i class="fa fa-check"></i>7 - Modeling</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#specifying-sample-designs-and-replicate-weights-in-srvyr"><i class="fa fa-check"></i>10 - Specifying sample designs and replicate weights in {srvyr}</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#national-crime-victimization-survey-vignette"><i class="fa fa-check"></i>13 - National Crime Victimization Survey Vignette</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#americasbarometer-vignette"><i class="fa fa-check"></i>14 - AmericasBarometer Vignette</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Exploring Complex Survey Data Analysis Using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="c11-missing-data" class="section level1 hasAnchor" number="11">
<h1><span class="header-section-number">Chapter 11</span> Missing data<a href="c11-missing-data.html#c11-missing-data" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p></p>
<div id="prereq11" class="section level3 unnumbered hasAnchor prereqbox-header">
<h3>Prerequisites<a href="c11-missing-data.html#prereq11" class="anchor-section" aria-label="Anchor link to header"></a></h3>
</div>
<div class="prereqbox">
<p>For this chapter, load the following packages:</p>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="c11-missing-data.html#cb344-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb344-2"><a href="c11-missing-data.html#cb344-2" tabindex="-1"></a><span class="fu">library</span>(survey)</span>
<span id="cb344-3"><a href="c11-missing-data.html#cb344-3" tabindex="-1"></a><span class="fu">library</span>(srvyr)</span>
<span id="cb344-4"><a href="c11-missing-data.html#cb344-4" tabindex="-1"></a><span class="fu">library</span>(srvyrexploR)</span>
<span id="cb344-5"><a href="c11-missing-data.html#cb344-5" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb344-6"><a href="c11-missing-data.html#cb344-6" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb344-7"><a href="c11-missing-data.html#cb344-7" tabindex="-1"></a><span class="fu">library</span>(gt)</span></code></pre></div>
<p>We are using data from ANES and RECS described in Chapter <a href="c04-getting-started.html#c04-getting-started">4</a>. As a reminder, here is the code to create the design objects for each to use throughout this chapter. For ANES, we need to adjust the weight so it sums to the population instead of the sample (see the ANES documentation and Chapter <a href="c04-getting-started.html#c04-getting-started">4</a> for more information.)</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="c11-missing-data.html#cb345-1" tabindex="-1"></a>targetpop <span class="ot">&lt;-</span> <span class="dv">231592693</span></span>
<span id="cb345-2"><a href="c11-missing-data.html#cb345-2" tabindex="-1"></a></span>
<span id="cb345-3"><a href="c11-missing-data.html#cb345-3" tabindex="-1"></a>anes_adjwgt <span class="ot">&lt;-</span> anes_2020 <span class="sc">%&gt;%</span></span>
<span id="cb345-4"><a href="c11-missing-data.html#cb345-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Weight =</span> Weight <span class="sc">/</span> <span class="fu">sum</span>(Weight) <span class="sc">*</span> targetpop)</span>
<span id="cb345-5"><a href="c11-missing-data.html#cb345-5" tabindex="-1"></a></span>
<span id="cb345-6"><a href="c11-missing-data.html#cb345-6" tabindex="-1"></a>anes_des <span class="ot">&lt;-</span> anes_adjwgt <span class="sc">%&gt;%</span></span>
<span id="cb345-7"><a href="c11-missing-data.html#cb345-7" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(</span>
<span id="cb345-8"><a href="c11-missing-data.html#cb345-8" tabindex="-1"></a>    <span class="at">weights =</span> Weight,</span>
<span id="cb345-9"><a href="c11-missing-data.html#cb345-9" tabindex="-1"></a>    <span class="at">strata =</span> Stratum,</span>
<span id="cb345-10"><a href="c11-missing-data.html#cb345-10" tabindex="-1"></a>    <span class="at">ids =</span> VarUnit,</span>
<span id="cb345-11"><a href="c11-missing-data.html#cb345-11" tabindex="-1"></a>    <span class="at">nest =</span> <span class="cn">TRUE</span></span>
<span id="cb345-12"><a href="c11-missing-data.html#cb345-12" tabindex="-1"></a>  )</span></code></pre></div>
<p>For RECS, details are included in the RECS documentation and Chapter <a href="c10-sample-designs-replicate-weights.html#c10-sample-designs-replicate-weights">10</a>.</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="c11-missing-data.html#cb346-1" tabindex="-1"></a>recs_des <span class="ot">&lt;-</span> recs_2020 <span class="sc">%&gt;%</span></span>
<span id="cb346-2"><a href="c11-missing-data.html#cb346-2" tabindex="-1"></a>  <span class="fu">as_survey_rep</span>(</span>
<span id="cb346-3"><a href="c11-missing-data.html#cb346-3" tabindex="-1"></a>    <span class="at">weights =</span> NWEIGHT,</span>
<span id="cb346-4"><a href="c11-missing-data.html#cb346-4" tabindex="-1"></a>    <span class="at">repweights =</span> NWEIGHT1<span class="sc">:</span>NWEIGHT60,</span>
<span id="cb346-5"><a href="c11-missing-data.html#cb346-5" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">&quot;JK1&quot;</span>,</span>
<span id="cb346-6"><a href="c11-missing-data.html#cb346-6" tabindex="-1"></a>    <span class="at">scale =</span> <span class="dv">59</span> <span class="sc">/</span> <span class="dv">60</span>,</span>
<span id="cb346-7"><a href="c11-missing-data.html#cb346-7" tabindex="-1"></a>    <span class="at">mse =</span> <span class="cn">TRUE</span></span>
<span id="cb346-8"><a href="c11-missing-data.html#cb346-8" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<div id="introduction-9" class="section level2 hasAnchor" number="11.1">
<h2><span class="header-section-number">11.1</span> Introduction<a href="c11-missing-data.html#introduction-9" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Missing data in surveys refer to situations where participants do not provide complete responses to survey questions. Respondents may not have seen a question by design. Or, they may not respond to a question for various other reasons, such as not wanting to answer a particular question, not understanding the question, or simply forgetting to answer. Missing data are important to consider and account for, as it can introduce bias and reduce the representativeness of the data. This chapter provides an overview of the types of missing data, how to assess missing data in surveys, and how to conduct analysis when missing data are present. Understanding this complex topic can help ensure accurate reporting of survey results and provide insight into potential changes to the survey design for the future.</p>
</div>
<div id="missing-data-mechanisms" class="section level2 hasAnchor" number="11.2">
<h2><span class="header-section-number">11.2</span> Missing data mechanisms<a href="c11-missing-data.html#missing-data-mechanisms" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There are two main categories that missing data typically fall into: missing by design and unintentional missing data. Missing by design is part of the survey plan and can be more easily incorporated into weights and analyses. Unintentional missing data on the other hand, can lead to bias in survey estimates if not correctly accounted for. Below we provide more information on the types of missing data.</p>
<ol style="list-style-type: decimal">
<li><p><strong>Missing by design/questionnaire skip logic</strong>: This type of missingness occurs when certain respondents are intentionally directed to skip specific questions based on their previous responses or characteristics. For example, in a survey about employment, if a respondent indicates that they are not employed, they may be directed to skip questions related to their job responsibilities. Additionally, some surveys randomize questions or modules so that not all participants respond to all questions. In these instances, respondents would have missing data for the modules not randomly assigned to them.</p></li>
<li><p><strong>Unintentional missing data</strong>: This type of missingness occurs when researchers do not intend for there to be missing data on a particular question, for example, if respondents did not finish the survey or refused to answer individual questions. There are three main types of unintentional missing data that each should be considered and handled differently <span class="citation">(<a href="#ref-mack">Mack, Su, and Westreich 2018</a>; <a href="#ref-Schafer2002">Schafer and Graham 2002</a>)</span>:</p>
<ol style="list-style-type: lower-alpha">
<li><p><strong>Missing completely at random (MCAR)</strong>: The missing data are unrelated to both observed and unobserved data, and the probability of being missing is the same across all cases. For example, if a respondent missed a question because they had to leave the survey early due to an emergency.</p></li>
<li><p><strong>Missing at random (MAR)</strong>: The missing data are related to observed data but not unobserved data, and the probability of being missing is the same within groups. For example, we know the respondents’ ages if and older respondents choose not to answer specific questions but younger respondents do answer them.</p></li>
<li><p><strong>Missing not at random (MNAR)</strong>: The missing data are related to unobserved data, and the probability of being missing varies for reasons we are not measuring. For example, if respondents with depression do not answer a question about depression severity.</p></li>
</ol></li>
</ol>
</div>
<div id="assessing-missing-data" class="section level2 hasAnchor" number="11.3">
<h2><span class="header-section-number">11.3</span> Assessing missing data<a href="c11-missing-data.html#assessing-missing-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before beginning an analysis, we should explore the data to determine if there is missing data and what types of missing data are present. Conducting descriptive analysis can help with the analysis and reporting of survey data (see Section <a href="c12-recommendations.html#c12-recommendations">12</a>) and can inform the survey design in future studies. For example, large amounts of unexpected missing data may indicate the questions were unclear or difficult to recall. There are several ways to explore missing data, which we walk through below. When assessing the missing data, we recommend using a data.frame object and not the survey object, as most of the analysis is about patterns of records, and weights are not necessary.</p>
<div id="summarize-data" class="section level3 hasAnchor" number="11.3.1">
<h3><span class="header-section-number">11.3.1</span> Summarize data<a href="c11-missing-data.html#summarize-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>
A very rudimentary first exploration is to use the <code>summary()</code> function to summarize the data, which illuminates <code>NA</code> values in the data. Let’s look at a few analytic variables on the ANES 2020 data using <code>summary()</code>:</p>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="c11-missing-data.html#cb347-1" tabindex="-1"></a>anes_2020 <span class="sc">%&gt;%</span></span>
<span id="cb347-2"><a href="c11-missing-data.html#cb347-2" tabindex="-1"></a>  <span class="fu">select</span>(V202051<span class="sc">:</span>EarlyVote2020) <span class="sc">%&gt;%</span></span>
<span id="cb347-3"><a href="c11-missing-data.html#cb347-3" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>##     V202051                Income7                  Income    
##  Min.   :-9.000   $125k or more:1468   Under $9,999    : 647  
##  1st Qu.:-1.000   Under $20k   :1076   $50,000-59,999  : 485  
##  Median :-1.000   $20k to &lt; 40k:1051   $100,000-109,999: 451  
##  Mean   :-0.726   $40k to &lt; 60k: 984   $250,000 or more: 405  
##  3rd Qu.:-1.000   $60k to &lt; 80k: 920   $80,000-89,999  : 383  
##  Max.   : 3.000   (Other)      :1437   (Other)         :4565  
##                   NA&#39;s         : 517   NA&#39;s            : 517  
##     V201617x       V201616      V201615      V201613      V201611  
##  Min.   :-9.0   Min.   :-3   Min.   :-3   Min.   :-3   Min.   :-3  
##  1st Qu.: 4.0   1st Qu.:-3   1st Qu.:-3   1st Qu.:-3   1st Qu.:-3  
##  Median :11.0   Median :-3   Median :-3   Median :-3   Median :-3  
##  Mean   :10.4   Mean   :-3   Mean   :-3   Mean   :-3   Mean   :-3  
##  3rd Qu.:17.0   3rd Qu.:-3   3rd Qu.:-3   3rd Qu.:-3   3rd Qu.:-3  
##  Max.   :22.0   Max.   :-3   Max.   :-3   Max.   :-3   Max.   :-3  
##                                                                    
##     V201610      V201607      Gender        V201600     
##  Min.   :-3   Min.   :-3   Male  :3375   Min.   :-9.00  
##  1st Qu.:-3   1st Qu.:-3   Female:4027   1st Qu.: 1.00  
##  Median :-3   Median :-3   NA&#39;s  :  51   Median : 2.00  
##  Mean   :-3   Mean   :-3                 Mean   : 1.47  
##  3rd Qu.:-3   3rd Qu.:-3                 3rd Qu.: 2.00  
##  Max.   :-3   Max.   :-3                 Max.   : 2.00  
##                                                         
##                 RaceEth        V201549x       V201547z     V201547e 
##  White              :5420   Min.   :-9.0   Min.   :-3   Min.   :-3  
##  Black              : 650   1st Qu.: 1.0   1st Qu.:-3   1st Qu.:-3  
##  Hispanic           : 662   Median : 1.0   Median :-3   Median :-3  
##  Asian, NH/PI       : 248   Mean   : 1.5   Mean   :-3   Mean   :-3  
##  AI/AN              : 155   3rd Qu.: 2.0   3rd Qu.:-3   3rd Qu.:-3  
##  Other/multiple race: 237   Max.   : 6.0   Max.   :-3   Max.   :-3  
##  NA&#39;s               :  81                                           
##     V201547d     V201547c     V201547b     V201547a     V201546     
##  Min.   :-3   Min.   :-3   Min.   :-3   Min.   :-3   Min.   :-9.00  
##  1st Qu.:-3   1st Qu.:-3   1st Qu.:-3   1st Qu.:-3   1st Qu.: 2.00  
##  Median :-3   Median :-3   Median :-3   Median :-3   Median : 2.00  
##  Mean   :-3   Mean   :-3   Mean   :-3   Mean   :-3   Mean   : 1.84  
##  3rd Qu.:-3   3rd Qu.:-3   3rd Qu.:-3   3rd Qu.:-3   3rd Qu.: 2.00  
##  Max.   :-3   Max.   :-3   Max.   :-3   Max.   :-3   Max.   : 2.00  
##                                                                     
##         Education       V201510             AgeGroup         Age      
##  Less than HS: 312   Min.   :-9.00   18-29      : 871   Min.   :18.0  
##  High school :1160   1st Qu.: 3.00   30-39      :1241   1st Qu.:37.0  
##  Post HS     :2514   Median : 5.00   40-49      :1081   Median :53.0  
##  Bachelor&#39;s  :1877   Mean   : 5.62   50-59      :1200   Mean   :51.8  
##  Graduate    :1474   3rd Qu.: 6.00   60-69      :1436   3rd Qu.:66.0  
##  NA&#39;s        : 116   Max.   :95.00   70 or older:1330   Max.   :80.0  
##                                      NA&#39;s       : 294   NA&#39;s   :294   
##     V201507x                 TrustPeople      V201237     
##  Min.   :-9.0   Always             :  48   Min.   :-9.00  
##  1st Qu.:35.0   Most of the time   :3511   1st Qu.: 2.00  
##  Median :51.0   About half the time:2020   Median : 3.00  
##  Mean   :49.4   Some of the time   :1597   Mean   : 2.78  
##  3rd Qu.:66.0   Never              : 264   3rd Qu.: 3.00  
##  Max.   :80.0   NA&#39;s               :  13   Max.   : 5.00  
##                                                           
##             TrustGovernment    V201233     
##  Always             :  80   Min.   :-9.00  
##  Most of the time   :1016   1st Qu.: 3.00  
##  About half the time:2313   Median : 4.00  
##  Some of the time   :3313   Mean   : 3.43  
##  Never              : 702   3rd Qu.: 4.00  
##  NA&#39;s               :  29   Max.   : 5.00  
##                                            
##                      PartyID        V201231x        V201230      
##  Strong democrat         :1796   Min.   :-9.00   Min.   :-9.000  
##  Strong republican       :1545   1st Qu.: 2.00   1st Qu.:-1.000  
##  Independent-democrat    : 881   Median : 4.00   Median :-1.000  
##  Independent             : 876   Mean   : 3.83   Mean   : 0.013  
##  Not very strong democrat: 790   3rd Qu.: 6.00   3rd Qu.: 1.000  
##  (Other)                 :1540   Max.   : 7.00   Max.   : 3.000  
##  NA&#39;s                    :  25                                   
##     V201229          V201228      VotedPres2016_selection
##  Min.   :-9.000   Min.   :-9.00   Clinton:2911           
##  1st Qu.:-1.000   1st Qu.: 1.00   Trump  :2466           
##  Median : 1.000   Median : 2.00   Other  : 390           
##  Mean   : 0.515   Mean   : 1.99   NA&#39;s   :1686           
##  3rd Qu.: 1.000   3rd Qu.: 3.00                          
##  Max.   : 2.000   Max.   : 5.00                          
##                                                          
##     V201103      VotedPres2016    V201102          V201101      
##  Min.   :-9.00   Yes :5810     Min.   :-9.000   Min.   :-9.000  
##  1st Qu.: 1.00   No  :1622     1st Qu.:-1.000   1st Qu.:-1.000  
##  Median : 1.00   NA&#39;s:  21     Median : 1.000   Median :-1.000  
##  Mean   : 1.04                 Mean   : 0.105   Mean   : 0.085  
##  3rd Qu.: 2.00                 3rd Qu.: 1.000   3rd Qu.: 1.000  
##  Max.   : 5.00                 Max.   : 2.000   Max.   : 2.000  
##                                                                 
##     V201029          V201028        V201025x        V201024     
##  Min.   :-9.000   Min.   :-9.0   Min.   :-4.00   Min.   :-9.00  
##  1st Qu.:-1.000   1st Qu.:-1.0   1st Qu.: 3.00   1st Qu.:-1.00  
##  Median :-1.000   Median :-1.0   Median : 3.00   Median :-1.00  
##  Mean   :-0.897   Mean   :-0.9   Mean   : 2.92   Mean   :-0.86  
##  3rd Qu.:-1.000   3rd Qu.:-1.0   3rd Qu.: 3.00   3rd Qu.:-1.00  
##  Max.   :12.000   Max.   : 2.0   Max.   : 4.00   Max.   : 4.00  
##                                                                 
##  EarlyVote2020
##  Yes : 375    
##  No  : 115    
##  NA&#39;s:6963    
##               
##               
##               
## </code></pre>
<p>We see that there are <code>NA</code> values in several of the derived variables (those not beginning with “V”) and negative values in the original variables (those beginning with “V”.) We can also use the <code>count()</code> function to get an understanding of the different types of missing data on the original variables. For example, let’s look at the count of data for <code>V202072</code>, which corresponds to our <code>VotedPres2020</code> variable.</p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="c11-missing-data.html#cb349-1" tabindex="-1"></a>anes_2020 <span class="sc">%&gt;%</span></span>
<span id="cb349-2"><a href="c11-missing-data.html#cb349-2" tabindex="-1"></a>  <span class="fu">count</span>(VotedPres2020, V202072)</span></code></pre></div>
<pre><code>## # A tibble: 7 × 3
##   VotedPres2020 V202072                                   n
##   &lt;fct&gt;         &lt;dbl+lbl&gt;                             &lt;int&gt;
## 1 Yes           -1 [-1. Inapplicable]                   361
## 2 Yes            1 [1. Yes, voted for President]       5952
## 3 No            -1 [-1. Inapplicable]                    10
## 4 No             2 [2. No, didn&#39;t vote for President]    77
## 5 &lt;NA&gt;          -9 [-9. Refused]                          2
## 6 &lt;NA&gt;          -6 [-6. No post-election interview]       4
## 7 &lt;NA&gt;          -1 [-1. Inapplicable]                  1047</code></pre>
<p>Here, we can see that there are three types of missing data, and the majority of them fall under the “Inapplicable” category. This is usually a term associated with data missing due to skip patterns and is considered to be missing data by design. Based on the documentation from ANES <span class="citation">(<a href="#ref-debell">DeBell 2010</a>)</span>, we can see that this question was only asked to respondents who voted in the election.</p>
</div>
<div id="visualization-of-missing-data" class="section level3 hasAnchor" number="11.3.2">
<h3><span class="header-section-number">11.3.2</span> Visualization of missing data<a href="c11-missing-data.html#visualization-of-missing-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>It can be challenging to look at tables for every variable and instead may be more efficient to view missing data in a graphical format to help narrow in on patterns or unique variables. The {naniar} package is very useful in exploring missing data visually. We can use the <code>vis_miss()</code> function available in both {visdat} and {naniar} packages to view the amount of missing data by variable (see Figure <a href="c11-missing-data.html#fig:missing-anes-vismiss">11.1</a>) <span class="citation">(<a href="#ref-visdattierney">Tierney 2017</a>; <a href="#ref-naniar2023">Tierney and Cook 2023</a>)</span>.</p>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb351-1"><a href="c11-missing-data.html#cb351-1" tabindex="-1"></a>anes_2020_derived <span class="ot">&lt;-</span> anes_2020 <span class="sc">%&gt;%</span></span>
<span id="cb351-2"><a href="c11-missing-data.html#cb351-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">!</span><span class="fu">starts_with</span>(<span class="st">&quot;V2&quot;</span>), <span class="sc">-</span>CaseID, <span class="sc">-</span>InterviewMode, <span class="sc">-</span>Weight, <span class="sc">-</span>Stratum, <span class="sc">-</span>VarUnit)</span>
<span id="cb351-3"><a href="c11-missing-data.html#cb351-3" tabindex="-1"></a></span>
<span id="cb351-4"><a href="c11-missing-data.html#cb351-4" tabindex="-1"></a>anes_2020_derived <span class="sc">%&gt;%</span></span>
<span id="cb351-5"><a href="c11-missing-data.html#cb351-5" tabindex="-1"></a>  <span class="fu">vis_miss</span>(<span class="at">cluster =</span> <span class="cn">TRUE</span>, <span class="at">show_perc =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb351-6"><a href="c11-missing-data.html#cb351-6" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(</span>
<span id="cb351-7"><a href="c11-missing-data.html#cb351-7" tabindex="-1"></a>    <span class="at">values =</span> book_colors[<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>)],</span>
<span id="cb351-8"><a href="c11-missing-data.html#cb351-8" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Present&quot;</span>, <span class="st">&quot;Missing&quot;</span>),</span>
<span id="cb351-9"><a href="c11-missing-data.html#cb351-9" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb351-10"><a href="c11-missing-data.html#cb351-10" tabindex="-1"></a>  )</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:missing-anes-vismiss"></span>
<img src="bookdown_files/figure-html/missing-anes-vismiss-1.png" alt="This chart shows a the missingness of the selected variables where missing is highlighted in a dark color. Each row of the plot is an observation and each column is a variable. There are some patterns observed such as a large block of missing for `VotedPres2016_selection` and many of the same respondents also having missing for `VotedPres2020_selection`." width="672" />
<p class="caption">
FIGURE 11.1: Visual depiction of missing data in the ANES 2020 data
</p>
</div>
<p>From the visualization in Figure <a href="c11-missing-data.html#fig:missing-anes-vismiss">11.1</a>, we can start to get a picture of what questions may be connected to each other in terms of missing data. Even if we did not have the informative variable names, we could deduce that <code>VotedPres2020</code>, <code>VotedPres2020_selection</code>, and <code>EarlyVote2020</code> are likely connected since their missing data patterns are similar.</p>
<p>Additionally, we can also look at <code>VotedPres2016_selection</code> and see that there is a lot of missing data in that variable. The missing data are likely due to a skip pattern, and we can look at other graphics to see how they relate to other variables. The {naniar} package has multiple visualization functions that can help dive deeper, such as the <code>gg_miss_fct()</code> function, which looks at missing data for all variables by levels of another variable (see Figure <a href="c11-missing-data.html#fig:missing-anes-ggmissfct">11.2</a>.)</p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="c11-missing-data.html#cb352-1" tabindex="-1"></a>anes_2020_derived <span class="sc">%&gt;%</span></span>
<span id="cb352-2"><a href="c11-missing-data.html#cb352-2" tabindex="-1"></a>  <span class="fu">gg_miss_fct</span>(VotedPres2016) <span class="sc">+</span></span>
<span id="cb352-3"><a href="c11-missing-data.html#cb352-3" tabindex="-1"></a>  <span class="fu">scale_fill_gradientn</span>(</span>
<span id="cb352-4"><a href="c11-missing-data.html#cb352-4" tabindex="-1"></a>    <span class="at">guide =</span> <span class="st">&quot;colorbar&quot;</span>,</span>
<span id="cb352-5"><a href="c11-missing-data.html#cb352-5" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">&quot;% Miss&quot;</span>,</span>
<span id="cb352-6"><a href="c11-missing-data.html#cb352-6" tabindex="-1"></a>    <span class="at">colors =</span> book_colors[<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>)]</span>
<span id="cb352-7"><a href="c11-missing-data.html#cb352-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb352-8"><a href="c11-missing-data.html#cb352-8" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Variable&quot;</span>) <span class="sc">+</span></span>
<span id="cb352-9"><a href="c11-missing-data.html#cb352-9" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Voted for President in 2016&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:missing-anes-ggmissfct"></span>
<img src="bookdown_files/figure-html/missing-anes-ggmissfct-1.png" alt="This chart has x-axis 'Voted for President in 2016' with labels Yes, No and NA and has y-axis 'Variable' with labels Age, AgeGroup, CampaignInterest, EarlyVote2020, Education, Gender, Income, Income7, PartyID, RaceEth, TrustGovernment, TrustPeople, VotedPres2016_selection, VotedPres2020 and VotedPres2020_selection. There is a legend indicating fill is used to show pct_miss, ranging from 0 represented by fill very pale blue to 100 shown as fill dark blue. Among those that voted for president in 2016, they had little missing for other variables (light color) but those that did not vote have more missing data in their 2020 voting patterns and their 2016 president selection." width="672" />
<p class="caption">
FIGURE 11.2: Missingness in variables for each level of <code>VotedPres2016</code> in the ANES 2020 data
</p>
</div>
<p>In Figure <a href="c11-missing-data.html#fig:missing-anes-ggmissfct">11.2</a>, we can see that if respondents did not vote for president in 2016 or did not answer that question, then they were not asked about who they voted for in 2016 (the percentage of missing data is 100%.) Additionally, we can see with Figure <a href="c11-missing-data.html#fig:missing-anes-ggmissfct">11.2</a>, that there is more missing data across all questions if they did not provide an answer to <code>VotedPres2016</code>.
</p>
<p>
There are other visualizations that work well with numeric data. For example, in the RECS 2020 data, we can plot two continuous variables and the missing data associated with them to see if there are any patterns in the missingness. To do this, we can use the <code>bind_shadow()</code> function from the {naniar} package. This creates a <strong>nabular</strong> (combination of “na” with “tabular”), which features the original columns followed by the same number of columns with a specific <code>NA</code> format. These <code>NA</code> columns are indicators of whether the value in the original data is missing or not. The example printed below shows how most levels of <code>HeatingBehavior</code> are not missing (<code>!NA</code>) in the NA variable of <code>HeatingBehavior_NA</code>, but those missing in <code>HeatingBehavior</code> are also missing in <code>HeatingBehavior_NA</code>.</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="c11-missing-data.html#cb353-1" tabindex="-1"></a>recs_2020_shadow <span class="ot">&lt;-</span> recs_2020 <span class="sc">%&gt;%</span></span>
<span id="cb353-2"><a href="c11-missing-data.html#cb353-2" tabindex="-1"></a>  <span class="fu">bind_shadow</span>()</span>
<span id="cb353-3"><a href="c11-missing-data.html#cb353-3" tabindex="-1"></a></span>
<span id="cb353-4"><a href="c11-missing-data.html#cb353-4" tabindex="-1"></a><span class="fu">ncol</span>(recs_2020)</span></code></pre></div>
<pre><code>## [1] 100</code></pre>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="c11-missing-data.html#cb355-1" tabindex="-1"></a><span class="fu">ncol</span>(recs_2020_shadow)</span></code></pre></div>
<pre><code>## [1] 200</code></pre>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="c11-missing-data.html#cb357-1" tabindex="-1"></a>recs_2020_shadow <span class="sc">%&gt;%</span></span>
<span id="cb357-2"><a href="c11-missing-data.html#cb357-2" tabindex="-1"></a>  <span class="fu">count</span>(HeatingBehavior, HeatingBehavior_NA)</span></code></pre></div>
<pre><code>## # A tibble: 7 × 3
##   HeatingBehavior                               HeatingBehavior_NA     n
##   &lt;fct&gt;                                         &lt;fct&gt;              &lt;int&gt;
## 1 Set one temp and leave it                     !NA                 7806
## 2 Manually adjust at night/no one home          !NA                 4654
## 3 Programmable or smart thermostat automatical… !NA                 3310
## 4 Turn on or off as needed                      !NA                 1491
## 5 No control                                    !NA                  438
## 6 Other                                         !NA                   46
## 7 &lt;NA&gt;                                          NA                   751</code></pre>
<p>We can then use these new variables to plot the missing data alongside the actual data. For example, let’s plot a histogram of the total electric bill grouped by those missing and not missing by heating behavior (see Figure <a href="c11-missing-data.html#fig:missing-recs-hist">11.3</a>.)</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="c11-missing-data.html#cb359-1" tabindex="-1"></a>recs_2020_shadow <span class="sc">%&gt;%</span></span>
<span id="cb359-2"><a href="c11-missing-data.html#cb359-2" tabindex="-1"></a>  <span class="fu">filter</span>(TOTALDOL <span class="sc">&lt;</span> <span class="dv">5000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb359-3"><a href="c11-missing-data.html#cb359-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> TOTALDOL, <span class="at">fill =</span> HeatingBehavior_NA)) <span class="sc">+</span></span>
<span id="cb359-4"><a href="c11-missing-data.html#cb359-4" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb359-5"><a href="c11-missing-data.html#cb359-5" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(</span>
<span id="cb359-6"><a href="c11-missing-data.html#cb359-6" tabindex="-1"></a>    <span class="at">values =</span> book_colors[<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>)],</span>
<span id="cb359-7"><a href="c11-missing-data.html#cb359-7" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Present&quot;</span>, <span class="st">&quot;Missing&quot;</span>),</span>
<span id="cb359-8"><a href="c11-missing-data.html#cb359-8" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">&quot;Heating Behavior&quot;</span></span>
<span id="cb359-9"><a href="c11-missing-data.html#cb359-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb359-10"><a href="c11-missing-data.html#cb359-10" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb359-11"><a href="c11-missing-data.html#cb359-11" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Total Energy Cost (Truncated at $5000)&quot;</span>) <span class="sc">+</span></span>
<span id="cb359-12"><a href="c11-missing-data.html#cb359-12" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Number of Households&quot;</span>) <span class="sc">+</span></span>
<span id="cb359-13"><a href="c11-missing-data.html#cb359-13" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Histogram of Energy Cost by Heating Behavior Missing Data&quot;</span>)</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<div class="figure"><span style="display:block;" id="fig:missing-recs-hist"></span>
<img src="bookdown_files/figure-html/missing-recs-hist-1.png" alt="This chart has title 'Histogram of Energy Cost by Heating Behavior Missing Data'. It has x-axis 'Total Energy Cost (Truncated at $5000)' with labels 0, 1000, 2000, 3000, 4000 and 5000. It has y-axis 'Number of Households' with labels 0, 500, 1000 and 1500. There is a legend indicating fill is used to show HeatingBehavior_NA, with 2 levels: !NA shown as very pale blue fill and  NA shown as dark blue fill. The chart is a bar chart with 30 vertical bars. These are stacked, as sorted by HeatingBehavior_NA." width="672" />
<p class="caption">
FIGURE 11.3: Histogram of Energy Cost by Heating Behavior Missing Data
</p>
</div>
<p>Figure <a href="c11-missing-data.html#fig:missing-recs-hist">11.3</a> indicates that respondents who did not provide a response for the heating behavior question may have a different distribution of total energy cost compared to respondents who did provide a response. This view of the raw data and missingness could indicate some bias in the data. Researchers take these different bias aspects into account when calculating weights, and we need to make sure that we incorporate the weights when analyzing the data. </p>
<p>There are many other visualizations that can be helpful in reviewing the data, and we recommend reviewing the {naniar} documentation for more information <span class="citation">(<a href="#ref-naniar2023">Tierney and Cook 2023</a>)</span>.</p>
</div>
</div>
<div id="analysis-with-missing-data" class="section level2 hasAnchor" number="11.4">
<h2><span class="header-section-number">11.4</span> Analysis with missing data<a href="c11-missing-data.html#analysis-with-missing-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>
Once we understand the types of missingness, we can begin the analysis of the data. Different missingness types may be handled in different ways. In most publicly available datasets, researchers have already calculated weights and imputed missing values if necessary. Often there are imputation flags included in the data that indicate if each value in a given variable is imputed. For example, in the RECS data we may see a logical variable of <code>ZWinterTempNight</code>, where a value of <code>TRUE</code> means that the value of <code>WinterTempNight</code> for that respondent was imputed and <code>FALSE</code> means that it was not imputed. We may use these imputation flags if we are interested in examining the nonresponse rates in the original data. For those interested in learning more about how to calculate weights and impute data for different missing data mechanisms, we recommended <span class="citation">Kim and Shao (<a href="#ref-Kim2021">2021</a>)</span> and <span class="citation">Valliant and Dever (<a href="#ref-Valliant2018weights">2018</a>)</span>.</p>
<p>Even with weights and imputation, missing data are most likely still present and need to be accounted for in analysis. This section provides an overview on how to recode missing data in R, and how to account for skip patterns in analysis.
</p>
<div id="recoding-missing-data" class="section level3 hasAnchor" number="11.4.1">
<h3><span class="header-section-number">11.4.1</span> Recoding missing data<a href="c11-missing-data.html#recoding-missing-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>
Even within a variable, there can be different reasons for missing data. In publicly released data,, negative values are often present to provide different meanings for values. For example, in the ANES 2020 data, they have the following negative values to represent different types of missing data:</p>
<ul>
<li>-9: Refused</li>
<li>-8: Don’t Know</li>
<li>-7: No post-election data, deleted due to incomplete interview</li>
<li>-6: No post-election interview</li>
<li>-5: Interview breakoff (sufficient partial IW)</li>
<li>-4: Technical error</li>
<li>-3: Restricted</li>
<li>-2: Other missing reason (question specific)</li>
<li>-1: Inapplicable</li>
</ul>
<p>When we created the derived variables for use in this book, we coded all negative values as <code>NA</code> and proceeded to analyze the data. For most cases, this is an appropriate approach as long as we filter the data appropriately to account for skip patterns (see Section <a href="c11-missing-data.html#missing-skip-patt">11.4.2</a>). However, the {naniar} package does have the option to code special missing values. For example, if we wanted to have two <code>NA</code> values, one that indicated the question was missing by design (e.g., due to skip patterns) and one for the other missing categories, we can use the <code>nabular</code> format to incorporate these with the <code>recode_shadow()</code> function.</p>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="c11-missing-data.html#cb361-1" tabindex="-1"></a>anes_2020_shadow <span class="ot">&lt;-</span> anes_2020 <span class="sc">%&gt;%</span></span>
<span id="cb361-2"><a href="c11-missing-data.html#cb361-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">&quot;V2&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb361-3"><a href="c11-missing-data.html#cb361-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">case_when</span>(</span>
<span id="cb361-4"><a href="c11-missing-data.html#cb361-4" tabindex="-1"></a>    .x <span class="sc">&lt;</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">~</span> <span class="cn">NA</span>,</span>
<span id="cb361-5"><a href="c11-missing-data.html#cb361-5" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> .x</span>
<span id="cb361-6"><a href="c11-missing-data.html#cb361-6" tabindex="-1"></a>  ))) <span class="sc">%&gt;%</span></span>
<span id="cb361-7"><a href="c11-missing-data.html#cb361-7" tabindex="-1"></a>  <span class="fu">bind_shadow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb361-8"><a href="c11-missing-data.html#cb361-8" tabindex="-1"></a>  <span class="fu">recode_shadow</span>(<span class="at">V201103 =</span> <span class="fu">.where</span>(V201103 <span class="sc">==</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">~</span> <span class="st">&quot;skip&quot;</span>))</span>
<span id="cb361-9"><a href="c11-missing-data.html#cb361-9" tabindex="-1"></a></span>
<span id="cb361-10"><a href="c11-missing-data.html#cb361-10" tabindex="-1"></a>anes_2020_shadow <span class="sc">%&gt;%</span></span>
<span id="cb361-11"><a href="c11-missing-data.html#cb361-11" tabindex="-1"></a>  <span class="fu">count</span>(V201103, V201103_NA)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 3
##   V201103                 V201103_NA     n
##   &lt;dbl+lbl&gt;               &lt;fct&gt;      &lt;int&gt;
## 1 -1 [-1. Inapplicable]   NA_skip     1643
## 2  1 [1. Hillary Clinton] !NA         2911
## 3  2 [2. Donald Trump]    !NA         2466
## 4  5 [5. Other {SPECIFY}] !NA          390
## 5 NA                      NA            43</code></pre>
<p>However, it is important to note that at the time of publication, there is no easy way to implement <code>recode_shadow()</code> to multiple variables at once (e.g., we cannot use the tidyverse feature of <code>across()</code>.) The example code above only implements this for a single variable, so this would have to be done manually or in a loop for all variables of interest. </p>
</div>
<div id="missing-skip-patt" class="section level3 hasAnchor" number="11.4.2">
<h3><span class="header-section-number">11.4.2</span> Accounting for skip patterns<a href="c11-missing-data.html#missing-skip-patt" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When questions are skipped by design in a survey, it is meaningful that the data are later missing. For example,the RECS survey asks people how they control the heat in their home in the winter (<code>HeatingBehavior</code>.) This is only among those who have heat in their home (<code>SpaceHeatingUsed</code>.) If no there is no heating equipment used, the value of <code>HeatingBehavior</code> is missing. One has several choices when analyzing these data which include 1) only including those with a valid value of <code>HeatingBehavior</code> and specifying the universe as those with heat or 2) including those who do not have heat. It is important to specify what population an analysis generalizes to.</p>
<p>
Here is an example where we only include those with a valid value of <code>HeatingBehavior</code> (choice 1.) Note that we use the design object (<code>recs_des</code>) and then filter to those that are not missing on <code>HeatingBehavior</code>. </p>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="c11-missing-data.html#cb363-1" tabindex="-1"></a>heat_cntl_1 <span class="ot">&lt;-</span> recs_des <span class="sc">%&gt;%</span></span>
<span id="cb363-2"><a href="c11-missing-data.html#cb363-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(HeatingBehavior)) <span class="sc">%&gt;%</span></span>
<span id="cb363-3"><a href="c11-missing-data.html#cb363-3" tabindex="-1"></a>  <span class="fu">group_by</span>(HeatingBehavior) <span class="sc">%&gt;%</span></span>
<span id="cb363-4"><a href="c11-missing-data.html#cb363-4" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb363-5"><a href="c11-missing-data.html#cb363-5" tabindex="-1"></a>    <span class="at">p =</span> <span class="fu">survey_prop</span>()</span>
<span id="cb363-6"><a href="c11-missing-data.html#cb363-6" tabindex="-1"></a>  )</span>
<span id="cb363-7"><a href="c11-missing-data.html#cb363-7" tabindex="-1"></a></span>
<span id="cb363-8"><a href="c11-missing-data.html#cb363-8" tabindex="-1"></a>heat_cntl_1</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   HeatingBehavior                                              p    p_se
##   &lt;fct&gt;                                                    &lt;dbl&gt;   &lt;dbl&gt;
## 1 Set one temp and leave it                              0.430   4.69e-3
## 2 Manually adjust at night/no one home                   0.264   4.54e-3
## 3 Programmable or smart thermostat automatically adjust… 0.168   3.12e-3
## 4 Turn on or off as needed                               0.102   2.89e-3
## 5 No control                                             0.0333  1.70e-3
## 6 Other                                                  0.00208 3.59e-4</code></pre>
<p></p>
<p>Here is an example where we include those that do not have heat (choice 2.) To help understand what we are looking at, we have included the output to show both variables, <code>SpaceHeatingUsed</code> and <code>HeatingBehavior</code>. </p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="c11-missing-data.html#cb365-1" tabindex="-1"></a>heat_cntl_2 <span class="ot">&lt;-</span> recs_des <span class="sc">%&gt;%</span></span>
<span id="cb365-2"><a href="c11-missing-data.html#cb365-2" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">interact</span>(SpaceHeatingUsed, HeatingBehavior)) <span class="sc">%&gt;%</span></span>
<span id="cb365-3"><a href="c11-missing-data.html#cb365-3" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb365-4"><a href="c11-missing-data.html#cb365-4" tabindex="-1"></a>    <span class="at">p =</span> <span class="fu">survey_prop</span>()</span>
<span id="cb365-5"><a href="c11-missing-data.html#cb365-5" tabindex="-1"></a>  )</span>
<span id="cb365-6"><a href="c11-missing-data.html#cb365-6" tabindex="-1"></a></span>
<span id="cb365-7"><a href="c11-missing-data.html#cb365-7" tabindex="-1"></a>heat_cntl_2</span></code></pre></div>
<pre><code>## # A tibble: 7 × 4
##   SpaceHeatingUsed HeatingBehavior                             p    p_se
##   &lt;lgl&gt;            &lt;fct&gt;                                   &lt;dbl&gt;   &lt;dbl&gt;
## 1 FALSE            &lt;NA&gt;                                  0.0469  2.07e-3
## 2 TRUE             Set one temp and leave it             0.410   4.60e-3
## 3 TRUE             Manually adjust at night/no one home  0.251   4.36e-3
## 4 TRUE             Programmable or smart thermostat aut… 0.160   2.95e-3
## 5 TRUE             Turn on or off as needed              0.0976  2.79e-3
## 6 TRUE             No control                            0.0317  1.62e-3
## 7 TRUE             Other                                 0.00198 3.41e-4</code></pre>
<p> </p>
<p>If we ran the first analysis, we would say that 16.8% <strong>of households with heat</strong> use a programmable or smart thermostat for heating of their home. If we used the results from the second analysis, we would say that 16% <strong>of households</strong> use a programmable or smart thermostat for heating of their home. The distinction between the two statements is made bold for emphasis. Skip patterns often change the universe we are talking about and need to be carefully examined. </p>
<p>
Filtering to the correct universe is important when handling these types of missing data. The <code>nabular</code> we created above can also help with this. If we have <code>NA_skip</code> values in the shadow, we can make sure that we filter out all of these values and only include relevant missing values. To do this with survey data, we could first create the <code>nabular</code>, then create the design object on that data, and then use the shadow variables to assist with filtering the data. Let’s use the <code>nabular</code> we created above for ANES 2020 (<code>anes_2020_shadow</code>) to create the design object.</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="c11-missing-data.html#cb367-1" tabindex="-1"></a>anes_adjwgt_shadow <span class="ot">&lt;-</span> anes_2020_shadow <span class="sc">%&gt;%</span></span>
<span id="cb367-2"><a href="c11-missing-data.html#cb367-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">V200010b =</span> V200010b <span class="sc">/</span> <span class="fu">sum</span>(V200010b) <span class="sc">*</span> targetpop)</span>
<span id="cb367-3"><a href="c11-missing-data.html#cb367-3" tabindex="-1"></a></span>
<span id="cb367-4"><a href="c11-missing-data.html#cb367-4" tabindex="-1"></a>anes_des_shadow <span class="ot">&lt;-</span> anes_adjwgt_shadow <span class="sc">%&gt;%</span></span>
<span id="cb367-5"><a href="c11-missing-data.html#cb367-5" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(</span>
<span id="cb367-6"><a href="c11-missing-data.html#cb367-6" tabindex="-1"></a>    <span class="at">weights =</span> V200010b,</span>
<span id="cb367-7"><a href="c11-missing-data.html#cb367-7" tabindex="-1"></a>    <span class="at">strata =</span> V200010d,</span>
<span id="cb367-8"><a href="c11-missing-data.html#cb367-8" tabindex="-1"></a>    <span class="at">ids =</span> V200010c,</span>
<span id="cb367-9"><a href="c11-missing-data.html#cb367-9" tabindex="-1"></a>    <span class="at">nest =</span> <span class="cn">TRUE</span></span>
<span id="cb367-10"><a href="c11-missing-data.html#cb367-10" tabindex="-1"></a>  )</span></code></pre></div>
<p></p>
<p>Then, we can use this design object to look at the percentage of the population that voted for each candidate in 2016 (<code>V201103</code>.) First, let’s look at the percentages without removing any cases: </p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="c11-missing-data.html#cb368-1" tabindex="-1"></a>pres16_select1 <span class="ot">&lt;-</span> anes_des_shadow <span class="sc">%&gt;%</span></span>
<span id="cb368-2"><a href="c11-missing-data.html#cb368-2" tabindex="-1"></a>  <span class="fu">group_by</span>(V201103) <span class="sc">%&gt;%</span></span>
<span id="cb368-3"><a href="c11-missing-data.html#cb368-3" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb368-4"><a href="c11-missing-data.html#cb368-4" tabindex="-1"></a>    <span class="at">All_Missing =</span> <span class="fu">survey_prop</span>()</span>
<span id="cb368-5"><a href="c11-missing-data.html#cb368-5" tabindex="-1"></a>  )</span>
<span id="cb368-6"><a href="c11-missing-data.html#cb368-6" tabindex="-1"></a></span>
<span id="cb368-7"><a href="c11-missing-data.html#cb368-7" tabindex="-1"></a>pres16_select1</span></code></pre></div>
<pre><code>## # A tibble: 5 × 3
##   V201103                 All_Missing All_Missing_se
##   &lt;dbl+lbl&gt;                     &lt;dbl&gt;          &lt;dbl&gt;
## 1 -1 [-1. Inapplicable]       0.324          0.00933
## 2  1 [1. Hillary Clinton]     0.330          0.00728
## 3  2 [2. Donald Trump]        0.299          0.00728
## 4  5 [5. Other {SPECIFY}]     0.0409         0.00230
## 5 NA                          0.00627        0.00121</code></pre>
<p>Next, we look at the percentages, removing only those missing due to skip patterns (i.e., they did not receive this question.) </p>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb370-1"><a href="c11-missing-data.html#cb370-1" tabindex="-1"></a>pres16_select2 <span class="ot">&lt;-</span> anes_des_shadow <span class="sc">%&gt;%</span></span>
<span id="cb370-2"><a href="c11-missing-data.html#cb370-2" tabindex="-1"></a>  <span class="fu">filter</span>(V201103_NA <span class="sc">!=</span> <span class="st">&quot;NA_skip&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb370-3"><a href="c11-missing-data.html#cb370-3" tabindex="-1"></a>  <span class="fu">group_by</span>(V201103) <span class="sc">%&gt;%</span></span>
<span id="cb370-4"><a href="c11-missing-data.html#cb370-4" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb370-5"><a href="c11-missing-data.html#cb370-5" tabindex="-1"></a>    <span class="at">No_Skip_Missing =</span> <span class="fu">survey_prop</span>()</span>
<span id="cb370-6"><a href="c11-missing-data.html#cb370-6" tabindex="-1"></a>  )</span>
<span id="cb370-7"><a href="c11-missing-data.html#cb370-7" tabindex="-1"></a></span>
<span id="cb370-8"><a href="c11-missing-data.html#cb370-8" tabindex="-1"></a>pres16_select2</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
##   V201103                 No_Skip_Missing No_Skip_Missing_se
##   &lt;dbl+lbl&gt;                         &lt;dbl&gt;              &lt;dbl&gt;
## 1  1 [1. Hillary Clinton]         0.488              0.00870
## 2  2 [2. Donald Trump]            0.443              0.00856
## 3  5 [5. Other {SPECIFY}]         0.0606             0.00330
## 4 NA                              0.00928            0.00178</code></pre>
<p>Finally, we look at the percentages, removing all missing values both due to skip patterns and due to those who refused to answer the question. </p>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb372-1"><a href="c11-missing-data.html#cb372-1" tabindex="-1"></a>pres16_select3 <span class="ot">&lt;-</span> anes_des_shadow <span class="sc">%&gt;%</span></span>
<span id="cb372-2"><a href="c11-missing-data.html#cb372-2" tabindex="-1"></a>  <span class="fu">filter</span>(V201103_NA <span class="sc">==</span> <span class="st">&quot;!NA&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb372-3"><a href="c11-missing-data.html#cb372-3" tabindex="-1"></a>  <span class="fu">group_by</span>(V201103) <span class="sc">%&gt;%</span></span>
<span id="cb372-4"><a href="c11-missing-data.html#cb372-4" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb372-5"><a href="c11-missing-data.html#cb372-5" tabindex="-1"></a>    <span class="at">No_Missing =</span> <span class="fu">survey_prop</span>()</span>
<span id="cb372-6"><a href="c11-missing-data.html#cb372-6" tabindex="-1"></a>  )</span>
<span id="cb372-7"><a href="c11-missing-data.html#cb372-7" tabindex="-1"></a></span>
<span id="cb372-8"><a href="c11-missing-data.html#cb372-8" tabindex="-1"></a>pres16_select3</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   V201103                No_Missing No_Missing_se
##   &lt;dbl+lbl&gt;                   &lt;dbl&gt;         &lt;dbl&gt;
## 1 1 [1. Hillary Clinton]     0.492        0.00875
## 2 2 [2. Donald Trump]        0.447        0.00861
## 3 5 [5. Other {SPECIFY}]     0.0611       0.00332</code></pre>
<p> </p>

<div id="edxahdlkim" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#edxahdlkim table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#edxahdlkim thead, #edxahdlkim tbody, #edxahdlkim tfoot, #edxahdlkim tr, #edxahdlkim td, #edxahdlkim th {
  border-style: none;
}

#edxahdlkim p {
  margin: 0;
  padding: 0;
}

#edxahdlkim .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#edxahdlkim .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#edxahdlkim .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#edxahdlkim .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#edxahdlkim .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#edxahdlkim .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#edxahdlkim .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#edxahdlkim .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#edxahdlkim .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#edxahdlkim .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#edxahdlkim .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#edxahdlkim .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#edxahdlkim .gt_spanner_row {
  border-bottom-style: hidden;
}

#edxahdlkim .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#edxahdlkim .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#edxahdlkim .gt_from_md > :first-child {
  margin-top: 0;
}

#edxahdlkim .gt_from_md > :last-child {
  margin-bottom: 0;
}

#edxahdlkim .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#edxahdlkim .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#edxahdlkim .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#edxahdlkim .gt_row_group_first td {
  border-top-width: 2px;
}

#edxahdlkim .gt_row_group_first th {
  border-top-width: 2px;
}

#edxahdlkim .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#edxahdlkim .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#edxahdlkim .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#edxahdlkim .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#edxahdlkim .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#edxahdlkim .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#edxahdlkim .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#edxahdlkim .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#edxahdlkim .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#edxahdlkim .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#edxahdlkim .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#edxahdlkim .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#edxahdlkim .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#edxahdlkim .gt_left {
  text-align: left;
}

#edxahdlkim .gt_center {
  text-align: center;
}

#edxahdlkim .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#edxahdlkim .gt_font_normal {
  font-weight: normal;
}

#edxahdlkim .gt_font_bold {
  font-weight: bold;
}

#edxahdlkim .gt_font_italic {
  font-style: italic;
}

#edxahdlkim .gt_super {
  font-size: 65%;
}

#edxahdlkim .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#edxahdlkim .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#edxahdlkim .gt_indent_1 {
  text-indent: 5px;
}

#edxahdlkim .gt_indent_2 {
  text-indent: 10px;
}

#edxahdlkim .gt_indent_3 {
  text-indent: 15px;
}

#edxahdlkim .gt_indent_4 {
  text-indent: 20px;
}

#edxahdlkim .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <caption><span id="tab:missing-anes-shadow-tab">TABLE 11.1: </span>Percentage of Votes by Candidate for Different Missing Data Inclusions</caption>
  <thead>
    <tr class="gt_col_headings gt_spanner_row">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col" id="Candidate">Candidate</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" scope="colgroup" id="Including All Missing Data">
        <span class="gt_column_spanner">Including All Missing Data</span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" scope="colgroup" id="Removing Skip Patterns Only">
        <span class="gt_column_spanner">Removing Skip Patterns Only</span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" scope="colgroup" id="Removing All Missing Data">
        <span class="gt_column_spanner">Removing All Missing Data</span>
      </th>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="%">%</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="s.e. (%)">s.e. (%)</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="%">%</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="s.e. (%)">s.e. (%)</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="%">%</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="s.e. (%)">s.e. (%)</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="Candidate" class="gt_row gt_left">Did not Vote for President in 2016</td>
<td headers="All_Missing" class="gt_row gt_right">32.4%</td>
<td headers="All_Missing_se" class="gt_row gt_right">0.9%</td>
<td headers="No_Skip_Missing" class="gt_row gt_right">NA</td>
<td headers="No_Skip_Missing_se" class="gt_row gt_right">NA</td>
<td headers="No_Missing" class="gt_row gt_right">NA</td>
<td headers="No_Missing_se" class="gt_row gt_right">NA</td></tr>
    <tr><td headers="Candidate" class="gt_row gt_left">Hillary Clinton</td>
<td headers="All_Missing" class="gt_row gt_right">33.0%</td>
<td headers="All_Missing_se" class="gt_row gt_right">0.7%</td>
<td headers="No_Skip_Missing" class="gt_row gt_right">48.8%</td>
<td headers="No_Skip_Missing_se" class="gt_row gt_right">0.9%</td>
<td headers="No_Missing" class="gt_row gt_right">49.2%</td>
<td headers="No_Missing_se" class="gt_row gt_right">0.9%</td></tr>
    <tr><td headers="Candidate" class="gt_row gt_left">Donald Trump</td>
<td headers="All_Missing" class="gt_row gt_right">29.9%</td>
<td headers="All_Missing_se" class="gt_row gt_right">0.7%</td>
<td headers="No_Skip_Missing" class="gt_row gt_right">44.3%</td>
<td headers="No_Skip_Missing_se" class="gt_row gt_right">0.9%</td>
<td headers="No_Missing" class="gt_row gt_right">44.7%</td>
<td headers="No_Missing_se" class="gt_row gt_right">0.9%</td></tr>
    <tr><td headers="Candidate" class="gt_row gt_left">Other Candidate</td>
<td headers="All_Missing" class="gt_row gt_right">4.1%</td>
<td headers="All_Missing_se" class="gt_row gt_right">0.2%</td>
<td headers="No_Skip_Missing" class="gt_row gt_right">6.1%</td>
<td headers="No_Skip_Missing_se" class="gt_row gt_right">0.3%</td>
<td headers="No_Missing" class="gt_row gt_right">6.1%</td>
<td headers="No_Missing_se" class="gt_row gt_right">0.3%</td></tr>
    <tr><td headers="Candidate" class="gt_row gt_left">Missing</td>
<td headers="All_Missing" class="gt_row gt_right">0.6%</td>
<td headers="All_Missing_se" class="gt_row gt_right">0.1%</td>
<td headers="No_Skip_Missing" class="gt_row gt_right">0.9%</td>
<td headers="No_Skip_Missing_se" class="gt_row gt_right">0.2%</td>
<td headers="No_Missing" class="gt_row gt_right">NA</td>
<td headers="No_Missing_se" class="gt_row gt_right">NA</td></tr>
  </tbody>
  
  
</table>
</div>
<p>As Table <a href="c11-missing-data.html#tab:missing-anes-shadow-tab">11.1</a> shows, the results can vary greatly depending on which type of missing data are removed. If we remove only the skip patterns the margin between Clinton and Trump is 4.5 percentage points, but if we include all data, even including those that did not vote in 2016, the margin is 3.1 percentage points. How we handle the different types of missing values is important for interpreting the data.
</p>
<p></p>

</div>
</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-debell" class="csl-entry">
DeBell, Matthew. 2010. <span>“How to Analyze ANES Survey Data.”</span> ANES Technical Report Series nes012492. Palo Alto, CA: Stanford University; Ann Arbor, MI: the University of Michigan; <a href="https://electionstudies.org/wp-content/uploads/2018/05/HowToAnalyzeANESData.pdf" class="uri">https://electionstudies.org/wp-content/uploads/2018/05/HowToAnalyzeANESData.pdf</a>.
</div>
<div id="ref-Kim2021" class="csl-entry">
Kim, Jae Kwang, and Jun Shao. 2021. <em>Statistical Methods for Handling Incomplete Data</em>. Chapman &amp; Hall/CRC Press.
</div>
<div id="ref-mack" class="csl-entry">
Mack, Christina, Zhaohui Su, and Daniel Westreich. 2018. <span>“Types of Missing Data.”</span> In <em>Managing Missing Data in Patient Registries: Addendum to Registries for Evaluating Patient Outcomes: A User’s Guide, Third Edition [Internet]</em>. Rockville (MD): Agency for Healthcare Research; Quality (US); <a href="https://www.ncbi.nlm.nih.gov/books/NBK493614/" class="uri">https://www.ncbi.nlm.nih.gov/books/NBK493614/</a>.
</div>
<div id="ref-Schafer2002" class="csl-entry">
Schafer, Joseph L, and John W Graham. 2002. <span>“Missing Data: Our View of the State of the Art.”</span> <em>Psychological Methods</em> 7: 147–77. <a href="https://doi.org/10.1037//1082-989X.7.2.147">https://doi.org/10.1037//1082-989X.7.2.147</a>.
</div>
<div id="ref-visdattierney" class="csl-entry">
Tierney, Nicholas. 2017. <span>“<span class="nocase">visdat</span>: Visualising Whole Data Frames.”</span> <em>Journal of Open Source Software</em> 2 (16): 355. <a href="https://doi.org/10.21105/joss.00355">https://doi.org/10.21105/joss.00355</a>.
</div>
<div id="ref-naniar2023" class="csl-entry">
Tierney, Nicholas, and Dianne Cook. 2023. <span>“Expanding Tidy Data Principles to Facilitate Missing Data Exploration, Visualization and Assessment of Imputations.”</span> <em>Journal of Statistical Software</em> 105 (7): 1–31. <a href="https://doi.org/10.18637/jss.v105.i07">https://doi.org/10.18637/jss.v105.i07</a>.
</div>
<div id="ref-Valliant2018weights" class="csl-entry">
Valliant, Richard, and Jill A. Dever. 2018. <em>Survey Weights: A Step-by-Step Guide to Calculation</em>. Stata Press.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="c10-sample-designs-replicate-weights.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="c12-recommendations.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": true,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "github"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/tidy-survey-r/tidy-survey-book/blob/main/11-missing-data.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
