<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Specifying sample designs in srvyr | Tidy Survey Book</title>
  <meta name="description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Specifying sample designs in srvyr | Tidy Survey Book" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  <meta name="github-repo" content="tidy-survey-r/tidy-survey-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Specifying sample designs in srvyr | Tidy Survey Book" />
  
  <meta name="twitter:description" content="Bookdown for upcoming book on survey analysis the tidy way." />
  

<meta name="author" content="Stephanie Zimmer, Rebecca Powell, and Isabella Velásquez" />


<meta name="date" content="2022-06-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="c04.html"/>
<link rel="next" href="c06.html"/>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#why-read-this-book"><i class="fa fa-check"></i>Why read this book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#structure-of-the-book"><i class="fa fa-check"></i>Structure of the book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-information-and-conventions"><i class="fa fa-check"></i>Software information and conventions</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="c01.html"><a href="c01.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="c02.html"><a href="c02.html"><i class="fa fa-check"></i><b>2</b> Introducing survey data</a></li>
<li class="chapter" data-level="3" data-path="c03.html"><a href="c03.html"><i class="fa fa-check"></i><b>3</b> Understanding survey data files</a></li>
<li class="chapter" data-level="4" data-path="c04.html"><a href="c04.html"><i class="fa fa-check"></i><b>4</b> Introducing the srvyr package</a></li>
<li class="chapter" data-level="5" data-path="c05.html"><a href="c05.html"><i class="fa fa-check"></i><b>5</b> Specifying sample designs in srvyr</a>
<ul>
<li class="chapter" data-level="5.1" data-path="c05.html"><a href="c05.html#simple-random-sample-without-replacement"><i class="fa fa-check"></i><b>5.1</b> Simple random sample without replacement</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="c05.html"><a href="c05.html#the-math"><i class="fa fa-check"></i><b>5.1.1</b> The math</a></li>
<li class="chapter" data-level="5.1.2" data-path="c05.html"><a href="c05.html#the-syntax"><i class="fa fa-check"></i><b>5.1.2</b> The syntax</a></li>
<li class="chapter" data-level="5.1.3" data-path="c05.html"><a href="c05.html#an-example"><i class="fa fa-check"></i><b>5.1.3</b> An example</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="c05.html"><a href="c05.html#simple-random-sample-with-replacement"><i class="fa fa-check"></i><b>5.2</b> Simple random sample with replacement</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="c05.html"><a href="c05.html#the-math-1"><i class="fa fa-check"></i><b>5.2.1</b> The math</a></li>
<li class="chapter" data-level="5.2.2" data-path="c05.html"><a href="c05.html#the-syntax-1"><i class="fa fa-check"></i><b>5.2.2</b> The syntax</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="c05.html"><a href="c05.html#stratified-sampling"><i class="fa fa-check"></i><b>5.3</b> Stratified sampling</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="c05.html"><a href="c05.html#the-math-2"><i class="fa fa-check"></i><b>5.3.1</b> The math</a></li>
<li class="chapter" data-level="5.3.2" data-path="c05.html"><a href="c05.html#the-syntax-2"><i class="fa fa-check"></i><b>5.3.2</b> The syntax</a></li>
<li class="chapter" data-level="5.3.3" data-path="c05.html"><a href="c05.html#an-example-1"><i class="fa fa-check"></i><b>5.3.3</b> An example</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="c05.html"><a href="c05.html#clustered-sampling"><i class="fa fa-check"></i><b>5.4</b> Clustered sampling</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="c05.html"><a href="c05.html#the-math-3"><i class="fa fa-check"></i><b>5.4.1</b> The math</a></li>
<li class="chapter" data-level="5.4.2" data-path="c05.html"><a href="c05.html#the-syntax-3"><i class="fa fa-check"></i><b>5.4.2</b> The syntax</a></li>
<li class="chapter" data-level="5.4.3" data-path="c05.html"><a href="c05.html#an-example-2"><i class="fa fa-check"></i><b>5.4.3</b> An example</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="c05.html"><a href="c05.html#understanding-survey-design-documentation"><i class="fa fa-check"></i><b>5.5</b> Understanding survey design documentation</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="c06.html"><a href="c06.html"><i class="fa fa-check"></i><b>6</b> Descriptive analyses in srvyr</a></li>
<li class="chapter" data-level="7" data-path="c07.html"><a href="c07.html"><i class="fa fa-check"></i><b>7</b> Statistical testing</a></li>
<li class="chapter" data-level="8" data-path="c08.html"><a href="c08.html"><i class="fa fa-check"></i><b>8</b> Modeling</a></li>
<li class="chapter" data-level="9" data-path="c09.html"><a href="c09.html"><i class="fa fa-check"></i><b>9</b> Presenting results</a></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="more-to-say.html"><a href="more-to-say.html"><i class="fa fa-check"></i><b>A</b> More to Say</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tidy Survey Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="c05" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapter 5</span> Specifying sample designs in srvyr<a href="c05.html#c05" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The primary reason for using packages like {survey} and {srvyr} are to incorporate the sampling design into estimates. By incorporating the sampling design, precision estimates (e.g. standard errors and confidence intervals) are appropriately calculated. In this chapter, we will introduce common sampling designs, the mathematical methods for calculating estimates and standard errors for a given sampling design, and the R syntax to specify the sampling design. While we will show the math behind the estimates, the functions in these packages will do the calculation.</p>
<div id="simple-random-sample-without-replacement" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Simple random sample without replacement<a href="c05.html#simple-random-sample-without-replacement" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The simple random sample (SRS) without replacement is a sampling design where a fixed sample size <span class="math inline">\((n)\)</span> is selected from a sampling frame of size <span class="math inline">\((N)\)</span>, and every possible subsample has equal probability of selection. A sampling frame is a list of the units from which a sample is selected. This is like sampling items out of a hat without replacing them back in the hat. While SRS is one of the simplest designs, it is not often implemented in large studies. To select a SRS, a list of all the units in the population must be available which is not always feasible. Additionally, the sample is drawn randomly without regard for the structure of the population which may not be practical for data collection so other designs are implemented as will be discussed later though SRS may still be a component of a stage of these designs.</p>
<p>When analyzing survey data, some of the most common estimates desired are means, proportions, and their standard errors so we will introduce the formula for each of these under each design. Note that the package will implement these, but it is useful to understand.</p>
<div id="the-math" class="section level3 hasAnchor" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> The math<a href="c05.html#the-math" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The estimate for the population mean of variable <span class="math inline">\(y\)</span> is:</p>
<p><span class="math display">\[\bar{y}=\frac{1}{n}\sum_{i=1}^n y_i\]</span></p>
<p>and the estimate of the standard deviation of mean is:</p>
<p><span class="math display">\[se(\bar{y})=\sqrt{\frac{s^2}{n}\left( 1-\frac{n}{N} \right)}\]</span> and</p>
<p><span class="math display">\[s^2=\frac{1}{n-1}\sum_{i=1}^n\left(y_i-\bar{y}\right)^2.\]</span></p>
<p>This standard error estimate might look very similar to equations in other applications seen except for the bit on the right side of the equation <span class="math inline">\(1-\frac{n}{N}\)</span> - this is call the finite population correction factor (FPC). If the size of the frame, <span class="math inline">\(N\)</span>, is very large, the FPC is negligible so it is often ignored.</p>
<p>To estimate proportions, we define <span class="math inline">\(x_i\)</span> as the indicator that the outcome is observed. That is, <span class="math inline">\(x_i=1\)</span> if the outcome is observed and <span class="math inline">\(x_i=0\)</span> if the outcome is not observed. Then the estimated proportion from a SRS design is:</p>
<p><span class="math display">\[\hat{p}=\frac{1}{n}\sum_{i=1}^n x_i \]</span>
and the estimated standard deviation of the proportion is:</p>
<p><span class="math display">\[se(\hat{p})=\sqrt{\frac{\hat{p}(1-\hat{p})}{n-1}\left(1-\frac{n}{N}\right)} \]</span></p>
</div>
<div id="the-syntax" class="section level3 hasAnchor" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> The syntax<a href="c05.html#the-syntax" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If a sample that was drawn through SRS and had no nonresponse or other weighting adjustments, in R specify this design as:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="c05.html#cb3-1" aria-hidden="true" tabindex="-1"></a>des_srs1 <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="c05.html#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">fpc =</span> fpcvar)</span></code></pre></div>
<p>where <code>dat</code> is a tibble or data.frame with the survey data and <code>fpcvar</code> is a variable on the tibble which indicates the size of the sampling frame. If the frame was very large, sometimes the frame size is not provided. In that case, specify the design as:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="c05.html#cb4-1" aria-hidden="true" tabindex="-1"></a>des_srs2 <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="c05.html#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>()</span></code></pre></div>
<p>If some post-survey adjustments were implemented and the weights are not all equal, specify the design as:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="c05.html#cb5-1" aria-hidden="true" tabindex="-1"></a>des_srs3 <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="c05.html#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">weights =</span> wtvar, <span class="at">fpc =</span> fpcvar)</span></code></pre></div>
<p>where <code>wtvar</code> is the variable for the weight on the data. Again, the fpc can be omitted if it is not necessary because the frame is large.</p>
</div>
<div id="an-example" class="section level3 hasAnchor" number="5.1.3">
<h3><span class="header-section-number">5.1.3</span> An example<a href="c05.html#an-example" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The {survey} package in R provides some example datasets to use and those will be used throughout this chapter. The Academic Performance Index (API) was a program administered by the California Department of Education. These datasets are derived from that data and include a population file (frame) of all schools with at least 100 students and several samples from that data. A SRS of 200 schools was sampled and included in <code>apisrs</code>. The SRS sample data is illustrated below:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="c05.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">tidyverse.quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-2"><a href="c05.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb6-3"><a href="c05.html#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey)</span></code></pre></div>
<pre><code>## Loading required package: grid</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Loading required package: survival</code></pre>
<pre><code>## 
## Attaching package: &#39;survey&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:graphics&#39;:
## 
##     dotchart</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="c05.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(srvyr)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;srvyr&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     filter</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="c05.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(api)</span>
<span id="cb17-2"><a href="c05.html#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="c05.html#cb17-3" aria-hidden="true" tabindex="-1"></a>apisrs_slim <span class="ot">&lt;-</span> </span>
<span id="cb17-4"><a href="c05.html#cb17-4" aria-hidden="true" tabindex="-1"></a>  apisrs <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="c05.html#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="c05.html#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(dnum, snum) <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="c05.html#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(cds, dnum, snum, dname, sname, fpc, pw)</span></code></pre></div>
<p>School districts have identifiers <code>dnum</code> and schools have identifiers of <code>snum</code> along with their names. Additionally, the <code>fpc</code> is included as <code>fpc</code> and the weight as <code>pw</code>. This design should be specified as:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="c05.html#cb18-1" aria-hidden="true" tabindex="-1"></a>des_apisrs <span class="ot">&lt;-</span> apisrs_slim <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="c05.html#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">weights =</span> pw, <span class="at">fpc =</span> fpc)</span>
<span id="cb18-3"><a href="c05.html#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="c05.html#cb18-4" aria-hidden="true" tabindex="-1"></a>des_apisrs</span></code></pre></div>
<pre><code>## Independent Sampling design
## Called via srvyr
## Sampling variables:
##  - ids: `1`
##  - fpc: fpc
##  - weights: pw
## Data variables: cds (chr), dnum (int), snum (dbl),
##   dname (chr), sname (chr), fpc (dbl), pw (dbl)</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="c05.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(des_apisrs)</span></code></pre></div>
<pre><code>## Independent Sampling design
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0323  0.0323  0.0323  0.0323  0.0323  0.0323 
## Population size (PSUs): 6194 
## Data variables:
## [1] &quot;cds&quot;   &quot;dnum&quot;  &quot;snum&quot;  &quot;dname&quot; &quot;sname&quot; &quot;fpc&quot;  
## [7] &quot;pw&quot;</code></pre>
<p>Printing the design object above, the design is described as an “Independent Sampling design” which is another terminology for SRS. The ids are specified as <code>1</code> which means there is no clustering (a topic described later in this chapter), the fpc variable is indicated, and the weights are indicated. When looking at the summary of the design object, the population size is given a summary of the probabilities (inverse of the weights).</p>
</div>
</div>
<div id="simple-random-sample-with-replacement" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Simple random sample with replacement<a href="c05.html#simple-random-sample-with-replacement" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The simple random sample (SRSWR) with replacement is a sampling design where a fixed sample size <span class="math inline">\((n)\)</span> is selected from a sampling frame of size <span class="math inline">\((N)\)</span> and units can be selected more than once. This is like sampling items out of a hat and replacing them back in the hat before selecting another item. Similar to a SRS design, a full list of the population must be available. As a reminder, units can be selected more than once so would appear in the data frame more than once and thus appear in the sums more than once.</p>
<div id="the-math-1" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> The math<a href="c05.html#the-math-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The estimate for the population mean of variable <span class="math inline">\(y\)</span> is:</p>
<p><span class="math display">\[\bar{y}=\frac{1}{n}\sum_{i=1}^n y_i\]</span></p>
<p>and the estimate of the standard deviation of mean is:</p>
<p><span class="math display">\[\sqrt{\frac{s^2}{n}}\]</span> and</p>
<p><span class="math display">\[s^2=\frac{1}{n-1}\sum_{i=1}^n\left(y_i-\bar{y}\right)^2.\]</span>
Again, we define <span class="math inline">\(x_i\)</span> as the indicator that the outcome is observed. Then the estimated proportion from a SRSWR design is:</p>
<p><span class="math display">\[\hat{p}=\frac{1}{n}\sum_{i=1}^n x_i \]</span>
and the estimated standard deviation of the proportion is:</p>
<p><span class="math display">\[se(\hat{p})=\sqrt{\frac{\hat{p}(1-\hat{p})}{n}} \]</span></p>
</div>
<div id="the-syntax-1" class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> The syntax<a href="c05.html#the-syntax-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If you had a sample that was drawn through SRSWR and had no nonresponse or other weighting adjustments, in R, you should specify this design as:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="c05.html#cb22-1" aria-hidden="true" tabindex="-1"></a>des_srswr1 <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="c05.html#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>()</span></code></pre></div>
<p>where <code>dat</code> is a tibble or data.frame with your survey data.</p>
<p>If some post-survey adjustments were implemented and the weights are not all equal, specify the design as:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="c05.html#cb23-1" aria-hidden="true" tabindex="-1"></a>des_srswr2 <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="c05.html#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">weights =</span> wtvar)</span></code></pre></div>
<p>where <code>wtvar</code> is the variable for the weight on the data.</p>
<p>The {survey} package does not include an example of SRSWR so we create an example below. Note that this is sampled with replacements so there are duplicates. These duplicates are listed more than once and for proper estimation are deduplicated.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="c05.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">409963</span>)</span>
<span id="cb24-2"><a href="c05.html#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="c05.html#cb24-3" aria-hidden="true" tabindex="-1"></a>apisrswr <span class="ot">&lt;-</span> apipop <span class="sc">%&gt;%</span></span>
<span id="cb24-4"><a href="c05.html#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="c05.html#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">200</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-6"><a href="c05.html#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(cds, dnum, snum, dname, sname) <span class="sc">%&gt;%</span></span>
<span id="cb24-7"><a href="c05.html#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb24-8"><a href="c05.html#cb24-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">weight =</span> <span class="fu">nrow</span>(apipop)<span class="sc">/</span><span class="dv">200</span></span>
<span id="cb24-9"><a href="c05.html#cb24-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-10"><a href="c05.html#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="c05.html#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(apisrswr)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 6
##   cds             dnum  snum dname         sname weight
##   &lt;chr&gt;          &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;         &lt;chr&gt;  &lt;dbl&gt;
## 1 43696416060065   533  5348 Palo Alto Un~ Jord~   31.0
## 2 07618046005060   650   509 San Ramon Va~ Alam~   31.0
## 3 19648086085674   457  2134 Montebello U~ La M~   31.0
## 4 07617056003719   346   377 Knightsen El~ Knig~   31.0
## 5 19650606023022   744  2351 Torrance Uni~ Carr~   31.0
## 6 01611196090120     6    13 Alameda City~ Pade~   31.0</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="c05.html#cb26-1" aria-hidden="true" tabindex="-1"></a>apisrswr <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="c05.html#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">duplicated</span>(cds) <span class="sc">|</span> <span class="fu">duplicated</span>(cds, <span class="at">fromLast=</span><span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 4 x 6
##   cds             dnum  snum dname         sname weight
##   &lt;chr&gt;          &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;         &lt;chr&gt;  &lt;dbl&gt;
## 1 39686766042782   716  4880 Stockton Cit~ Tyle~   31.0
## 2 15633216008841    41   869 Bakersfield ~ Chip~   31.0
## 3 39686766042782   716  4880 Stockton Cit~ Tyle~   31.0
## 4 15633216008841    41   869 Bakersfield ~ Chip~   31.0</code></pre>
<p>A weight variable was added which is the inverse of the probability of selection. To specify the sampling design for <code>apisrswr</code>, the following syntax should be used:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="c05.html#cb28-1" aria-hidden="true" tabindex="-1"></a>des_apisrswr <span class="ot">&lt;-</span> apisrswr <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="c05.html#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">weights =</span> weight)</span>
<span id="cb28-3"><a href="c05.html#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="c05.html#cb28-4" aria-hidden="true" tabindex="-1"></a>des_apisrswr</span></code></pre></div>
<pre><code>## Independent Sampling design (with replacement)
## Called via srvyr
## Sampling variables:
##  - ids: `1`
##  - weights: weight
## Data variables: cds (chr), dnum (int), snum (dbl),
##   dname (chr), sname (chr), weight (dbl)</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="c05.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(des_apisrswr)</span></code></pre></div>
<pre><code>## Independent Sampling design (with replacement)
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0323  0.0323  0.0323  0.0323  0.0323  0.0323 
## Data variables:
## [1] &quot;cds&quot;    &quot;dnum&quot;   &quot;snum&quot;   &quot;dname&quot;  &quot;sname&quot; 
## [6] &quot;weight&quot;</code></pre>
<p>When printing the design object or showing its summary, it is noted that the sampling is done “with replacement” because no fpc was specified unlike the SRS without replacement example.</p>
</div>
</div>
<div id="stratified-sampling" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Stratified sampling<a href="c05.html#stratified-sampling" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In stratified sampling, the population is divided into mutually exclusive subpopulations called strata and then samples are selected within each of the strata. Stratification is done for two primary reasons:</p>
<ol style="list-style-type: decimal">
<li><p>Ensuring sample representation from all the subpopulations. A SRS cannot guarantee that your sample will include all subpopulations that you may desire in your sample so this type of design ensures representation of all planned subpopulations. For example, if we are doing a survey of professors at a university, we might want to stratify by college to ensure we get professors in the sample from all colleges.</p></li>
<li><p>Stratification can be used for statistical efficiency. If the outcome is correlated with the subpopulations then the variance of the estimate will be lower when implementing stratification.</p></li>
</ol>
<p>Within each strata, sampling can be done in any manner but we will consider the case of SRS selection within each strata. Commonly, strata are numbered as <span class="math inline">\(1, \ldots, H\)</span>.</p>
<div id="the-math-2" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> The math<a href="c05.html#the-math-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let <span class="math inline">\(\bar{y}_h\)</span> be the sample mean for stratum <span class="math inline">\(h\)</span>, <span class="math inline">\(N_h\)</span> be the population size of stratum <span class="math inline">\(h\)</span>, and <span class="math inline">\(n_h\)</span> be the sample size of stratum <span class="math inline">\(h\)</span>. Then the estimate for the population mean under stratified SRS sampling is:</p>
<p><span class="math display">\[\bar{y}=\frac{1}{N}\sum_{h=1}^H N_h\bar{y}_h\]</span>
and the estimate of the standard error of <span class="math inline">\(\bar{y}\)</span> is:</p>
<p><span class="math display">\[\sqrt{\frac{1}{N^2} \sum_{h=1}^H N_h^2 s_h^2\left(1-\frac{n_h}{N_h}\right)} \]</span></p>
<p>where
<span class="math display">\[s_h^2=\frac{1}{n_h-1}\sum_{i=1}^{n_h}\left(y_{i,h}-\bar{y}_h\right)^2.\]</span></p>
<p>For estimates of proportions, let <span class="math inline">\(\hat{p}_h\)</span> be the estimated proportion in stratum <span class="math inline">\(h\)</span>. Then the population proportion estimate is:</p>
<p><span class="math display">\[\hat{p}= \frac{1}{N}\sum_{h=1}^H N_h \hat{p}_h\]</span></p>
<p>and the standard error of the proportion is:</p>
<p><span class="math display">\[se(\hat{p}) = \frac{1}{N} \sqrt{ \sum_{h=1}^H N_h^2 \frac{\hat{p}_h(1-\hat{p}_h)}{n_h-1} \left(1-\frac{n_h}{N_h}\right)}\]</span></p>
</div>
<div id="the-syntax-2" class="section level3 hasAnchor" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> The syntax<a href="c05.html#the-syntax-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To specify a stratified SRS design in {srvyr} where the population sizes of the strata are not too large and are known, that is you are using the fpc, specify the design as:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="c05.html#cb32-1" aria-hidden="true" tabindex="-1"></a>des_stsrs1 <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="c05.html#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">fpc =</span> fpcvar, <span class="at">strata =</span> stratvar)</span></code></pre></div>
<p>where <code>fpcvar</code> is a variable on your data which indicates <span class="math inline">\(N_h\)</span> for each row and <code>stratavar</code> is a variable indicating the stratum for each row. You can omit the fpc if it is not applicable. Additionally, you can indicate the weight variable if it is present where <code>wtvar</code> is a variable on your data with a numeric weight.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="c05.html#cb33-1" aria-hidden="true" tabindex="-1"></a>des_stsrs2 <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="c05.html#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">weights =</span> wtvar, <span class="at">strata =</span> stratvar)</span></code></pre></div>
</div>
<div id="an-example-1" class="section level3 hasAnchor" number="5.3.3">
<h3><span class="header-section-number">5.3.3</span> An example<a href="c05.html#an-example-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the example API data, <code>apistrat</code> is a stratified random sample, stratified by school type (<code>stype</code>). The data is illustrated below:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="c05.html#cb34-1" aria-hidden="true" tabindex="-1"></a>apistrat_slim <span class="ot">&lt;-</span> </span>
<span id="cb34-2"><a href="c05.html#cb34-2" aria-hidden="true" tabindex="-1"></a>  apistrat <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="c05.html#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="c05.html#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(dnum, snum) <span class="sc">%&gt;%</span></span>
<span id="cb34-5"><a href="c05.html#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(cds, dnum, snum, dname, sname, stype, fpc, pw)</span>
<span id="cb34-6"><a href="c05.html#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="c05.html#cb34-7" aria-hidden="true" tabindex="-1"></a>apistrat_slim <span class="sc">%&gt;%</span> </span>
<span id="cb34-8"><a href="c05.html#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(stype, fpc)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   stype   fpc     n
##   &lt;fct&gt; &lt;dbl&gt; &lt;int&gt;
## 1 E      4421   100
## 2 H       755    50
## 3 M      1018    50</code></pre>
<p>The fpc is the same within each stratum and 100 elementary schools were sampled while 50 schools were sampled from both the middle and high school levels. This design should be specified as:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="c05.html#cb36-1" aria-hidden="true" tabindex="-1"></a>des_apistrat <span class="ot">&lt;-</span> apistrat_slim <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="c05.html#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">strata =</span> stype, <span class="at">weights =</span> pw, <span class="at">fpc =</span> fpc)</span>
<span id="cb36-3"><a href="c05.html#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="c05.html#cb36-4" aria-hidden="true" tabindex="-1"></a>des_apistrat</span></code></pre></div>
<pre><code>## Stratified Independent Sampling design
## Called via srvyr
## Sampling variables:
##  - ids: `1`
##  - strata: stype
##  - fpc: fpc
##  - weights: pw
## Data variables: cds (chr), dnum (int), snum (dbl),
##   dname (chr), sname (chr), stype (fct), fpc (dbl), pw
##   (dbl)</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="c05.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(des_apistrat)</span></code></pre></div>
<pre><code>## Stratified Independent Sampling design
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0226  0.0226  0.0359  0.0401  0.0534  0.0662 
## Stratum Sizes: 
##              E  H  M
## obs        100 50 50
## design.PSU 100 50 50
## actual.PSU 100 50 50
## Population stratum sizes (PSUs): 
##    E    H    M 
## 4421  755 1018 
## Data variables:
## [1] &quot;cds&quot;   &quot;dnum&quot;  &quot;snum&quot;  &quot;dname&quot; &quot;sname&quot; &quot;stype&quot;
## [7] &quot;fpc&quot;   &quot;pw&quot;</code></pre>
<p>When printing the object, it is specified as a “Stratified Independent Sampling design” also known as a stratified SRS and the strata variable is included. In the summary, a numeric summary of the probabilities of selection are displayed as well as the sample and population stratum sizes.</p>
</div>
</div>
<div id="clustered-sampling" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Clustered sampling<a href="c05.html#clustered-sampling" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There are several forms of cluster sampling. In clustered sampling, a population is divided into mutually exclusive subgroups called clusters or primary sampling units (PSUs). These PSUs are randomly sampled and then sampling is done within these clusters. There can be multiple levels of this selection. Clustered sampling is often used when a list of the entire population is not available or data collection involves interviewers needing direct contact with respondents.</p>
<p>For example, consider a study needing a sample of 6th grade students in the United States, no list likely exists of all these students. Obtaining a list of schools that have 6th graders is more likely to be possible so a study design could select a random sample of schools that have 6th graders. The selected schools can then provide a list of students to do a second stage of sampling where 6th grade students are randomly sampled within each of the sampled schools. This is a one-stage sample design and will be the type of design we will discuss in formulas below.</p>
<p>A more complicated but realistic example is necessary when sending out interviewers to households for a survey. Counties could be selected as the PSU, then Census block groups within counties selected as the secondary sampling unit (SSU), and then households within the block groups. This type of design reduces the travel necessary for interviewers.</p>
<p>Clustered designs are used as a practical solution but are not statistically efficient and should be avoided if they are not necessary. In the household survey example, this process would not be necessary if surveys were mailed to homes but interviewers were never sent out in person.</p>
<div id="the-math-3" class="section level3 hasAnchor" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> The math<a href="c05.html#the-math-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Consider a population where the are <span class="math inline">\(N\)</span> clusters and <span class="math inline">\(n\)</span> clusters are sampled via SRSWOR. Units within the sampled cluster are sampled via SRSWOR as well. Let <span class="math inline">\(M_i\)</span> be the number of units in cluster <span class="math inline">\(i\)</span> and <span class="math inline">\(\bar{y}_i\)</span> be the sample mean of cluster <span class="math inline">\(i\)</span>. Then, a ratio estimator of the population mean is:</p>
<p><span class="math display">\[\bar{y}=\frac{\sum_{i=1}^n M_i \bar{y}_i}{ \sum_{i=1}^n M_i}\]</span>
Note this is a consistent but biased estimator. Often the population size is not known so this is a method to estimate a mean without knowing the population size. The estimated standard error of the mean is:</p>
<p><span class="math display">\[se(\bar{y})=\frac{1}{\hat{N}_{pop} } \sqrt{\frac{N^2 (1-\frac{n}{N})}{n}\frac{1}{n-1} \sum_{i=1}^n (M_i\bar{y}_i -\hat{t}/N)^2  + \frac{N}{n}  \sum_{i=1}^n \frac{M_i^2}{m_i}\left(1-\frac{m_i}{M_i}\right)s^2_i }\]</span>
where <span class="math inline">\(\hat{N}_{pop}\)</span> is the estimated population size, <span class="math inline">\(\hat{t}\)</span> is the estimated total, and <span class="math inline">\(s_i^2\)</span> is the sample variance of cluster <span class="math inline">\(i\)</span>.</p>
<p>For estimates of proportions, the estimated proportion is:</p>
<p><span class="math display">\[\hat{p}=\frac{\sum_{i=1}^n M_i \hat{p}_i}{ \sum_{i=1}^n M_i}\]</span></p>
<p>and the associated standard error estimate is:</p>
<p><span class="math display">\[se(\hat{p})=\frac{1}{\hat{N}_{pop} } \sqrt{\frac{N^2 (1-\frac{n}{N})}{n}\frac{1}{n-1} \sum_{i=1}^n (M_i\hat{p}_i -\hat{t}/N)^2  + \frac{N}{n}  \sum_{i=1}^n \frac{M_i^2}{m_i}\left(1-\frac{m_i}{M_i}\right)s^2_i }\]</span></p>
<p>where <span class="math inline">\(s^2_i\)</span> is defined as:</p>
<p><span class="math display">\[s^2_i = \frac{m_hp_h(1-p_h)}{m_h-1}\]</span>.</p>
</div>
<div id="the-syntax-3" class="section level3 hasAnchor" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> The syntax<a href="c05.html#the-syntax-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To specify a two-stage clustered design without replacement, use the following syntax:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="c05.html#cb40-1" aria-hidden="true" tabindex="-1"></a>des_clus2 <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="c05.html#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">weights =</span> wtvar, <span class="at">ids =</span> <span class="fu">c</span>(PSU, SSU), <span class="at">fpc =</span> <span class="fu">c</span>(N, M))</span></code></pre></div>
<p>where <code>SSU</code> and <code>PSU</code> are the variables indicating the PSU and SSU identifiers and <code>N</code> and <code>M</code> are the variables indicating the population sizes - the number of clusters and then the number of units within each cluster. Note that <code>N</code> will be the same for all records (within a strata) and <code>M</code> will be the same for all records within the same cluster.</p>
<p>If clusters were sampled with replacement or from a very large population, a fpc is not necessary. Additionally, only the first stage of selection is necessary. The syntax below will yield the same estimates in the end:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="c05.html#cb41-1" aria-hidden="true" tabindex="-1"></a>des_clus2wra <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="c05.html#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">weights =</span> wtvar, <span class="at">ids =</span> <span class="fu">c</span>(PSU, SSU))</span>
<span id="cb41-3"><a href="c05.html#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="c05.html#cb41-4" aria-hidden="true" tabindex="-1"></a>des_clus2wrb <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb41-5"><a href="c05.html#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">weights =</span> wtvar, <span class="at">ids =</span> PSU)</span></code></pre></div>
</div>
<div id="an-example-2" class="section level3 hasAnchor" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> An example<a href="c05.html#an-example-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <code>survey</code> package includes a two-stage cluster sample data, <code>apiclus2</code>, in which school districts were sampled and then a random sample of 5 schools was selected within each district. For districts with fewer than 5 schools, all schools were sampled. School districts have identifiers <code>dnum</code> and schools have identifiers of <code>snum</code>. The variable <code>fpc1</code> indicates how many districts there were in California and <code>fpc2</code> indicates how many schools were in a given district with at least 100 students. The data has a row for each school. In the data printed below, there are 757 school districts as indicated by <code>fpc1</code> and there are 9 schools in district 731, one school in district 742, 2 schools in district 768, 6 schools in district 781, and 1 school in district 795 as indicated by <code>fpc2</code>.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="c05.html#cb42-1" aria-hidden="true" tabindex="-1"></a>apiclus2_slim <span class="ot">&lt;-</span> </span>
<span id="cb42-2"><a href="c05.html#cb42-2" aria-hidden="true" tabindex="-1"></a>  apiclus2 <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="c05.html#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb42-4"><a href="c05.html#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(dnum), snum) <span class="sc">%&gt;%</span></span>
<span id="cb42-5"><a href="c05.html#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(cds, dnum, snum, fpc1, fpc2, pw)</span>
<span id="cb42-6"><a href="c05.html#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="c05.html#cb42-7" aria-hidden="true" tabindex="-1"></a>apiclus2_slim</span></code></pre></div>
<pre><code>## # A tibble: 126 x 6
##    cds             dnum  snum  fpc1  fpc2    pw
##    &lt;chr&gt;          &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt;
##  1 47704826050942   795  5552   757     1  18.9
##  2 07618126005169   781   530   757     6  22.7
##  3 07618126005177   781   531   757     6  22.7
##  4 07618126005185   781   532   757     6  22.7
##  5 07618126005193   781   533   757     6  22.7
##  6 07618126005243   781   535   757     6  22.7
##  7 19650786023337   768  2371   757     2  18.9
##  8 19650786023345   768  2372   757     2  18.9
##  9 54722076054423   742  5898   757     1  18.9
## 10 50712906053086   731  5781   757     9  34.1
## # ... with 116 more rows</code></pre>
<p>To specify this design in R, the following syntax should be used:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="c05.html#cb44-1" aria-hidden="true" tabindex="-1"></a>des_apiclus2 <span class="ot">&lt;-</span> apiclus2_slim <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="c05.html#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">ids =</span> <span class="fu">c</span>(dnum, snum), <span class="at">fpc =</span> <span class="fu">c</span>(fpc1, fpc2), <span class="at">weights=</span>pw)</span>
<span id="cb44-3"><a href="c05.html#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="c05.html#cb44-4" aria-hidden="true" tabindex="-1"></a>des_apiclus2</span></code></pre></div>
<pre><code>## 2 - level Cluster Sampling design
## With (40, 126) clusters.
## Called via srvyr
## Sampling variables:
##  - ids: `dnum + snum`
##  - fpc: `fpc1 + fpc2`
##  - weights: pw
## Data variables: cds (chr), dnum (int), snum (dbl),
##   fpc1 (dbl), fpc2 (int), pw (dbl)</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="c05.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(des_apiclus2)</span></code></pre></div>
<pre><code>## 2 - level Cluster Sampling design
## With (40, 126) clusters.
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 0.00367 0.03774 0.05284 0.04239 0.05284 0.05284 
## Population size (PSUs): 757 
## Data variables:
## [1] &quot;cds&quot;  &quot;dnum&quot; &quot;snum&quot; &quot;fpc1&quot; &quot;fpc2&quot; &quot;pw&quot;</code></pre>
<p>The design objects are described as “2 - level Cluster Sampling design” and includes the ids (cluster), fpc, and weight variables. In the summary, it is noted that the sample includes 40 first-level clusters (PSUs) which are school districts and 126 second-level clusters (SSUs) which are schools. Additionally, the summary includes a numeric summary of the probabilities and the population size (number of PSUs) as 757.</p>
</div>
</div>
<div id="understanding-survey-design-documentation" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Understanding survey design documentation<a href="c05.html#understanding-survey-design-documentation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>SRS, stratified, and clustered designs are the backbone of sampling designs and the features are often combined in one design. Additionally, rather than using SRS for selection, other mechanisms are commonly used such as probability proportional to size (PPS), systematic sampling, or selection with unequal probabilities.</p>
<p>A common method of sampling is to stratify PSUs, select PSUs within stratum using PPS selection, and then select units within the PSUs either with SRS or PPS. Reading survey documentation is an important first step of survey analysis to understand the design and variables necessary to specify the design. Good documentation will highlight the variables necessary to specify the design. This is often found in User’s Guides, methodology, analysis guides, or technical documentation.</p>
<p>For example, the 2017-2019 National Survey of Family Growth (NSFG)<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> had a stratified multi-stage area probability sample. Counties or collections of counties were the primary sampling units which were stratified by Census region/division, size (population), and MSA status. Within each stratum, PSUs were selected PPS. At the second stage, neighborhoods were selected within the sampled PSUs using PPS selection. At the third stage, housing units were selected within the sampled neighborhoods. At the fourth stage, a person was randomly chosen within the selected housing units among eligible persons using unequal probabilities based on person’s age and sex. The public use file does not include all these levels of selection and instead includes pseudo-strata and pseudo-clusters<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> which are the variables used in R to specify the design. As specified on page 4, the stratum variable is <code>SEST</code>, the cluster variable is <code>SECU</code>, and the weight variable is <code>WGT2017_2019</code>. Thus, to specify this design in R, one would use the following syntax:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="c05.html#cb48-1" aria-hidden="true" tabindex="-1"></a>des_nsfg <span class="ot">&lt;-</span> nsfgdata <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="c05.html#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(<span class="at">ids =</span> SECU, <span class="at">strata =</span> SEST, <span class="at">weights =</span> WGT2017_2019)</span></code></pre></div>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>2017-2019 National Survey of Family Growth (NSFG): Sample Design Documentation - <a href="https://www.cdc.gov/nchs/data/nsfg/NSFG-2017-2019-Sample-Design-Documentation-508.pdf" class="uri">https://www.cdc.gov/nchs/data/nsfg/NSFG-2017-2019-Sample-Design-Documentation-508.pdf</a><a href="c05.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>2017-2019 National Survey of Family Growth (NSFG): Sample Error Estimation Design - <a href="https://www.cdc.gov/nchs/data/nsfg/NSFG-2017-2019-Sample-Error-Estimation-Design-508.pdf" class="uri">https://www.cdc.gov/nchs/data/nsfg/NSFG-2017-2019-Sample-Error-Estimation-Design-508.pdf</a><a href="c05.html#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="c04.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="c06.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/05-specifying-sample-designs.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
