---
title: "AmericasBarometer 2021"
output: 
  github_document:
    html_preview: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data information

All data and resources were downloaded from http://datasets.americasbarometer.org/database/ on May 7, 2023.

```{r}
#| label: loadpackageh
#| message: FALSE

library(here) #easy relative paths
```

```{r}
#| label: loadpackages

library(tidyverse) #data manipulation
library(haven) #data import
library(tidylog) #informative logging messages
library(osfr) # be sure to have PAT saved in Renviron as OSF_PAT
```

## Import data and create derived variables

```{r}
#| label: derivedata

stata_files <- osf_retrieve_node("https://osf.io/z5c3m/") %>%
  osf_ls_files(path="LAPOP_2021", n_max=40, pattern=".dta")

read_stata_unlabeled <- function(osf_tbl_i){
  filedet <- osf_tbl_i %>%
    osf_download(conflicts="overwrite", path=here("osf_dl"))
  
  tibin <- filedet %>%
    pull(local_path) %>%
    read_stata() %>%
    zap_labels() %>%
    zap_label()
  
  unlink(pull(filedet, "local_path"))
  
  return(tibin)
}

lapop_in <- stata_files %>% 
  split(1:nrow(stata_files)) %>%
  map_df(read_stata_unlabeled)

# https://www.vanderbilt.edu/lapop/ab2021/AB2021-Core-Questionnaire-v17.5-Eng-210514-W-v2.pdf 
lapop <- lapop_in %>%
  select(pais, strata, upm, weight1500, strata, core_a_core_b,
         q2, q1tb, covid2at, a4, idio2, idio2cov, it1, jc13,
         m1, mil10a, mil10e, ccch1, ccch3, ccus1, ccus3,
         edr, ocup4a, q14, q11n, q12c, q12bn,
         starts_with("covidedu1"), gi0n,
         r15, r18n, r18
         ) 

 
```



## Save data

```{r savedat}

summary(lapop)

lapop_temp_loc <- here("osf_dl", "lapop_2021.rds")

write_rds(lapop, lapop_temp_loc)

target_dir <- osf_retrieve_node("https://osf.io/gzbkn/?view_only=8ca80573293b4e12b7f934a0f742b957") 

osf_upload(target_dir, path=lapop_temp_loc, conflicts="overwrite")

unlink(lapop_temp_loc)
```

